// worker.js: the site's router, generated from its table. Do not edit.
const STATUS = 301;
// Every page and script address the earlier site served, to its page now.
const MOVED = {
"/address.html": "/ostrowski/",
"/algebra.html": "/budget/",
"/audits.html": "/ruler/",
"/automata": "/residues/",
"/automata.html": "/residues/",
"/benford.html": "/dual/",
"/blind.html": "/headroom/",
"/build": "/",
"/build.html": "/",
"/carrier.html": "/clock/",
"/cascade.html": "/cascade/",
"/ceilings.html": "/ruler/",
"/certificate.html": "/clock/",
"/chains.html": "/redundant/",
"/claims-blind.html": "/claims/",
"/claims-cascade.html": "/claims/",
"/claims-computation.html": "/claims/",
"/claims-constants.html": "/claims/",
"/claims-fields.html": "/claims/",
"/claims-flattening.html": "/claims/",
"/claims-growth.html": "/claims/",
"/claims-inside.html": "/claims/",
"/claims-instruments.html": "/claims/",
"/claims-irreducibility.html": "/claims/",
"/claims-learning.html": "/claims/",
"/claims-measure.html": "/claims/",
"/claims-object.html": "/claims/",
"/claims-observatory.html": "/claims/",
"/claims-principal.html": "/claims/",
"/claims-probe.html": "/claims/",
"/claims-reading.html": "/claims/",
"/claims-redundancy.html": "/claims/",
"/claims-schedule.html": "/claims/",
"/claims-thermal.html": "/claims/",
"/claims-walls.html": "/claims/",
"/claims.html": "/claims/",
"/claims/blind": "/claims/",
"/claims/blind/": "/claims/",
"/claims/cascade": "/claims/",
"/claims/cascade/": "/claims/",
"/claims/computation": "/claims/",
"/claims/computation/": "/claims/",
"/claims/constants": "/claims/",
"/claims/constants/": "/claims/",
"/claims/fields": "/claims/",
"/claims/fields/": "/claims/",
"/claims/flattening": "/claims/",
"/claims/flattening/": "/claims/",
"/claims/growth": "/claims/",
"/claims/growth/": "/claims/",
"/claims/inside": "/claims/",
"/claims/inside/": "/claims/",
"/claims/instruments": "/claims/",
"/claims/instruments/": "/claims/",
"/claims/irreducibility": "/claims/",
"/claims/irreducibility/": "/claims/",
"/claims/learning": "/claims/",
"/claims/learning/": "/claims/",
"/claims/measure": "/claims/",
"/claims/measure/": "/claims/",
"/claims/object": "/claims/",
"/claims/object/": "/claims/",
"/claims/observatory": "/claims/",
"/claims/observatory/": "/claims/",
"/claims/principal": "/claims/",
"/claims/principal/": "/claims/",
"/claims/probe": "/claims/",
"/claims/probe/": "/claims/",
"/claims/reading": "/claims/",
"/claims/reading/": "/claims/",
"/claims/redundancy": "/claims/",
"/claims/redundancy/": "/claims/",
"/claims/schedule": "/claims/",
"/claims/schedule/": "/claims/",
"/claims/thermal": "/claims/",
"/claims/thermal/": "/claims/",
"/claims/walls": "/claims/",
"/claims/walls/": "/claims/",
"/clock.html": "/clock/",
"/clocks.html": "/supply/",
"/collisions.html": "/collide/",
"/completions.html": "/reading/",
"/computation": "/machine/",
"/computation.html": "/machine/",
"/computation/": "/machine/",
"/computation/clocks": "/supply/",
"/computation/clocks/": "/supply/",
"/computation/delay": "/supply/",
"/computation/delay/": "/supply/",
"/computation/dividend": "/coordinates/",
"/computation/dividend/": "/coordinates/",
"/computation/interface": "/machine/",
"/computation/interface/": "/machine/",
"/computation/recovery": "/supply/",
"/computation/recovery/": "/supply/",
"/constants": "/growth/",
"/constants.html": "/growth/",
"/constants/": "/growth/",
"/crt": "/object/",
"/crt.html": "/object/",
"/degeneracy.html": "/triple/",
"/delay.html": "/supply/",
"/delays.html": "/code/delays/",
"/dial.html": "/clock/",
"/dividend.html": "/coordinates/",
"/dual.html": "/dual/",
"/dynamics": "/object/",
"/dynamics.html": "/object/",
"/ecc": "/object/",
"/ecc.html": "/object/",
"/engineering": "/",
"/engineering.html": "/",
"/fields.html": "/growth/",
"/files/crt.py": "/code/crt.py",
"/files/explore_above_window.py": "/",
"/files/explore_abscissa_reserve.py": "/growth/",
"/files/explore_aperiodic_address.py": "/reading/",
"/files/explore_aperiodic_cut.py": "/shifts/",
"/files/explore_apparition_density.py": "/ostrowski/",
"/files/explore_arc_opening.py": "/redundant/",
"/files/explore_archimedean_dial.py": "/machines/",
"/files/explore_arithmetic_gate.py": "/reading/",
"/files/explore_arrival_defect.py": "/observatory/",
"/files/explore_astar_slope.py": "/memory/",
"/files/explore_asymptotic_density.py": "/thermal/",
"/files/explore_bandwidth_dial.py": "/learner/",
"/files/explore_bank_period.py": "/learner/",
"/files/explore_banking_reader.py": "/learner/",
"/files/explore_bare_class.py": "/machine/",
"/files/explore_bare_cost.py": "/clock/",
"/files/explore_beta_delay.py": "/redundant/",
"/files/explore_binding_depth.py": "/binding/",
"/files/explore_bit_supply.py": "/machine/",
"/files/explore_blind_adams.py": "/growth/",
"/files/explore_blind_bernoulli.py": "/memory/",
"/files/explore_blind_model.py": "/memory/",
"/files/explore_blind_share.py": "/memory/",
"/files/explore_blind_spot_infinite.py": "/memory/",
"/files/explore_block_clock.py": "/clock/",
"/files/explore_bootstrap_cures.py": "/learner/",
"/files/explore_born_at_zero.py": "/supply/",
"/files/explore_born_set.py": "/clock/",
"/files/explore_bottomless_columns.py": "/growth/",
"/files/explore_bounded_half.py": "/shifts/",
"/files/explore_bridge_reach.py": "/",
"/files/explore_carrier_window.py": "/clock/",
"/files/explore_cascade_chars.py": "/principal/",
"/files/explore_cascade_closure.py": "/shifts/",
"/files/explore_cascade_residual.py": "/cascade/",
"/files/explore_cascade_roof.py": "/shifts/",
"/files/explore_cascade_rule.py": "/shifts/",
"/files/explore_cascade_scale.py": "/shifts/",
"/files/explore_cascade_seed.py": "/cascade/",
"/files/explore_cascade_span.py": "/shifts/",
"/files/explore_cascade_theorem.py": "/cascade/",
"/files/explore_cascade_values.py": "/shifts/",
"/files/explore_ceiling_anatomy.py": "/ruler/",
"/files/explore_ceiling_constant.py": "/principal/",
"/files/explore_ceiling_curve.py": "/principal/",
"/files/explore_ceiling_dials.py": "/ruler/",
"/files/explore_ceiling_early.py": "/principal/",
"/files/explore_ceiling_forcing.py": "/principal/",
"/files/explore_ceiling_fourthcell.py": "/principal/",
"/files/explore_ceiling_realcubic.py": "/principal/",
"/files/explore_ceiling_realquad.py": "/principal/",
"/files/explore_ceiling_ruler.py": "/ruler/",
"/files/explore_ceiling_squares.py": "/principal/",
"/files/explore_ceiling_topband.py": "/principal/",
"/files/explore_census_theorem.py": "/clock/",
"/files/explore_cf_conductor.py": "/reading/",
"/files/explore_cf_flow.py": "/reading/",
"/files/explore_cf_nonlinear.py": "/reading/",
"/files/explore_cf_redundant.py": "/reading/",
"/files/explore_cf_window.py": "/reading/",
"/files/explore_chain_cells.py": "/redundant/",
"/files/explore_chain_certify.py": "/redundant/",
"/files/explore_chain_delay.py": "/redundant/",
"/files/explore_chain_matching.py": "/redundant/",
"/files/explore_chain_mixed.py": "/redundant/",
"/files/explore_chain_persistence.py": "/learner/",
"/files/explore_chain_product.py": "/redundant/",
"/files/explore_chain_recip.py": "/redundant/",
"/files/explore_charged_radius.py": "/learner/",
"/files/explore_checksum_ring.py": "/coordinates/",
"/files/explore_chi_decay_constant.py": "/naming/",
"/files/explore_chi_primality.py": "/naming/",
"/files/explore_class_character.py": "/triple/",
"/files/explore_class_criterion.py": "/ostrowski/",
"/files/explore_class_dual.py": "/triple/",
"/files/explore_class_gap.py": "/growth/",
"/files/explore_class_level.py": "/tools/",
"/files/explore_class_null.py": "/triple/",
"/files/explore_class_order.py": "/tools/",
"/files/explore_class_schedule.py": "/limit/",
"/files/explore_class_share.py": "/triple/",
"/files/explore_class_species_nf.py": "/element/",
"/files/explore_class_wide.py": "/triple/",
"/files/explore_clique_betti.py": "/tower/",
"/files/explore_clock_counter.py": "/supply/",
"/files/explore_clock_factorization.py": "/memory/",
"/files/explore_clock_vacuity.py": "/machines/",
"/files/explore_closure_family.py": "/shifts/",
"/files/explore_coarse_type.py": "/limit/",
"/files/explore_coarsest_colouring.py": "/limit/",
"/files/explore_coefficient_triangle.py": "/observatory/",
"/files/explore_collision_equivalence.py": "/growth/",
"/files/explore_collision_growth.py": "/learner/",
"/files/explore_comparator_delay.py": "/redundant/",
"/files/explore_comparator_ruler.py": "/tools/",
"/files/explore_completion_atlas.py": "/reading/",
"/files/explore_completion_lift.py": "/flush/",
"/files/explore_completion_reader.py": "/flush/",
"/files/explore_complexity_ledger.py": "/growth/",
"/files/explore_composite_move.py": "/machines/",
"/files/explore_congruence_kill.py": "/",
"/files/explore_conjugate_spectrum.py": "/reading/",
"/files/explore_constant_a_borrow.py": "/ostrowski/",
"/files/explore_continuity_converse.py": "/shifts/",
"/files/explore_corner_limit.py": "/shifts/",
"/files/explore_coupled_inference.py": "/binding/",
"/files/explore_coupling_order.py": "/residues/",
"/files/explore_cover_exclusion.py": "/logic/",
"/files/explore_covering_lag.py": "/redundant/",
"/files/explore_cross_kind_tie.py": "/clock/",
"/files/explore_cubic_carrier.py": "/clock/",
"/files/explore_cubic_class_map.py": "/triple/",
"/files/explore_cubic_field_shop.py": "/clock/",
"/files/explore_cubic_first_hit.py": "/triple/",
"/files/explore_cubic_order_level.py": "/tools/",
"/files/explore_cubic_principal.py": "/triple/",
"/files/explore_cubic_regime_sorter.py": "/principal/",
"/files/explore_cubic_ring.py": "/clock/",
"/files/explore_cubic_split_triple.py": "/principal/",
"/files/explore_cubic_transposition.py": "/triple/",
"/files/explore_cubic_undercut.py": "/clock/",
"/files/explore_cubic_zero_tilt.py": "/principal/",
"/files/explore_cunningham_bias.py": "/naming/",
"/files/explore_curve_skeleton.py": "/logic/",
"/files/explore_cutoff_ladder.py": "/tools/",
"/files/explore_cyclotomic_ghost.py": "/reading/",
"/files/explore_davenport_egz.py": "/naming/",
"/files/explore_decidable_equivalence.py": "/machine/",
"/files/explore_decidable_side.py": "/supply/",
"/files/explore_decision_trade.py": "/learner/",
"/files/explore_deep_pairs.py": "/shifts/",
"/files/explore_deep_spectrum.py": "/observatory/",
"/files/explore_defect_kleene.py": "/residues/",
"/files/explore_delay_choice.py": "/redundant/",
"/files/explore_delay_sweep.py": "/redundant/",
"/files/explore_deleted_budget.py": "/logic/",
"/files/explore_deletion_ruler.py": "/ruler/",
"/files/explore_demand_reading.py": "/machines/",
"/files/explore_density_extended.py": "/thermal/",
"/files/explore_depth_observer.py": "/memory/",
"/files/explore_descent26.py": "/collide/",
"/files/explore_descent26_close.py": "/collide/",
"/files/explore_descent26_mix.py": "/collide/",
"/files/explore_descent26_why.py": "/collide/",
"/files/explore_descent26_wide.py": "/collide/",
"/files/explore_descent_hunt.py": "/collide/",
"/files/explore_designed_ramification.py": "/logic/",
"/files/explore_divider_lookahead.py": "/tools/",
"/files/explore_division_ladder.py": "/logic/",
"/files/explore_door_grades.py": "/forget/",
"/files/explore_door_index.py": "/clock/",
"/files/explore_double_birth.py": "/object/",
"/files/explore_doubling_counter.py": "/supply/",
"/files/explore_drop_ascent.py": "/reading/",
"/files/explore_drop_column.py": "/reading/",
"/files/explore_dual_affine_class.py": "/dual/",
"/files/explore_dual_least_lookahead.py": "/dual/",
"/files/explore_dual_lipschitz.py": "/reading/",
"/files/explore_dual_locality.py": "/dual/",
"/files/explore_dual_measure.py": "/dual/",
"/files/explore_dual_merge.py": "/residues/",
"/files/explore_dual_pole.py": "/dual/",
"/files/explore_dual_redundant.py": "/dual/",
"/files/explore_ecc_borrow.py": "/machine/",
"/files/explore_eigenvalue_landscape.py": "/fingerprint/",
"/files/explore_eigenvalue_operator.py": "/fingerprint/",
"/files/explore_element_cascade.py": "/cascade/",
"/files/explore_element_limit.py": "/limit/",
"/files/explore_element_schedule_nf.py": "/clock/",
"/files/explore_embedding.py": "/learner/",
"/files/explore_engineered_tie.py": "/clock/",
"/files/explore_equation_bound.py": "/shifts/",
"/files/explore_erasure_ledger.py": "/machine/",
"/files/explore_eval_ceiling.py": "/ruler/",
"/files/explore_even_winner.py": "/clock/",
"/files/explore_evidence_calculus.py": "/gates/",
"/files/explore_exactness_bridge.py": "/memory/",
"/files/explore_expressiveness_perimeter.py": "/machine/",
"/files/explore_face_accident.py": "/collide/",
"/files/explore_face_spectrum.py": "/collide/",
"/files/explore_family_term.py": "/principal/",
"/files/explore_farey_delay.py": "/redundant/",
"/files/explore_fate_clock.py": "/machines/",
"/files/explore_fate_image.py": "/limit/",
"/files/explore_fate_image_ff.py": "/limit/",
"/files/explore_fermat_reciprocal_tail.py": "/coordinates/",
"/files/explore_filtration_price.py": "/clock/",
"/files/explore_first_hit_bound.py": "/supply/",
"/files/explore_first_hit_survival.py": "/principal/",
"/files/explore_five_prints.py": "/collide/",
"/files/explore_flatten_band.py": "/flatten/",
"/files/explore_flatten_class.py": "/flatten/",
"/files/explore_flatten_d2.py": "/tools/",
"/files/explore_flatten_deep.py": "/flatten/",
"/files/explore_flatten_dk.py": "/flatten/",
"/files/explore_flatten_dk_edge.py": "/flatten/",
"/files/explore_flatten_endvalue.py": "/flatten/",
"/files/explore_flatten_family.py": "/flatten/",
"/files/explore_flatten_gen.py": "/flatten/",
"/files/explore_flatten_height.py": "/flatten/",
"/files/explore_flatten_lattice.py": "/tools/",
"/files/explore_flatten_near.py": "/flatten/",
"/files/explore_flatten_offchart.py": "/flatten/",
"/files/explore_flatten_recur.py": "/flatten/",
"/files/explore_flatten_select.py": "/flatten/",
"/files/explore_flatten_swap.py": "/flatten/",
"/files/explore_flatten_theorem.py": "/flatten/",
"/files/explore_flip_floor.py": "/ruler/",
"/files/explore_flip_inbox.py": "/ruler/",
"/files/explore_flip_level.py": "/ruler/",
"/files/explore_flip_risk.py": "/ruler/",
"/files/explore_flip_timing.py": "/machine/",
"/files/explore_floor_grade_shape.py": "/principal/",
"/files/explore_flush_closure.py": "/flush/",
"/files/explore_flush_depth.py": "/flush/",
"/files/explore_flush_floor.py": "/flush/",
"/files/explore_flush_law.py": "/flush/",
"/files/explore_flush_order.py": "/flush/",
"/files/explore_flush_price.py": "/flush/",
"/files/explore_flush_seed.py": "/flush/",
"/files/explore_flush_theorem.py": "/flush/",
"/files/explore_forced_one.py": "/supply/",
"/files/explore_forgetting_certificate.py": "/forget/",
"/files/explore_four_prints.py": "/learner/",
"/files/explore_frontier_rider.py": "/machine/",
"/files/explore_function_field_lock.py": "/growth/",
"/files/explore_function_field_melt.py": "/growth/",
"/files/explore_g2_separator.py": "/learner/",
"/files/explore_gap_centering.py": "/redundant/",
"/files/explore_gap_choice.py": "/redundant/",
"/files/explore_gap_finite.py": "/redundant/",
"/files/explore_gap_horizon.py": "/redundant/",
"/files/explore_gap_lattice.py": "/redundant/",
"/files/explore_gate_budget.py": "/gates/",
"/files/explore_gaussian_runaway.py": "/clock/",
"/files/explore_general_max_string.py": "/ostrowski/",
"/files/explore_genesis_ladder.py": "/object/",
"/files/explore_genome_fibre.py": "/memory/",
"/files/explore_genus_index.py": "/principal/",
"/files/explore_ghost_wander.py": "/cascade/",
"/files/explore_goldenbase_control.py": "/reading/",
"/files/explore_grammar_growth.py": "/learner/",
"/files/explore_greedy_image_ec.py": "/element/",
"/files/explore_greedy_image_g2.py": "/element/",
"/files/explore_greedy_image_nf.py": "/element/",
"/files/explore_greedy_limit.py": "/limit/",
"/files/explore_growth_capability.py": "/growth/",
"/files/explore_growth_certificate.py": "/supply/",
"/files/explore_growth_laws.py": "/growth/",
"/files/explore_growth_machine.py": "/machines/",
"/files/explore_halt_clock.py": "/growth/",
"/files/explore_head_width.py": "/clock/",
"/files/explore_headed_block.py": "/clock/",
"/files/explore_headed_cubic_walk.py": "/clock/",
"/files/explore_headed_image.py": "/element/",
"/files/explore_headed_ladder.py": "/clock/",
"/files/explore_headroom.py": "/memory/",
"/files/explore_hit_triangle.py": "/observatory/",
"/files/explore_horizon_rate.py": "/naming/",
"/files/explore_horizon_route.py": "/naming/",
"/files/explore_hot_limit.py": "/thermal/",
"/files/explore_idempotent_logic.py": "/residues/",
"/files/explore_image_domain.py": "/element/",
"/files/explore_image_lattice.py": "/image/",
"/files/explore_image_share.py": "/principal/",
"/files/explore_increment_group.py": "/limit/",
"/files/explore_index_transform.py": "/coordinates/",
"/files/explore_induction_ceiling.py": "/memory/",
"/files/explore_interactive_hand.py": "/machine/",
"/files/explore_interactive_observer.py": "/machine/",
"/files/explore_irreducibility_crossfield.py": "/memory/",
"/files/explore_irreducibility_order.py": "/memory/",
"/files/explore_irreducibility_places.py": "/memory/",
"/files/explore_joint_measurement.py": "/logic/",
"/files/explore_jump_digits.py": "/observatory/",
"/files/explore_jump_haar.py": "/observatory/",
"/files/explore_jump_set.py": "/observatory/",
"/files/explore_kary_ceiling.py": "/ruler/",
"/files/explore_keep_law.py": "/learner/",
"/files/explore_kummer_layers.py": "/ostrowski/",
"/files/explore_ladder_entry.py": "/learner/",
"/files/explore_ladder_stop.py": "/limit/",
"/files/explore_lambda_tower.py": "/object/",
"/files/explore_late_seating.py": "/clock/",
"/files/explore_lattice_avoidance.py": "/shifts/",
"/files/explore_lcm_shifted_primes.py": "/thermal/",
"/files/explore_lcm_wait.py": "/supply/",
"/files/explore_lead_law.py": "/tools/",
"/files/explore_least_factor_seat.py": "/principal/",
"/files/explore_ledger_threshold.py": "/growth/",
"/files/explore_limit_column.py": "/shifts/",
"/files/explore_limit_maps.py": "/shifts/",
"/files/explore_limit_object.py": "/object/",
"/files/explore_linnik_injectivity.py": "/object/",
"/files/explore_local_clock.py": "/observatory/",
"/files/explore_lock_budget.py": "/clock/",
"/files/explore_lock_prime.py": "/machines/",
"/files/explore_lookahead_band.py": "/flush/",
"/files/explore_lookahead_proof.py": "/redundant/",
"/files/explore_lookahead_table.py": "/tools/",
"/files/explore_loose_floor.py": "/memory/",
"/files/explore_machine_word_tower.py": "/coordinates/",
"/files/explore_manystream_delay.py": "/tools/",
"/files/explore_margin_locus.py": "/redundant/",
"/files/explore_margin_wedge.py": "/redundant/",
"/files/explore_masking_layer.py": "/size/",
"/files/explore_max_string_witness.py": "/ostrowski/",
"/files/explore_meaning_codeword.py": "/binding/",
"/files/explore_member_monoid.py": "/shifts/",
"/files/explore_membership_ruler.py": "/ruler/",
"/files/explore_menu_faces.py": "/collide/",
"/files/explore_menu_factorization.py": "/collide/",
"/files/explore_menu_invisibility.py": "/limit/",
"/files/explore_menu_parting.py": "/clock/",
"/files/explore_menu_reach.py": "/collide/",
"/files/explore_merge_dissolution.py": "/residues/",
"/files/explore_minimal_carrier.py": "/machine/",
"/files/explore_minimal_cell.py": "/learner/",
"/files/explore_missed_primes.py": "/naming/",
"/files/explore_mixing26.py": "/collide/",
"/files/explore_mixing34.py": "/collide/",
"/files/explore_mode_staircase.py": "/memory/",
"/files/explore_module_law.py": "/clock/",
"/files/explore_moment_resonance.py": "/fingerprint/",
"/files/explore_monoid_columns.py": "/shifts/",
"/files/explore_monoid_correction.py": "/redundant/",
"/files/explore_monoid_ladder.py": "/shifts/",
"/files/explore_monoid_quotient.py": "/redundant/",
"/files/explore_monomial_delay.py": "/redundant/",
"/files/explore_move_set.py": "/learner/",
"/files/explore_mu16_face.py": "/",
"/files/explore_mu32_face.py": "/",
"/files/explore_mu8_grading.py": "/",
"/files/explore_multiprime_exclusion.py": "/logic/",
"/files/explore_naming_complex.py": "/tower/",
"/files/explore_narayana_window.py": "/reading/",
"/files/explore_nimber_tower.py": "/coordinates/",
"/files/explore_noncommutative_merge.py": "/residues/",
"/files/explore_noncyclic_level.py": "/principal/",
"/files/explore_nonidentified_statement.py": "/ruler/",
"/files/explore_nonquadratic_window.py": "/shifts/",
"/files/explore_norm5_carrier.py": "/clock/",
"/files/explore_noroot_margin.py": "/ruler/",
"/files/explore_number_field_lock.py": "/growth/",
"/files/explore_numeration_windows.py": "/coordinates/",
"/files/explore_observer_view.py": "/memory/",
"/files/explore_odd_a_freeze.py": "/ostrowski/",
"/files/explore_odd_cycles.py": "/shifts/",
"/files/explore_odd_doubling.py": "/shifts/",
"/files/explore_odd_m2_bound.py": "/shifts/",
"/files/explore_odd_transfer.py": "/shifts/",
"/files/explore_one_and.py": "/supply/",
"/files/explore_one_vehicle.py": "/clock/",
"/files/explore_one_way.py": "/memory/",
"/files/explore_onestream_delay.py": "/redundant/",
"/files/explore_onestream_widened.py": "/redundant/",
"/files/explore_opening_law.py": "/clock/",
"/files/explore_orbit_cost.py": "/gates/",
"/files/explore_order_wall_shape.py": "/redundant/",
"/files/explore_organizing_relations.py": "/residues/",
"/files/explore_ostrowski_window.py": "/ostrowski/",
"/files/explore_output_comparator.py": "/redundant/",
"/files/explore_overlap_carrier.py": "/binding/",
"/files/explore_paired_division.py": "/principal/",
"/files/explore_parity_derivation.py": "/shifts/",
"/files/explore_pending_fires.py": "/supply/",
"/files/explore_pentanomial_free.py": "/collide/",
"/files/explore_pentanomial_reciprocal.py": "/collide/",
"/files/explore_period2_borrow.py": "/ostrowski/",
"/files/explore_period3_borrow.py": "/ostrowski/",
"/files/explore_phase_selector.py": "/shifts/",
"/files/explore_phoenix_bill.py": "/memory/",
"/files/explore_piecewise_delay.py": "/tools/",
"/files/explore_piecewise_smooth.py": "/tools/",
"/files/explore_pinned_composite.py": "/learner/",
"/files/explore_pinned_freshening.py": "/learner/",
"/files/explore_pinned_telescope.py": "/learner/",
"/files/explore_pisot_confound.py": "/reading/",
"/files/explore_plateau_collisions.py": "/fingerprint/",
"/files/explore_plateau_rate.py": "/fingerprint/",
"/files/explore_polynomial_delay.py": "/redundant/",
"/files/explore_populated_door.py": "/clock/",
"/files/explore_powered_fingerprint.py": "/fingerprint/",
"/files/explore_powered_theorem.py": "/fingerprint/",
"/files/explore_prediction_door.py": "/forget/",
"/files/explore_premium.py": "/memory/",
"/files/explore_price_hypotheses.py": "/clock/",
"/files/explore_price_schedule.py": "/limit/",
"/files/explore_prime_chain.py": "/supply/",
"/files/explore_prime_gaps.py": "/thermal/",
"/files/explore_prime_reader.py": "/supply/",
"/files/explore_principal_place.py": "/principal/",
"/files/explore_principal_regulator.py": "/triple/",
"/files/explore_principal_scale.py": "/triple/",
"/files/explore_principal_share.py": "/principal/",
"/files/explore_product_delay.py": "/redundant/",
"/files/explore_product_necessity.py": "/reading/",
"/files/explore_proth_window.py": "/memory/",
"/files/explore_quadratic_middle.py": "/reading/",
"/files/explore_quantifier_envelope.py": "/residues/",
"/files/explore_quantifier_ladder.py": "/residues/",
"/files/explore_quartic_level.py": "/principal/",
"/files/explore_quartic_seat.py": "/principal/",
"/files/explore_quartic_second.py": "/principal/",
"/files/explore_ram_tie.py": "/clock/",
"/files/explore_ramification_face.py": "/logic/",
"/files/explore_ramified_door.py": "/clock/",
"/files/explore_rank2_gap.py": "/flatten/",
"/files/explore_rank2_hunt.py": "/principal/",
"/files/explore_rank_face.py": "/logic/",
"/files/explore_ratchet_learner.py": "/learner/",
"/files/explore_ray_class_inverted.py": "/principal/",
"/files/explore_ray_class_lines.py": "/principal/",
"/files/explore_reachable_offsets.py": "/redundant/",
"/files/explore_read_surface.py": "/machine/",
"/files/explore_reader_box.py": "/flush/",
"/files/explore_reader_runs.py": "/flush/",
"/files/explore_reading_geometry.py": "/reading/",
"/files/explore_readout_proof.py": "/observatory/",
"/files/explore_readout_triangle.py": "/tools/",
"/files/explore_real_principal.py": "/principal/",
"/files/explore_realizability.py": "/logic/",
"/files/explore_reduction_law.py": "/observatory/",
"/files/explore_redundant_lookback.py": "/redundant/",
"/files/explore_redundant_ostrowski.py": "/flush/",
"/files/explore_reference_families.py": "/learner/",
"/files/explore_regulator_face.py": "/logic/",
"/files/explore_relation_address.py": "/reading/",
"/files/explore_reordering.py": "/image/",
"/files/explore_reserve_zoo.py": "/growth/",
"/files/explore_reset_corner.py": "/machines/",
"/files/explore_resolver_threshold.py": "/memory/",
"/files/explore_resonance_transparency.py": "/fingerprint/",
"/files/explore_rest_price.py": "/sets/",
"/files/explore_rich_rung_constants.py": "/naming/",
"/files/explore_rich_rungs.py": "/naming/",
"/files/explore_rider_recursion.py": "/limit/",
"/files/explore_ring_ca.py": "/binding/",
"/files/explore_ring_free_door.py": "/clock/",
"/files/explore_rns_comparator.py": "/tools/",
"/files/explore_rogue_world.py": "/collide/",
"/files/explore_ruler_abandon.py": "/sets/",
"/files/explore_ruler_barecell.py": "/sets/",
"/files/explore_ruler_boundary.py": "/ruler/",
"/files/explore_ruler_boundedgap.py": "/sets/",
"/files/explore_ruler_box.py": "/sets/",
"/files/explore_ruler_divergence.py": "/ruler/",
"/files/explore_ruler_dual.py": "/sets/",
"/files/explore_ruler_excess.py": "/sets/",
"/files/explore_ruler_exchange.py": "/sets/",
"/files/explore_ruler_family.py": "/",
"/files/explore_ruler_forced.py": "/sets/",
"/files/explore_ruler_gain.py": "/sets/",
"/files/explore_ruler_gaplaw.py": "/sets/",
"/files/explore_ruler_ladder.py": "/machine/",
"/files/explore_ruler_multiswap.py": "/sets/",
"/files/explore_ruler_optimum.py": "/sets/",
"/files/explore_ruler_profilecert.py": "/sets/",
"/files/explore_ruler_room.py": "/sets/",
"/files/explore_ruler_setvalued.py": "/sets/",
"/files/explore_ruler_surplus.py": "/sets/",
"/files/explore_ruler_swap.py": "/sets/",
"/files/explore_rung_existence.py": "/shifts/",
"/files/explore_rung_finite.py": "/shifts/",
"/files/explore_rung_law.py": "/shifts/",
"/files/explore_rung_odd.py": "/observatory/",
"/files/explore_rung_schedule.py": "/clock/",
"/files/explore_rung_theorem.py": "/observatory/",
"/files/explore_saturation_twins.py": "/shifts/",
"/files/explore_scale_clock.py": "/learner/",
"/files/explore_schedule_image.py": "/limit/",
"/files/explore_schedule_lattice.py": "/element/",
"/files/explore_score_criterion.py": "/learner/",
"/files/explore_seated_cover.py": "/limit/",
"/files/explore_second_point.py": "/observatory/",
"/files/explore_second_ruler.py": "/machine/",
"/files/explore_seed_cofactor.py": "/collide/",
"/files/explore_seed_confine.py": "/collide/",
"/files/explore_seed_exclusion.py": "/learner/",
"/files/explore_seed_flower_complexes.py": "/tower/",
"/files/explore_seed_flower_k8.py": "/naming/",
"/files/explore_seed_flower_operator.py": "/naming/",
"/files/explore_seed_line_floor.py": "/collide/",
"/files/explore_seed_pentanomial.py": "/collide/",
"/files/explore_seed_plane_floor.py": "/collide/",
"/files/explore_seed_rank_law.py": "/collide/",
"/files/explore_seed_rank_nine.py": "/collide/",
"/files/explore_seed_shape.py": "/collide/",
"/files/explore_seed_specialize.py": "/collide/",
"/files/explore_seed_torsion.py": "/collide/",
"/files/explore_segmented_delay.py": "/redundant/",
"/files/explore_selection_frame.py": "/growth/",
"/files/explore_shallow_route.py": "/",
"/files/explore_shift_repair.py": "/shifts/",
"/files/explore_shift_telescope.py": "/learner/",
"/files/explore_shifted_prime_density.py": "/thermal/",
"/files/explore_shifts_next_cap.py": "/shifts/",
"/files/explore_sieve_connection.py": "/object/",
"/files/explore_sign_minimal.py": "/redundant/",
"/files/explore_sign_monoid.py": "/redundant/",
"/files/explore_sign_reach.py": "/redundant/",
"/files/explore_sign_sparse.py": "/redundant/",
"/files/explore_sign_window.py": "/redundant/",
"/files/explore_silent_set.py": "/memory/",
"/files/explore_silent_window.py": "/reading/",
"/files/explore_silver_discontinuity.py": "/ostrowski/",
"/files/explore_similarity_carrier.py": "/binding/",
"/files/explore_size_crystallization.py": "/size/",
"/files/explore_size_transform.py": "/size/",
"/files/explore_sizeless_kernel.py": "/machine/",
"/files/explore_slack_machine.py": "/machines/",
"/files/explore_slope_arc.py": "/redundant/",
"/files/explore_slope_assemble.py": "/redundant/",
"/files/explore_slope_dodge.py": "/redundant/",
"/files/explore_slope_empty.py": "/redundant/",
"/files/explore_slope_lattice.py": "/redundant/",
"/files/explore_slope_parity.py": "/redundant/",
"/files/explore_slope_proof.py": "/redundant/",
"/files/explore_slope_step.py": "/redundant/",
"/files/explore_slope_tail.py": "/redundant/",
"/files/explore_slope_tree.py": "/redundant/",
"/files/explore_slope_twolevel.py": "/redundant/",
"/files/explore_slope_width.py": "/redundant/",
"/files/explore_slope_window.py": "/",
"/files/explore_slope_wrap.py": "/redundant/",
"/files/explore_slot_algebra.py": "/tools/",
"/files/explore_snapback_ca.py": "/binding/",
"/files/explore_spectral_theorem.py": "/fingerprint/",
"/files/explore_splice_cap.py": "/clock/",
"/files/explore_sqrt_delay.py": "/redundant/",
"/files/explore_sqrt_supply.py": "/supply/",
"/files/explore_square_line.py": "/redundant/",
"/files/explore_staircase_reduction.py": "/logic/",
"/files/explore_stall_assembly.py": "/learner/",
"/files/explore_stall_domination.py": "/learner/",
"/files/explore_stall_maprate.py": "/learner/",
"/files/explore_stall_tie.py": "/learner/",
"/files/explore_stall_unresourced.py": "/learner/",
"/files/explore_standing_move.py": "/headroom/",
"/files/explore_standing_recipe.py": "/cascade/",
"/files/explore_stopped_untie.py": "/limit/",
"/files/explore_storey_descent.py": "/observatory/",
"/files/explore_subset_sum_weld.py": "/forget/",
"/files/explore_super_critical.py": "/supply/",
"/files/explore_super_log.py": "/coordinates/",
"/files/explore_supply_tameness.py": "/supply/",
"/files/explore_support_growth.py": "/clock/",
"/files/explore_tame_face.py": "/observatory/",
"/files/explore_tame_readout.py": "/tools/",
"/files/explore_telescope.py": "/observatory/",
"/files/explore_tetranacci_window.py": "/reading/",
"/files/explore_the_twelve.py": "/image/",
"/files/explore_thermal_growth.py": "/thermal/",
"/files/explore_three_prints.py": "/supply/",
"/files/explore_three_seats.py": "/supply/",
"/files/explore_threshold_miss.py": "/tools/",
"/files/explore_throttled_reader.py": "/learner/",
"/files/explore_tick_pump.py": "/clock/",
"/files/explore_tie_world.py": "/forget/",
"/files/explore_tilt_resonance.py": "/ruler/",
"/files/explore_torus_geometry.py": "/tower/",
"/files/explore_torus_knots.py": "/tower/",
"/files/explore_tower_geometry.py": "/tower/",
"/files/explore_tower_naming.py": "/naming/",
"/files/explore_trade_exclusion.py": "/gates/",
"/files/explore_tribonacci_discontinuity.py": "/reading/",
"/files/explore_triple_cube_term.py": "/principal/",
"/files/explore_triple_excess_box.py": "/principal/",
"/files/explore_triple_far_window.py": "/principal/",
"/files/explore_triple_image_level.py": "/principal/",
"/files/explore_triple_ramified_term.py": "/principal/",
"/files/explore_two_adic_prices.py": "/growth/",
"/files/explore_two_place_universality.py": "/machine/",
"/files/explore_uint64_tower.py": "/coordinates/",
"/files/explore_unary_price.py": "/machine/",
"/files/explore_unbounded_supply.py": "/supply/",
"/files/explore_uncounted_corner.py": "/ruler/",
"/files/explore_uncounted_inside.py": "/ruler/",
"/files/explore_uncounted_term.py": "/ruler/",
"/files/explore_undercut.py": "/limit/",
"/files/explore_undercut_nf.py": "/clock/",
"/files/explore_uniform_close.py": "/shifts/",
"/files/explore_unit_escape.py": "/object/",
"/files/explore_universal_reader.py": "/flush/",
"/files/explore_urow_kill.py": "/shifts/",
"/files/explore_vehicle_coincidence.py": "/limit/",
"/files/explore_void_untie.py": "/element/",
"/files/explore_vsa_encoder.py": "/learner/",
"/files/explore_walls_provenance.py": "/size/",
"/files/explore_weight_thresholds.py": "/size/",
"/files/explore_wild_ring.py": "/clock/",
"/files/explore_witness_family.py": "/reading/",
"/files/explore_working_amnesiac.py": "/forget/",
"/files/explore_wrap_word.py": "/supply/",
"/files/explore_zeckendorf_discontinuity.py": "/reading/",
"/files/explore_zeckendorf_window.py": "/reading/",
"/flattening": "/flatten/",
"/flattening.html": "/flatten/",
"/flattening/": "/flatten/",
"/flattening/multipliers": "/flatten/",
"/flattening/multipliers/": "/flatten/",
"/flattening/products": "/flatten/",
"/flattening/products/": "/flatten/",
"/forcing.html": "/triple/",
"/forgetting.html": "/forget/",
"/frequency.html": "/fingerprint/",
"/generator.html": "/triple/",
"/growth.html": "/growth/",
"/growth/blind": "/headroom/",
"/growth/blind/": "/headroom/",
"/growth/carrier": "/clock/",
"/growth/carrier/": "/clock/",
"/growth/cascade": "/cascade/",
"/growth/cascade/": "/cascade/",
"/growth/clock": "/clock/",
"/growth/clock/": "/clock/",
"/growth/constants": "/growth/",
"/growth/constants/": "/growth/",
"/growth/degeneracy": "/triple/",
"/growth/degeneracy/": "/principal/",
"/growth/dial": "/clock/",
"/growth/dial/": "/clock/",
"/growth/fields": "/growth/",
"/growth/fields/": "/growth/",
"/growth/generator": "/triple/",
"/growth/generator/": "/principal/",
"/growth/inside": "/memory/",
"/growth/inside/": "/memory/",
"/growth/irreducibility": "/thermal/",
"/growth/irreducibility/": "/thermal/",
"/growth/limit": "/limit/",
"/growth/limit/": "/limit/",
"/growth/principal": "/principal/",
"/growth/principal/": "/principal/",
"/growth/probe": "/headroom/",
"/growth/probe/": "/headroom/",
"/growth/rings": "/clock/",
"/growth/rings/": "/clock/",
"/growth/schedule": "/limit/",
"/growth/schedule/": "/limit/",
"/growth/thermal": "/thermal/",
"/growth/thermal/": "/thermal/",
"/growth/triple": "/triple/",
"/growth/triple/": "/triple/",
"/heat": "/growth/",
"/heat.html": "/growth/",
"/image.html": "/image/",
"/inside.html": "/memory/",
"/instruments.html": "/instruments/",
"/instruments/audits": "/ruler/",
"/instruments/audits/": "/ruler/",
"/instruments/ceilings": "/ruler/",
"/instruments/ceilings/": "/ruler/",
"/instruments/sets": "/sets/",
"/instruments/sets/": "/sets/",
"/instruments/swap": "/sets/",
"/instruments/swap/": "/sets/",
"/instruments/uncertainty": "/ruler/",
"/instruments/uncertainty/": "/ruler/",
"/interface.html": "/machine/",
"/irreducibility.html": "/thermal/",
"/jumpset.html": "/observatory/",
"/lab": "/",
"/lab.html": "/",
"/learning": "/learner/",
"/learning.html": "/learner/",
"/learning/": "/learner/",
"/learning/audits": "/ruler/",
"/learning/audits/": "/ruler/",
"/learning/ceilings": "/ruler/",
"/learning/ceilings/": "/ruler/",
"/learning/collisions": "/collide/",
"/learning/collisions/": "/collide/",
"/learning/flattening": "/flatten/",
"/learning/flattening/": "/flatten/",
"/learning/forgetting": "/forget/",
"/learning/forgetting/": "/forget/",
"/learning/mechanisms": "/collide/",
"/learning/mechanisms/": "/collide/",
"/learning/multipliers": "/flatten/",
"/learning/multipliers/": "/flatten/",
"/learning/nesting": "/learner/",
"/learning/nesting/": "/learner/",
"/learning/products": "/flatten/",
"/learning/products/": "/flatten/",
"/learning/seeds": "/collide/",
"/learning/seeds/": "/collide/",
"/learning/sets": "/sets/",
"/learning/sets/": "/sets/",
"/learning/stalls": "/learner/",
"/learning/stalls/": "/learner/",
"/learning/substrate": "/learner/",
"/learning/substrate/": "/learner/",
"/learning/swap": "/sets/",
"/learning/swap/": "/sets/",
"/learning/uncertainty": "/ruler/",
"/learning/uncertainty/": "/ruler/",
"/limit.html": "/limit/",
"/lookahead.html": "/shifts/",
"/meaning.html": "/binding/",
"/measure": "/logic/",
"/measure.html": "/logic/",
"/measure/": "/logic/",
"/measure/price": "/gates/",
"/measure/price/": "/gates/",
"/measure/worlds": "/torsion/",
"/measure/worlds/": "/torsion/",
"/mechanisms.html": "/collide/",
"/members.html": "/shifts/",
"/multipliers.html": "/flatten/",
"/naming.html": "/naming/",
"/nesting.html": "/learner/",
"/numbers.html": "/coordinates/",
"/object.html": "/object/",
"/object/frequency": "/fingerprint/",
"/object/frequency/": "/fingerprint/",
"/object/naming": "/naming/",
"/object/naming/": "/naming/",
"/object/structure": "/naming/",
"/object/structure/": "/naming/",
"/observatory.html": "/observatory/",
"/openings.html": "/image/",
"/order.html": "/redundant/",
"/output.html": "/flush/",
"/piecewise.html": "/redundant/",
"/polynomial.html": "/redundant/",
"/prediction": "/naming/",
"/prediction.html": "/naming/",
"/price.html": "/gates/",
"/primer": "/object/",
"/primer.html": "/object/",
"/principal.html": "/principal/",
"/principal/degeneracy": "/triple/",
"/principal/degeneracy/": "/triple/",
"/principal/forcing": "/triple/",
"/principal/forcing/": "/triple/",
"/principal/generator": "/triple/",
"/principal/generator/": "/triple/",
"/principal/jumpset": "/observatory/",
"/principal/jumpset/": "/observatory/",
"/principal/observatory": "/observatory/",
"/principal/observatory/": "/observatory/",
"/principal/shortfall": "/principal/",
"/principal/shortfall/": "/principal/",
"/principal/triple": "/triple/",
"/principal/triple/": "/triple/",
"/probe.html": "/headroom/",
"/products.html": "/flatten/",
"/quadratic.html": "/ostrowski/",
"/reading.html": "/reading/",
"/reading/address": "/ostrowski/",
"/reading/address/": "/ostrowski/",
"/reading/chains": "/redundant/",
"/reading/chains/": "/redundant/",
"/reading/completions": "/reading/",
"/reading/completions/": "/reading/",
"/reading/lookahead": "/shifts/",
"/reading/lookahead/": "/shifts/",
"/reading/members": "/shifts/",
"/reading/members/": "/shifts/",
"/reading/output": "/flush/",
"/reading/output/": "/flush/",
"/reading/polynomial": "/redundant/",
"/reading/polynomial/": "/redundant/",
"/reading/quadratic": "/ostrowski/",
"/reading/quadratic/": "/ostrowski/",
"/reading/redundant": "/redundant/",
"/reading/redundant/": "/redundant/",
"/reading/shifts": "/shifts/",
"/reading/shifts/": "/shifts/",
"/recovery.html": "/supply/",
"/redundancy": "/redundant/",
"/redundancy.html": "/redundant/",
"/redundancy/": "/redundant/",
"/redundancy/chains": "/redundant/",
"/redundancy/chains/": "/redundant/",
"/redundancy/output": "/flush/",
"/redundancy/output/": "/flush/",
"/redundancy/piecewise": "/redundant/",
"/redundancy/piecewise/": "/redundant/",
"/redundancy/polynomial": "/redundant/",
"/redundancy/polynomial/": "/redundant/",
"/redundancy/redundant": "/redundant/",
"/redundancy/redundant/": "/redundant/",
"/redundant.html": "/redundant/",
"/ring": "/object/",
"/ring.html": "/object/",
"/rings.html": "/clock/",
"/schedule": "/limit/",
"/schedule.html": "/limit/",
"/schedule/": "/limit/",
"/schedule/carrier": "/clock/",
"/schedule/carrier/": "/clock/",
"/schedule/certificate": "/clock/",
"/schedule/certificate/": "/clock/",
"/schedule/clock": "/clock/",
"/schedule/clock/": "/clock/",
"/schedule/dial": "/clock/",
"/schedule/dial/": "/clock/",
"/schedule/image": "/image/",
"/schedule/image/": "/image/",
"/schedule/limit": "/limit/",
"/schedule/limit/": "/limit/",
"/schedule/openings": "/image/",
"/schedule/openings/": "/image/",
"/schedule/rings": "/clock/",
"/schedule/rings/": "/clock/",
"/seedflower": "/naming/",
"/seedflower.html": "/naming/",
"/seeds.html": "/collide/",
"/sets.html": "/sets/",
"/shifts.html": "/shifts/",
"/shortfall.html": "/principal/",
"/sieve": "/object/",
"/sieve.html": "/object/",
"/size.html": "/size/",
"/stalls.html": "/learner/",
"/structure.html": "/naming/",
"/substrate.html": "/learner/",
"/swap.html": "/sets/",
"/thermal.html": "/thermal/",
"/tools.html": "/tools/",
"/tools/delays": "/code/delays/",
"/tools/delays/": "/code/delays/",
"/tower.html": "/tower/",
"/triple.html": "/triple/",
"/uncertainty.html": "/ruler/",
"/walls": "/residues/",
"/walls.html": "/residues/",
"/walls/": "/residues/",
"/walls/algebra": "/budget/",
"/walls/algebra/": "/budget/",
"/walls/benford": "/dual/",
"/walls/benford/": "/dual/",
"/walls/dual": "/dual/",
"/walls/dual/": "/dual/",
"/walls/meaning": "/binding/",
"/walls/meaning/": "/binding/",
"/walls/numbers": "/coordinates/",
"/walls/numbers/": "/coordinates/",
"/walls/order": "/redundant/",
"/walls/order/": "/redundant/",
"/walls/quadratic": "/ostrowski/",
"/walls/quadratic/": "/ostrowski/",
"/walls/reading": "/reading/",
"/walls/reading/": "/reading/",
"/walls/redundant": "/redundant/",
"/walls/redundant/": "/redundant/",
"/walls/size": "/size/",
"/walls/size/": "/size/",
"/worlds.html": "/torsion/"
};
// Every page's address, its slash form.
const PAGES = new Set([
"/",
"/binding/",
"/bridges/",
"/budget/",
"/cascade/",
"/claims/",
"/clock/",
"/code/",
"/code/audit/",
"/code/band/",
"/code/binding/",
"/code/bonacci/",
"/code/borrow/",
"/code/bridges/",
"/code/budget/",
"/code/carrier/",
"/code/cascade/",
"/code/ceiling/",
"/code/census/",
"/code/chains/",
"/code/checksum/",
"/code/clock/",
"/code/clocks/",
"/code/cofactor/",
"/code/collide/",
"/code/collision/",
"/code/column/",
"/code/comparators/",
"/code/comparison/",
"/code/conductor/",
"/code/coordinates/",
"/code/coverage_cap/",
"/code/crt/",
"/code/cubic/",
"/code/delays/",
"/code/dial/",
"/code/door/",
"/code/dual/",
"/code/element/",
"/code/element_ring/",
"/code/erring_label/",
"/code/erring_widths/",
"/code/estimators/",
"/code/faces/",
"/code/fates/",
"/code/fingerprint/",
"/code/flatten/",
"/code/floors/",
"/code/flush/",
"/code/forecast/",
"/code/forget/",
"/code/free_image/",
"/code/gaplaw/",
"/code/gates/",
"/code/growth/",
"/code/halfsize/",
"/code/headroom/",
"/code/image/",
"/code/learner/",
"/code/lid/",
"/code/limit/",
"/code/lira/",
"/code/logic/",
"/code/machine/",
"/code/manystream/",
"/code/members/",
"/code/memory/",
"/code/mixing/",
"/code/module_law/",
"/code/naming/",
"/code/ostrowski/",
"/code/pentanomial/",
"/code/piecewise/",
"/code/poles/",
"/code/precision/",
"/code/principal/",
"/code/quadrinomial/",
"/code/quarantine/",
"/code/quarter/",
"/code/race/",
"/code/rank2/",
"/code/rates/",
"/code/rationed/",
"/code/reading/",
"/code/readout/",
"/code/redundant/",
"/code/relative/",
"/code/rider/",
"/code/rns_compare/",
"/code/rooted/",
"/code/rung/",
"/code/seat/",
"/code/selfreport/",
"/code/sensor/",
"/code/sets/",
"/code/shifts/",
"/code/shortfall/",
"/code/sign/",
"/code/size/",
"/code/sizeless/",
"/code/spectrum/",
"/code/sprawl/",
"/code/staircase/",
"/code/standing/",
"/code/statements/",
"/code/stop/",
"/code/storey/",
"/code/supply/",
"/code/swaps/",
"/code/tame/",
"/code/thermal/",
"/code/torsion/",
"/code/tower_growth/",
"/code/tower_rungs/",
"/code/triangle/",
"/code/triple/",
"/code/weld/",
"/code/wild/",
"/code/winner/",
"/collide/",
"/coordinates/",
"/digits/",
"/dual/",
"/element/",
"/fingerprint/",
"/flatten/",
"/flush/",
"/forget/",
"/gates/",
"/growth/",
"/headroom/",
"/image/",
"/instruments/",
"/key/",
"/learner/",
"/limit/",
"/local/",
"/logic/",
"/machine/",
"/machines/",
"/memory/",
"/naming/",
"/object/",
"/observatory/",
"/ostrowski/",
"/principal/",
"/rates/",
"/reading/",
"/redundant/",
"/residues/",
"/ruler/",
"/sets/",
"/shifts/",
"/size/",
"/supply/",
"/terms/",
"/thermal/",
"/tools/",
"/torsion/",
"/tower/",
"/triple/",
"/walks/"
]);

async function dead(env, url) {
  const r = await env.ASSETS.fetch(new URL('/404', url.origin));
  return new Response(r.body, {status: 404,
    headers: {'content-type': 'text/html; charset=utf-8'}});
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    const path = url.pathname;
    const go = (to) => Response.redirect(new URL(to, url.origin), STATUS);
    if (Object.prototype.hasOwnProperty.call(MOVED, path)) return go(MOVED[path]);
    if (path.endsWith('/index.html')) {
      const dir = path.slice(0, -'index.html'.length);
      return PAGES.has(dir) ? go(dir) : dead(env, url);
    }
    if (path.endsWith('.html')) return dead(env, url);
    if (path.endsWith('/')) {
      return PAGES.has(path) ? env.ASSETS.fetch(request) : dead(env, url);
    }
    if (!path.slice(path.lastIndexOf('/') + 1).includes('.')) {
      return PAGES.has(path + '/') ? go(path + '/') : dead(env, url);
    }
    const r = await env.ASSETS.fetch(request);
    if (r.status === 404) return dead(env, url);
    if (path.endsWith('.py') || path.endsWith('.md')) {
      const out = new Response(r.body, r);
      out.headers.set('content-type', 'text/plain; charset=utf-8');
      return out;
    }
    return r;
  }
};
