// worker.js -- GENERATED by build.py from manifest.py. Do not edit.
export default {
  async fetch(request, env) {
    const url = new URL(request.url);

    /* 301s for every URL that ever shipped -- generated from the manifest */
    const REDIRECTS = {
      '/tower': '/object',
      '/tower.html': '/object',
      '/crt': '/object',
      '/crt.html': '/object',
      '/heat': '/growth',
      '/heat.html': '/growth',
      '/ecc': '/object',
      '/ecc.html': '/object',
      '/automata': '/walls',
      '/automata.html': '/walls',
      '/dynamics': '/object',
      '/dynamics.html': '/object',
      '/prediction': '/object',
      '/prediction.html': '/object',
      '/build': '/',
      '/build.html': '/',
      '/primer': '/object',
      '/primer.html': '/object',
      '/ring': '/object',
      '/ring.html': '/object',
      '/sieve': '/object',
      '/sieve.html': '/object',
      '/seedflower': '/object',
      '/seedflower.html': '/object',
      '/engineering': '/',
      '/engineering.html': '/',
      '/lab': '/',
      '/lab.html': '/',
      '/constants': '/growth/constants',
      '/reading': '/walls/reading',
    };
    const redir = REDIRECTS[url.pathname];
    if (redir) return Response.redirect(new URL(redir, url.origin), 301);

    /* Static assets -- everything with an extension */
    if (url.pathname.includes('.')) {
      return env.ASSETS.fetch(request);
    }

    /* Every URL the site has, mapped to its page file -- dist is flat,
       the URLs nest. EXACT match: a path the manifest does not carry is
       not a page here, however plausibly it is spelled. */
    const PAGES = {
      '/': 'index',
      '/object': 'object',
      '/object/structure': 'structure',
      '/growth': 'growth',
      '/growth/limit': 'limit',
      '/growth/schedule': 'schedule',
      '/growth/clock': 'clock',
      '/growth/inside': 'inside',
      '/growth/thermal': 'thermal',
      '/growth/constants': 'constants',
      '/computation': 'computation',
      '/computation/recovery': 'recovery',
      '/observatory': 'observatory',
      '/walls': 'walls',
      '/walls/numbers': 'numbers',
      '/walls/meaning': 'meaning',
      '/walls/reading': 'reading',
      '/walls/algebra': 'algebra',
      '/measure': 'measure',
      '/measure/worlds': 'worlds',
      '/measure/price': 'price',
      '/learning': 'learning',
      '/learning/substrate': 'substrate',
      '/learning/forgetting': 'forgetting',
      '/learning/ceilings': 'ceilings',
      '/claims': 'claims',
    };
    const page = PAGES[url.pathname.replace(/(.)\/$/, '$1')];
    if (!page) return new Response(null, {status: 404});
    return env.ASSETS.fetch(new URL('/' + page + '.html', url.origin));
  }
};
