"""
The idempotent lattice as a non-Boolean logic.

The 2^k idempotents of a rung are truth values; the ring polynomials
    AND(a,b) = a*b
    OR(a,b)  = a + b - a*b
    NOT(a)   = 1 - a
    IMP(a,b) = 1 - a + a*b          (= NOT(a) OR b)
restrict to exact Boolean logic on the lattice (e_S <-> subset S).
The probe: what do these SAME polynomials do on the rest of the ring,
where elements are not idempotent?

Findings preview (full statements at the bottom):
  1. On the lattice: exact Boolean algebra 2^k, residuation law exhaustive.
  2. Off the lattice: every failing Boolean law fails inside the defect
     ideal generated by delta(x) = x^2 - x; the charted laws deform in a
     single variable. delta is the curvature.
  3. Truth is per-channel: delta(a) = 0 on channel p iff residue in {0,1}.
  4. Collapse a -> a^lambda = e_supp(a) is a homomorphism for AND but not
     OR: graded disjunction has one-directional destructive interference,
     rate (p-2)/(p-1)^2 per channel on true-true pairs.
  5. The counting valuation mu(e_S) = 1/prod(p not in S) is multiplicative
     (log-additive over EXCLUDED channels): strength = what a proposition
     forbids. Additive valuations exist but are exactly channel-weight
     functionals (disjoint join IS ring sum).
  6. delta COMPOSES exactly under every connective: delta(NOT a) =
     delta(a); delta(a AND b) = delta(a)delta(b) + delta(a)b + a delta(b)
     (a twisted Leibniz rule, equivalently a^2 delta(b) + delta(a) b);
     OR and IMP are the NOT-conjugates; delta(a+b) = delta(a) + delta(b)
     + 2ab (the polarization that dies in char 2 -- Artin-Schreier).
     Nesting in the four CONNECTIVES never CREATES non-classicality
     (supp(delta(F)) inside the union of the inputs' defect supports for
     every AND/OR/NOT/IMP formula; bare ring + escapes -- 2ab creates
     defect from classical inputs); it cancels on a channel in exactly
     TWO ways per binary connective (AND: partner 0 or x^{-1}; OR:
     partner 1 or its NOT-mirror; IMP the same two per argument
     position; NOT: never).
  7. The quantifier was the measurement: the collapse DIA(a) =
     a^lambda ("true to SOME degree") and its De Morgan conjugate BOX(a)
     = 1 - (1-a)^lambda ("FULLY true") are an exact quantifier/modal
     pair: DIA NOT = NOT BOX exactly (finding 4's NOT-failure is NOT
     exchanging the pair), DIA exact on AND, BOX exact on OR, each
     leaking on the dual connective at the SAME p-2 per-channel count
     (NOT maps one mismatch set onto the other). Mixed-form T, 4, 5, K,
     necessitation, and the Halmos closure law hold exactly. Quantifying
     over CHANNELS instead is walled: [a = 0] is not channel-local (two
     constraints pin one channel value both ways), so no ring polynomial
     plays the global quantifier -- degree quantifiers are free,
     channel quantifiers cost the deleted place. The orthomodular hook
     DISSOLVES: orthomodularity is a lattice law and the graded region
     has no order (finding 3) -- no carrier for the question.

Runs on RAD (k=7) with exhaustive small-k cross-checks. ~1 s, tiny memory.
"""

import sys, os, random
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from crt import (Ring, RAD_RING, encode, decode, idempotent, all_idempotents,
                 primes_up_to)

random.seed(37)
R = RAD_RING
N = R.N
K = R.k

def section(title):
    print()
    print("=" * 72)
    print(title)
    print("=" * 72)

# Ring-op shorthands on integers mod N
def AND(a, b, n=N): return (a * b) % n
def OR(a, b, n=N):  return (a + b - a * b) % n
def NOT(a, n=N):    return (1 - a) % n
def IMP(a, b, n=N): return (1 - a + a * b) % n
def DELTA(a, n=N):  return (a * a - a) % n

def supp(a, ring):
    return frozenset(i for i, r in enumerate(encode(a, ring)) if r != 0)

# ───────────────────────────────────────────────────────────────────────
section("I. THE CONNECTIVES CLOSE ON THE LATTICE (exhaustive, RAD)")
# ───────────────────────────────────────────────────────────────────────

idems = all_idempotents(R)                      # [(channel_set, value)]
val_of = {chans: val for chans, val in idems}
vals = [val for _, val in idems]
ALL = frozenset(range(K))

ok = True
for S, eS in idems:
    if NOT(eS) != val_of[ALL - S]:
        ok = False
    for T, eT in idems:
        if AND(eS, eT) != val_of[S & T]: ok = False
        if OR(eS, eT)  != val_of[S | T]: ok = False
        if IMP(eS, eT) != val_of[(ALL - S) | T]: ok = False
print(f"AND->intersection, OR->union, NOT->complement, IMP->(S^c)|T")
print(f"  over all {len(idems)}^2 = {len(idems)**2} idempotent pairs: "
      f"{'VERIFIED' if ok else 'FAILED'}")
assert ok

# ───────────────────────────────────────────────────────────────────────
section("II. RESIDUATION LAW ON THE LATTICE (exhaustive 128^3, RAD)")
# ───────────────────────────────────────────────────────────────────────
# Order: e_S <= e_T iff e_S * e_T = e_S (iff S subset of T).
# Residuation: (x AND a) <= b  iff  x <= IMP(a, b).

idx = {val: i for i, val in enumerate(vals)}
n_id = len(vals)
LE  = [[AND(x, b) == x for b in vals] for x in vals]
ANDt = [[idx[AND(x, a)] for a in vals] for x in vals]
IMPt = [[idx[IMP(a, b)] for b in vals] for a in vals]

fails = 0
for xi in range(n_id):
    LEx, ANDx = LE[xi], ANDt[xi]
    for ai in range(n_id):
        xa = ANDx[ai]
        IMPa = IMPt[ai]
        LExa = LE[xa]
        for bi in range(n_id):
            if LExa[bi] != LEx[IMPa[bi]]:
                fails += 1
print(f"(x AND a) <= b  iff  x <= (a IMP b): "
      f"{n_id**3} triples, {fails} failures "
      f"({'VERIFIED' if fails == 0 else 'FAILED'})")
assert fails == 0

# Off the lattice the order does not even exist -- DEFINITIONALLY:
# a <= a unfolds to a*a = a, which IS idempotence. No experiment needed;
# the graded region carries no internal order, the logic's order
# structure lives entirely on the skeleton.
print("Off-lattice: a <= a unfolds to a*a = a, i.e. idempotence itself --")
print("  the graded region carries NO internal order (definitional).")

# ───────────────────────────────────────────────────────────────────────
section("III. THE GRADED EXTENSION: delta(a) = a^2 - a IS THE CURVATURE")
# ───────────────────────────────────────────────────────────────────────
# The same polynomials act on ALL ring elements. Laws that survive
# identically (in ANY commutative ring -- nothing tower-specific):
#   commutativity, associativity of AND and OR, De Morgan both ways,
#   double negation, identity elements, contraposition.
# The charted laws below each fail by delta(a) times a polynomial
# (the general defect-ideal statement is printed after the table):

LAWS = [
    ("a AND a - a            = delta(a)",
     lambda a, b, c, n: (AND(a, a, n) - a - DELTA(a, n)) % n),
    ("a OR a - a             = -delta(a)",
     lambda a, b, c, n: (OR(a, a, n) - a + DELTA(a, n)) % n),
    ("a AND NOT a            = -delta(a)",
     lambda a, b, c, n: (AND(a, NOT(a, n), n) + DELTA(a, n)) % n),
    ("a OR NOT a - 1         = delta(a)          [excluded middle]",
     lambda a, b, c, n: (OR(a, NOT(a, n), n) - 1 - DELTA(a, n)) % n),
    ("a IMP a - 1            = delta(a)",
     lambda a, b, c, n: (IMP(a, a, n) - 1 - DELTA(a, n)) % n),
    ("a AND (a OR b) - a     = delta(a)(1-b)     [absorption]",
     lambda a, b, c, n: (AND(a, OR(a, b, n), n) - a
                         - DELTA(a, n) * (1 - b)) % n),
    ("a OR (a AND b) - a     = -delta(a)b        [absorption]",
     lambda a, b, c, n: (OR(a, AND(a, b, n), n) - a
                         + DELTA(a, n) * b) % n),
    ("a AND (b OR c) - (a AND b) OR (a AND c) = delta(a)bc",
     lambda a, b, c, n: (AND(a, OR(b, c, n), n)
                         - OR(AND(a, b, n), AND(a, c, n), n)
                         - DELTA(a, n) * b * c) % n),
    ("a OR (b AND c) - (a OR b) AND (a OR c) = -delta(a)(1-b)(1-c)",
     lambda a, b, c, n: (OR(a, AND(b, c, n), n)
                         - AND(OR(a, b, n), OR(a, c, n), n)
                         + DELTA(a, n) * (1 - b) * (1 - c)) % n),
    ("a AND (a IMP b) - (a AND b) = -delta(a)(1-b) [modus ponens leak]",
     lambda a, b, c, n: (AND(a, IMP(a, b, n), n) - AND(a, b, n)
                         + DELTA(a, n) * (1 - b)) % n),
    ("(a IMP b) - (NOT b IMP NOT a) = 0           [contraposition holds]",
     lambda a, b, c, n: (IMP(a, b, n) - IMP(NOT(b, n), NOT(a, n), n)) % n),
]

# Exhaustive at k=3 (Z/30: 27,000 triples), random at RAD (20,000 triples).
R3 = Ring("K3", (2, 3, 5), (1, 1, 1))
n3 = R3.N
ex_ok = all(law(a, b, c, n3) == 0
            for _, law in LAWS
            for a in range(n3) for b in range(n3) for c in range(n3))
print(f"Exhaustive Z/30 (all 30^3 triples x {len(LAWS)} identities): "
      f"{'VERIFIED' if ex_ok else 'FAILED'}")
assert ex_ok

triples = [(random.randrange(N), random.randrange(N), random.randrange(N))
           for _ in range(20000)]
rad_ok = all(law(a, b, c, N) == 0 for _, law in LAWS for a, b, c in triples)
print(f"Random RAD (20,000 triples x {len(LAWS)} identities):      "
      f"{'VERIFIED' if rad_ok else 'FAILED'}")
assert rad_ok
print()
for name, _ in LAWS:
    print(f"  {name}")
print()
print("Each charted law deforms in a SINGLE variable: it holds whenever")
print("that variable is classical, the others arbitrary. The general fact")
print("(any law, any number of deforming variables): the idempotents of any")
print("commutative ring form a Boolean algebra under these connectives")
print("(standard), so for ANY Boolean law LHS - RHS vanishes in")
print("Z[x]/(x_i^2 - x_i) -- the defect lies in the IDEAL generated by the")
print("delta(x_i). Every failure is a combination sum(delta(x_i) * g_i).")
print()
print("delta vanishes channel-wise: residue r contributes r(r-1) = 0 iff")
print("r in {0,1}. An element is CLASSICAL exactly where its channels read")
print("0 or 1; the 2^k idempotents are the elements classical everywhere.")

# Channel-wise check: supp(delta(a)) = non-classical channels of a.
ok = True
for a in random.sample(range(N), 2000):
    t = encode(a, R)
    nonclass = frozenset(i for i, r in enumerate(t) if r not in (0, 1))
    if supp(DELTA(a), R) != nonclass:
        ok = False
print(f"supp(delta(a)) = non-classical channels: 2,000 random elements: "
      f"{'VERIFIED' if ok else 'FAILED'}")
assert ok

# ───────────────────────────────────────────────────────────────────────
section("IV. COLLAPSE a -> a^lambda: MEASUREMENT, AND ITS ASYMMETRY")
# ───────────────────────────────────────────────────────────────────────
# x^lambda = e_supp(x) (the 490 mechanism): every element has a
# classical shadow. Is collapse a homomorphism of the logic?

def collapse(a, ring=R):
    return pow(a, ring.lam, ring.N)

ok = all(collapse(a) == val_of[supp(a, R)] for a in random.sample(range(N), 2000))
print(f"collapse(a) = e_supp(a): 2,000 random elements: "
      f"{'VERIFIED' if ok else 'FAILED'}")
assert ok

# AND: exact. Fields have no zero divisors, so supp(ab) = supp(a) & supp(b).
pairs = [(random.randrange(N), random.randrange(N)) for _ in range(20000)]
and_ok = all(collapse(AND(a, b)) == AND(collapse(a), collapse(b))
             for a, b in pairs)
print(f"collapse(a AND b) = collapse(a) AND collapse(b): 20,000 pairs: "
      f"{'VERIFIED' if and_ok else 'FAILED'}  [exact: channels are fields]")
assert and_ok

# NOT: fails exactly on the defect channels.
not_ok = all(
    (lambda d, m: d == m)(
        frozenset(i for i, (x, y) in enumerate(zip(
            encode(collapse(NOT(a)), R), encode(NOT(collapse(a)), R))) if x != y),
        supp(DELTA(a), R))
    for a in random.sample(range(N), 2000))
print(f"collapse(NOT a) vs NOT collapse(a): differ EXACTLY on supp(delta(a)):")
print(f"  2,000 random elements: {'VERIFIED' if not_ok else 'FAILED'}")
assert not_ok

# OR: destructive interference. On channel p, two TRUE inputs (x,y != 0)
# disjoin to FALSE when x + y - xy = 0, i.e. (1-x)(1-y) = 1. Substitute
# u = 1-x: u must be invertible (u != 0, since u = 0 makes the product 0),
# and u != 1 (that is x != 0); then y = 1 - u^{-1} is determined, and
# y != 0 holds automatically (u^{-1} = 1 would need u = 1). So u ranges
# over F_p minus {0, 1}: exactly p - 2 of the (p-1)^2 true-true pairs.
print()
print("OR interference census (exact, per channel, all pairs in F_p^2):")
print(f"  {'p':>4} {'true-true pairs':>16} {'interfering':>12} "
      f"{'rate':>10} {'(p-2)/(p-1)^2':>14}")
for p in primes_up_to(23):
    inter = sum(1 for x in range(1, p) for y in range(1, p)
                if (x + y - x * y) % p == 0)
    rate = inter / (p - 1) ** 2
    pred = (p - 2) / (p - 1) ** 2
    print(f"  {p:>4} {(p-1)**2:>16} {inter:>12} {rate:>10.4f} {pred:>14.4f}")
    assert inter == p - 2
print("  interfering count = p - 2 EXACTLY at every p (proved by the")
print("  u = 1-x substitution; census confirms).")

# One-directional: OR never fabricates truth (0 OR 0 = 0 per channel),
# and AND never interferes (xy = 0 iff x = 0 or y = 0 in a field).
fab = sum(1 for a, b in pairs
          if any(za == 0 and zb == 0 and zo != 0
                 for za, zb, zo in zip(encode(a, R), encode(b, R),
                                       encode(OR(a, b), R))))
print(f"OR fabricating truth from two falses: {fab}/20,000 pairs "
      f"[impossible: 0+0-0 = 0]")
assert fab == 0

# Tuple-level mismatch rate at RAD: per channel, uniform pairs mismatch
# with prob (p-2)/p^2; tuple mismatches if any channel does.
pred_tuple = 1.0
for p in R.primes:
    pred_tuple *= 1 - (p - 2) / p ** 2
pred_tuple = 1 - pred_tuple
mism = sum(1 for a, b in pairs
           if collapse(OR(a, b)) != OR(collapse(a), collapse(b)))
print(f"collapse(a OR b) != collapse(a) OR collapse(b) at RAD: "
      f"measured {mism/len(pairs):.4f}, predicted {pred_tuple:.4f}")
print()
print("ASYMMETRY: graded conjunction is classical (collapse-exact);")
print("graded disjunction interferes destructively, one-directionally")
print("(truth can be lost, never fabricated), at rate ~1/p per channel.")

# ───────────────────────────────────────────────────────────────────────
section("V. VALUATION: WHAT IS LOGICAL STRENGTH HERE?")
# ───────────────────────────────────────────────────────────────────────
# (a) Disjoint join IS ring sum: e_S e_T = 0  =>  e_{S|T} = e_S + e_T.
ok = all(OR(val_of[S], val_of[T]) == (val_of[S] + val_of[T]) % N
         and (val_of[S] + val_of[T]) % N == val_of[S | T]
         for S, _ in idems for T, _ in idems if not (S & T))
print(f"(a) Disjoint join = ring sum (all disjoint idempotent pairs): "
      f"{'VERIFIED' if ok else 'FAILED'}")
assert ok
print("    => every ADDITIVE valuation is a channel-weight functional")
print("       v(e_S) = sum of w_p over p in S (primitive decomposition).")
print("       Probability-shaped strengths exist but carry no more")
print("       information than a weight per channel. The IE gate")
print("       w_p = -1/(p-1) (moment resonance) is one such -- SIGNED,")
print("       so not a probability.")

# (b) The counting valuation: mu(e_S) = #{x : x e_S = x} / N.
#     x e_S = x iff supp(x) subset S: count = prod(p in S) = N/prod(p not in S).
print()
print("(b) Counting valuation mu(e_S) = #{x : x*e_S = x}/N = 1/prod(p not in S)")
mu = {}
for S, eS in idems:
    cnt = 1
    for i in range(K):
        if i in S:
            cnt *= R.primes[i]
    mu[S] = cnt / N
spot = all(abs(mu[S] - 1 / __import__('math').prod(
    R.primes[i] for i in range(K) if i not in S)) < 1e-15 for S, _ in idems)
# direct count on a sub-check (k=3 ring, exhaustive)
mu3_ok = True
for mask in range(8):
    S3 = frozenset(i for i in range(3) if mask & (1 << i))
    e3 = idempotent(S3, R3)
    direct = sum(1 for x in range(n3) if (x * e3) % n3 == x) / n3
    closed = 1.0
    for i in range(3):
        if i not in S3:
            closed /= R3.primes[i]
    if abs(direct - closed) > 1e-12:
        mu3_ok = False
print(f"    closed form vs direct count, exhaustive k=3: "
      f"{'VERIFIED' if mu3_ok else 'FAILED'}")
assert mu3_ok and spot

# Multiplicativity: mu(S&T) * mu(S|T) = mu(S) * mu(T)  (all pairs, RAD).
# Exact over the integer counts cnt(S) = prod(p in S) (mu = cnt/N).
def cnt(S):
    out = 1
    for i in S:
        out *= R.primes[i]
    return out
ok = all(cnt(S & T) * cnt(S | T) == cnt(S) * cnt(T)
         for S, _ in idems for T, _ in idems)
print(f"    mu(S AND T) * mu(S OR T) = mu(S) * mu(T), all 128^2 pairs: "
      f"{'VERIFIED' if ok else 'FAILED'}")
assert ok
print()
print("    mu is MULTIPLICATIVE, not additive: -log mu(e_S) = sum of log p")
print("    over the EXCLUDED primes. The strength of a truth value is the")
print("    log-mass of what it forbids -- content, not chance. It is")
print("    additive in the log domain: at home in the tropical/idempotent-")
print("    analysis semiring (the Maslov probe), not the probability one.")
print("    mu(0) = 1/N != 0: even FALSE forbids only finitely much here.")

# ───────────────────────────────────────────────────────────────────────
section("VI. DELTA COMPOSES UNDER NESTING (exact laws)")
# ───────────────────────────────────────────────────────────────────────
# The earlier chart proved every failing law lands in the defect ideal. The
# open hook asked whether delta itself COMPOSES under formula nesting.
# It does, exactly -- closed laws by substitution (a^2 = delta(a) + a):

COMP = [
    ("delta(a AND b) = delta(a)delta(b) + delta(a)b + a delta(b)",
     lambda a, b, n: (DELTA(AND(a, b, n), n)
                      - (DELTA(a, n) * DELTA(b, n)
                         + DELTA(a, n) * b + a * DELTA(b, n))) % n),
    ("delta(a AND b) = a^2 delta(b) + delta(a) b   [twisted Leibniz]",
     lambda a, b, n: (DELTA(AND(a, b, n), n)
                      - (a * a * DELTA(b, n) + DELTA(a, n) * b)) % n),
    ("delta(NOT a)   = delta(a)                    [NOT preserves delta]",
     lambda a, b, n: (DELTA(NOT(a, n), n) - DELTA(a, n)) % n),
    ("delta(a OR b)  = delta(a)delta(b) + delta(a)(1-b) + (1-a)delta(b)",
     lambda a, b, n: (DELTA(OR(a, b, n), n)
                      - (DELTA(a, n) * DELTA(b, n)
                         + DELTA(a, n) * (1 - b) + (1 - a) * DELTA(b, n))) % n),
    ("delta(a IMP b) = delta(a)delta(b) + delta(a)(1-b) + a delta(b)",
     lambda a, b, n: (DELTA(IMP(a, b, n), n)
                      - (DELTA(a, n) * DELTA(b, n)
                         + DELTA(a, n) * (1 - b) + a * DELTA(b, n))) % n),
    ("delta(a + b)   = delta(a) + delta(b) + 2ab   [polarization]",
     lambda a, b, n: (DELTA((a + b) % n, n)
                      - (DELTA(a, n) + DELTA(b, n) + 2 * a * b)) % n),
]
ex_ok = all(law(a, b, n3) == 0 for _, law in COMP
            for a in range(n3) for b in range(n3))
rad_ok = all(law(a, b, N) == 0 for _, law in COMP for a, b in pairs)
print(f"Composition laws, exhaustive Z/30 (900 pairs) "
      f"+ 20,000 RAD pairs: {'VERIFIED' if ex_ok and rad_ok else 'FAILED'}")
assert ex_ok and rad_ok
for name, _ in COMP:
    print(f"  {name}")
print()
print("delta obeys a twisted LEIBNIZ RULE for AND (twist a -> a^2 --")
print("multiplicative but not additive, so delta is no derivation: its")
print("additive failure is exactly the 2ab polarization) and is an exact")
print("invariant of NOT; OR and IMP are the NOT-conjugates of the AND law.")
print("The additive polarization 2ab dies in characteristic 2: there delta")
print("is the additive Artin-Schreier map x^2 - x (our channel 2 is wholly")
print("classical -- F_2 = {0,1} -- so the graded logic lives on odd channels).")

# Support monotonicity: nesting in the four CONNECTIVES never CREATES
# non-classicality. By the AND/OR/NOT/IMP laws above, delta(F) lies
# channel-wise in the ideal of the inputs' deltas, so supp(delta(F)) is
# contained in the union of input defect supports -- induction over the
# formula tree. Bare ring + is OUTSIDE this scope: its polarization 2ab
# does not lie in the ideal (delta(1+1) = 2 from two classical inputs).
# Mechanical: random connective trees.
def rand_formula(depth):
    if depth == 0:
        return random.randrange(3)
    op = random.choice(("AND", "OR", "IMP", "NOT"))
    if op == "NOT":
        return ("NOT", rand_formula(depth - 1))
    return (op, rand_formula(depth - 1), rand_formula(depth - 1))

def eval_formula(f, env, n):
    if isinstance(f, int):
        return env[f]
    if f[0] == "NOT":
        return NOT(eval_formula(f[1], env, n), n)
    x = eval_formula(f[1], env, n)
    y = eval_formula(f[2], env, n)
    return {"AND": AND, "OR": OR, "IMP": IMP}[f[0]](x, y, n)

strict = 0
for _ in range(400):
    f = rand_formula(random.randrange(2, 6))
    env = [random.randrange(N) for _ in range(3)]
    allowed = frozenset().union(*(supp(DELTA(v), R) for v in env))
    got = supp(DELTA(eval_formula(f, env, N)), R)
    assert got <= allowed
    if got < allowed:
        strict += 1
print(f"supp(delta(F)) inside union of input defect supports: 400 random")
print(f"  formulas (depth 2-5, 3 RAD variables): VERIFIED "
      f"({strict} strictly smaller -- cancellation is real)")

# Cancellation is EXACTLY two partners per binary connective. For x
# outside {0,1} on channel p: delta(xy) = 0 iff xy in {0,1} iff y = 0
# (annihilate by FALSE) or y = x^{-1} (two non-classicals multiply to
# TRUE); dually delta(x OR y) = 0 iff y = 1 or y = 1 - (1-x)^{-1}.
# IMP (asymmetric) has the same count in each argument position:
# antecedent x non-classical -> y in {1, 1 - x^{-1}}; consequent y
# non-classical -> x in {0, (1-y)^{-1}}. NOT never cancels.
for p in primes_up_to(23):
    for x in range(2, p):
        inv = pow(x, p - 2, p)
        mirror = (1 - pow((1 - x) % p, p - 2, p)) % p
        assert {y for y in range(p) if (x * y) % p in (0, 1)} == {0, inv}
        assert {y for y in range(p)
                if (x + y - x * y) % p in (0, 1)} == {1, mirror}
        assert {y for y in range(p)
                if (1 - x + x * y) % p in (0, 1)} == {1, (1 - inv) % p}
        assert {w for w in range(p)
                if (1 - w + w * x) % p in (0, 1)} == \
            {0, pow((1 - x) % p, p - 2, p)}
print()
print("Cancellation census (all p <= 23, all non-classical x): the AND")
print("partners are exactly {0, x^{-1}}, the OR partners exactly")
print("{1, 1-(1-x)^{-1}}, the IMP partners {1, 1-x^{-1}} (as antecedent)")
print("and {0, (1-x)^{-1}} (as consequent) -- two each, VERIFIED. A")
print("non-classical channel is classicalized only by absorption or by an")
print("inverse.")

# ───────────────────────────────────────────────────────────────────────
section("VII. THE QUANTIFIER PAIR: COLLAPSE AND ITS CONJUGATE")
# ───────────────────────────────────────────────────────────────────────
# The 'what plays quantifier' hook. Answer: the measurement already was
# one -- HALF of a pair. DIA(a) = a^lambda reads 'true to SOME degree'
# (channel 1 iff residue != 0); its De Morgan conjugate
# BOX(a) = 1 - (1-a)^lambda reads 'FULLY true' (channel 1 iff residue = 1).
# Both are ring polynomials, hence channel-local -- they exist for free.

def DIA(a, n=N, lam=R.lam):
    return pow(a % n, lam, n)

def BOX(a, n=N, lam=R.lam):
    return (1 - pow((1 - a) % n, lam, n)) % n

singles = random.sample(range(N), 2000)
ok = all(encode(DIA(a), R) == tuple(1 if r != 0 else 0 for r in encode(a, R))
         and encode(BOX(a), R) == tuple(1 if r == 1 else 0 for r in encode(a, R))
         for a in singles)
print(f"Channel reads -- DIA: 1 iff residue != 0; BOX: 1 iff residue = 1:")
print(f"  2,000 random elements: {'VERIFIED' if ok else 'FAILED'}")
assert ok

# De Morgan conjugacy is EXACT (definitional: (1-a)^lambda = e_supp(1-a)).
# Finding 4's NOT-failure re-read: collapse(NOT a) != NOT(collapse a)
# because NOT exchanges the two quantifiers, not because NOT breaks.
ok = all(DIA(NOT(a)) == NOT(BOX(a)) and BOX(NOT(a)) == NOT(DIA(a))
         for a in singles)
print(f"DIA NOT = NOT BOX and BOX NOT = NOT DIA (exact conjugacy): "
      f"{'VERIFIED' if ok else 'FAILED'}")
assert ok

# Exactness mirror: DIA commutes with AND (section IV), BOX with OR.
box_or_ok = all(BOX(OR(a, b)) == OR(BOX(a), BOX(b)) for a, b in pairs)
print(f"BOX(a OR b) = BOX a OR BOX b: 20,000 pairs: "
      f"{'VERIFIED' if box_or_ok else 'FAILED'}  [exact: (1-x)(1-y)=0 iff x=1 or y=1]")
assert box_or_ok

# Each leaks on its dual connective -- at the SAME per-channel count.
# DIA over OR loses truth (interference, section IV); BOX over AND GAINS
# truth by inversion: xy = 1 with x != 1 (two partial truths multiply to
# full truth). NOT maps each mismatch set onto the other, pair by pair.
print()
print("The leak mirror (per channel, exhaustive):")
print(f"  {'p':>4} {'DIA-over-OR mismatches':>24} {'BOX-over-AND mismatches':>24}")
for p in primes_up_to(23):
    or_set = {(x, y) for x in range(p) for y in range(p)
              if ((x + y - x * y) % p != 0) != (x != 0 or y != 0)}
    and_set = {(x, y) for x in range(p) for y in range(p)
               if ((x * y) % p == 1) != (x == 1 and y == 1)}
    assert len(or_set) == len(and_set) == max(p - 2, 0)
    assert {((1 - x) % p, (1 - y) % p) for x, y in or_set} == and_set
    print(f"  {p:>4} {len(or_set):>24} {len(and_set):>24}")
print("  both = p - 2 exactly; NOT biject the two sets (VERIFIED).")
mism_box = sum(1 for a, b in pairs
               if BOX(AND(a, b)) != AND(BOX(a), BOX(b)))
print(f"  RAD tuple level: BOX-over-AND mismatch {mism_box/len(pairs):.4f}, "
      f"predicted {pred_tuple:.4f} (same law as DIA-over-OR)")

# The S5/monadic contact: the listed laws hold EXACTLY (per-channel case
# analysis; the bulk is not Boolean, so each is checked on its own).
ok_t = all(AND(BOX(a), a) == BOX(a) and AND(DIA(a), a) == a for a in singles)
print()
print(f"Mixed-form T -- BOX(a) AND a = BOX(a); DIA(a) AND a = a: "
      f"{'VERIFIED' if ok_t else 'FAILED'}")
assert ok_t
ok_45 = all(DIA(DIA(a)) == DIA(a) and BOX(BOX(a)) == BOX(a)
            and BOX(DIA(a)) == DIA(a) and DIA(BOX(a)) == BOX(a)
            for a in singles)
print(f"4/5-form -- DIA, BOX idempotent and fixing each other's output: "
      f"{'VERIFIED' if ok_45 else 'FAILED'}")
assert ok_45
ok_h = all(DIA(AND(a, DIA(b))) == AND(DIA(a), DIA(b)) for a, b in pairs)
print(f"Halmos closure -- DIA(a AND DIA b) = DIA a AND DIA b: "
      f"{'VERIFIED' if ok_h else 'FAILED'}")
assert ok_h
# K (box form), in the lattice order on the idempotent outputs:
# BOX(a IMP b) AND BOX(a) <= BOX(b). Channel: 1-x+xy = 1 iff x = 0 or
# y = 1; with x = 1 that forces y = 1.
def below(e, f, n=N):
    return AND(e, f, n) == e
ok_k = all(below(AND(BOX(IMP(a, b), n3, R3.lam), BOX(a, n3, R3.lam), n3),
                 BOX(b, n3, R3.lam), n3)
           for a in range(n3) for b in range(n3))
ok_k_rad = all(below(AND(BOX(IMP(a, b)), BOX(a)), BOX(b)) for a, b in pairs)
print(f"K -- BOX(a IMP b) AND BOX(a) <= BOX(b): exhaustive Z/30 + 20,000 RAD: "
      f"{'VERIFIED' if ok_k and ok_k_rad else 'FAILED'}")
assert ok_k and ok_k_rad
assert BOX(1) == 1 and BOX(0) == 0 and DIA(1) == 1 and DIA(0) == 0
print("Necessitation/grounding -- BOX 1 = 1, DIA 0 = 0: VERIFIED")

# What is quantified: the DEGREE of truth within a channel (any degree vs
# full degree). Quantifying over CHANNELS instead -- 'some channel true',
# 'a = 0 globally' -- is WALLED: [a = 0] is not channel-local. Proof in
# two constraints: a channel-local f computing [a = 0] must have its
# channel-2 component send residue 0 to 1 (from f(0) = 1) AND to 0 (from
# f(e) = 0 at any nonzero e with channel-2 residue 0). Witnesses at Z/30:
e35 = idempotent(frozenset({1, 2}), R3)        # channels 3,5 -> e = 16
assert e35 != 0 and encode(e35, R3)[0] == 0    # nonzero, reads 0 at p=2
assert encode(1, R3)[0] == 1 and encode(0, R3)[0] == 0
print()
print("Global quantifier walled: [a=0] needs the channel-2 component to")
print(f"  send 0 -> 1 (input a=0) and 0 -> 0 (input a={e35}=e_{{3,5}}): no")
print("  channel-local f exists, so no ring polynomial (locality criterion,")
print("  explore_size_transform.py). Degree quantifiers are free (DIA, BOX")
print("  are polynomials); channel quantifiers cost the deleted place.")
print()
print("The orthomodular hook DISSOLVES: orthomodularity is a lattice law,")
print("the graded region has no order (section II) -- no carrier for the")
print("question. The quantum flavor lives in the measurement pair instead:")
print("DIA loses truth over OR exactly as BOX gains it over AND.")

# ───────────────────────────────────────────────────────────────────────
section("FINDINGS")
# ───────────────────────────────────────────────────────────────────────
print("""
1. RULE (per-channel proof + exhaustive RAD): AND = ab, OR = a+b-ab,
   NOT = 1-a, IMP = 1-a+ab realize exact Boolean logic 2^k on the
   idempotents (intersection/union/complement); the residuation law
   (x AND a) <= b iff x <= (a IMP b) holds over all 128^3 RAD triples.

2. RULE (proved; identities verified exhaustively Z/30 + 20,000 RAD
   triples): off the lattice every failing Boolean law fails inside
   the DEFECT IDEAL (delta(x_i) = x_i^2 - x_i): idempotents of any
   commutative ring form a Boolean algebra (standard), so any law's
   LHS - RHS vanishes in Z[x]/(x_i^2 - x_i). The eleven charted laws
   each deform in a single variable: excluded middle by +delta,
   contradiction by -delta, absorption by delta*(1-b), both
   distributivities by delta*bc / -delta*(1-b)(1-c), modus ponens by
   -delta*(1-b) -- each holds whenever that ONE variable is classical.
   Contraposition and De Morgan survive identically. delta is the
   curvature of the logic; it vanishes channel-wise iff the residue
   reads 0 or 1.

3. RULE (proved + verified): truth is a PER-CHANNEL property. The
   classical region of channel p is {0,1} in F_p; classical-everywhere
   = the 2^k idempotents. The graded region has NO internal order
   (a <= a already fails) -- unlike fuzzy logics, degrees are not
   ordered; they are LOCATED (which channels are non-classical).

4. RULE (proved per-channel, census p <= 23, measured RAD): collapse
   a -> a^lambda = e_supp(a) is the logic's measurement. It commutes
   with AND exactly (fields), fails for NOT exactly on supp(delta(a)),
   and fails for OR by destructive interference: two true channels
   disjoin to false iff (1-x)(1-y) = 1, exactly p-2 of (p-1)^2
   true-true pairs (~1/p). Interference is one-directional: graded OR
   loses truth, never fabricates it. Conjunction is classical;
   disjunction is the quantum-flavored connective.

5. OBSERVATION (closed forms verified; framing): the lattice's
   canonical valuation is multiplicative, not additive --
   mu(e_S) = 1/prod(excluded p), with mu(meet)mu(join) = mu mu.
   Logical strength = log-mass EXCLUDED (content/falsifiability),
   additive in the tropical semiring, not probability. Additive
   valuations exist but are exactly channel-weight functionals
   (disjoint join = ring sum); the IE gate -1/(p-1) is a signed one.

6. RULE (proved by substitution, verified exhaustively Z/30 +
   20,000 RAD pairs): delta COMPOSES exactly under every connective.
   delta(NOT a) = delta(a); delta(a AND b) = delta(a)delta(b) +
   delta(a)b + a delta(b) -- a twisted Leibniz rule (twist a -> a^2);
   OR and IMP are the NOT-conjugates; delta(a+b) = delta(a) +
   delta(b) + 2ab (polarization; dies in char 2 -- Artin-Schreier).
   Nesting in the four CONNECTIVES never creates non-classicality:
   supp(delta(F)) lies in the union of the inputs' defect supports
   for every AND/OR/NOT/IMP formula F (induction over the laws);
   bare ring + escapes the scope -- its polarization creates defect
   from classical inputs (delta(1+1) = 2). Cancellation is exactly
   TWO partners per binary connective (AND: 0 or x^{-1}; OR: 1 or
   1-(1-x)^{-1}; IMP: the same two per argument position; NOT:
   never) -- census all p <= 23, all non-classical x.

7. RULE (per-channel case analysis, verified exhaustive Z/30 +
   RAD samples): the quantifier was the measurement, HALF of a pair.
   DIA(a) = a^lambda ('true to some degree') and its De Morgan
   conjugate BOX(a) = 1-(1-a)^lambda ('fully true') satisfy: exact
   conjugacy DIA NOT = NOT BOX (finding 4's NOT-failure = NOT
   exchanging the pair); DIA exact on AND, BOX exact on OR; each
   leaks on the dual connective at the same p-2 per-channel count,
   NOT bijecting the two mismatch sets (DIA loses truth over OR by
   interference exactly as BOX gains it over AND by inversion);
   mixed-form T, 4/5, K, necessitation, Halmos closure all exact.
   What is quantified is the DEGREE of truth within a channel.
   Quantifying over CHANNELS is walled: [a=0] is not channel-local
   (two constraints pin the channel-2 component both ways), so no
   ring polynomial plays the global quantifier. The orthomodular
   hook dissolves: a lattice law has no carrier in an order-free
   graded region; the quantum flavor lives in the measurement pair.

What the deformation buys: a logic whose non-classicality is an
ELEMENT of the same ring (delta(a)), measurable per channel, with an
exact composition law for the defect, an exact conjunction, and an
exact quantifier pair. The Boolean skeleton, the graded bulk, the
measurement, and the quantifiers all live in one arithmetic.
""")
print("ALL SECTIONS PASS")
