"""explore_quartic_level.py -- is the level shift of the non-square profile
between the two populations |d| itself, or the Minkowski conditioning the
increment carries with it? (sibling of explore_quartic_seat.py and
explore_quartic_second.py, whose populations and records it reads; the
null is explore_ceiling_early.py's C5, run here in the non-square share.)

THE QUESTION. The least partial place of a complex cubic field of 2-rank 1
is a non-square 0.338 +- 0.014 above one half over |d| <= 24000 and 0.300
+- 0.014 over 24000 < |d| <= 48000, and the second population's profile
sits under the first's at EVERY rank pool -- 0.046, 0.028 and 0.015 over
ranks 1-3, 4-6 and 7-10 (explore_quartic_second.py F3) -- a shift of the
profile's level and not of its shape. Two readings are unseparated there.
Either the level is a function of |d| (a finite-discriminant component of
whatever puts the 4-cycles first), or it is the generation conditioning:
the class group is generated by the prime ideals of norm below the
Minkowski bound M = (4/pi)(3!/3^3) sqrt|d| = 0.283 sqrt|d|, so a field
whose sub-bound places are few carries a non-square among them BY
CONSTRUCTION (the squares are an index-2 subgroup, and a set inside a
proper subgroup generates nothing), and the fewer the sub-bound places
the harder that construction leans on the least one. M runs from 43.8 to
62.0 across the second population against 4.8 to 43.8 across the first, so
the second population has more sub-bound places per field and the
conditioning leans on its least place LESS. The confound, if it is one,
has the SIGN of the shift.

THE HAND-ATTACK (pre-engine, on paper).

  (1) THE NULL'S ALGEBRA IN THE 2-PART. Draw every partial place's class
      uniformly from the group, keep the split fibers as the field has
      them, reject unless the sub-bound set generates. Generation needs,
      among other things, a non-square in the sub-bound set. Where the
      sub-bound SPLIT places already hold one (a split prime whose
      Frobenius is a double transposition carries two), the 2-part of the
      condition is met before any draw and the partial draws are free in
      the 2-part; where they do not, at least one of the k sub-bound
      partial classes must be drawn a non-square, and a given one of them
      is then a non-square with probability (1/2) / (1 - 2^-k): excess
      +0.500 at k = 1, +0.167 at k = 2, +0.071 at k = 3, +0.033 at k = 4,
      +0.016 at k = 5. The odd part of the condition (an element of order
      divisible by each odd prime dividing h) is independent of the
      2-part in a cyclic group and moves the non-square share by nothing.
      So the null's rank-1 excess is an average of (1/2)/(1 - 2^-k) - 1/2
      over the fields whose sub-bound split set carries no non-square,
      weighted by their share, and it is a function of the COUNT of
      sub-bound partial places -- which is a function of M, hence of |d|.
      The null's expected SHAPE over rank: a place at rank r enters the
      condition only while its prime lies below M, so the excess is
      largest at rank 1 and falls to zero once the rank's typical prime
      clears the bound -- by rank 4 on the first population's lower half
      (M < 31, the fourth odd prime 11 below it only in fields where 3,
      5, 7 are all partial), later on the second.
  (2) THE EXPECTED SIZE UNDER EACH READING. With the partial primes
      at the transposition rate 1/2 and the odd primes below M, the mean
      sub-bound partial count is about 4 at |d| = 6000 (M = 21.9, odd
      primes 3 to 19), 6 at 24000 (M = 43.8) and 8 at 48000 (M = 62),
      and the sub-bound split set carries a non-square about as often as
      not. The null's rank-1 excess is then of order +0.02 on the first
      population (its small-|d| fields carrying the k = 2 and k = 3
      terms) and under +0.01 on the second -- a DIFFERENCE of order 0.01
      to 0.02 against the empirical 0.038 +- 0.020. The generator-cell
      null on the base and wide populations read +0.037 +- 0.007 and
      +0.009 +- 0.006 (explore_ceiling_early.py C5; a draw-to-draw bar,
      so the sizes and not the bars are carried), of the same order.
      Under the CONFOUND reading the null's difference is the empirical
      one: both about 0.04 at rank 1 and the corrected shift zero. Under
      the |d| reading the null's difference is a fraction of it. The
      sizes above are the author's estimate and not the observable; the
      observable is frozen in P1 and P2.
  (3) THE BAR IS OVER FIELDS. The treatment's figure is a mean over
      fields with a field-to-field bar, so the null's is too: each field
      contributes the MEAN of its indicator over its accepted draws, one
      row per field, and the bar is taken across fields (a bar over the
      pooled redraws of a fixed field set understates, the draws of one
      field being correlated). With 100 accepted draws a field the draw
      noise adds at most sqrt(1/400) = 0.05 to a field's own standard
      deviation of 0.5 in quadrature, under one percent of the bar.
  (4) THE NULL IS AN UPPER BOUND ON THE CONFOUND. The ramified places
      below M generate too and carry no class in these records, so the
      condition demands generation from a SUBSET of the true generating
      set and leans on the drawn classes harder than the arithmetic does.
      A field whose sub-bound set cannot generate under any draw -- one
      the omitted places carry -- is excluded and counted. The bound
      runs in the direction that makes the confound look LARGER, so a
      null that fails to move by the shift fails a fortiori.
  (5) THE POPULATIONS ARE THE SIBLINGS' EXACTLY: the same two caches,
      the same filter (explore_quartic_seat.py records_from: even class
      number, 2-rank 1, the place floor), and the empirical profiles are
      reprinted from them before the null is read, within 0.003 of the
      siblings' pooled rank-1 figures.

THE SLATE (predictions frozen before the engine ran). Let N1(r), N2(r) be
the null's non-square excess at rank r on the first and second
populations with field bars s1, s2; E1(r), E2(r) the empirical; dE = E1 -
E2 and dN = N1 - N2 with bars in quadrature; the CORRECTED shift dC = dE
- dN.

  C1  THE UNCONDITIONED NULL (uniform draws, no rejection) reads within 3
      sigma of zero at every pool and within 3.5 sigma at every single
      rank on both populations (the single-rank line was 3 sigma at the
      freeze; the rehearsal's C2 tripped it at |z| = 3.05 on one of 18
      statistics that are uniform by construction, a 5-percent false
      fail at 3 sigma, so the singles moved to 3.5 before the run).
  C2  THE POSITIVE CONTROL. Conditioning on the rank-1 place ALONE
      generating forces it into the generating cell, which is inside the
      non-squares at every even h (a generator of a cyclic group of even
      order is never a square): the rank-1 excess reads +0.500 EXACTLY on
      every field with an accepted draw, and ranks 2 to 10 within 3.5
      sigma of zero singly (C1's line). Fields whose group no single
      class generates are excluded there and counted.
  C3  THE REPRINT. The empirical rank-1 excess on the records this
      script reads is within 0.003 of +0.338 and +0.300.
  C4  THE ALGEBRA. Over the fields whose sub-bound split set holds no
      non-square, the null's rank-1 excess by sub-bound partial count k
      = 1, 2, 3, 4 is within 2 sigma of (1/2)/(1 - 2^-k) - 1/2 wherever
      the cell holds at least 15 fields.
  P1  THE CONFOUND NAMED: dN(1) is at least half of dE(1), AND dC is
      within 2 sigma of zero at rank 1 and over ranks 1-3 pooled.
  P2  |d| STANDS: dN(1) + 2 s_dN is under half of dE(1), AND dC at rank 1
      is at least 2 sigma from zero.
      Neither P1 nor P2: MIXED -- the null moves by a fraction of the
      shift too large to dismiss and too small to account for it.
  P1 and P2 are read on the full populations only, dE being the
  siblings' shift; a rehearsal at a stride prints no verdict.
  The null's shape is read descriptively: N1 and N2 by rank beside E1
  and E2; the rank-1 null by |d| band (to 6000, 12000, 24000, 36000,
  48000) beside the empirical rank-1 share there -- if the null's steps
  across the bands match the empirical steps, the level is the
  conditioning's; and the null's rank-1 excess by sub-bound partial
  count, which is C4's table.

THE DESIGN. Records: the two populations through explore_quartic_seat.py
records_from, from the mapped caches QSEAT_CACHE and QSECOND_CACHE (the
first rebuilt by explore_quartic_seat.py records, the second by
explore_quartic_second.py mapped_increment, if a cache is absent).
Empirical rows: explore_quartic_seat.py field_rows and rank_table. The
null: per field, draws of every partial place's class uniform from the
group, the split fiber kept, accepted when explore_ceiling_early.py's
subbound_generators and generates say the sub-bound set generates, 100
accepted draws or 4000 tries; the non-square indicator minus one half at
ranks 1 to 10 averaged over the field's accepted draws; the field means
through rank_table, so the bar is over fields. C2 accepts a draw when the
rank-1 class alone generates. QLEVEL_STRIDE = n keeps every n-th field
of each population for the rehearsal.

THE FINDINGS (the post-run record; every number is a print of the run).

  THE POPULATIONS. 686 and 840 fields (h = 2: 484 and 529; h = 4: 101
  and 118; h = 6: 65 and 117; h = 8: 19 and 30; larger even h: 17 and
  46). Minkowski bound 4.8 to 43.8 and 43.9 to 62.0; sub-bound partial
  places per field 4.38 (0 to 10) and 6.92 (1 to 12), inside the
  hand-attack's 4-to-6 and 6-to-8; a sub-bound SPLIT place already carries a
  non-square in 514 of 686 and 770 of 840 fields -- three in four and
  eleven in twelve, not the "as often as not" of the hand-attack, which
  is why the null is smaller than its estimate.

  CONTROLS. C3: +0.338 +- 0.014 and +0.300 +- 0.014 reprint. C1: the
  free null's largest |z| is 1.88 and 2.01 over the ten single ranks and
  1.43 and 1.87 over the pools. C2: acceptance 0.474 and 0.460, no field
  excluded (every group of the two populations is cyclic), rank 1 +0.500
  exactly on every field, ranks 2-10 largest |z| 1.16 and 2.25. C4: over
  the fields whose sub-bound split set holds no non-square the null's
  rank-1 excess by sub-bound partial count is +0.500 at k = 1 (6 fields,
  the algebra's 0.500), +0.146 +- 0.018 at k = 2 (9 fields, 0.167),
  +0.078 +- 0.009 at k = 3 (31 fields, 0.071) and +0.045 +- 0.009 at k
  = 4 (29 fields, 0.033), and +0.000 +- 0.001 over the 1284 fields
  whose split set holds one -- the null IS the 2-part algebra of (1).

  F1  THE CONDITIONING IS A THIRD OF THE SHIFT AT RANK 1 AND A FIFTH
      OVER RANKS 1-3, AND NEARLY ALL OF IT LIVES BELOW |d| = 6000 (observation; the
      null an upper bound on the confound, hand-attack (4)). The
      conditioned null on the first population, bar over 685 fields (one
      excluded, acceptance 0.923): +0.012 +- 0.003 at rank 1, +0.010 +-
      0.002 at rank 2, +0.006 +- 0.002 at rank 3, +0.003 +- 0.002 at
      rank 4 and zero within 0.002 from rank 5 on; pooled +0.009 +-
      0.001 over ranks 1-3, +0.001 +- 0.001 over 4-6, +0.000 +- 0.001
      over 7-10. On the second population (840 fields, acceptance 0.999)
      the null is zero at every rank and pool within 0.003: +0.000 +-
      0.002 at rank 1. So dN = +0.012 +- 0.003 at rank 1 and +0.009 +-
      0.002 over ranks 1-3 against dE = +0.038 +- 0.020 and +0.046 +-
      0.012; -0.001 +- 0.001 over 4-6 and 7-10 against +0.028 +- 0.014
      and +0.015 +- 0.012. By |d| band the null's rank-1 share is 0.551
      +- 0.011 below 6000 (119 fields), 0.508 +- 0.004 to 12000, 0.502
      +- 0.003 to 24000, 0.500 +- 0.002 over both halves of the second
      population -- the conditioning is a property of the fields with a
      Minkowski bound under 22, where the empirical share reads 0.892 +-
      0.028; 0.008 over the next band and 0.002 after it.

  F2  THE VERDICT IS MIXED BY ITS LETTER, AND WHAT STANDS IS A |d|
      COMPONENT AT 3 SIGMA POOLED (observation). P2's first clause holds
      by a hair -- dN + 2 sigma = 0.018 against half of dE = 0.019 -- and
      its second fails: the corrected shift at rank 1 is +0.027 +- 0.020
      (z +1.3). Over ranks 1-3 pooled the corrected shift is +0.037 +-
      0.012 (z +3.2), over 4-6 +0.028 +- 0.014 (z +2.0), over 7-10
      +0.016 +- 0.012 (z +1.3): the part of the level the conditioning
      does not price is the larger part at every pool and is the
      conditioning's OPPOSITE in shape -- the null is confined to ranks
      1-3 and nearly all to |d| < 6000, while the residual shift runs through rank
      6 and, by the band table, sits between 6000 and 24000 (empirical
      rank-1 share 0.855 +- 0.027 to 12000, 0.815 +- 0.019 to 24000,
      0.798 +- 0.020 and 0.802 +- 0.019 across the second population's
      halves; the null's steps there 0.006, 0.002, 0.000). What the
      sibling's F3 called a level shift of 0.046, 0.028 and 0.015 by
      pool reads, with the Minkowski conditioning removed at its upper
      bound, 0.037 +- 0.012, 0.028 +- 0.014 and 0.016 +- 0.012.

WHAT IS NOT CONTROLLED. The mechanism, as in the siblings; and what the
residual |d| component is -- a secondary term of whatever puts the
4-cycles first, with the data saying only that it has fallen by |d| =
24000. The null omits the ramified places below the bound, which can
only make the true conditioning SMALLER than the null reads.

RUN RECORD. 2026-08-20, Windows 11, Python 3, `python
prime/code/memwatch.py --limit 512 prime/code/explore_quartic_level.py`
with QSEAT_CACHE and QSECOND_CACHE set to the siblings' mapped caches.
One process, CPython, no BLAS. Rehearsed at QLEVEL_STRIDE = 10 (69 and
84 fields, 2.7 s), which moved C1's and C2's single-rank line from 3 to
3.5 sigma and the C4 count to the condition's own set before the full
run; nothing else in the slate moved. Full run 16.5 s, 9 checks, peak
working set 211.5 MB.
"""
import os
os.environ.setdefault("OPENBLAS_NUM_THREADS", "1")

import gc                                          # noqa: E402
import pickle                                      # noqa: E402
import random                                      # noqa: E402
import sys                                         # noqa: E402
import time                                        # noqa: E402
from collections import defaultdict                # noqa: E402
from math import sqrt                              # noqa: E402

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import explore_ceiling_early as EE                 # noqa: E402
import explore_ceiling_constant as EC              # noqa: E402
import explore_ceiling_curve as CV                 # noqa: E402
import explore_quartic_seat as QS                  # noqa: E402
import explore_quartic_second as QSd               # noqa: E402

CHECKS = 0
SEED = 20888
DRAWS = 100
TRIES = 4000
RANKS = QS.RANKS
RANK_POOLS = QS.RANK_POOLS
BANDS = ((0, 6000), (6000, 12000), (12000, 24000), (24000, 36000),
         (36000, 48000))
K_CELLS = (1, 2, 3, 4)
MIN_CELL = 15
REPRINT = {1: 0.338, 2: 0.300}
STRIDE = int(os.environ.get("QLEVEL_STRIDE", "1"))

mean_se = CV.mean_se
fmt = EC.fmt


def ok(cond, msg):
    global CHECKS
    CHECKS += 1
    if not cond:
        print("  FAIL: " + msg)
        sys.exit(1)


def section(t):
    print("\n" + "=" * 72 + "\n" + t + "\n" + "=" * 72)


# ------------------------------------------------------------- the records
def load_mapped(env, rebuild):
    cache = os.environ.get(env)
    if cache and os.path.exists(cache):
        with open(cache, "rb") as fh:
            mapped = pickle.load(fh)
        print("  mapped records read from %s" % cache)
        return mapped
    print("  no %s: rebuilding the class reading" % env)
    return rebuild()


def population(label, env, rebuild):
    mapped = load_mapped(env, rebuild)
    recs = QS.records_from(mapped)
    del mapped
    gc.collect()
    if STRIDE > 1:
        recs = recs[::STRIDE]
        print("  (rehearsal: every %d-th field, %d kept)" % (STRIDE,
                                                            len(recs)))
    by_h = defaultdict(int)
    for rec in recs:
        by_h[rec['h']] += 1
    print("  %s: %d fields, by class number %s"
          % (label, len(recs), dict(sorted(by_h.items()))))
    return recs


def rebuild_first():
    import explore_ceiling_topband as TB
    import explore_cubic_transposition as XT
    return XT.s3_profiles(TB.wide_class_reading())


# ---------------------------------------------------------------- the null
def split_nonsquare_below(rec):
    """Does a sub-bound split place already carry a non-square?"""
    G = rec['G']
    M = EE.minkowski(rec['d'])
    for p, t in rec['types'].items():
        if p > M or t == 'dropped' or t[0] != 'split':
            continue
        if any(key not in G.squares for key in t[1]):
            return True
    return False


def subbound_partial_count(rec):
    """The partial places the condition actually reads: below M, classed
    (a dropped place carries no class and is outside the condition), and
    among the drawn places."""
    M = EE.minkowski(rec['d'])
    drawn = set(p for (p, key) in rec['places'])
    return sum(1 for p, t in rec['types'].items()
               if p <= M and t != 'dropped' and t[0] == 'partial'
               and p in drawn)


def null_rows(recs, rng, mode):
    """One row per field: the non-square indicator minus 1/2 by rank,
    averaged over the field's accepted draws. mode: 'free' (no
    rejection), 'subbound' (C5's condition), 'rank1' (C2: the rank-1
    class alone must generate). Returns (rows, excluded, accept_rate)."""
    rows = []
    excluded = tried = accepted = 0
    for rec in recs:
        G = rec['G']
        places = sorted(rec['places'])
        sums = [0.0] * min(RANKS, len(places))
        got = local = 0
        while got < DRAWS and local < TRIES:
            local += 1
            tried += 1
            drawn = {p: rng.choice(G.keys) for (p, key) in places}
            if mode == 'subbound':
                if not EE.generates(G, EE.subbound_generators(rec, drawn)):
                    continue
            elif mode == 'rank1':
                if not EE.generates(G, [drawn[places[0][0]]]):
                    continue
            accepted += 1
            got += 1
            for i in range(len(sums)):
                if drawn[places[i][0]] not in G.squares:
                    sums[i] += 1.0
        if got == 0:
            excluded += 1
            continue
        rows.append(dict(h=G.h, d=rec['d'], ns=[s / got - 0.5 for s in sums],
                         got=got, k=subbound_partial_count(rec),
                         split_ns=split_nonsquare_below(rec)))
    rate = accepted / float(tried) if tried else 0.0
    return rows, excluded, rate


def profile(rows):
    """rank_table's numbers without its print."""
    out = {}
    for r in range(1, RANKS + 1):
        vals = [row['ns'][r - 1] for row in rows if len(row['ns']) >= r]
        if len(vals) >= 2:
            out[r] = mean_se(vals)
    for (a, b) in RANK_POOLS:
        vals = [sum(row['ns'][a - 1:b]) / (b - a + 1) for row in rows
                if len(row['ns']) >= b]
        if len(vals) >= 2:
            out[(a, b)] = mean_se(vals)
    return out


def diff(x, y):
    return x[0] - y[0], sqrt(x[1] ** 2 + y[1] ** 2)


def z_of(pair):
    return pair[0] / pair[1] if pair[1] else 0.0


def band_rank1(rows, lo, hi):
    vals = [row['ns'][0] + 0.5 for row in rows
            if lo < abs(row['d']) <= hi and row['ns']]
    if len(vals) < 2:
        return None
    return mean_se(vals) + (len(vals),)


# ------------------------------------------------------------------ main
def main():
    t0 = time.time()
    rng = random.Random(SEED)
    pops = {}

    section("THE TWO POPULATIONS (2-rank 1, the place floor)")
    pops[1] = population("first (|d| <= 24000)", "QSEAT_CACHE",
                         rebuild_first)
    pops[2] = population("second (24000 < |d| <= 48000)", "QSECOND_CACHE",
                         QSd.mapped_increment)
    for i in (1, 2):
        ms = [EE.minkowski(rec['d']) for rec in pops[i]]
        ks = [subbound_partial_count(rec) for rec in pops[i]]
        sh = sum(1 for rec in pops[i] if split_nonsquare_below(rec))
        print("  population %d: Minkowski bound %.1f to %.1f; sub-bound"
              " partial places per field mean %.2f (min %d, max %d); a"
              " sub-bound split place carries a non-square in %d of %d"
              " fields" % (i, min(ms), max(ms), sum(ks) / float(len(ks)),
                           min(ks), max(ks), sh, len(ks)))

    section("C3  THE EMPIRICAL PROFILES, REPRINTED")
    emp = {}
    for i in (1, 2):
        rows = QS.field_rows(pops[i])
        emp[i] = QS.rank_table(rows, "population %d, empirical" % i)
        if STRIDE == 1:
            ok(abs(emp[i][1][0] - REPRINT[i]) < 0.003,
               "C3: population %d rank-1 excess %s is not %.3f"
               % (i, fmt(*emp[i][1]), REPRINT[i]))
    if STRIDE == 1:
        print("  C3 PASSES: both rank-1 excesses reprint within 0.003")

    section("C1  THE UNCONDITIONED NULL (uniform draws, no rejection)")
    for i in (1, 2):
        rows, exc, rate = null_rows(pops[i], rng, 'free')
        prof = profile(rows)
        zs = [z_of(prof[r]) for r in range(1, RANKS + 1) if r in prof]
        zp = [z_of(prof[k]) for k in RANK_POOLS if k in prof]
        print("  population %d: rank 1 %s, ranks 1-3 %s; largest |z| %.2f"
              " over %d single ranks, %.2f over %d pools"
              % (i, fmt(*prof[1]), fmt(*prof[(1, 3)]),
                 max(abs(z) for z in zs), len(zs),
                 max(abs(z) for z in zp), len(zp)))
        ok(all(abs(z) < 3.5 for z in zs) and all(abs(z) < 3.0 for z in zp),
           "C1: population %d unconditioned null off zero" % i)
    print("  C1 PASSES: the free null is flat at every rank on both")

    section("C2  THE POSITIVE CONTROL (the rank-1 class alone generates)")
    for i in (1, 2):
        rows, exc, rate = null_rows(pops[i], rng, 'rank1')
        prof = profile(rows)
        r1 = [row['ns'][0] for row in rows]
        zs = [z_of(prof[r]) for r in range(2, RANKS + 1) if r in prof]
        print("  population %d: %d fields accepted, %d excluded (no single"
              " generator), acceptance %.3f; rank 1 %s (min %.3f, max"
              " %.3f); ranks 2-10 largest |z| %.2f"
              % (i, len(rows), exc, rate, fmt(*prof[1]), min(r1), max(r1),
                 max(abs(z) for z in zs)))
        ok(all(abs(v - 0.5) < 1e-12 for v in r1),
           "C2: population %d rank-1 excess is not exactly +0.5" % i)
        ok(all(abs(z) < 3.5 for z in zs),
           "C2: population %d ranks 2-10 off zero" % i)
    print("  C2 PASSES: the condition forces rank 1 non-square exactly and"
          " touches no other rank")

    section("THE GENERATION-CONDITIONED NULL, BOTH POPULATIONS, BAR OVER"
            " FIELDS")
    nul, nrows = {}, {}
    for i in (1, 2):
        t1 = time.time()
        rows, exc, rate = null_rows(pops[i], rng, 'subbound')
        nrows[i] = rows
        print("  population %d: %d fields with accepted draws, %d excluded"
              " (cannot generate without the unclassed ramified places),"
              " acceptance %.3f, %.1f s" % (i, len(rows), exc, rate,
                                            time.time() - t1))
        nul[i] = QS.rank_table(rows, "population %d, conditioned null" % i)

    section("SIDE BY SIDE: EMPIRICAL AND NULL, THE SHIFT AND ITS CORRECTION")
    print("  %-12s %-16s %-16s %-16s %-16s" % ("", "E1", "N1", "E2", "N2"))
    keys = [r for r in range(1, RANKS + 1)] + list(RANK_POOLS)
    for key in keys:
        if not all(key in t for t in (emp[1], nul[1], emp[2], nul[2])):
            continue
        lab = ("rank %d" % key) if isinstance(key, int) else (
            "ranks %d-%d" % key)
        print("  %-12s %s  %s  %s  %s"
              % (lab, fmt(*emp[1][key]), fmt(*nul[1][key]),
                 fmt(*emp[2][key]), fmt(*nul[2][key])))
    print()
    print("  %-12s %-16s %-16s %-16s" % ("", "dE = E1-E2", "dN = N1-N2",
                                        "dC = dE-dN"))
    shift = {}
    for key in keys:
        if not all(key in t for t in (emp[1], nul[1], emp[2], nul[2])):
            continue
        dE = diff(emp[1][key], emp[2][key])
        dN = diff(nul[1][key], nul[2][key])
        dC = diff(dE, dN)
        shift[key] = (dE, dN, dC)
        lab = ("rank %d" % key) if isinstance(key, int) else (
            "ranks %d-%d" % key)
        print("  %-12s %s  %s  %s  z(dC) %+.1f"
              % (lab, fmt(*dE), fmt(*dN), fmt(*dC), z_of(dC)))

    section("THE NULL'S SHAPE: RANK 1 BY |d| BAND, AND BY SUB-BOUND COUNT")
    print("  %-16s %-22s %-22s" % ("|d| band", "empirical rank-1 share",
                                  "null rank-1 share"))
    erows = {i: QS.field_rows(pops[i]) for i in (1, 2)}
    for (lo, hi) in BANDS:
        i = 1 if hi <= 24000 else 2
        e = band_rank1(erows[i], lo, hi)
        n = band_rank1(nrows[i], lo, hi)
        if e is None or n is None:
            continue
        print("  %6d-%-6d    %s (%4d)     %s (%4d)"
              % (lo, hi, fmt(e[0], e[1]), e[2], fmt(n[0], n[1]), n[2]))
    print()
    print("  C4: the null's rank-1 excess by sub-bound partial count k, over"
          " fields whose sub-bound split set holds no non-square, against"
          " (1/2)/(1 - 2^-k) - 1/2 (both populations pooled):")
    allrows = nrows[1] + nrows[2]
    c4_ok = True
    for k in K_CELLS:
        vals = [row['ns'][0] for row in allrows
                if row['k'] == k and not row['split_ns']]
        pred = 0.5 / (1.0 - 2.0 ** (-k)) - 0.5
        if len(vals) < 2:
            print("    k = %d: no fields" % k)
            continue
        mu, se = mean_se(vals)
        flag = "" if len(vals) < MIN_CELL else (
            "  within 2 sigma" if abs(mu - pred) < 2 * se else "  OFF")
        if len(vals) >= MIN_CELL and abs(mu - pred) >= 2 * se:
            c4_ok = False
        print("    k = %d: null %s  algebra %+.3f  (%d fields)%s"
              % (k, fmt(mu, se), pred, len(vals), flag))
    vals = [row['ns'][0] for row in allrows if row['split_ns']]
    if len(vals) >= 2:
        print("    fields whose split set holds a non-square: null %s"
              " (%d fields), the algebra's zero" % (fmt(*mean_se(vals)),
                                                   len(vals)))
    ok(c4_ok, "C4: a sub-bound cell of at least %d fields is off the"
       " algebra" % MIN_CELL)
    print("  C4 PASSES: the null's cells sit on the algebra")

    section("THE VERDICT (P1 / P2, frozen)")
    if STRIDE > 1:
        print("  rehearsal: the verdict is read on the full populations only"
              " (dE is the siblings' shift)")
        print("\n%d checks passed, %.1f s" % (CHECKS, time.time() - t0))
        return
    dE1, dN1, dC1 = shift[1]
    dC13 = shift[(1, 3)][2]
    half = 0.5 * dE1[0]
    print("  rank 1: dE %s, dN %s, half of dE %+.3f, dN + 2 sigma %+.3f;"
          " dC %s (z %+.1f), ranks 1-3 dC %s (z %+.1f)"
          % (fmt(*dE1), fmt(*dN1), half, dN1[0] + 2 * dN1[1], fmt(*dC1),
             z_of(dC1), fmt(*dC13), z_of(dC13)))
    p1 = dN1[0] >= half and abs(z_of(dC1)) < 2 and abs(z_of(dC13)) < 2
    p2 = (dN1[0] + 2 * dN1[1] < half) and abs(z_of(dC1)) >= 2
    if p1:
        print("  P1: THE CONFOUND NAMED -- the null moves by the shift and"
              " the corrected shift is zero")
    elif p2:
        print("  P2: |d| STANDS -- the null moves by under half the shift"
              " at 2 sigma and the corrected shift survives")
    else:
        print("  MIXED -- neither letter met; the null moves by a fraction"
              " of the shift")

    print("\n%d checks passed, %.1f s" % (CHECKS, time.time() - t0))


if __name__ == "__main__":
    main()
