"""
THE RAMIFICATION FACE -- is the compact factor's deletion per-term?

The deleted-budget law (explore_deleted_budget.py, explore_rank_face.py,
explore_regulator_face.py) prices what deleting a PLACE buys at a global
constraint as the deleted term's own local group, per-term at every
measured face, with the class of the deleted ideal as the one global
correction. This probe deletes less: not the place, only its COMPACT
factor -- the local units -- from the norm subgroup, allowing
ramification there while the place stays. Every quotient of the idele
class group by an open subgroup is a ray class group, so the purchase is
readable in ray class numbers: for a finite modulus m = prod P^n,

    1 -> O*_{m,1} -> O* -> (O/m)^* -> Cl_m -> Cl -> 1,
    h_m = h * |(O/m)^*| / |im(O* -> (O/m)^*)|.

The local factor |(O/m)^*| = prod |(O/P^n)^*| is per-term outright
(CRT). The whole question sits in the CORRECTION, the global unit
group's image: does im(O* -> prod) factor as the product of its
per-place projections -- each place corrected by its own local unit
image, the per-term reading -- or does the image entangle the terms?
The instrument is the RESIDUAL

    rho(m) = prod_P |im_P| / |im_joint|  >= 1,

with rho = 1 exactly the per-term case, and h_m(true) =
h_m(per-term prediction) * rho, so an entangled modulus's ray class
number exceeds the per-term prediction by exactly rho.

TRANSPLANT FLAG: "per-term" is imported from the five measured faces,
where the priced objects (a sign, a Brauer class, a rank, a covolume, a
lattice index) attach to terms. Here the correction is the image of ONE
finitely generated group in a PRODUCT, and nothing about products says
an image is the product of its projections.

THE RANK-COUNTING SUSPICION (frozen with the slate): im_joint is a
quotient of O*, so it is generated by at most r + 1 elements (unit rank
r plus cyclic torsion), while the product of the per-place images can
need a generator per place from torsion alone. Once the place count s
exceeds the generator count, the product is out of reach: entanglement
FORCED by counting, the same flavor as the rank face's Dirichlet count.
Sharpest at unit rank 0 (imaginary quadratic): im_joint = <(-1,...,-1)>
has order at most 2, the product over s odd unramified places is 2^s,
so rho = 2^(s-1) -- unbounded in the place count.

THE HAND-ATTACK (before any engine code).
  (i) Residue machinery. Split or ramified place over p at root r
  (sqrt(d) -> r): O/P = F_p via a + b sqrt(d) -> a + b r. Inert p:
  O/P = F_p[t]/(t^2 - d), order p^2, unit group cyclic of order
  p^2 - 1. Level n = 1 throughout (the compact factor's first layer).
  (ii) K1 = Q(sqrt(2)): h = 1, eps = 1 + sqrt(2), torsion {+-1}.
  Hand table of unit images (ord = order of eps's residue):
    P7  r=3:  eps -> 4,  ord 3  (4, 2, 1); -1 not in <4>; im = 6.
    P7' r=4:  eps -> 5,  ord 6  (5^3 = 6 = -1); im = 6.
    P17 r=6:  eps -> 7,  ord 16 (7^8 = 16 = -1); im = 16.
    P17' r=11: eps -> 12, ord 16 (12^8 = -1); im = 16.
    P3 inert: eps = 1 + t in F_9, (1+t)^2 = 2t, (2t)^2 = 2 = -1,
      ord 8; im = 8.
    P23 r=5:  eps -> 6,  ord 11 (6^11 = 1, odd); -1 not in; im = 22.
    P23' r=18: eps -> -4, ord 22 ((-4)^11 = -(2^22) = -1); im = 22.
  (iii) K1 witness pair m = P7(r=3) * P23(r=5): prod im = 6 * 22 =
  132; joint = <(4,6), (-1,-1)>, with <(4,6)> of order lcm(3,11) = 33
  (odd, so (-1,-1) outside): joint = 66, rho = 2, h_m = 132/66 = 2
  against per-term 1. Control pair m = P7(r=3) * P17(r=6): joint =
  <(4,7), (-1,-1)>, <(4,7)> of order 48, (-1,-1) outside (4^k is
  never -1 mod 7), joint = 96 = prod im, rho = 1: per-term HOLDS at
  this pair, so entanglement is the modulus's property, not the
  construction's.
  (iv) K2 = Q(sqrt(-5)): h = 2, units {+-1}, rank 0. Places over 3
  split (roots 1, 2), over 7 split (-5 = 2 = 3^2 mod 7; roots 3, 4),
  over 2 ramified with O/P2 = F_2 (im trivial). Witness m = P3 * P3':
  prod im = 4, joint = <(-1,-1)> = 2, rho = 2, h_m = 2 * 4/2 = 4
  against per-term 2. Three places m = P3 * P3' * P7'(r=4): prod im =
  8, joint = 2, rho = 4 = 2^(s-1), h_m = 2 * 24/2 = 24 against
  per-term 6.
  (v) The K2 independent check (ideal witnesses, since h = 2 makes
  the quotient formula only half the group). P7' = (7, sqrt(-5) - 4)
  is non-principal (x^2 + 5 y^2 = 7 insoluble); 2 + 3 sqrt(-5) has
  norm 49 with residue 14 = 0 mod 7 at r=4 and 11 != 0 at r=3, so
  P7'^2 = (2 + 3 sqrt(-5)). Its residue mod both places over 3 is 2
  (the 3 sqrt(-5) term dies mod 3), so the NEGATIVE generator is 1 at
  both: [P7'] has order 2 in Cl_m, mapping onto the nontrivial class.
  Kernel witness: (sqrt(-5)) has residue (1, 2) = (1, -1), outside
  the joint image {(1,1), (-1,-1)}, and (sqrt(-5))^2 = (-5) with
  -5 = 1 mod 3: order 2, principal. Two distinct order-2 elements,
  one per factor of the extension: Cl_m = Z/2 x Z/2, order 4 -- the
  formula's count confirmed by structure.
  (vi) ENUMERATION HONESTY. The unit group is exactly {+-eps^k}
  (Dirichlet, rank 1) and {+-1} (rank 0), so the image is the closure
  of the generators' residues -- no enumeration can miss a unit. The
  guard is saturation read the other way: the closure of
  {eps mod m, -1 mod m} must equal the set of residues of +-eps^k
  enumerated to k = 40, at every modulus.

THE PREDICTIONS (frozen before the engine; kills are what the rig
PRINTS, weighed after).
  F0 POSITIVE CONTROLS, run first: (a) splitting verdicts -- K1: 2
  ramified, 3 inert, 7 split (3, 4), 17 split (6, 11), 23 split
  (5, 18); K2: 2 ramified, 3 split (1, 2), 7 split (3, 4), 11 inert.
  (b) the residue machinery reprints the hand table in (ii), all
  seven orders and all seven image sizes. (c) saturation: the
  generator closure equals the enumerated-unit image at every frozen
  modulus. (d) N(2 + 3 sqrt(-5)) = 49 with valuations (0, 2) at
  (r=3, r=4).
  F1 (the witness): m = P7(r=3) * P23(r=5) over K1 prints prod im
  132, joint 66, rho 2, h_m 2 against per-term 1 -- the per-term
  reading REFUSES at this modulus.
  F2 (the control): m = P7(r=3) * P17(r=6) over K1 prints rho 1 --
  some moduli do factor, so rho is a nontrivial function of the
  modulus, not a constant defect.
  F3 (rank 0, the forced case): over K2, m = P3 * P3' prints rho 2
  and h_m 4; m = P3 * P3' * P7' prints rho 4 and h_m 24 -- rho =
  2^(s-1) at s odd unramified places, the entanglement unbounded in
  the place count. The ideal witnesses print: [P7'] order 2 in Cl_m,
  (sqrt(-5)) residue outside the joint image with square trivial --
  structure Z/2 x Z/2 at the two-place witness.
  F4 (the full scan): over all 21 pairs from K1's seven places, every
  printed rho equals prod im / joint computed independently by
  closure, and rho > 1 at some pair whose eps-orders are BOTH odd
  (the -1 diagonal the mechanism predicts: with both eps-orders odd,
  -1 enters each per-place image freely but only diagonally in the
  joint).
  KILL (frozen when the probe was banked): the rig only restates the
  ray-class-number formula with no per-term verdict -- then the weld
  stays a citation and there is no sixth face. A residual table with
  witnesses on both sides of 1 IS a verdict.

RESOURCE ESTIMATE: groups of order < 1000, closures by breadth-first
multiplication, well under a second and under 50 MB.

FINDINGS (run record below; every frozen prediction landed).
  F0 GREEN: all splitting verdicts as frozen; the seven-row hand table
  reprinted exactly (orders 3, 6, 16, 16, 8, 11, 22; image sizes 6, 6,
  16, 16, 8, 22, 22); saturation equal=True at both frozen moduli;
  N(2 + 3 sqrt(-5)) = 49 with valuations (0, 2).
  F1 CONFIRMED: the witness prints prod im=132 joint=66 rho=2 h_m=2
  perterm=1 -- the per-term reading REFUSES.
  F2 CONFIRMED: the control prints rho=1 -- rho is the modulus's
  property, not the construction's.
  F3 CONFIRMED: two-place rho=2 h_m=4, three-place rho=4 h_m=24 --
  rho = 2^(s-1) at rank 0, unbounded in the place count. Ideal
  witnesses: -(2 + 3 sqrt(-5)) prints (1, 1) so [P7'] has order 2;
  sqrt(-5)'s residue (1, 2) is outside the joint image with trivial
  square: Cl_m = Z/2 x Z/2.
  F4 CONFIRMED, with structure the slate did not predict: 7 of 21
  pairs entangled, rho in {2, 3, 4, 11, 16}, and the largest residuals
  sit at CONJUGATE pairs -- the two places over one rational prime
  with equal eps-order: P17(r=6) * P17(r=11) prints rho=16 (joint 16
  against product 256) and P23(r=5) * P23(r=18) prints rho=11. The
  odd-odd -1 mechanism fired where predicted (P7(r=3) * P23(r=5), the
  one odd-odd entangled pair). VERDICT: the compact factor's deletion
  is NOT per-term -- the local factor prices per-term (CRT), and the
  global-unit correction is ONE JOINT object, a subgroup on at most
  r + 1 generators whose failure to factor is the exact excess of the
  true ray class number over the per-term prediction.

RUN RECORD: python prime/code/explore_ramification_face.py -- 0.05 s,
all controls green, output reproduced in the findings above.
"""

# ---------------------------------------------------------------- engine

def make_split_place(p, r, d):
    """Residue map for a split/ramified place at root r (sqrt(d) -> r)."""
    assert (r * r - d) % p == 0
    return {
        "kind": "split" if d % p != 0 and (2 * r) % p != 0 else "ram",
        "p": p, "r": r, "d": d,
        "order": p - 1,
        "one": 1 % p,
        "red": (lambda a, b, p=p, r=r: (a + b * r) % p),
        "mul": (lambda x, y, p=p: (x * y) % p),
        "label": f"P{p}(r={r})",
    }


def make_inert_place(p, d):
    """Residue map for an inert place: F_p[t]/(t^2 - d), pairs (x, y)."""
    return {
        "kind": "inert", "p": p, "d": d,
        "order": p * p - 1,
        "one": (1, 0),
        "red": (lambda a, b, p=p: (a % p, b % p)),
        "mul": (lambda u, v, p=p, d=d: (
            (u[0] * v[0] + u[1] * v[1] * d) % p,
            (u[0] * v[1] + u[1] * v[0]) % p)),
        "label": f"P{p}(inert)",
    }


def elt_order(place, g):
    """Multiplicative order of g in the place's residue unit group."""
    x, n = g, 1
    while x != place["one"]:
        x = place["mul"](x, g)
        n += 1
        assert n <= place["order"]
    return n


def closure(mul, one, gens):
    """Subgroup generated by gens under mul (finite, breadth-first)."""
    seen = {one}
    frontier = [one]
    while frontier:
        nxt = []
        for x in frontier:
            for g in gens:
                y = mul(x, g)
                if y not in seen:
                    seen.add(y)
                    nxt.append(y)
        frontier = nxt
    return seen


def tuple_mul(places):
    def mul(u, v):
        return tuple(pl["mul"](a, b) for pl, a, b in zip(places, u, v))
    return mul


def unit_residues(place, eps, torsion_minus_one=True):
    """Residues of the fundamental generators at one place."""
    gens = []
    if eps is not None:
        gens.append(place["red"](*eps))
    if torsion_minus_one:
        gens.append(place["red"](-1, 0))
    return gens


def place_image(place, eps):
    return closure(place["mul"], place["one"], unit_residues(place, eps))


def joint_image(places, eps):
    one = tuple(pl["one"] for pl in places)
    gens = []
    if eps is not None:
        gens.append(tuple(pl["red"](*eps) for pl in places))
    gens.append(tuple(pl["red"](-1, 0) for pl in places))
    return closure(tuple_mul(places), one, gens)


def enumerated_unit_image(places, eps, kmax=40):
    """Image of +-eps^k, k in [-kmax, kmax], by direct enumeration
    (integer arithmetic in Z[sqrt(d)], reduced at each place)."""
    d = places[0]["d"]
    out = set()
    a, b = 1, 0  # eps^0
    powers = [(1, 0)]
    for _ in range(kmax):
        a, b = a * eps[0] + b * eps[1] * d, a * eps[1] + b * eps[0]
        powers.append((a, b))
    # inverse powers: eps^-1 = +-conjugate depending on norm; walk both
    # signs of every power instead, and conjugates for negative k
    for (a, b) in powers:
        for (u, v) in ((a, b), (-a, -b), (a, -b), (-a, b)):
            # (a, -b) is the conjugate: eps^-k up to the norm's sign,
            # so all of +-eps^k for |k| <= kmax appear among these
            out.add(tuple(pl["red"](u, v) for pl in places))
    return out


def norm(a, b, d):
    return a * a - b * b * d


def valuation(place, a, b):
    """v_P(a + b sqrt(d)) at a split place, by Hensel-free counting:
    divide by p while the residue at r is 0 and the norm allows."""
    p, r, d = place["p"], place["r"], place["d"]
    n = abs(norm(a, b, d))
    v = 0
    while n % p == 0 and (a + b * r) % p == 0:
        # divide the ideal: multiply by the conjugate uniformizer's
        # effect -- track via norm and residue instead of element
        # division; for this rig's uses (prime-power norms) the count
        # v = v_p(N) at a split place with residue 0 at r only
        v += 1
        n //= p
    return v


def run():
    d1, d2 = 2, -5
    eps1 = (1, 1)  # 1 + sqrt(2)

    K1_places = [
        make_split_place(7, 3, d1), make_split_place(7, 4, d1),
        make_split_place(17, 6, d1), make_split_place(17, 11, d1),
        make_inert_place(3, d1),
        make_split_place(23, 5, d1), make_split_place(23, 18, d1),
    ]
    K2_P3 = make_split_place(3, 1, d2)
    K2_P3p = make_split_place(3, 2, d2)
    K2_P7p = make_split_place(7, 4, d2)

    print("== F0 controls ==")
    # (a) splitting verdicts by direct quadratic-residue check
    def split_kind(p, d):
        if d % p == 0 or p == 2 and d % 2 == 0:
            return "ram", []
        roots = [r for r in range(p) if (r * r - d) % p == 0]
        if p == 2:
            return ("ram", roots) if (1 - d) % 2 == 0 else ("?", roots)
        return ("split", roots) if roots else ("inert", roots)
    for (dd, plist) in ((d1, (2, 3, 7, 17, 23)), (d2, (2, 3, 7, 11))):
        for p in plist:
            kind, roots = split_kind(p, dd)
            print(f"  d={dd} p={p}: {kind} {roots}")

    # (b) the hand table
    print("  -- K1 unit-image table (ord eps, |im|) --")
    for pl in K1_places:
        e = pl["red"](*eps1)
        im = place_image(pl, eps1)
        print(f"  {pl['label']}: ord(eps)={elt_order(pl, e)} |im|={len(im)}")

    # (c) saturation at the frozen moduli
    frozen_K1 = [
        (K1_places[0], K1_places[5]),   # P7(r=3) * P23(r=5) witness
        (K1_places[0], K1_places[2]),   # P7(r=3) * P17(r=6) control
    ]
    for pair in frozen_K1:
        ji = joint_image(list(pair), eps1)
        en = enumerated_unit_image(list(pair), eps1)
        print(f"  saturation {pair[0]['label']}*{pair[1]['label']}: "
              f"closure={len(ji)} enumerated={len(en)} "
              f"equal={ji == en}")

    # (d) the K2 ideal witness arithmetic
    g = (2, 3)  # 2 + 3 sqrt(-5)
    print(f"  N(2+3 sqrt(-5)) = {norm(*g, d2)}")
    v3 = valuation(make_split_place(7, 3, d2), *g)
    v4 = valuation(K2_P7p, *g)
    print(f"  valuations over 7 at (r=3, r=4): ({v3}, {v4})")

    print("== F1/F2: the K1 witness and control ==")
    for pair, tag in zip(frozen_K1, ("witness", "control")):
        pls = list(pair)
        ims = [place_image(pl, eps1) for pl in pls]
        ji = joint_image(pls, eps1)
        prod_im = 1
        for im in ims:
            prod_im *= len(im)
        group = 1
        for pl in pls:
            group *= pl["order"]
        rho = prod_im // len(ji)
        h_m = group // len(ji)          # h = 1 for K1
        perterm = group // prod_im
        print(f"  {tag} {pls[0]['label']}*{pls[1]['label']}: "
              f"prod im={prod_im} joint={len(ji)} rho={rho} "
              f"h_m={h_m} perterm={perterm}")

    print("== F3: K2, rank 0 ==")
    h_K2 = 2
    for pls, tag in (([K2_P3, K2_P3p], "two-place"),
                     ([K2_P3, K2_P3p, K2_P7p], "three-place")):
        ims = [place_image(pl, None) for pl in pls]
        ji = joint_image(pls, None)
        prod_im = 1
        for im in ims:
            prod_im *= len(im)
        group = 1
        for pl in pls:
            group *= pl["order"]
        rho = prod_im // len(ji)
        h_m = h_K2 * group // len(ji)
        perterm = h_K2 * group // prod_im
        print(f"  {tag}: prod im={prod_im} joint={len(ji)} rho={rho} "
              f"h_m={h_m} perterm={perterm}")

    # ideal witnesses at the two-place modulus
    pls = [K2_P3, K2_P3p]
    ji = joint_image(pls, None)
    res_gamma = tuple(pl["red"](-2, -3) for pl in pls)   # -(2+3 sqrt(-5))
    res_sqrt = tuple(pl["red"](0, 1) for pl in pls)      # sqrt(-5)
    res_five = tuple(pl["red"](-5, 0) for pl in pls)     # (sqrt(-5))^2 gen
    ones = tuple(pl["one"] for pl in pls)
    print(f"  -(2+3 sqrt(-5)) mod (P3, P3') = {res_gamma} "
          f"(1 at both: {res_gamma == ones}) -> [P7'] order 2")
    print(f"  sqrt(-5) residue = {res_sqrt}, in joint image: "
          f"{res_sqrt in ji}; (-5) residue = {res_five}, trivial "
          f"coset: {res_five in ji}")

    print("== F4: the full K1 pair scan ==")
    odd_odd_entangled = []
    for i in range(len(K1_places)):
        for j in range(i + 1, len(K1_places)):
            pls = [K1_places[i], K1_places[j]]
            ims = [place_image(pl, eps1) for pl in pls]
            ji = joint_image(pls, eps1)
            prod_im = len(ims[0]) * len(ims[1])
            rho = prod_im // len(ji)
            o1 = elt_order(pls[0], pls[0]["red"](*eps1))
            o2 = elt_order(pls[1], pls[1]["red"](*eps1))
            flag = " <-- entangled" if rho > 1 else ""
            print(f"  {pls[0]['label']}*{pls[1]['label']}: "
                  f"ords=({o1},{o2}) prod={prod_im} joint={len(ji)} "
                  f"rho={rho}{flag}")
            if rho > 1 and o1 % 2 == 1 and o2 % 2 == 1:
                odd_odd_entangled.append((pls[0]["label"], pls[1]["label"]))
    print(f"  odd-odd entangled pairs: {odd_odd_entangled}")


if __name__ == "__main__":
    run()
