"""
explore_three_prints.py -- three conjectures, each decided by the cheapest
print that can end it: the offset word's pair correlation against a
rotation, the splitting-field walk's admissibility test against Rabin's,
and the flag-setter census over a disassembled binary's loops.

THE THREE QUESTIONS.

  Q1. THE OFFSET SOURCE. On a fractional-power supply m(g) = ceil g^(1/c)
      with 1 < c < 2 the growing-window rider lands at a sequence of
      passes t_n, each landing sitting in the gap window d_n at offset
      o_n = top(d_n) - t_n below the window's top, top(d) = floor(d^c) - 2
      (explore_supply_tameness.py, explore_super_critical.py). The
      normalized offset o_n / w(d_n), w(d) = top(d) - top(d-1) the window
      width, was measured uniform on [0, 1) to Kolmogorov distance 0.003
      over 10^5 landings. The conjecture reads that uniformity as a
      random source. The question: is the offset word a rotation in
      disguise -- consecutive offsets tied by a deterministic angle --
      or is it correlation-free at every lag?

  Q2. THE SPLITTING-FIELD FACTORY. Over F_2[x] the transparency wall at
      clock L = 2^n - 1 is x^(2^n) + x, the product of every irreducible
      of degree dividing n (the wall identity, explore_fate_image_ff.py F2).
      A least-move
      transparency walk with that clock from the seed x dies at the
      wall, having multiplied by every such irreducible. The question:
      what does DECIDING a move's admissibility cost -- is "lambda(N m)
      divides L" a computation cheaper than an irreducibility test of
      m, or is it that test under another name?

  Q3. THE BORROW-GATED ISA. If nearly every loop in real machine code
      is controlled by a subtraction-family instruction (cmp, sub, dec,
      neg, sbb -- the depth face's decremented counter), then an
      instruction set that gates subtraction and comparison behind one
      privilege bit has that bit on in nearly every loop, and its
      decidable core is empty. The question: over a large disassembled
      binary, what share of backward conditional jumps read flags set
      by a subtraction-family instruction, and what share by a Boolean
      one (test, and, or, xor) or by none at all?

THE HAND ATTACK, before any engine code.

  Q1. The top offset obeys o(d) = (o(d-1) + w(d)) mod d at every
      populated window, w(d) ~ c d^(c-1) < d inside the band, so the
      offset moves by one window width per gap value and wraps once per
      d / w(d) ~ d^(2-c) / c values. Read as a point on the circle at
      resolution d, the offset is a ROTATION by the angle w(d)/d ~
      c d^(c-2), an angle that drifts to zero as d grows: the word is
      the fractional part of (c/(c-1)) d^(c-1) plus bookkeeping, a Weyl
      sequence n^theta with theta = c - 1 in (0, 1), equidistributed by
      Fejer's theorem and nothing random about it. Two consequences a
      print can read. (a) Consecutive normalized offsets differ by the
      angle, so the lag-1 difference (x_{n+1} - x_n) mod 1 is
      concentrated near one drifting value instead of uniform. (b) The
      sweep completes about K(N) ~ (c/(c-1)) N^(c-1) turns in N
      landings, so its star discrepancy falls like N^(1-c): the
      exponent 1/2 at c = 3/2 -- the one c the census measured to
      Kolmogorov 0.003 ~ 1/sqrt(10^5), a coincidence of the exponent --
      and 2/3, 1/3, 1/4 at c = 4/3, 5/3, 7/4, where a random source
      prints 1/2 at every c and a rotation about 1.
      TRANSPLANT FLAG: the recurrence was derived at the sqrt supply
      and restated over any monotone supply by the tameness record; the
      landings here are generated by the closed pointer and
      bisimulated against the tick rider on every supply before any
      offset is read.

  Q2. lambda(N m) divides 2^n - 1 with N already dividing x^(2^n) + x
      iff m is squarefree, coprime to N, and every irreducible factor
      of m has degree dividing n -- iff m divides x^(2^n) + x and
      gcd(m, N) = 1. So admissibility is one gcd with x^(2^n) + x, the
      distinct-degree step of the Berlekamp-Rabin factorization, and
      the least-move walk supplies its candidates by exhaustive
      enumeration in degree order. Once the state holds every
      irreducible of degree properly dividing n, a candidate of degree
      n is admissible iff it is irreducible: the admissibility test is
      then exactly Rabin's irreducibility test (m | x^(2^n) + x, with
      the proper-divisor gcds discharged by the state), and the factory
      is Rabin's test run over every polynomial of degree n. The walk
      from x at clock 63 should take x + 1, the one quadratic, the two
      cubics and the nine sextics, fourteen moves, and die at
      x^64 + x.

  Q3. An x86 conditional jump reads flags, and the flag-setter of a
      loop's back edge is a comparison of the counter or index against
      a bound (cmp), a decrement (dec, sub) or a Boolean test of a
      loaded value (test, and). Compilers emit cmp for counted loops
      and test for pointer and flag loops. The subtraction family
      should dominate. A backward jump whose nearest flag-setter is a
      call or nothing within the block is opaque and counted as such.
      The depth/element split is approximated by the operands: a
      subtraction-family flag-setter with no memory operand is
      counter-shaped, one reading memory is data-shaped; the
      approximation is named as one.

PREDICTIONS, fixed before the run.
  P1. At every c in {4/3, 3/2, 5/3, 7/4}, the lag-1 difference
      histogram (100 bins) of the normalized offset word carries more
      than half its mass in its heaviest bin; a seeded random word
      carries about 0.01 there and the rotation by phi carries 1.0.
  P2. The star discrepancy's log-log slope between N = 10^4 and 10^5
      sits within 0.15 of -(c - 1) at each c; the random control's
      within 0.15 of -0.5; the rotation's below -0.8.
  P3. The walk from x at clock 63 makes exactly 14 moves, in degree
      order 1, 2, 3, 3, 6 x 9, and its final state is x^64 + x; over
      all 64 monic sextics, admissibility from the state holding the
      degree-1, 2, 3 irreducibles agrees with Rabin's test at all 64.
  P4. Subtraction-family flag-setters at 80% or more of backward
      conditional jumps; Boolean at most 20%; opaque under 5%.

KILL CRITERIA, as observables.
  Q1 killed iff P1 and P2 both print (a rotation with a drifting angle,
      pair-correlated at lag 1 at every c); survives iff the heaviest
      bin is under 0.1 at every c and the slope is within 0.15 of -0.5
      at every c.
  Q2 killed by the derivation, the run its positive control: P3.
  Q3 killed iff the subtraction-family share is 80% or more on both
      binaries read; survives iff under 50% on either.

THE SECOND SITTING'S ADDENDUM, frozen after the first run's prints and
before the second. The first run left Q1 and Q3 between their bands
(the findings below), so two further prints were added.
  Q1b. The discrepancy ladder extended to N = 10^6 at c = 3/2 and 7/4
       with the slope read over the last decade, the lag-1..8 heaviest
       bins, and a second random seed to calibrate the slope's noise.
       Prediction P5: the offset word's slope over 10^5..10^6 stays
       above -0.45 at both c (slower than random) while both random
       seeds print between -0.65 and -0.35, and every lag's heaviest
       bin stays under 0.02.
  Q3b. For every backward conditional jump, the loop BODY -- the
       instructions from the jump's target to the jump -- scanned for
       any subtraction-family instruction. Prediction P6: 85% or more
       of bodies carry one on both binaries. Refrozen kill: Q3 killed
       iff that share is 80% or more on both.

FINDINGS (both runs; the second run's prints, which include the first's).

  F1. THE OFFSET WORD IS NOT A ROTATION, AND THE HAND ATTACK WAS WRONG
      ABOUT WHY. The lag-1 and lag-2 heaviest centiles are 0.010-0.012
      at every c (random 0.010-0.011; the rotation 1.000), and lags 1..8
      at c = 3/2 and 7/4 all sit at 0.010-0.013: no pair correlation at
      any lag read. P1 failed outright. The transplant that failed is
      the step "o(d) = o(d-1) + w(d) mod d per window": inside the band
      almost every window is EMPTY (multiplicity at most 1, the gap
      growing as t^(1/c)), so consecutive landings sit many windows
      apart and the offset at the next landing is not the last offset
      plus one width. What the word IS (Q1b's print over landings
      100..20000: mean deviation 0.00025 at c = 3/2 and 0.00017 at 7/4;
      0.00044 at 4/3 in a hand check outside the script): the normalized
      offset is 1 - frac((t_n + 2)^(1/c))
      to first order, since a landing in window d has (t + 2)^(1/c) in
      (d - 1, d] and o = floor(d^c) - 2 - t ~ w(d) * (d - (t+2)^(1/c)).
      A Weyl word frac(f(t)) along the landing orbit, f = t^(1/c), whose
      increment (1/c) t^(2/c - 1) grows along the orbit -- the increments
      themselves equidistribute, which is why every lag is flat.
  F2. ITS DISCREPANCY IS A RANDOM SOURCE'S AT c = 3/2 AND WORSE AT 7/4.
      Star discrepancy over the decade 10^5..10^6: slope -0.58 at c = 3/2
      and -0.37 at c = 7/4, the two random seeds -0.53 and -0.52, the
      rotation -1.05; over 10^4..10^5 the four c print -0.34, -0.33,
      -0.40, -0.32 against random's -0.58 and -0.46. D*(10^6) = 0.00081
      at 3/2 and 0.00115 at 7/4 against random's 0.00071 and 0.00066.
      P2's predicted exponents (-(c - 1)) are wrong at every c; P5 is
      half wrong (c = 3/2 fell to random's rate over the last decade).
      Verdict on Q1: the source is deterministic, seed-free and exactly
      analysable, as claimed, because it is a Weyl sequence, whose
      equidistribution is van der Corput's theorem and not the supply's;
      its coverage bound is no better than a hashed generator's
      empirical one, and quasi-Monte Carlo already owns the deterministic
      source with a PROVEN bound, (log N)/N, better by a power. Killed at
      incumbent contact.
  F3. THE FACTORY IS RABIN'S TEST. The walk from x at clock 63 takes 13
      moves (P3 said 14, counting the seed): x + 1, x^2 + x + 1, the two
      cubics, the nine sextics in integer order, 9, 8, ..., 1 admissible
      at degree 6 as they go, and dies with the state exactly x^64 + x.
      From the state holding the degree-1, 2, 3 irreducibles, sextic
      admissibility agrees with Rabin's irreducibility test at 64 of 64
      (9 admissible). The derivation stands: admissibility at the wall
      clock is one gcd with x^(2^n) + x, and at degree n from that state
      it is Rabin's test, its proper-divisor gcds discharged by what is
      seated. Killed.
  F4. THE BIT IS ON IN NINETEEN LOOPS OF TWENTY. At the back edge the
      subtraction family sets the flags of 59.7% (python312.dll, 19,339
      backward conditional jumps) and 65.0% (libstdc++-6.dll, 6,124) of
      loops, Boolean tests 34.6% and 32.5%, other arithmetic 4.3% and
      1.4%, opaque 1.4% and 1.1% -- between the frozen bands, P4 wrong
      on the Boolean share. Over the loop BODY, 94.9% and 93.3% carry a
      subtraction-family instruction: P6 met, the refrozen kill fired.
      The counter-shaped split (register/immediate operands only) is
      42.4% and 66.8% of the subtraction family, an approximation.
      Killed: an ISA gating subtraction and comparison behind one bit
      has the bit on in nineteen of twenty loops on both corpora.

RUN RECORD. Second run: 16.6 s wall, peak working set 359 MB
(memwatch, limit 512), Python 3.12 on Windows, objdump from the WinLibs
mingw64 toolchain over python312.dll (3.12.10) and libstdc++-6.dll.
The first run's pointer stepped the gap by one and never finished at
c = 4/3, where the gap reaches 1.6 x 10^13 by the 10^5th landing; the
pointer now iterates d <- m(t + d + 2) to its least fixed point.

Run: python prime/code/explore_three_prints.py  (about twenty seconds;
the disassembly is read from objdump on the two binaries named in Q3's
section, and skipped with a notice if objdump is absent).
"""
import os
os.environ.setdefault("OPENBLAS_NUM_THREADS", "1")
import math
import random
import re
import shutil
import subprocess
import sys
import time
from fractions import Fraction

# ----------------------------------------------------------------------
# Q1. THE OFFSET WORD
# ----------------------------------------------------------------------

def iroot_floor(a, k):
    """largest r >= 0 with r^k <= a (exact, integers)."""
    if a < 2:
        return a
    r = int(round(a ** (1.0 / k)))
    while r ** k > a:
        r -= 1
    while (r + 1) ** k <= a:
        r += 1
    return r

def make_supply(c):
    """c = p/q. m(g) = ceil g^(q/p) = least m with m^p >= g^q;
    M(d) = floor d^(p/q) = largest M with M^q <= d^p."""
    p, q = c.numerator, c.denominator
    def m(g):
        if g <= 0:
            return 0
        r = iroot_floor(g ** q, p)
        return r if r ** p >= g ** q else r + 1
    def M(d):
        return iroot_floor(d ** p, q)
    return m, M

def landings_pointer(m, n_land):
    """Landing passes t_1..t_n by the closed pointer: from a landing at
    t the gap is d = min{j >= 2 : j >= m(t + j + 2)}, non-decreasing."""
    t, d = 0, 2
    out = []
    while len(out) < n_land:
        # least j >= d with j >= m(t + j + 2): iterate d <- m(t + d + 2),
        # every j below the image failing since m is non-decreasing
        while True:
            nd = m(t + d + 2)
            if nd <= d:
                break
            d = nd
        t += d
        out.append((t, d))
    return out

def landings_rider(m, t_max):
    """The tick rider itself: v := (v + 1) mod max(2, m(g)), g = t + 2,
    one pass per tick; a landing is a pass at which v returns to 0."""
    v = 0
    out = []
    for t in range(1, t_max + 1):
        v = (v + 1) % max(2, m(t + 2))
        if v == 0:
            out.append(t)
    return out

def star_discrepancy(xs):
    xs = sorted(xs)
    n = len(xs)
    best = 0.0
    for i, x in enumerate(xs, 1):
        best = max(best, i / n - x, x - (i - 1) / n)
    return best

def lag_histogram(xs, lag=1, bins=100):
    h = [0] * bins
    for i in range(len(xs) - lag):
        dlt = (xs[i + lag] - xs[i]) % 1.0
        h[min(bins - 1, int(dlt * bins))] += 1
    tot = sum(h)
    return max(h) / tot

def word_report(name, xs):
    d3 = star_discrepancy(xs[:1000])
    d4 = star_discrepancy(xs[:10000])
    d5 = star_discrepancy(xs[:100000])
    slope = math.log(d5 / d4) / math.log(10)
    top1 = lag_histogram(xs, 1)
    top2 = lag_histogram(xs, 2)
    print("  %-22s D*(10^3)=%.4f D*(10^4)=%.4f D*(10^5)=%.5f "
          "slope %.2f | lag-1 top bin %.3f, lag-2 %.3f"
          % (name, d3, d4, d5, slope, top1, top2))
    if len(xs) >= 1000000:
        d6 = star_discrepancy(xs[:1000000])
        slope6 = math.log(d6 / d5) / math.log(10)
        lags = " ".join("%.3f" % lag_histogram(xs[:200000], k)
                        for k in range(1, 9))
        print("  %-22s D*(10^6)=%.6f slope over the last decade %.2f | "
              "lag 1..8 heaviest bins %s" % ("", d6, slope6, lags))
        return slope6, top1
    return slope, top1

def q1b():
    print("\nQ1b THE LADDER TO 10^6, the lags to 8, a second seed")
    N = 1000000
    out = {}
    for c in (Fraction(3, 2), Fraction(7, 4)):
        m, M = make_supply(c)
        t0 = time.time()
        L = landings_pointer(m, N)
        top = lambda d: M(d) - 2
        xs = [(top(d) - t) / (top(d) - top(d - 1)) for t, d in L]
        print("  c = %s: %d landings (%.1fs)" % (c, N, time.time() - t0))
        # the closed form: x_n ~ 1 - frac((t_n + 2)^(1/c)), read in floats
        # over the first 20,000 landings, where t is exact in a double
        dev = 0.0
        for (t, d), x in list(zip(L, xs))[100:20000]:
            y = 1.0 - math.fmod((t + 2) ** (1.0 / float(c)), 1.0)
            dev += abs(x - y)
        print("  %-22s mean |x - (1 - frac((t+2)^(1/c)))| = %.5f over "
              "landings 100..20000" % ("", dev / 19900))
        out[c] = word_report("offset / width", xs)
    for seed in (1, 2):
        rng = random.Random(seed)
        out["seed %d" % seed] = word_report(
            "random (seed %d)" % seed, [rng.random() for _ in range(N)])
    return out

def q1():
    print("Q1  THE OFFSET WORD against a rotation and a random source")
    N = 100000
    results = {}
    for c in (Fraction(4, 3), Fraction(3, 2), Fraction(5, 3),
              Fraction(7, 4)):
        m, M = make_supply(c)
        t0 = time.time()
        L = landings_pointer(m, N)
        # positive control: bisimulate the pointer against the rider
        T = 200000
        rider = landings_rider(m, T)
        ptr = [t for t, _ in L if t <= T]
        assert rider == ptr, ("pointer/rider disagree at c=%s" % c)
        top = lambda d: M(d) - 2
        xs_w, xs_d = [], []
        for t, d in L:
            o = top(d) - t
            w = top(d) - top(d - 1)
            assert 0 <= o < w, (c, t, d, o, w)
            xs_w.append(o / w)
            xs_d.append(o / d)
        print("  c = %s: %d landings, last t = %d, last gap %d, "
              "rider agrees on %d landings to t = %d (%.1fs)"
              % (c, N, L[-1][0], L[-1][1], len(rider), T,
                 time.time() - t0))
        s_w, b_w = word_report("offset / width", xs_w)
        s_d, b_d = word_report("offset / gap", xs_d)
        results[c] = (s_w, b_w, s_d, b_d)
    rng = random.Random(1)
    xr = [rng.random() for _ in range(N)]
    phi = (math.sqrt(5) - 1) / 2
    xrot = [(n * phi) % 1.0 for n in range(N)]
    print("  controls:")
    s_r, b_r = word_report("random (seed 1)", xr)
    s_rot, b_rot = word_report("rotation by phi", xrot)
    return results, (s_r, b_r), (s_rot, b_rot)

# ----------------------------------------------------------------------
# Q2. THE SPLITTING-FIELD WALK
# ----------------------------------------------------------------------

def pmul(a, b):
    r = 0
    while b:
        if b & 1:
            r ^= a
        a <<= 1
        b >>= 1
    return r

def pmod(a, b):
    db = b.bit_length() - 1
    while a and a.bit_length() - 1 >= db:
        a ^= b << (a.bit_length() - 1 - db)
    return a

def pgcd(a, b):
    while b:
        a, b = b, pmod(a, b)
    return a

def pdeg(a):
    return a.bit_length() - 1

def x_pow2n_plus_x(n):
    """x^(2^n) + x as an integer polynomial over F_2 (degree 2^n)."""
    return (1 << (1 << n)) ^ 2

def rabin_irreducible(m, n):
    """Rabin: deg m = n, m | x^(2^n) + x, and gcd(m, x^(2^(n/q)) + x) = 1
    for every prime q | n -- computed with the full wall polynomials,
    which is affordable at n = 6."""
    if pdeg(m) != n:
        return False
    if pmod(x_pow2n_plus_x(n), m) != 0:
        return False
    for q in (2, 3, 5, 7):
        if n % q == 0:
            if pgcd(m, x_pow2n_plus_x(n // q)) != 1:
                return False
    return True

def q2():
    print("\nQ2  THE SPLITTING-FIELD WALK at clock 63 from seed x")
    n = 6
    wall = x_pow2n_plus_x(n)
    N = 0b10  # x
    moves = []
    while True:
        found = None
        for e in range(1, n + 1):
            cands = [m for m in range(1 << e, 1 << (e + 1))
                     if pmod(wall, m) == 0 and pgcd(m, N) == 1]
            if cands:
                found = (e, min(cands), len(cands))
                break
        if found is None:
            break
        e, m, k = found
        N = pmul(N, m)
        moves.append((e, m, k))
        print("  move %2d: degree %d, m = %s (%d admissible at that "
              "degree), state degree %d"
              % (len(moves), e, format(m, "b"), k, pdeg(N)))
    print("  walk dead after %d moves; final state == x^64 + x: %s"
          % (len(moves), N == wall))
    # the derivation's check: from the state holding every irreducible
    # of degree 1, 2, 3, admissibility of a sextic == Rabin's test
    S = 0b10
    for e in (1, 2, 3):
        for m in range(1 << e, 1 << (e + 1)):
            if pmod(wall, m) == 0 and pgcd(m, S) == 1:
                S = pmul(S, m)
    agree = 0
    adm = 0
    for m in range(1 << 6, 1 << 7):
        a = (pmod(wall, m) == 0 and pgcd(m, S) == 1)
        r = rabin_irreducible(m, 6)
        agree += (a == r)
        adm += a
    print("  from the degree-1..3 state, sextic admissibility agrees "
          "with Rabin's test at %d of 64 (%d admissible)" % (agree, adm))
    return moves, N == wall, agree, adm

# ----------------------------------------------------------------------
# Q3. THE FLAG-SETTER CENSUS
# ----------------------------------------------------------------------

SUBFAM = {"cmp", "sub", "dec", "neg", "sbb", "comisd", "comiss",
          "ucomisd", "ucomiss", "vcomisd", "vcomiss", "vucomisd",
          "vucomiss"}
BOOLF = {"test", "and", "or", "xor", "bt", "bts", "btr"}
OTHERF = {"add", "inc", "adc", "shl", "shr", "sar", "sal", "imul",
          "mul", "rol", "ror", "shld", "shrd", "popcnt", "bsf", "bsr",
          "lzcnt", "tzcnt"}
CTRL = {"jmp", "call", "ret", "int3", "hlt", "nop"}

def census(path):
    exe = shutil.which("objdump")
    if exe is None:
        print("  objdump absent; Q3 skipped")
        return None
    out = subprocess.run([exe, "-d", "--no-show-raw-insn", "-M", "intel",
                          path], capture_output=True, text=True,
                         errors="replace").stdout
    line_re = re.compile(r"^\s*([0-9a-f]+):\s+(\S+)\s*(.*)$")
    ins = []
    for line in out.splitlines():
        mm = line_re.match(line)
        if mm and not line.strip().endswith(":"):
            ins.append((int(mm.group(1), 16), mm.group(2), mm.group(3)))
    n_back = 0
    n_back_jmp = 0
    tally = {"sub": 0, "bool": 0, "other": 0, "opaque": 0}
    counter_shaped = 0
    body_sub = 0
    addr_index = {a: i for i, (a, _, _) in enumerate(ins)}
    for i, (addr, mn, ops) in enumerate(ins):
        if not mn.startswith("j"):
            continue
        tm = re.match(r"^(?:0x)?([0-9a-f]+)", ops.strip())
        if not tm:
            continue
        target = int(tm.group(1), 16)
        if target >= addr:
            continue
        if mn == "jmp":
            n_back_jmp += 1
            continue
        n_back += 1
        j0 = addr_index.get(target)
        if j0 is not None and any(ins[j][1] in SUBFAM
                                  for j in range(j0, i + 1)):
            body_sub += 1
        kind = "opaque"
        for j in range(i - 1, max(-1, i - 12), -1):
            m2, o2 = ins[j][1], ins[j][2]
            base = m2.rstrip("bwlq") if m2 not in SUBFAM | BOOLF | OTHERF else m2
            if m2 in SUBFAM or base in SUBFAM:
                kind = "sub"
                if "PTR" not in o2 and "[" not in o2:
                    counter_shaped += 1
                break
            if m2 in BOOLF or base in BOOLF:
                kind = "bool"
                break
            if m2 in OTHERF or base in OTHERF:
                kind = "other"
                break
            if m2 in CTRL or m2.startswith("j") or m2.startswith("cmov") \
                    or m2.startswith("set"):
                break
        tally[kind] += 1
    print("  %s: %d instructions, %d backward conditional jumps "
          "(+%d unconditional back-jumps)"
          % (os.path.basename(path), len(ins), n_back, n_back_jmp))
    for k in ("sub", "bool", "other", "opaque"):
        print("    %-7s %6d  %5.1f%%" % (k, tally[k],
                                         100.0 * tally[k] / max(1, n_back)))
    print("    of the subtraction family, register/immediate only "
          "(counter-shaped, approximate): %d = %.1f%%"
          % (counter_shaped, 100.0 * counter_shaped / max(1, tally["sub"])))
    print("    loop bodies (target..jump) carrying any subtraction-family "
          "instruction: %d = %.1f%%"
          % (body_sub, 100.0 * body_sub / max(1, n_back)))
    return tally["sub"] / max(1, n_back), body_sub / max(1, n_back)

def q3():
    print("\nQ3  THE FLAG-SETTER CENSUS over backward conditional jumps")
    cands = [
        os.path.join(os.path.dirname(sys.executable), "python312.dll"),
        os.path.join(os.path.dirname(shutil.which("objdump") or ""),
                     "libstdc++-6.dll"),
    ]
    shares = []
    for p in cands:
        if os.path.exists(p):
            s = census(p)
            if s is not None:
                shares.append(s)
        else:
            print("  %s not found, skipped" % p)
    return shares

if __name__ == "__main__":
    t0 = time.time()
    r1, rnd, rot = q1()
    r2 = q2()
    r3 = q3()
    r1b = q1b()
    print("\nSUMMARY")
    for c, (s_w, b_w, s_d, b_d) in r1.items():
        print("  c=%s  predicted slope %.2f  printed %.2f (width) %.2f (gap)"
              "  lag-1 top bin %.3f / %.3f" % (c, -(float(c) - 1), s_w, s_d,
                                              b_w, b_d))
    print("  random slope %.2f top bin %.3f; rotation slope %.2f top bin "
          "%.3f" % (rnd[0], rnd[1], rot[0], rot[1]))
    print("  walk: %d moves, dead at the wall: %s, Rabin agreement %d/64"
          % (len(r2[0]), r2[1], r2[2]))
    print("  subtraction-family shares at the back edge: %s; in the "
          "body: %s"
          % (", ".join("%.1f%%" % (100 * s) for s, _ in r3),
             ", ".join("%.1f%%" % (100 * b) for _, b in r3)))
    for k, (sl, tb) in r1b.items():
        print("  10^6 ladder %s: last-decade slope %.2f" % (k, sl))
    print("  wall %.1fs" % (time.time() - t0))
