"""The continued-fraction window: the reading geometry's third deletion.

THE QUESTION
------------
The reading lemma (explore_reading_geometry.py) models a window as a
metric measure geometry — a metric, a measure, and a nested cover
sequence — and prices readability at bounded lookahead by Lipschitz
constants against the covers' mesh and Lebesgue numbers. Its first
two instances were positional: the trailing (b-adic) window and the
leading/scale-circle window. This script opens a third window that is
NOT positional: precision t = the first t partial quotients of the
continued fraction. The cell at depth t (the cylinder of
[a_0; a_1, ..., a_t]) is a Stern–Brocot interval with endpoints the
convergent p_t/q_t and the mediant neighbor
(p_t + p_{t-1})/(q_t + q_{t-1}); cells partition the irrationals at
each depth and nest across depths.

THE CRUX, resolved on paper before the engines: what is the CF
window's metric — the one in which CF-readability IS Lipschitz?
The answer is a PAIR. In the Baire ultrametric on quotient strings,
readability at lookahead c is verbatim Lipschitz with constant 2^c —
the ultrametric instance of the lemma, true of any nested cell tree,
tautological. The value metric is where the maps of interest (integer
Mobius maps x -> (ax+b)/(cx+d)) carry honest Lipschitz constants —
but the cover's value-metric mesh is not a function of the depth:
the cylinder at [1,1,...,1] (t ones) has length ~ phi^{-2t} (quotient
1 is the smallest scale step) while same-depth cells with large
quotients are arbitrarily smaller. The window's theory lives in the
EXCHANGE RATE between the two metrics: by the Shannon–McMillan–
Breiman theorem the almost-everywhere rate (1/t) ln(1/|C_t|) is the
entropy of the Gauss map, pi^2/(6 ln 2), with real fluctuations
(Levy's constant); a positional window is exactly the zero-variance
case, where digit count and scale are the same ruler and one metric
suffices. Consequently "bounded lookahead" FORKS at this window into
two inequivalent notions — DIGIT-delay (quotients consumed minus
quotients emitted) and SCALE-delay (log of input precision consumed
over output precision emitted) — and the hand analysis predicts:

  THE UNIT GATE. An integer Mobius map with det = +-1 acts on CF
  strings with bounded digit-delay: GL(2,Z) is generated by
  x -> x+1, x -> 1/x, and x -> x/(x+1) (first-quotient increment),
  each an exact transducer of delay <= 1, and delays add over a
  fixed word. [Sharpened after the run: the word argument as stated
  covers nonnegative-entry unimodular maps — the Stern-Brocot
  factorization into positive words in the three generators;
  sign-crossing words need the classical bounded negation rewrites,
  which the battery does not scan.] det != +-1 is not boundedly
  readable, witnessed by
  rate mismatch: x = phi = [1;(1)] has per-quotient denominator rate
  ln phi, while 2*phi = 1 + sqrt5 = [3;(4)] has rate
  ln(2 + sqrt5) = 3 ln phi exactly (phi^3 = 2 + sqrt5), so emitting
  t output quotients consumes ~3t input quotients — delay 2t, linear.
  The same gate shape as the positional windows: a multiplication-like
  map is readable iff it is a UNIT of the window's native structure
  (trailing/leading: u, v invertible in Z[1/b] — the radical gates;
  here: M invertible in M_2(Z)). Serret's theorem (same CF tail iff
  GL(2,Z)-equivalent) is the classical shadow.

  THE RATE LAW. The stall is orbit-local, not det-uniform: the local
  emission slope sigma = (output quotients per input quotient) equals
  the ratio rate_in/rate_out of the two orbits' denominator rates,
  and the digit-delay is the accumulated rate mismatch. A det-2 map
  can have ratio 1 at some witness — 2*sqrt2 = [2;(1,4)] has rate
  ln(1+sqrt2) = sqrt2's own rate, a Pell identity — and stall only
  elsewhere. Scale-delay stays bounded throughout: the fork made
  visible.

  THE BOUNDARY COLLAPSE. Cells partition (Lebesgue number 0), and the
  positional analogue (the leading window) turns that into permanent
  alignment walls. Here the hand analysis predicts NO separate
  boundary mechanism for Mobius maps: output cylinder boundaries are
  rationals, a preimage of a rational under an integer Mobius map is
  rational, hence finite CF — every boundary hug resolves at the
  preimage's CF length, which is itself the rate conversion of the
  boundary's scale. (Permanent boundary walls should need irrational
  boundary preimages — nonlinear maps like x -> x^2 — outside this
  script's Mobius scope.)

  THE OWN MEASURE. The Gauss measure dmu = dx/((1+x) ln 2) is the
  shift-invariant measure; the digit law is Gauss–Kuzmin
  P(a = k) = log2(1 + 1/(k(k+2))) — this window's mirror of Benford
  (the digit law = the invariant measure read through the digit
  grid; cells are not measure-uniform). The metric and measure
  chapters meet at the entropy: mesh decay = entropy a.e. (SMB),
  computable as the Rokhlin integral 2 int ln(1/x) dmu.

THE DESIGN
----------
Four engines, all exact-rational (Fraction) interval semantics: the
reader of M at input depth n knows only the depth-n input cylinder
I_n; the output quotients determined are extracted by walking the
continued fraction common to every point of the interval M(I_n)
(floor both endpoints, emit on agreement, recurse on reciprocals —
conservative at vertices). No closed form from the target laws enters
any rig; closed forms appear only as predicted values.

E0  POSITIVE CONTROLS (read before any verdict). (i) x -> 1/x at phi
    must read with digit-delay <= 1 at every scanned depth (the shift
    law). (ii) x -> 2x at phi must show emission slope near 1/3 (the
    known stall) — the rig must be able to SEE a stall.

E1  THE UNIT GATE. Battery: det = +-1 maps {x+1, 1/x, x/(x+1),
    (2x+1)/(x+1), x-1 (a negative-entry word; every witness exceeds
    1, so positivity holds)} and
    det != +-1 maps {2x, 3x, x/2} on witnesses {phi = [1;(1)],
    sqrt2 = [1;(2)], sqrt3 = [1;(1,2)], and a fixed pseudo-generic
    quotient string (deterministic LCG, quotients 1..5)}. For each
    pair, e(n) = output quotients determined at input depth n;
    delay(n) = n - e(n). Verdicts: unimodular pairs' delay is bounded
    and non-growing (max over the second half of depths equals, to
    +-1, the max over the first half); det != +-1 at phi grows
    linearly.

E2  THE RATE LAW. For each det != +-1 pair: measure the input rate
    r_in = ln(q_n)/n from the witness's convergents, the output rate
    r_out = ln(q_e)/e from the EMITTED quotients' convergents, and
    the emission slope sigma = e(n)/n at the deepest scan. Verdict:
    sigma * (r_out/r_in) = 1 within tolerance at every pair — the
    stall is the rate mismatch, including ratio 3 exactly at
    (2x, phi) (phi^3 identity) and ratio 1 at (2x, sqrt2) (Pell
    identity: expect sigma ~ 1, delay bounded/fluctuating there
    despite det = 2). SCALE-delay: ln(1/|output cell determined|) /
    ln(1/|I_n|) stays near 1 at (2x, phi) while e(n)/n sits near 1/3
    — the two-notion fork in one table.

E3  THE BOUNDARY COLLAPSE. Boundary family: the output vertex
    r_m = F_m/F_{m+1} (Fibonacci ratios, the CF-longest boundaries at
    their scale); its preimage under 2x is F_m/(2 F_{m+1}), rational.
    Measure (i) the preimage's CF length ell(m) — predicted ~ m/3 + O(1)
    (the rate conversion), and (ii) the hug: input = the preimage's
    quotients continued with an all-1s tail; the reader's staircase
    e(n) must run AHEAD (slope ~3) while inside the hug and resolve at
    depth ~ ell(m) — no stall beyond the rate account, at every
    scanned m.

E4  THE OWN MEASURE. (a) Gauss–Kuzmin masses log2(1 + 1/(k(k+2)))
    sum to 1 (partial sum + integral tail bound); (b) Gauss-map
    invariance of mu verified per depth-1 cell by the exact preimage
    decomposition (series in j, cutoff + tail bound); (c) the grid
    mismatch: mu(C)/|C| over a depth-2 cylinder census lies in
    [1/(2 ln 2), 1/ln 2], approaching the top at cells near 0;
    (d) the Rokhlin integral 2 int ln(1/x) dmu = pi^2/(6 ln 2) by
    quadrature; (e) the fluctuation witness: the mesh rate at phi is
    2 ln phi = 0.9624 (all-1s, the fattest chain), NOT the entropy
    2.3731 — the a.e. statement is measure-typical, not uniform; the
    positional control (all base-b cells at depth t have size b^{-t})
    has zero variance by construction.

PREDICTIONS (fixed before the run)
----------------------------------
P1  THE UNIT GATE: every unimodular pair reads at bounded,
    non-growing delay (<= 4 at all scanned depths); 2x, 3x, x/2 at
    phi stall linearly. Emission ratio at (2x, phi) -> 3 with the
    output rate hitting ln(2+sqrt5) = 3 ln phi (exact identity).
P2  THE RATE LAW: sigma * r_out/r_in = 1 within 6% at every
    det != +-1 pair at quadratic witnesses; (2x, sqrt2) has ratio 1
    (Pell) and shows NO linear stall; scale-delay ratio stays within
    a constant of 1 at (2x, phi) while digit emission sits near 1/3.
P3  THE BOUNDARY COLLAPSE: ell(m)/m -> 1/3 for the halved Fibonacci
    boundaries; the hug staircase resolves at ~ ell(m) with no
    stall beyond the rate account (delay after resolution returns to
    the phi-tail slope-2 line). [This partially REFUTES the framing
    "arithmetic stalls at cell boundaries": the unbounded stall is
    real but its mechanism is rate mismatch; the partition's
    Lebesgue-0 wall does not act separately for Mobius maps.]
P4  THE OWN MEASURE: digit masses sum to 1; invariance exact to
    tail-bound accuracy; mismatch ratios inside
    [1/(2 ln 2), 1/ln 2] = [0.7213, 1.4427]; Rokhlin integral =
    2.3731 to quadrature accuracy; mesh rate at phi 0.962, at the
    pseudo-generic string strictly between 0.962 and the entropy's
    neighborhood.

[Transplant marker: the redundancy prediction from the positional
corpus — that an overlapping (signed-quotient) CF cover buys the
delay back — is NOT tested here; the hand analysis says overlap can
kill only boundary stalls, and the CF stall is rate-shaped, so the
purchase should differ structurally. Deferred to its own slate.
SETTLED since by explore_cf_redundant.py: the hand analysis held —
the mediant cover cures every scanned wall and buys back none of
the rate stall (the ladder law: overlap extends terminated ladders,
adds rank nowhere else).]

Scopes are small (seconds); every engine prints its table, the
checks encode the predictions above, and the exit status is nonzero
on any failure.

FINDINGS (entered after the run; ALL ENGINES PASS)
--------------------------------------------------
P1  THE UNIT GATE CONFIRMED. Every unimodular pair reads at bounded
    NEGATIVE delay (maxima x+1 and x-1: -1; 1/x: -2; x/(x+1) and
    (2x+1)/(x+1): -3, identical across both depth halves at every
    witness — the interval reader runs ahead on mediant
    information; x-1 is the battery's negative-entry word),
    non-growing across depths 6..120.
    det != +-1 at phi stalls linearly: delay(60)/delay(150) =
    40/100 (2x), 30/74 (3x), 38/98 (x/2) — for 2x that is
    delay = 2n/3 in input digits, i.e. 2t in output digits, the
    hand-predicted slope. Rate ratio at (2x, phi) measured 3.0112
    (phi^3 = 2 + sqrt5 exact); output rate 1.4425 vs
    ln(2+sqrt5) = 1.4436.
P2  THE RATE LAW CONFIRMED, AND THE GATE IS ORBIT-LOCAL.
    sigma * r_out/r_in in [0.9947, 1.0264] at all nine det != +-1
    pairs. The Pell witness is the sharpest print: (2x, sqrt2) has
    rate ratio 0.9947 and delay(150) = 0 — a det-2 map reading a
    quadratic at ZERO delay, so non-unimodularity does NOT stall
    every orbit; it guarantees a mismatched witness exists (phi for
    the battery), and the stall is exactly the accumulated rate
    mismatch. Measured ratios sit at INTEGERS across all nine
    scanned quadratic pairs (3 at (2x, phi), (x/2, phi), (3x, sqrt3);
    2 at (3x, phi), (2x, sqrt3), (x/2, sqrt3), (3x, sqrt2); 1 at
    (2x, sqrt2), (x/2, sqrt2)) —
    regulator ratios of the orbit pairs. THE FORK made visible: at
    (2x, phi) the scale ratio holds at 0.978-0.982 while the digit
    ratio sits at 1/3 (0.350 -> 0.333) — bounded lookahead in scale,
    linear stall in digits, the two-metric split in one table. The
    pseudo-generic control runs AHEAD (delay -22 at 120, -60 at 240):
    the lcg string's digit law is not Gauss-Kuzmin, so its rate
    mismatch runs negative — the mismatch integral is signed.
P3  THE BOUNDARY COLLAPSE CONFIRMED. Halved Fibonacci boundaries
    F_m/(2F_{m+1}) have CF length ell/m = 0.400, 0.375, 0.364,
    0.357, 0.353 at m = 10..34, descending toward 1/3 (the rate
    conversion). The hug staircase runs ahead at slope ~3 inside the
    preimage (emitted 21 at depth 7), resolves at ~ell, and returns
    to the 1/3 rate account (post-resolution slope 0.333): no stall
    beyond the rate integral. The framing "arithmetic stalls at cell
    boundaries" is thereby partially refuted for Mobius maps: the
    unbounded stall is real but boundary hugs are finite (rational
    preimages, finite CF) and priced by the same rate account.
P4  THE OWN MEASURE CONFIRMED. Digit masses sum to 0.99998557 with
    tail < 1.4e-5; invariance exact to 7e-6 at scanned cells; grid
    mismatch spans [0.7385, 1.3764] inside [1/(2 ln 2), 1/ln 2] with
    cells near 0 at 1.4081; Rokhlin integral 2.3730 vs entropy
    2.3731; mesh rate at phi 0.9619 = 2 ln phi (the all-1s floor,
    NOT the entropy) vs 2.2479 at the pseudo-generic string — the
    digit/scale exchange rate is measure-typical with real
    fluctuations, and the positional window is its zero-variance
    degeneration. [The predictions as first written mis-copied the
    Gauss-Kuzmin constant as 1/(k(k+1)); the sum assert failed at
    1.2799 and the invariance engine's independently computed cell
    mass 0.415037 = log2(4/3) pinned the correct 1/(k(k+2)); one
    constant corrected, nothing else touched.]

Tier summary: the unit gate's sufficiency (det = +-1 reads at
bounded delay) is a RULE for nonnegative-entry unimodular maps —
the Stern-Brocot word decomposition (x+1, 1/x, x/(x+1) exact
transducers, delays add), verified at all scanned pairs — extending
to sign-crossing words by the classical negation rewrites
(unscanned; settled since at quadratic streams: boundedness there
is proved word-free — explore_cf_flow.py); its necessity holds as a
rule for the scanned battery (the
phi stall is algebraic: 2phi = [3;(4)] with phi^3 = 2+sqrt5) and is
CONJECTURED for general det != +-1 (every non-unimodular map should
own a mismatched witness — open) (settled since: PROVED — the
reduction to scalings with phi the universal witness,
explore_cf_conductor.py; its remaining lean points closed by
explore_cf_flow.py's rate forcing). The rate law
(sigma = r_in/r_out, delay = the signed mismatch integral) is a
RULE at the nine scanned pairs; the integer rate ratios are an
OBSERVATION (settled since: they are the conductor law — the ratio
is (i_out/i_in)(ell_in/ell_out) in unit indices and periods, a rule
recovering all nine — see explore_cf_conductor.py). The fork (scale-delay bounded, digit-delay stalls) is
a RULE at scanned scopes. The boundary collapse is a RULE at the
scanned family. The measure chapter verifies classical facts
(Gauss-Kuzmin, invariance, Rokhlin entropy) as controls for the
mirror statement: the digit law is the invariant measure read
through the digit grid, and the metric and measure chapters meet at
the entropy (SMB), where positional windows sit at zero variance.

RUN RECORD: ALL ENGINES PASS, < 1 s. E1 twenty unimodular pairs
bounded negative delay + three linear stalls at phi; E2 nine-pair
rate-law table as printed above; E3 ell/m descent + hug staircase;
E4 masses/invariance/mismatch/Rokhlin/mesh-rate prints as quoted.
"""

from fractions import Fraction
from math import log, pi, sqrt


# ------------------------------------------------------------------ #
# CF machinery (exact, Fraction-based)                                #
# ------------------------------------------------------------------ #

def convergents(quots):
    """(p, q) numerator/denominator lists for a quotient prefix."""
    ps, qs = [], []
    pm2, qm2, pm1, qm1 = 0, 1, 1, 0
    for a in quots:
        p, q = a * pm1 + pm2, a * qm1 + qm2
        ps.append(p)
        qs.append(q)
        pm2, qm2, pm1, qm1 = pm1, qm1, p, q
    return ps, qs


def cylinder(quots, n):
    """The depth-n cell: interval of all reals whose CF starts with
    quots[:n+1] (entries a_0..a_n). Endpoints: convergent p_n/q_n and
    mediant (p_n + p_{n-1})/(q_n + q_{n-1}). Returns (lo, hi)."""
    ps, qs = convergents(quots[: n + 1])
    end1 = Fraction(ps[n], qs[n])
    if n == 0:
        end2 = Fraction(ps[0] + 1)
    else:
        end2 = Fraction(ps[n] + ps[n - 1], qs[n] + qs[n - 1])
    return (end1, end2) if end1 < end2 else (end2, end1)


def interval_cf(lo, hi, cap=10 ** 4):
    """Quotients shared by EVERY point of the open interval (lo, hi).
    Conservative at vertices: emits only what is forced."""
    out = []
    while len(out) < cap:
        alo, ahi = lo.numerator // lo.denominator, hi.numerator // hi.denominator
        if hi == ahi:            # hi is an integer: interior floors top out at ahi-1
            ahi -= 1
        if alo != ahi:
            break
        out.append(alo)
        flo, fhi = lo - alo, hi - alo
        if flo == 0:             # next reciprocal unbounded above: undetermined
            break
        lo, hi = 1 / fhi, 1 / flo
    return out


def mobius(mat, x):
    a, b, c, d = mat
    return (a * x + b) / (c * x + d)


def image_interval(mat, lo, hi):
    u, v = mobius(mat, lo), mobius(mat, hi)
    return (u, v) if u < v else (v, u)


def emitted(mat, quots, n):
    """Output quotients determined from the depth-n input cylinder."""
    lo, hi = cylinder(quots, n)
    return interval_cf(*image_interval(mat, lo, hi))


def q_rate(quots):
    """ln(q)/len for the deepest convergent of a quotient list."""
    ps, qs = convergents(quots)
    n = len(qs) - 1
    return log(qs[n]) / n if n >= 1 and qs[n] > 1 else 0.0


def lcg_quots(count, seed=12345):
    """Fixed pseudo-generic quotient string, values 1..5."""
    out, s = [], seed
    for _ in range(count):
        s = (1103515245 * s + 12345) % (2 ** 31)
        out.append(1 + (s >> 8) % 5)
    return out


def rational_cf(fr):
    """Canonical CF of a positive rational (last quotient > 1)."""
    out = []
    while True:
        a = fr.numerator // fr.denominator
        out.append(a)
        fr -= a
        if fr == 0:
            return out
        fr = 1 / fr


# ------------------------------------------------------------------ #
# witnesses and battery                                               #
# ------------------------------------------------------------------ #

LMAX = 400
WITNESSES = {
    "phi":   [1] * LMAX,                       # [1;(1)]
    "sqrt2": [1] + [2] * LMAX,                 # [1;(2)]
    "sqrt3": [1] + [1, 2] * (LMAX // 2),       # [1;(1,2)]
    "lcg":   [1] + lcg_quots(LMAX),            # pseudo-generic, a_0 = 1
}

UNIMODULAR = {
    "x+1":         (1, 1, 0, 1),
    "x-1":         (1, -1, 0, 1),
    "1/x":         (0, 1, 1, 0),
    "x/(x+1)":     (1, 0, 1, 1),
    "(2x+1)/(x+1)": (2, 1, 1, 1),
}
NONUNIT = {
    "2x":  (2, 0, 0, 1),
    "3x":  (3, 0, 0, 1),
    "x/2": (1, 0, 0, 2),
}

FAILS = []


def check(label, ok):
    print(("  PASS  " if ok else "  FAIL  ") + label)
    if not ok:
        FAILS.append(label)


# ------------------------------------------------------------------ #
# E0: positive controls                                               #
# ------------------------------------------------------------------ #

def e0():
    print("\nE0 POSITIVE CONTROLS")
    quots = WITNESSES["phi"]
    delays = [n - len(emitted(UNIMODULAR["1/x"], quots, n))
              for n in range(4, 121, 8)]
    print(f"  1/x at phi: delays over depths 4..120: "
          f"min {min(delays)} max {max(delays)}")
    check("control (i): 1/x at phi delay <= 1", max(delays) <= 1)

    n = 150
    e = len(emitted(NONUNIT["2x"], quots, n))
    print(f"  2x at phi: e({n}) = {e}, emission slope {e / n:.4f}")
    check("control (ii): 2x at phi emission slope in (0.28, 0.40)",
          0.28 < e / n < 0.40)


# ------------------------------------------------------------------ #
# E1: the unit gate                                                   #
# ------------------------------------------------------------------ #

def e1():
    print("\nE1 THE UNIT GATE (delay(n) = n - e(n))")
    depths = list(range(6, 121, 6))
    print("  unimodular battery:")
    worst = 0
    grow_ok = True
    for mname, mat in UNIMODULAR.items():
        for wname, quots in WITNESSES.items():
            ds = [n - len(emitted(mat, quots, n)) for n in depths]
            half = len(ds) // 2
            worst = max(worst, max(ds))
            if max(ds[half:]) > max(ds[:half]) + 1:
                grow_ok = False
            print(f"    {mname:13s} at {wname:5s}: "
                  f"delay first-half max {max(ds[:half])}, "
                  f"second-half max {max(ds[half:])}")
    check("unimodular: delay bounded (<= 4) at all scanned pairs",
          worst <= 4)
    check("unimodular: delay non-growing (second half <= first half + 1)",
          grow_ok)

    print("  det != +-1 at phi (linear stall):")
    lin_ok = True
    for mname, mat in NONUNIT.items():
        d60 = 60 - len(emitted(mat, WITNESSES["phi"], 60))
        d150 = 150 - len(emitted(mat, WITNESSES["phi"], 150))
        print(f"    {mname:4s}: delay(60) = {d60}, delay(150) = {d150}")
        if d150 < d60 + 30:      # far more than any bounded reader allows
            lin_ok = False
    check("det != +-1 at phi: delay grows by >= 30 from depth 60 to 150",
          lin_ok)


# ------------------------------------------------------------------ #
# E2: the rate law                                                    #
# ------------------------------------------------------------------ #

def e2():
    print("\nE2 THE RATE LAW (sigma * r_out / r_in = 1)")
    n = 150
    rows = []
    for mname, mat in NONUNIT.items():
        for wname in ("phi", "sqrt2", "sqrt3"):
            quots = WITNESSES[wname]
            out = emitted(mat, quots, n)
            e = len(out)
            r_in = q_rate(quots[: n + 1])
            r_out = q_rate(out)
            sigma = e / n
            prod = sigma * r_out / r_in
            rows.append((mname, wname, sigma, r_in, r_out, prod))
            print(f"    {mname:4s} at {wname:5s}: sigma {sigma:.4f}  "
                  f"r_in {r_in:.4f}  r_out {r_out:.4f}  "
                  f"sigma*r_out/r_in {prod:.4f}")
    check("rate law: |sigma * r_out/r_in - 1| <= 0.06 at all 9 pairs",
          all(abs(p - 1) <= 0.06 for *_, p in rows))

    ratio = next(r[4] / r[3] for r in rows if r[0] == "2x" and r[1] == "phi")
    print(f"    (2x, phi) rate ratio {ratio:.4f} vs 3 (phi^3 = 2+sqrt5)")
    check("(2x, phi): rate ratio = 3 within 0.05", abs(ratio - 3) <= 0.05)

    ratio2 = next(r[4] / r[3] for r in rows if r[0] == "2x" and r[1] == "sqrt2")
    d150 = 150 - len(emitted(NONUNIT["2x"], WITNESSES["sqrt2"], 150))
    print(f"    (2x, sqrt2) rate ratio {ratio2:.4f} vs 1 (Pell); "
          f"delay(150) = {d150}")
    check("(2x, sqrt2): rate ratio = 1 within 0.05 (det 2, no mismatch)",
          abs(ratio2 - 1) <= 0.05)

    print("  the fork (2x at phi): digit vs scale")
    quots = WITNESSES["phi"]
    for nn in (40, 80, 150):
        lo, hi = cylinder(quots, nn)
        out = emitted(NONUNIT["2x"], quots, nn)
        olo, ohi = cylinder(out, len(out) - 1)
        s_in = log(1 / float(hi - lo))
        s_out = log(1 / float(ohi - olo))
        print(f"    n {nn:3d}: digit e/n {len(out) / nn:.3f}   "
              f"scale out/in {s_out / s_in:.3f}")
    lo, hi = cylinder(quots, 150)
    out = emitted(NONUNIT["2x"], quots, 150)
    olo, ohi = cylinder(out, len(out) - 1)
    check("the fork: at (2x, phi) scale ratio >= 0.9 while digit "
          "ratio <= 0.4",
          log(1 / float(ohi - olo)) / log(1 / float(hi - lo)) >= 0.9
          and len(out) / 150 <= 0.4)

    d240 = 240 - len(emitted(NONUNIT["2x"], WITNESSES["lcg"], 240))
    d120 = 120 - len(emitted(NONUNIT["2x"], WITNESSES["lcg"], 120))
    print(f"    2x at lcg (generic control): delay(120) = {d120}, "
          f"delay(240) = {d240}  [observation only]")


# ------------------------------------------------------------------ #
# E3: the boundary collapse                                           #
# ------------------------------------------------------------------ #

def e3():
    print("\nE3 THE BOUNDARY COLLAPSE (halved Fibonacci boundaries)")
    fib = [1, 1]
    while len(fib) < 40:
        fib.append(fib[-1] + fib[-2])
    ratios = []
    for m in (10, 16, 22, 28, 34):
        pre = Fraction(fib[m], 2 * fib[m + 1])
        ell = len(rational_cf(pre)) - 1          # count past a_0
        ratios.append(ell / m)
        print(f"    m {m:2d}: preimage F_m/(2F_m+1) CF length {ell}, "
              f"ell/m {ell / m:.3f}")
    check("boundary preimages: ell/m in (0.25, 0.45) at all scanned m",
          all(0.25 < r < 0.45 for r in ratios))

    # the hug: preimage's quotients + all-1s tail; staircase around ell
    m = 28
    pre = Fraction(fib[m], 2 * fib[m + 1])
    hug = rational_cf(pre)
    hug = hug[:-1] + [hug[-1] - 1, 1] if hug[-1] > 1 else hug  # open the vertex
    quots = hug + [1] * 200
    ell = len(hug) - 1
    pts = [(n, len(emitted(NONUNIT["2x"], quots, n)))
           for n in (ell - 4, ell, ell + 20, ell + 60, ell + 120)]
    for n, e in pts:
        print(f"    hug m=28 (ell = {ell}): depth {n:3d} -> emitted {e}")
    inside_ahead = pts[0][1] >= 2 * pts[0][0]
    tail1 = (pts[4][1] - pts[3][1]) / (pts[4][0] - pts[3][0])
    print(f"    post-resolution emission slope {tail1:.3f} "
          f"(phi-tail rate account: 1/3)")
    check("the hug runs ahead inside (e >= 2n at depth ell-4)",
          inside_ahead)
    check("post-resolution slope returns to the rate account "
          "(1/3 within 0.08)", abs(tail1 - 1 / 3) <= 0.08)


# ------------------------------------------------------------------ #
# E4: the own measure                                                 #
# ------------------------------------------------------------------ #

def mu(lo, hi):
    """Gauss measure of (lo, hi) inside (0,1)."""
    return (log(1 + hi) - log(1 + lo)) / log(2)


def e4():
    print("\nE4 THE OWN MEASURE")
    # (a) Gauss-Kuzmin masses sum to 1
    K = 10 ** 5
    s = sum(log(1 + 1 / (k * (k + 2))) for k in range(1, K)) / log(2)
    tail = 1 / (K * log(2))      # log(1+x) <= x, sum_{k>=K} 1/(k(k+2)) < 1/K
    print(f"    digit masses: partial sum {s:.8f} + tail < {tail:.1e}")
    check("Gauss-Kuzmin masses sum to 1 (within tail bound)",
          abs(s - 1) < tail)

    # (b) invariance on depth-1 cells: G^{-1}((1/(k+1), 1/k)) = U_j ...
    inv_ok = True
    for k in (1, 2, 5):
        cell = mu(Fraction(1, k + 1), Fraction(1, k))
        J = 10 ** 5
        pre = sum(mu(Fraction(k, j * k + 1), Fraction(k + 1, j * (k + 1) + 1))
                  for j in range(1, J))
        if abs(pre - cell) > 1e-4:
            inv_ok = False
        print(f"    invariance k={k}: mu(cell) {cell:.6f}  "
              f"mu(preimage) {pre:.6f}")
    check("Gauss measure invariant on depth-1 cells (1e-4 w/ cutoff)",
          inv_ok)

    # (c) grid mismatch on a depth-2 census
    lo_b, hi_b = 1 / (2 * log(2)), 1 / log(2)
    worst_lo, worst_hi = 1e9, 0
    for k1 in range(1, 21):
        for k2 in range(1, 21):
            a, b = cylinder([0, k1, k2], 2)
            r = mu(a, b) / float(b - a)
            worst_lo, worst_hi = min(worst_lo, r), max(worst_hi, r)
    deep_a, deep_b = cylinder([0, 40, 1], 2)
    deep = mu(deep_a, deep_b) / float(deep_b - deep_a)
    print(f"    mismatch mu(C)/|C| over depth-2 census: "
          f"[{worst_lo:.4f}, {worst_hi:.4f}] inside "
          f"[{lo_b:.4f}, {hi_b:.4f}]; near 0 (k1=40): {deep:.4f}")
    check("grid mismatch inside [1/(2ln2), 1/ln2]",
          lo_b - 1e-9 < worst_lo and worst_hi < hi_b + 1e-9)
    check("cells near 0 approach the top density 1/ln2", deep > 1.40)

    # (d) Rokhlin integral (Simpson quadrature)
    N = 100000
    h = 1.0 / N
    tot = 0.0
    for i in range(1, N):
        x = i * h
        w = 4 if i % 2 else 2
        tot += w * (2 * log(1 / x) / ((1 + x) * log(2)))
    # endpoint x=0 has an integrable log singularity; Simpson over
    # [h, 1] plus an exact-form patch on (0, h): int 2 ln(1/x) dx/(ln2 (1+x))
    # <= 2 h (1 - ln h)/ln 2  (crude but < 3e-4 at N = 1e5)
    rok = tot * h / 3
    target = pi ** 2 / (6 * log(2))
    print(f"    Rokhlin integral ~ {rok:.4f} vs entropy {target:.4f}")
    check("entropy = pi^2/(6 ln 2) within 2e-3", abs(rok - target) < 2e-3)

    # (e) mesh-rate fluctuation
    rates = {}
    for wname in ("phi", "lcg"):
        quots = WITNESSES[wname]
        lo, hi = cylinder(quots, 300)
        rates[wname] = log(1 / float(hi - lo)) / 300
    print(f"    mesh rate at phi {rates['phi']:.4f} (2 ln phi = "
          f"{2 * log((1 + sqrt(5)) / 2):.4f}); at lcg {rates['lcg']:.4f}; "
          f"entropy {target:.4f}; positional base-b: ln b, zero variance")
    check("phi mesh rate = 2 ln phi within 1e-3",
          abs(rates["phi"] - 2 * log((1 + sqrt(5)) / 2)) < 1e-3)
    check("mesh rate at lcg exceeds phi's floor",
          rates["lcg"] > rates["phi"] + 0.2)


if __name__ == "__main__":
    e0()
    e1()
    e2()
    e3()
    e4()
    print("\n" + ("ALL ENGINES PASS" if not FAILS
                  else f"{len(FAILS)} FAILURES: {FAILS}"))
    raise SystemExit(1 if FAILS else 0)
