r"""DOES THE CONDUCTOR RULE'S MECHANISM SURVIVE BEING COMPUTED? -- the
ray class group of the quadratic resolvent modulo the conductor, built
rather than inferred, and its 3-part split into the two lines
conjugation leaves.

THE FINDING THIS INTERROGATES. explore_cubic_regime_sorter.py F5 sorts
the complex cubic fields of relation class number 3 into their
split-triple regimes by a predicate on the conductor: degenerate exactly
when a rational prime q = 1 mod 3 divides f, or 9 divides f and 3 splits
in k = Q(sqrt(d_0)). Its F6 offers a mechanism -- R = D wants an abelian
E of degree 9 over k inside the ray class field modulo f, the cubic
field's own line is inverted by conjugation, and E needs a second line
FIXED by it -- and then reads off which conductors carry a fixed line by
a prime-by-prime argument. EVERY SENTENCE OF THAT ARGUMENT IS ABOUT A
GROUP THAT WAS NEVER COMPUTED: the predicate reads f as an integer and
infers the group from it. This file builds the group.

WHOSE VOCABULARY THE SUSPICION IS IN, asked at the freeze. F6's
argument is written in the vocabulary of LINES -- a fixed line, an
inverted line, a conductor that "carries" one. The object those words
name is the 3-part of a ray class group as a module over the two-element
group generated by conjugation, and the translation is not free. A line
is a rank-1 piece of that module; whether one EXISTS is a rank
computation; whether it can be USED is a second question about local
components that the word "carries" does not distinguish, and derivation
(6) below is where the two come apart.

TRANSPLANT FLAGS, fixed at the freeze.

 T1 FROM THE SORTER: the population, the conductor decomposition
    d_K = f^2 * d_0, the regime label and its threshold are
    explore_cubic_regime_sorter.py's, imported and re-run rather than
    re-implemented. What is new is the group engine and one column per
    field read off it.

 T2 THE REGIME LABEL IS A MEASUREMENT AND NOT A CERTIFICATE, inherited
    unchanged: a field is degenerate when its equal-class fraction is at
    or above 0.9 over at least 10 totally split primes.

 T3 THE MODULE ENGINE IS NEW HERE and is controlled from scratch: the
    order of the unit group against an independent Euler product, the
    conjugation map against the ring laws it must respect, and the
    plus/minus ranks against the total 3-rank they must sum to.

 T4 AN INTUITION IS BEING IMPORTED ACROSS A PRIME. F6 argues at q = 3
    by analogy with the primes q =/= 3, where the 3-part of a local unit
    group is the residue field's and conjugation acts through Frobenius.
    At 3 the source is the ONE-UNITS, a different group with a different
    action, and derivation (4) treats it separately for that reason.

THE HAND-DERIVATION (pre-engine, on paper).

  (1) THE CONDUCTOR IS THE RATIONAL INTEGER f, AS AN IDEAL. Let K be a
      complex cubic field with quadratic resolvent k, Galois closure N,
      and let chi be the cubic character of k cutting out N. Conductor-
      discriminant for the degree-6 field N/Q gives
      |d_K| = |d_0| * N(fr) for fr the conductor ideal of chi, so
      N(fr) = f^2 where d_K = f^2 * d_0. chi is anti-invariant under
      conjugation (chi o sigma = chi^-1), so fr is sigma-stable. Running
      the primes below shows every sigma-stable ideal of norm f^2 that
      can carry chi is (f) itself, so fr = (f) and the modulus is a
      rational integer. This is what makes a brute-forced residue ring
      the right engine.

  (2) THE PLUS PART OF THE RAY CLASS GROUP IS PURELY LOCAL. The ray
      class sequence

          1 -> (O_k/f)^* / im(O_k^*) -> Cl_f(k) -> Cl(k) -> 1

      is a sequence of modules over <sigma>, and since |<sigma>| = 2 is
      invertible on a 3-group, taking 3-parts and then plus parts is
      exact. For k imaginary quadratic, an ideal times its conjugate is
      principal, so sigma acts on Cl(k) as INVERSION and the plus part
      of Cl(k)_3 is trivial. Hence

          Cl_f(k)_3^+  =  ((O_k/f)^*)_3^+,

      and the global class group does not enter the plus side at all.
      The image of the global units is trivial at 3 except at d_0 = -3,
      where it is generated by a cube root of unity -- which conjugation
      INVERTS, so it lies in the minus part and the identity above is
      unaffected there too.

  (3) WHICH PRIMES CAN DIVIDE f AT ALL. chi is anti-invariant, so at
      every prime Q of k dividing fr the local component chi_Q is a
      nontrivial cubic character of the local units, and where sigma
      FIXES Q it must be anti-invariant there. Reading the 3-part of the
      local units, for q =/= 3:
        - q split: two primes swapped by sigma, each with local 3-part
          the 3-part of (Z/q^a)^*, nontrivial iff q = 1 mod 3. Nothing
          forbids chi, since sigma does not fix either prime.
        - q inert: one prime, local 3-part the 3-part of q^2 - 1.
          If q = 1 mod 3 that 3-part sits in q - 1, inside the prime
          field, where Frobenius -- which IS conjugation -- acts
          trivially: the whole local 3-part is FIXED, so an
          anti-invariant chi_Q must be trivial and q cannot divide f.
          If q = 2 mod 3 the 3-part sits in q + 1, where Frobenius
          inverts, and chi_Q may be nontrivial.
        - q ramified: one prime with residue field F_q, whose units are
          fixed pointwise by sigma, and higher unit quotients of order a
          power of q. So the local 3-part is fixed and q = 1 mod 3
          cannot divide f; q = 2 mod 3 has no local 3-part to use.
      Hence: **q = 1 mod 3 divides f only when q SPLITS in k, and
      q = 2 mod 3 only when q is INERT.**

  (4) AND AT q = 3, WHERE THE SOURCE IS THE ONE-UNITS. Write a = v_3(f),
      so N(fr_3) = 3^(2a).
        - 3 split: fr_3 = P^a Pbar^a, local 3-part at each prime the
          3-part of (Z/3^a)^*, of order 3^(a-1). Nontrivial iff a >= 2.
        - 3 inert: fr_3 = (3)^a, local 3-part U_1/U_a. At a = 1 it is
          trivial. At a = 2 it is U_1/U_2 = O_k/3 = F_9 as an additive
          group with sigma acting as Frobenius, which is F_3-linear of
          order 2 and fixes exactly the prime field: rank 2, ONE FIXED
          LINE AND ONE INVERTED. So an inert 3 with 9 | f DOES leave a
          fixed line, against F6's reading.
        - 3 ramified: (3) = Q^2 and N(Q) = 3, so fr_3 = Q^(2a). At
          a = 1 the local 3-part is U_1/U_2 = Q/Q^2, one-dimensional
          and INVERTED (a uniformizer may be taken with sigma(pi) =
          -pi). At a = 2 the 3-part has order 27 and its fixed part is
          the image of the units of Q_3, a single line.
      Sizes also pin v_3(f): v_3(d_K) = 2a + v_3(d_0) is at most 5 for
      a cubic field, so a <= 2, and a = 1 forces 3 | d_0 since 2 alone
      is not an admissible 3-valuation of a cubic discriminant.

  (5) SO A FIXED LINE EXISTS MORE OFTEN THAN THE PREDICATE FIRES, and
      the gap is exactly the inert and ramified 3. Something beyond
      EXISTENCE is doing the sorting.

  (6) WHAT A SECOND LINE MUST ALSO BE IS UNRAMIFIED OVER N. E = H_i N
      is unramified over N because H_i is unramified over K_i. Writing
      X = <chi, psi> for the character group of Gal(E/k), the inertia
      subgroup at a prime Q is dual to X restricted to the local units
      U_Q, and E/N is unramified at Q exactly when that restriction is
      no bigger than <chi_Q> -- that is, when

          psi|U_Q  lies in  <chi_Q>   for every Q dividing fr.

      Now let psi be a FIXED (plus) character. Where sigma fixes Q,
      chi_Q is anti-invariant and <chi_Q> contains no nontrivial
      invariant character, so the condition forces psi_Q = 1: psi must
      be UNRAMIFIED at Q. But by (2) every nontrivial plus character is
      ramified somewhere over f. Where sigma SWAPS two primes P, Pbar,
      "plus" is a condition relating psi_P to psi_Pbar and imposes
      nothing on psi_P alone; since the local 3-part there is cyclic and
      chi_P generates it, psi_P lies in <chi_P> automatically. Hence

          A USABLE FIXED LINE EXISTS  <=>  SOME PRIME OF k DIVIDING fr
          IS SPLIT OVER Q AND HAS NONTRIVIAL LOCAL 3-PART.

  (7) AND THAT IS THE PREDICATE, RE-DERIVED. By (3) and (4) the split
      primes dividing fr with nontrivial local 3-part are exactly the
      q = 1 mod 3 dividing f, together with q = 3 when 3 splits and
      9 | f. So derivation (6) reproduces F5's predicate exactly, by an
      argument that agrees with F6 at q =/= 3 and replaces its reason at
      q = 3: the inert 3 is excluded not because it leaves no fixed line
      but because the fixed line it leaves is ramified in a direction an
      anti-invariant chi cannot absorb.

  (8) WHICH DECIDES THE CORNER NO FIELD REACHED. At 9 | f with 3
      RAMIFIED in k, the prime above 3 is fixed by sigma, so by (6) its
      fixed line is unusable and no other prime supplies one unless some
      q = 1 mod 3 divides f. So such a field is UNIFORM. The prediction
      is derived, not measured, and it inherits the one step below.

  (9) WHAT IS STILL NOT DERIVED HERE -- SETTLED SINCE, and the scope
      that survives is this file's: explore_ray_class_inverted.py
      derivation (5) proves the step, from Gal(E/N) being Gal(H_1/K_1)
      and the conjugating element lying inside that abelian group. What
      stands below is what THIS file could reach, and it is the same
      step F6 names: that
      the second line must be FIXED rather than inverted. Nothing above
      forbids an E with both lines inverted; derivation (6) only prices
      the fixed ones. That step is necessary for (7) and (8) to be more
      than a coincidence, and this file MEASURES its consequence rather
      than proving it. Sufficiency -- that a usable fixed line forces
      R = D -- is untouched here and needs the Hilbert class field of K
      built rather than bounded.

THE SLATE -- PREDICTIONS, FROZEN BEFORE THE ENGINE.

  P1. THE ADMISSIBLE-PRIME LAW HOLDS ON THE POPULATION (derivation (3),
      (4)). For every field: every prime q = 1 mod 3 dividing f splits
      in k; every q = 2 mod 3 dividing f is inert in k; v_3(f) <= 2; and
      v_3(f) = 1 only where 3 divides d_0.

  P2. THE FIXED LINE EXISTS WHERE F6 SAYS IT DOES NOT (derivation (4)).
      At least one field of the population has an inert 3 with 9 | f,
      and at every such field the plus rank of the 3-part of
      (O_k/f)^* is at least 1. (A single such field with plus rank 0
      kills derivation (4) and restores F6's reading.)

  P3. EXISTENCE DOES NOT SORT (derivation (5)). The predicate "the plus
      rank is positive" disagrees with the regime on at least one field.

  P4. USABILITY DOES SORT (derivation (6)). The predicate "some prime of
      k dividing (f) is split over Q with nontrivial local 3-part"
      agrees with the regime on every field of the population.

  P5. THE CORNER IS UNIFORM WHERE IT IS OCCUPIED (derivation (8)). No
      field with 9 | f and 3 ramified in k, and no prime q = 1 mod 3
      dividing f, is degenerate.

THE KILLS, AS OBSERVABLES -- what the rig PRINTS, read after the
controls and never before.

  K1 kills P1: the printed count of admissible-prime violations. Any
     value above 0 kills it, and with it derivation (3) or (4).

  K2 kills P2: the printed count of fields with an inert 3 and 9 | f,
     and among them the count at plus rank 0. A zero first count makes
     P2 VACUOUS and is reported as such rather than as a pass; a nonzero
     second count kills it.

  K3 kills P3: the printed count of disagreements between "plus rank
     positive" and the regime. Zero kills P3 -- existence would then
     sort after all and derivation (5) would be wrong.

  K4 kills P4: the printed count of disagreements between the usability
     predicate and the regime. Any value above 0 kills it.

  K5 kills P5: the printed count of degenerate fields in the corner.
     Any value above 0 kills it. A zero occupancy makes it vacuous and
     is reported as such.

THE CONTROLS, run before any of the above is read.

  C1. THE MODULE ENGINE, from scratch (T3). Over a sample of
      discriminants and moduli: the brute-forced order of (O_k/m)^*
      against the Euler product m^2 * prod (1 - 1/N(Q)) computed from
      the splitting types alone; conjugation multiplicative and an
      involution on the ring; the 3-Sylow's order a power of 3 dividing
      the group order; the plus and minus ranks summing to the total
      3-rank; and the CRT factorization -- the ranks over m against the
      sum of the ranks over its prime powers.

  C2. THE HAND-COMPUTED PINS (derivation (4)), which are the two fields
      that produced the second clause. At d_0 = -19, f = 18, where 3 is
      inert: plus rank 1 and minus rank 2 over the whole modulus, and
      NO usable fixed line. At d_0 = -11, f = 18, where 3 splits: plus
      rank 1 and a usable fixed line. These are computed here and
      checked against values derived by hand above, so a broken engine
      cannot agree with them by accident.

  C3. THE POPULATION REPRODUCED. The field count and the two regime
      counts recomputed here must be 193 fields, 70 degenerate and 123
      uniform -- explore_cubic_regime_sorter.py F5's numbers -- or the
      population is not the same population.

THE FINDINGS.

  F1. THE ENGINE IS CONTROLLED AND ONE PIN WAS WRONG (S1, S2). Over 81
      discriminant-modulus pairs the brute-forced unit group agrees with
      the Euler product everywhere, conjugation is multiplicative and
      involutive, the 3-Sylow order divides the group order, the plus
      and minus ranks sum to the total 3-rank, and the ranks over a
      composite modulus equal the sum over its prime powers. THE PIN AT
      d_0 = -11 FIRED, and on the hand value rather than the engine: the
      frozen minus rank was 1, the engine read 2, and the re-derivation
      gives 2 -- the hand pass counted the split 3's inverted line and
      dropped the one an inert 2 contributes. That pin therefore
      controls only the plus rank and the usability at that field; the
      pin at d_0 = -19 stands whole, at plus rank 1 and minus rank 2.

  F2. WHICH RATIONAL PRIMES CAN DIVIDE A CONDUCTOR IS FORCED, AND THE
      POPULATION OBEYS IT EXACTLY (rule, derived at (3)-(4) and verified
      on the 193 conductors; S4). A prime q = 1 mod 3 divides f only
      when it SPLITS in k; a prime q = 2 mod 3 only when it is INERT;
      v_3(f) is at most 2, and equals 1 only where 3 divides d_0. The
      population has 52 split occurrences of the first kind and 96
      inert occurrences of the second with no exception either way, and
      18, 2 and 30 occurrences of q = 3 split, inert and ramified. So
      the conductor's factorization is not free data: reading f mod 3
      and reading how its primes sit in k are the same reading, which is
      why a predicate written in either vocabulary can look complete.

  F3. THE FIXED LINE EXISTS WHERE THE PREVIOUS MECHANISM SAID IT DOES
      NOT (observation, 2 fields; S5). Both fields with an inert 3 and
      9 | f -- the pair at d_K = -6156 over d_0 = -19 -- have plus rank
      1 and minus rank 2, not plus rank 0. The one-units at an inert 3
      reduced modulo 9 are F_9 as an additive group with conjugation
      acting as Frobenius, which fixes the prime field: the fixed line
      is there. explore_cubic_regime_sorter.py F6's reason for
      excluding that case -- that a fixed line needs two primes to swap
      -- is the q =/= 3 argument transplanted onto the one-units, and it
      is wrong.

  F4. EXISTENCE DOES NOT SORT AND USABILITY SORTS EXACTLY (pattern,
      0 of 193; S5). "A fixed line exists" disagrees with the regime at
      those 2 fields. "A fixed line is usable" -- derivation (6): some
      prime of k dividing (f) is split over Q with nontrivial local
      3-part -- disagrees NOWHERE. The joint table has three cells and
      no others: 121 uniform fields with no fixed line, 2 uniform fields
      with a fixed line that cannot be used, and 70 degenerate fields
      with a usable one. So the sorter's real content is not that the
      conductor carries a fixed line but that it carries one an
      anti-invariant character can absorb, and the two conditions part
      exactly at the inert 3.

  F5. WHICH RESTATES THE SORTER WITHOUT A CONGRUENCE LIST (pattern, the
      same 193 fields F4 reads). Because of
      F2 the usable-line condition and the mod-3 predicate are the same
      condition, so the law can be said intrinsically: **a complex cubic
      field of relation class number 3 is degenerate exactly when some
      prime of its resolvent dividing the conductor is SPLIT over Q and
      carries a nontrivial local 3-part.** The two clauses of the
      congruence form are the two ways that happens -- q = 1 mod 3
      (which by F2 is always split), and q = 3 with 9 | f when 3 splits
      -- and they stop being two clauses.

  F6. THE SECOND CLAUSE NO LONGER RESTS ON TWO FIELDS. It was fitted on
      the pair at d_K = -6156 and had exactly one out-of-sample band. It
      now follows from derivation (6) at the same step that gives the
      first clause, so the asymmetry the sorter recorded between its two
      clauses is gone. What both clauses rest on is derivation (9), the
      one step neither this file nor its predecessor derives: that E's
      second line must be FIXED rather than inverted. SETTLED SINCE:
      explore_ray_class_inverted.py proves it, and measures that it was
      carrying the whole mechanism -- a conjugation-stable E unramified
      over N exists at every field of this population, so both clauses
      now rest on nothing granted.

  F7. AND THE UNTOUCHED CORNER IS DECIDED BY ARGUMENT BECAUSE A CENSUS
      CANNOT REACH IT (S6). Derivation (8) predicts UNIFORM at 9 | f
      with 3 ramified in k, the prime above 3 being fixed by conjugation
      and its fixed line therefore unusable. The measurement cannot
      contradict or confirm it here. 9 | f with 3 | d_0 forces
      v_3(d_K) = 5 and forbids 27 | f, and every other prime of a cubic
      conductor is tame and totally ramified and so occurs to the first
      power, so the corner's discriminants are bounded by the 81*m^2*d_0
      over m squarefree and coprime to 3 and d_0 < 0 fundamental and
      divisible by 3. EIGHTEEN of them lie below 13000, SEVENTEEN of
      those CLEAN -- carrying no q = 1 mod 3 and so undecided by the
      first clause -- and NOT ONE carries a field of relation class
      number 3 with a readable fraction. The eighteenth is d_K = -11907
      at f = 63, which is the population's one field with 9 | f and 3
      ramified, and the 7 in its conductor decides it.
      SO THE CENSUS IS PRICED AND IT IS THE WRONG INSTRUMENT: filling
      the corner needs |d_0| in the hundreds and hence |d_K| in the tens
      of thousands, where the enumeration that reads a regime costs
      hours, and the corner is thin at every scale because it demands a
      cubic discriminant at the maximal 3-valuation. The prediction
      stands as a prediction.

RUN RECORD. `python prime/code/memwatch.py python
prime/code/explore_ray_class_lines.py`. One process, CPython, no BLAS.
14 checks, 363.0 s wall, peak working set 93.4 MB against memwatch's
512 MB ceiling. Almost all of it is the population: 2007 complex fields
enumerated to |d_K| <= 13000 in one pass, 193 at relation class number 3
with a readable fraction and 3 unresolved and skipped, 362.9 s. The
module engine's own controls run in under 0.1 s and the 193 ray class
computations in 0.1 s, which is the point -- the instrument is cheap and
what it needed was a population somebody had already paid for.
"""

import os

os.environ.setdefault("OPENBLAS_NUM_THREADS", "1")

import sys
import time
from math import gcd

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import explore_cubic_regime_sorter as ECRS

CHECKS = 0

CAP = 13000                      # the three bands of F5, read in one pass
N_FIELDS, N_DEG, N_UNI = 193, 70, 123      # C3


def ok(cond, msg):
    global CHECKS
    CHECKS += 1
    assert cond, msg


def section(t):
    print("\n" + "=" * 68)
    print(t)
    print("=" * 68)


# ------------------------------------------------ the ring O_k mod m
class Res(object):
    """Arithmetic in O_k / m for k = Q(sqrt(d_0)) imaginary quadratic,
    elements written a + b*w with w the standard generator: w =
    (1 + sqrt(d_0))/2 when d_0 = 1 mod 4, else w = sqrt(d_0/4). Both
    the product and the conjugation are read off w's minimal
    polynomial, so nothing here assumes which case it is beyond that."""

    def __init__(self, d0, m):
        self.d0, self.m = d0, m
        if d0 % 4 == 1:
            self.t, self.n = 1, (d0 - 1) // 4      # w^2 = t*w + n
        else:
            self.t, self.n = 0, d0 // 4

    def mul(self, x, y):
        (a, b), (c, d) = x, y
        m = self.m
        return ((a * c + b * d * self.n) % m,
                (a * d + b * c + b * d * self.t) % m)

    def conj(self, x):
        """sigma(a + b*w) = a + b*(t - w), since w + sigma(w) = t."""
        a, b = x
        return ((a + b * self.t) % self.m, (-b) % self.m)

    def norm(self, x):
        a, b = x
        return a * a + a * b * self.t - b * b * self.n

    def one(self):
        return (1 % self.m, 0)

    def units(self):
        out = []
        for a in range(self.m):
            for b in range(self.m):
                if gcd(self.norm((a, b)) % self.m, self.m) == 1:
                    out.append((a, b))
        return out

    def pow(self, x, e):
        r, base = self.one(), x
        while e:
            if e & 1:
                r = self.mul(r, base)
            base = self.mul(base, base)
            e >>= 1
        return r

    def inv(self, x, order):
        return self.pow(x, order - 1)


def splitting(d0, q):
    """'ram', 'split' or 'inert' for the rational prime q in k."""
    if d0 % q == 0:
        return "ram"
    if q == 2:
        return "split" if d0 % 8 == 1 else "inert"
    e = pow(d0 % q, (q - 1) // 2, q)
    return "split" if e == 1 else "inert"


def euler_order(d0, m):
    """|(O_k/m)^*| from the splitting types alone: m^2 * prod over the
    primes Q above the primes dividing m of (1 - 1/N(Q))."""
    n, tot = m, m * m
    d = 2
    facs = []
    while d * d <= n:
        if n % d == 0:
            while n % d == 0:
                n //= d
            facs.append(d)
        d += 1
    if n > 1:
        facs.append(n)
    num, den = tot, 1
    for q in facs:
        s = splitting(d0, q)
        if s == "split":
            num *= (q - 1) * (q - 1)
            den *= q * q
        elif s == "inert":
            num *= (q * q - 1)
            den *= q * q
        else:
            num *= (q - 1)
            den *= q
    assert num % den == 0
    return num // den, facs


def three_part(R, us):
    """(sylow, order) -- the 3-Sylow of the unit group given as a list
    of elements, as a list."""
    n = len(us)
    t, s3 = n, 1
    while t % 3 == 0:
        t //= 3
        s3 *= 3
    if s3 == 1:
        return [R.one()], 1
    syl = set()
    for x in us:
        syl.add(R.pow(x, t))
    return sorted(syl), s3


def rank3(R, elems, order):
    """The F_3-rank of a 3-group given as a list of its elements."""
    if order == 1:
        return 0
    e = R.one()
    k = sum(1 for x in elems if R.pow(x, 3) == e)
    r = 0
    while 3 ** r < k:
        r += 1
    assert 3 ** r == k, "3-torsion of size %d is not a power of 3" % k
    return r


def pm_parts(R, syl, order):
    """(plus, minus) as element lists, using the idempotents of <sigma>
    on a 3-group: x -> (x*sigma x)^u and x -> (x*sigma(x)^-1)^u with
    2u = 1 mod order."""
    if order == 1:
        return [R.one()], [R.one()]
    u = (order + 1) // 2          # 2u = order + 1 = 1 mod order, order odd
    plus, minus = set(), set()
    for x in syl:
        sx = R.conj(x)
        isx = R.pow(sx, order - 1)
        plus.add(R.pow(R.mul(x, sx), u))
        minus.add(R.pow(R.mul(x, isx), u))
    return sorted(plus), sorted(minus)


def module(d0, m):
    """(order, sylow_order, rank, plus_rank, minus_rank) of the 3-part
    of (O_k/m)^* as a module under conjugation."""
    R = Res(d0, m)
    us = R.units()
    syl, s3 = three_part(R, us)
    r = rank3(R, syl, s3)
    plus, minus = pm_parts(R, syl, s3)
    rp = rank3(R, plus, len(plus))
    rm = rank3(R, minus, len(minus))
    return len(us), s3, r, rp, rm


def prime_powers(f):
    n, out = f, []
    d = 2
    while d * d <= n:
        e = 0
        while n % d == 0:
            n //= d
            e += 1
        if e:
            out.append((d, e))
        d += 1
    if n > 1:
        out.append((n, 1))
    return out


def usable_fixed_line(d0, f):
    """Derivation (6): a fixed line that E can use exists exactly when
    some prime of k dividing (f) is SPLIT over Q and carries a
    nontrivial local 3-part."""
    for (q, e) in prime_powers(f):
        if splitting(d0, q) != "split":
            continue
        if module(d0, q ** e)[1] > 1:
            return True
    return False


# --------------------------------------------------------- the sections
def s1_engine():
    section("S1  C1 THE MODULE ENGINE -- controlled from scratch")
    d0s = [d for d in range(-200, 0)
           if d % 4 in (0, 1) and ECRS.fundamental_part(d)[1] == 1]
    bad_ord = bad_conj = bad_syl = bad_rank = bad_crt = 0
    t0 = time.time()
    n_case = 0
    for d0 in d0s[::7]:
        for m in (2, 3, 4, 5, 6, 7, 9, 14, 18):
            R = Res(d0, m)
            us = R.units()
            pred, _ = euler_order(d0, m)
            if len(us) != pred:
                bad_ord += 1
            e = R.one()
            for x in us[:8]:
                for y in us[:8]:
                    if R.conj(R.mul(x, y)) != R.mul(R.conj(x), R.conj(y)):
                        bad_conj += 1
                if R.conj(R.conj(x)) != x:
                    bad_conj += 1
                if R.mul(x, R.inv(x, len(us))) != e:
                    bad_conj += 1
            syl, s3 = three_part(R, us)
            if len(syl) != s3 or len(us) % s3 or (s3 > 1 and s3 % 3):
                bad_syl += 1
            r = rank3(R, syl, s3)
            plus, minus = pm_parts(R, syl, s3)
            if rank3(R, plus, len(plus)) + rank3(R, minus, len(minus)) != r:
                bad_rank += 1
            n_case += 1
        # CRT: the ranks over a composite modulus against the parts
        for m in (14, 18, 36, 45):
            tot = module(d0, m)
            acc = [0, 0, 0]
            for (q, ee) in prime_powers(m):
                _, _, r, rp, rm = module(d0, q ** ee)
                acc[0] += r
                acc[1] += rp
                acc[2] += rm
            if [tot[2], tot[3], tot[4]] != acc:
                bad_crt += 1
    print("  %d discriminants x moduli, %.1f s"
          % (n_case, time.time() - t0))
    print("  unit-group order against the Euler product: %d bad" % bad_ord)
    print("  conjugation multiplicative, involutive, inverses: %d bad"
          % bad_conj)
    print("  3-Sylow order a power of 3 dividing the order: %d bad" % bad_syl)
    print("  plus rank + minus rank = total 3-rank: %d bad" % bad_rank)
    print("  ranks over a composite modulus against its prime powers: "
          "%d bad" % bad_crt)
    ok(bad_ord == 0, "%d unit-group orders wrong" % bad_ord)
    ok(bad_conj == 0, "%d conjugation failures" % bad_conj)
    ok(bad_syl == 0, "%d bad 3-Sylow orders" % bad_syl)
    ok(bad_rank == 0, "%d rank decompositions wrong" % bad_rank)
    ok(bad_crt == 0, "%d CRT rank mismatches" % bad_crt)


def s2_pins():
    section("S2  C2 THE HAND-COMPUTED PINS -- the two fields that "
            "produced the second clause")
    print("  THE MINUS RANK AT d_0 = -11 IS A CORRECTED HAND VALUE and "
          "the correction is recorded rather than absorbed: the frozen "
          "pin read 1, the engine read 2, and the re-derivation gives 2 "
          "-- the hand pass counted the split 3's inverted line and "
          "dropped the one the inert 2 contributes. So at that field the "
          "minus rank is an agreement reached after the fact and only "
          "the plus rank and the usability are independent pins.")
    for (d0, f, want_rp, want_rm, want_use) in ((-19, 18, 1, 2, False),
                                                (-11, 18, 1, 2, True)):
        n, s3, r, rp, rm = module(d0, f)
        use = usable_fixed_line(d0, f)
        print("  d_0 = %-6d f = %-4d 3 is %-6s |U| = %-6d 3-part %-5d "
              "rank %d = %d+ %d-  usable fixed line: %s"
              % (d0, f, splitting(d0, 3), n, s3, r, rp, rm,
                 "yes" if use else "no"))
        ok(rp == want_rp, "d_0 = %d, f = %d: plus rank %d, hand value %d"
           % (d0, f, rp, want_rp))
        ok(rm == want_rm, "d_0 = %d, f = %d: minus rank %d, hand value %d"
           % (d0, f, rm, want_rm))
        ok(use == want_use, "d_0 = %d, f = %d: usability %s, hand value %s"
           % (d0, f, use, want_use))


def s3_population():
    section("S3  C3 THE POPULATION, RE-READ IN ONE PASS TO |d_K| <= %d"
            % CAP)
    t0 = time.time()
    rows, n_band, n_un = ECRS.band_rows(0, CAP)
    nd = sum(1 for t in rows if t[6] == "D")
    nm = sum(1 for t in rows if t[6] == "M")
    print("  %d complex fields enumerated, %d at relation class number 3 "
          "with a readable fraction, %d unresolved and skipped, %.1f s"
          % (n_band, len(rows), n_un, time.time() - t0))
    print("  [C3] %d degenerate, %d uniform (the sorter reports %d and %d "
          "over %d fields)" % (nd, nm, N_DEG, N_UNI, N_FIELDS))
    ok(len(rows) == N_FIELDS, "%d fields, expected %d"
       % (len(rows), N_FIELDS))
    ok(nd == N_DEG, "%d degenerate, expected %d" % (nd, N_DEG))
    ok(nm == N_UNI, "%d uniform, expected %d" % (nm, N_UNI))
    return rows


def s4_admissible(rows):
    section("S4  K1 THE ADMISSIBLE-PRIME LAW -- which rational primes "
            "can divide a conductor at all")
    bad = []
    tally = {}
    for (d, d0, f, ns, ne, frac, label) in rows:
        for (q, e) in prime_powers(f):
            s = splitting(d0, q)
            tally[(q % 3 if q != 3 else 3, s)] = tally.get(
                (q % 3 if q != 3 else 3, s), 0) + 1
            if q == 3:
                if e > 2 or (e == 1 and d0 % 3 != 0):
                    bad.append((d, d0, f, q, e, s))
            elif q % 3 == 1 and s != "split":
                bad.append((d, d0, f, q, e, s))
            elif q % 3 == 2 and s != "inert":
                bad.append((d, d0, f, q, e, s))
    print("  %-16s %-10s %s" % ("prime class", "in k", "occurrences"))
    for key in sorted(tally):
        lab = {1: "q = 1 mod 3", 2: "q = 2 mod 3", 3: "q = 3"}[key[0]]
        print("  %-16s %-10s %d" % (lab, key[1], tally[key]))
    print("  [K1] violations of derivation (3)-(4): %d" % len(bad))
    for t in bad[:8]:
        print("       d_K = %-8d d_0 = %-8d f = %-4d q = %d^%d is %s"
              % t)
    return bad


def s5_lines(rows):
    section("S5  K2 K3 K4 THE TWO PREDICATES -- a fixed line EXISTING "
            "against a fixed line being USABLE")
    out = []
    t0 = time.time()
    for (d, d0, f, ns, ne, frac, label) in rows:
        n, s3, r, rp, rm = module(d0, f)
        use = usable_fixed_line(d0, f)
        out.append((d, d0, f, splitting(d0, 3), s3, r, rp, rm, use, label))
    print("  %d fields, %.1f s" % (len(out), time.time() - t0))

    inert3 = [t for t in out if t[2] % 9 == 0 and t[3] == "inert"]
    flat = [t for t in inert3 if t[6] == 0]
    print("  [K2] fields with an inert 3 and 9 | f: %d; of those with "
          "plus rank 0: %d" % (len(inert3), len(flat)))
    for t in inert3:
        print("       d_K = %-8d d_0 = %-8d f = %-4d plus rank %d  "
              "minus rank %d  regime %s" % (t[0], t[1], t[2], t[6], t[7],
                                            t[9]))

    ex_bad = [t for t in out if (t[9] == "D") != (t[6] > 0)]
    us_bad = [t for t in out if (t[9] == "D") != t[8]]
    print("  [K3] disagreements between 'a fixed line EXISTS' and the "
          "regime: %d of %d" % (len(ex_bad), len(out)))
    for t in ex_bad[:12]:
        print("       d_K = %-8d d_0 = %-8d f = %-4d plus rank %d  "
              "regime %s" % (t[0], t[1], t[2], t[6], t[9]))
    print("  [K4] disagreements between 'a fixed line is USABLE' and the "
          "regime: %d of %d" % (len(us_bad), len(out)))
    for t in us_bad[:12]:
        print("       d_K = %-8d d_0 = %-8d f = %-4d 3 is %-6s regime %s"
              % (t[0], t[1], t[2], t[3], t[9]))

    print("  the joint table, existence against usability against regime:")
    joint = {}
    for t in out:
        joint[(t[6] > 0, t[8], t[9])] = joint.get((t[6] > 0, t[8], t[9]),
                                                  0) + 1
    print("  %-12s %-12s %-8s %s" % ("fixed line", "usable", "regime",
                                     "fields"))
    for key in sorted(joint):
        print("  %-12s %-12s %-8s %d"
              % ("yes" if key[0] else "no", "yes" if key[1] else "no",
                 key[2], joint[key]))
    return out


def s6_corner(out):
    section("S6  K5 THE CORNER -- 9 | f with 3 RAMIFIED in k, which "
            "derivation (8) decides and no measurement had reached")
    corner = [t for t in out if t[2] % 9 == 0 and t[3] == "ram"]
    clean = [t for t in corner
             if not any(q % 3 == 1 for (q, e) in prime_powers(t[2]))]
    deg = [t for t in clean if t[9] == "D"]
    print("  fields with 9 | f and 3 ramified: %d; of those with no "
          "q = 1 mod 3 in the conductor: %d" % (len(corner), len(clean)))
    for t in corner:
        print("       d_K = %-8d d_0 = %-8d f = %-4d plus rank %d  "
              "usable %-4s regime %s"
              % (t[0], t[1], t[2], t[6], "yes" if t[8] else "no", t[9]))
    print("  [K5] degenerate fields in the clean corner: %d" % len(deg))

    print("  AND WHAT THE CORNER COSTS TO REACH, read off the arithmetic "
          "rather than an enumeration: 9 | f with 3 | d_0 forces "
          "v_3(d_K) = 5 and 27 does not divide f, while every other prime "
          "of a cubic conductor is tamely and totally ramified and so "
          "occurs to the first power. So f = 9m over m squarefree and "
          "coprime to 3, and the corner's discriminants are the 81*m^2*d_0 "
          "over the fundamental d_0 < 0 divisible by 3 -- a bound on the "
          "candidates, since m's primes must also sit in k the way "
          "derivation (3) demands.")
    cand = []
    for d0 in range(-1, -CAP - 1, -1):
        if d0 % 3 or d0 % 4 not in (0, 1):
            continue
        if 81 * abs(d0) > CAP or ECRS.fundamental_part(d0)[1] != 1:
            continue
        m = 1
        while 81 * m * m * abs(d0) <= CAP:
            pp = prime_powers(m)
            if m % 3 and all(e == 1 for (q, e) in pp):
                cand.append((81 * m * m * d0, d0, 9 * m,
                             all(q % 3 != 1 for (q, e) in pp)))
            m += 1
    cand.sort(key=lambda t: abs(t[0]))
    seen = set(t[0] for t in out)
    cl = [t for t in cand if t[3]]
    print("  corner discriminants below the cap: %d, of which %d are "
          "CLEAN (no q = 1 mod 3 in the conductor, so undecided by the "
          "first clause) and %d carry a readable field of relation class "
          "number 3" % (len(cand), len(cl),
                        sum(1 for t in cl if t[0] in seen)))
    print("  " + " ".join(str(t[0]) for t in cl))
    print("  and the corner discriminants the first clause decides "
          "anyway: %s"
          % " ".join(str(t[0]) for t in cand if not t[3]))
    return corner, clean


def main():
    t0 = time.time()
    s1_engine()
    s2_pins()
    rows = s3_population()
    s4_admissible(rows)
    out = s5_lines(rows)
    s6_corner(out)
    section("SUMMARY")
    print("  %d checks passed here, %.1f s wall" % (CHECKS, time.time() - t0))


if __name__ == "__main__":
    main()
