"""DOES THE COVERAGE FLOOR SURVIVE AN INFINITE UNIT GROUP? -- the least
principal rank-1 characteristic over a REAL quadratic field.

THE QUESTION. explore_principal_place.py measured L_1(K), the least
PRINCIPAL rank-1 characteristic, over IMAGINARY quadratic fields and
found a floor, L_1 >= |D|/4, tight at D = -19995. That floor is scoped
to UNIT RANK and not to quadraticity: a principal degree-1 place
is generated by an element of norm p, its generators form ONE ORBIT
under the units, and an imaginary quadratic field's unit group is
FINITE -- so the norm form is definite and its values at non-rational
elements are bounded below by |D|/4. At positive unit rank the
generator moves by units through an INDEFINITE form, which has no such
bound. The doc says outright that nothing transfers to a real quadratic
field and that whether the per-place reading caps there at all is open.

That matters beyond bookkeeping. The per-place reading's whole
advantage over the tau route was measured as a COVERAGE ratio inside a
sweep bound, and the shape of that coverage -- near-full below the cap,
falling to zero above it -- was attributed to the floor. If the floor
is a unit-rank artifact, the fields the cascade actually cares about
(char-0 rings in general, not imaginary quadratic ones) sit on the
other side of it.

THE TRANSPLANT, FLAGGED. Every intuition below about a floor is
imported from D < 0, a neighbouring value of one parameter (the unit
rank), and is flagged as such. The imported intuition is exactly what
prediction 1 negates.

THE HAND-DERIVATION (pre-engine, on paper).

  (1) RANK-1 IS UNCHANGED. For a fundamental discriminant D and a prime
      p, p is unramified with a residue-degree-1 place iff the Kronecker
      symbol chi_D(p) = +1. Nothing in that statement sees the sign of
      D. So the rank-1 half of L_1 transfers verbatim and only
      PRINCIPALITY is in question.

  (2) PRINCIPALITY IS A NORM EQUATION, AND THE SIGN IS WHERE IT BITES.
      A place P above a split p has norm p, so P = (alpha) for some
      alpha in O_K iff |N(alpha)| = p. Writing the principal form as
      (1, b0, c0) with b0 = D mod 2 and c0 = (b0^2 - D)/4, and
      completing the square,

          4*(x^2 + b0*x*y + c0*y^2) = (2x + b0*y)^2 - D*y^2,

      so the test is: does u^2 - D*y^2 = 4p or = -4p have an integer
      solution with u = b0*y mod 2.

      At D < 0 this reads u^2 + |D|*y^2 = 4p, y = 0 would make p a
      square, so y != 0 and 4p >= |D|. THAT INEQUALITY IS THE ENTIRE
      FLOOR. At D > 0 the left side is indefinite: u^2 - D*y^2 = +-4p
      constrains no size at all, and y = 0 is still excluded for the
      same reason while excluding it now costs nothing. So the floor
      has no source over D > 0. This is a derivation, not a
      measurement, and predictions 1 and 3 below are what it commits
      to.

  (3) THE TEST CANNOT BE A LOOP OVER y. At D < 0 the loop is bounded by
      |D|*y^2 <= 4p and is essentially free. At D > 0 there is no such
      bound: a solution can require y as large as the fundamental unit
      makes it, and the regulator grows with D. The correct test is the
      CLASSICAL one on forms. For odd p, take b with b^2 = D mod 4p and
      b = D mod 2 (one Tonelli square root mod p, parity fixed mod 2;
      for p = 2, which is rank-1 exactly when D = 1 mod 8, b = 1 works).
      Then

          F  = (p, b, (b^2 - D)/(4p))       represents +p at (1, 0),
          F' = (-p, b, (b^2 - D)/(-4p))     represents -p at (1, 0),

      both of discriminant D. Two forms of discriminant D > 0 are
      equivalent iff their reduced forms share a CYCLE under rho, so:

          P is principal  <=>  reduced(F) or reduced(F') lies in the
                               PRINCIPAL CYCLE.

      Both are needed because the correspondence between ideal classes
      and indefinite form classes is with the NARROW class group. F
      alone tests narrow principality; the wide (= ideal) class group is
      the quotient by the kernel generated by an element of negative
      norm, and the disjunction over the two signs is exactly the test
      that quotients it out. That kernel is trivial iff the fundamental
      unit has norm -1 -- so the sign disjunction is doing real work at
      precisely the fields where N(eps) = +1, and none at the others.

      THIS CLAUSE CARRIED A FALSE RIDER AT THE FREEZE and control C2
      caught it before any result was read: the slate went on to say
      "which is iff the principal cycle has ODD length", and cycle
      length parity decides nothing here -- D = 8 (N = -1) and D = 12
      (N = +1) both have principal cycle length 2. The rider is struck
      rather than quietly rewritten, because it is what the control
      earned. What decides N(eps) is the kernel test itself: N(eps) =
      -1 iff the principal form's OPPOSITE is narrow-equivalent to it.
      Nothing in the PRINCIPALITY test above depended on the rider --
      it read the wide class number, which is why C2 and not C3 fired.

  (4) WHAT THE CLASS NUMBER MODEL SHOULD SAY, EITHER WAY. Among all
      primes, the rank-1 ones have density 1/2 and the principal ones
      among those density 1/h over the Hilbert class field, h the WIDE
      class number -- so a hit has density 1/(2h) whatever the sign of
      D, and whatever N(eps) is. The imaginary side measured its first
      hit 2.88x to 8.56x ABOVE that model, blamed on the START: there
      is nothing to hit below the floor. Remove the floor
      and the same model should stop undershooting. That is prediction
      2, and it is the sharp one -- it tests the doc's stated MECHANISM
      and not merely its inequality.

THE SLATE -- PREDICTIONS, FROZEN BEFORE THE ENGINE.

  P1. NO FLOOR. There are fundamental discriminants D > 0 of every size
      in the sweep with L_1 small -- concretely, fields with |D| far
      above 4*L_1, which is the imaginary side's forbidden region.

  P2. THE MODEL STOPS UNDERSHOOTING. Measured mean L_1 against the
      first-hit model's mean at density 1/(2h), stratified by h and
      compared on the same censoring, lands within 2x at every class
      number in range -- against 2.88x to 8.56x on the imaginary side.

  P3. COVERAGE DOES NOT DECAY WITH |D|. The fraction of fields with
      L_1 <= 1000 stays high across the |D| bands cut at 1000, 2500,
      5000, 10000, 20000, rather than running 3.0% -> 100% ABOVE the
      cap as it does at D < 0.

  P4. THE SIGN DISJUNCTION MOVES NO DENSITY. By (4) the hit density is
      1/(2h) whichever sign the fundamental unit's norm takes, so the
      N(eps) = -1 and N(eps) = +1 populations should show no systematic
      difference in L_1 once stratified by h. A difference here is a
      bug or a small sample before it is a phenomenon.

THE KILLS, AS OBSERVABLES -- what the rig PRINTS, read after the
control and never before.

  K1 kills P1: the printed MAX of |D| over swept fields with
     L_1 <= 100. If that max sits at or below about 400 -- the shape
     4*L_1 the imaginary floor would impose -- the transplant SURVIVED
     and a floor of the same shape exists over D > 0.

  K2 kills P2: the printed per-h ratio of measured mean L_1 to model
     mean. Any ratio above 2.88 -- the imaginary side's SMALLEST
     undershoot -- kills it at that h.

  K3 kills P3: the printed per-band fraction with L_1 <= 1000. A
     monotone fall toward zero across the five bands kills it.

  K4 kills P4: the printed per-h means split by the sign of N(eps).

THE POSITIVE CONTROLS, run and read FIRST.

  C1. THE IMAGINARY ANCHOR. The same driver run on the D < 0 branch
      must reproduce explore_principal_place.py's anchor exactly:
      L_1(-19995) = 4999, and L_1 >= |D|/4 at every swept D < 0.

  C2. THE TRIVIAL-CLASS IDENTITY. Over a real field with wide class
      number 1, EVERY rank-1 place is principal, so L_1 must equal the
      least prime with chi_D(p) = +1. Any h = 1 field where the cycle
      test disagrees with that is a broken test.

  C3. THE CYCLE TEST AGAINST BRUTE FORCE. For small D where the
      fundamental unit is tiny, |N(alpha)| = p is decidable by direct
      search over a bound derived from eps, since normalizing alpha by
      units puts |alpha| in [sqrt(p), sqrt(p*eps)). The form-cycle
      verdict must agree with that search at every pair tried.

RESOURCE. Pure integer arithmetic, no numpy, no arrays held; the only
per-field state is one principal cycle. Estimated well under 512MB and
under 3 minutes.

THE FINDINGS.

  F1. THE FLOOR IS NOT NARROWED, IT IS ABSENT (rule -- refuted by an
      exhibited witness, corroborated across 6081 fields). Of the 6081
      real fundamental discriminants to 20000, 5482 have L_1 <= 100. The
      extreme witness is D = 19996 with L_1 = 3, a ratio |D|/(4*L_1) of
      1666; the largest discriminant carrying L_1 <= 100 is 19997, where
      an imaginary-shaped floor would have forbidden anything past 52. A
      universal statement of the form L_1 >= |D|/4 dies to one witness,
      and the sweep adds that no weaker floor of that shape replaces it.
      The scoping of the floor to UNIT RANK is confirmed at
      exactly the parameter value it scoped itself away from, and
      derivation (2) says why: the completion of the square that yields
      4p >= |D| at D < 0 yields u^2 - D*y^2 = +-4p at D > 0, which
      constrains no size at all. P1 SURVIVES, and K1 misses on its own
      observable by a factor of 50 -- its threshold was about 400 and
      the printed max is 19997. (385 is the miss against the floor that
      field's OWN L_1 would impose, 52, and it is a different quantity;
      the kill named the threshold, so the kill's number is 50.)

  F2. COVERAGE DOES NOT DECAY WITH |D| (pattern, 6081 fields). The
      fraction with L_1 <= 1000 runs 100.0, 100.0, 99.9, 99.9, 99.8
      percent over the bands cut at 1000, 2500, 5000, 10000, 20000 --
      against 3.0 percent rising to 100 percent ABOVE the cap on the
      imaginary side. So at the same sweep bound the per-place reading
      closes essentially every real quadratic field in range, where over
      imaginary quadratic fields it closes none with |D| > 4P. What
      limited the reading was a unit-rank bound and not a bound of the
      reading. P3 SURVIVES -- and SURVIVES is the whole verdict: EIGHT
      fields in range are uncovered at this bound (3601, 7057, 9217,
      11665, 12469, 13321, 14401, 19041), so the reading is not being
      shown to cap NOWHERE, only to stop caring about |D|.

      AND THE TWO CANDIDATE EXPLANATIONS ARE ONE (property). By
      Dirichlet's unit theorem a number field has unit rank 0 exactly
      when it is Q or imaginary quadratic -- which is exactly when the
      norm form is definite. So "unit rank" and "archimedean signature"
      are not two hypotheses here waiting for a field to separate them:
      no number field does. Whatever a higher-degree widening measures,
      it is not that.

  F3. THE UNDERSHOOT SURVIVES THE FLOOR'S REMOVAL AND GROWS WITH THE
      CLASS NUMBER (observation, 8 class numbers, 1208 fields). This is
      the finding, and it is the one the slate got wrong. The
      imaginary side's 2.88x-8.56x undershoot of the first-hit model
      was attributed to the START -- there being nothing to hit below
      the floor. With no floor at all the ratio is 1.15 at h = 1 and
      then climbs: 1.68, 2.11, 2.27, 1.89, 3.23, 3.21, 2.81 at
      h = 2..8. THE TREND'S OWN SCOPE, and the rig prints it: the table
      stops at h = 8 because the strata above it carry 7 fields between
      them (h = 9, 10, 11, 12, 16) and are dropped under a minimum of
      5. A claim that the shortfall GROWS with h is therefore read over
      h <= 8 and is untested exactly where it would be largest.
      The floor therefore explains the h = 1 end and nothing
      above it. A SECOND mechanism, graded by the class number, is doing
      most of the work -- and it was doing it on the imaginary side too,
      where the floor was available to absorb the blame. (SETTLED by
      explore_principal_share.py: it is not a second mechanism. The share
      is a function of p and climbs to within a few per cent of nominal
      by p ~ 10^4, and at the scale L_1 is read it is short by enough to
      be the same ORDER as this undershoot -- so what survives here is
      the grading, not the count of mechanisms. The grading is the NARROW
      class number's, and the genus congruences named below are refuted
      as its carrier.)

      THE SLATE'S OWN DEFECT, RECORDED. P2 named TWO thresholds for one
      claim: "within 2x at every class number" in the prediction and
      "above 2.88" in the kill. Under its own text P2 fails at h = 3, 4,
      6, 7 and 8 -- h = 2's 1.68 and h = 5's 1.89 clear 2x -- while
      under K2's looser number it fails only at h = 6 and 7. The
      verdict taken is the PREDICTION's, a kill being no place to
      discover a second and friendlier threshold after the print.

  F4. THE UNIT'S NORM GRADES L_1 AT FIXED CLASS NUMBER (observation;
      P4 KILLED). Means split by the sign of N(eps) run 5.5/6.6,
      17.1/20.1, 32.0/44.8, 55.1/64.0, 61.2/72.3, 110.2/163.4,
      158.5/202.0 for h = 1..7, N(eps) = -1 smaller at every one; the
      single exception is h = 8, carrying 4 and 10 fields. Derivation
      (4) says the hit density is 1/(2h) whichever sign the unit's norm
      takes, so this is NOT a density effect and the derivation is not
      what failed. It is F3's mechanism read through a constraint on D
      itself: N(eps) = -1 forces D to have no prime factor congruent to
      3 mod 4 (else x^2 - D*y^2 = -4 is insoluble at that factor), which
      is a strong condition on the genus structure and hence on which
      small primes can be principal at all.

  F5. THE DENSITY ITSELF IS SHORT IN RANGE, AND SHORT BY MORE AS h GROWS
      (observation, K5, the SAME 1208 fields the K2 table rests on --
      a share divided into an undershoot has to come from the fields
      that undershot). What F3 and F4 jointly name is that the model's density
      1/(2h) is ASYMPTOTIC in p while L_1 is by construction read at the
      SMALLEST primes -- so the thing to measure is not the first hit
      but the SHARE, and it does not go through L_1 at all. The
      principal share of split primes p <= 1000, against 1/h: 1.0000 at
      h = 1 (all 583 fields, which is the trivial-class identity holding
      pointwise and not merely at the least prime), then 0.4573, 0.2975,
      0.2033, 0.1626, 0.1252, 0.1060, 0.0841 at h = 2..8 -- ratios to
      nominal of 1.00, 0.91, 0.89, 0.81, 0.81, 0.75, 0.74, 0.67. The
      deficit is real, it is graded by h, and it runs in the direction
      F3 needs.

      HOW MUCH OF F3 IT BUYS, stated honestly: a share ratio of 0.75 at
      h = 6 lengthens a first hit by about 1/0.75 = 1.33x, against a
      measured undershoot of 3.23x there, and dividing the deficit out
      at every h leaves a residual that still climbs (1.15, 1.53, 1.88,
      1.84, 1.53, 2.42, 2.38, 1.88). So the in-range density
      deficit accounts for PART of F3 and not all of it. That is what
      the suspicion predicts rather than a strike against it -- the
      share above is averaged over every prime to 1000, while L_1 reads
      the very bottom of that range, where equidistribution is worst.
      Measuring the share as a function of p, rather than pooled over
      the range, is the next thing this asks, and it is unmeasured here.
      (MEASURED by explore_principal_share.py, on both signs of D and
      against the genus characters directly.)

RUN RECORD: wall 0.3 s, pure integer arithmetic, no arrays
held beyond one principal cycle per field. Controls first and all three
green -- C1 reproduced L_1(-19995) = 4999 with the floor unviolated at
1217 imaginary fields, C2 matched L_1 to the least split prime at all
80 h = 1 real fields, C3 agreed with brute-force element search at
266 of 266 pairs. BOTH STATISTICS WALK ODD CHARACTERISTICS. An earlier
pass did not: it included p = 2, which the incumbent rig excludes
because the certified ladder walks odd characteristics and p = 2 is
closed by the budget inequality instead. That pass was comparing a
quantity to a floor and a coverage curve measured on a different one,
and its headline witness was a field whose L_1 was 2 -- not a value of
the statistic at all. An earlier pass of C2 failed at 11 of 55 fields and
the fault was the RIG's, not the identity's: N(eps) was being read off
the parity of the principal cycle's length, which decides nothing --
D = 8 (N = -1) and D = 12 (N = +1) both have principal cycle length 2.
It is read now from whether the principal form's opposite lies in that
cycle. The same pass reduced forms by comparing against floor(sqrt(D))
where the reduction condition wants sqrt(D); that is decided in exact
integers now.
"""

import sys
from math import isqrt


# ---------------------------------------------------------------- primes

def primes_upto(n):
    sieve = bytearray([1]) * (n + 1)
    sieve[0:2] = b"\x00\x00"
    for i in range(2, isqrt(n) + 1):
        if sieve[i]:
            sieve[i * i:: i] = bytearray(len(sieve[i * i:: i]))
    return [i for i in range(n + 1) if sieve[i]]


def kronecker(D, p):
    """chi_D(p) for p prime. +1 split, -1 inert, 0 ramified."""
    if D % p == 0:
        return 0
    if p == 2:
        return 1 if D % 8 == 1 else -1
    return 1 if pow(D % p, (p - 1) // 2, p) == 1 else -1


def sqrt_mod_p(a, p):
    """Tonelli-Shanks. Assumes a is a QR mod p, p odd prime."""
    a %= p
    if a == 0:
        return 0
    if p % 4 == 3:
        return pow(a, (p + 1) // 4, p)
    q, s = p - 1, 0
    while q % 2 == 0:
        q //= 2
        s += 1
    z = 2
    while pow(z, (p - 1) // 2, p) != p - 1:
        z += 1
    m, c, t, r = s, pow(z, q, p), pow(a, q, p), pow(a, (q + 1) // 2, p)
    while t != 1:
        i, t2 = 0, t
        while t2 != 1:
            t2 = t2 * t2 % p
            i += 1
        b = pow(c, 1 << (m - i - 1), p)
        m, c = i, b * b % p
        t, r = t * c % p, r * b % p
    return r


# ------------------------------------------------- fundamental discriminants

def squarefree(n):
    for d in range(2, isqrt(n) + 1):
        if n % (d * d) == 0:
            return False
    return True


def fundamental_discriminants(lo, hi, sign):
    """Fundamental discriminants D with lo < sign*D <= hi."""
    out = []
    for a in range(lo + 1, hi + 1):
        D = a if sign > 0 else -a
        if D % 4 == 1 and squarefree(abs(D)):
            out.append(D)
        elif D % 4 == 0:
            m = D // 4
            if m % 4 in (2, 3) and squarefree(abs(m)):
                out.append(D)
    return out


# -------------------------------------------------- indefinite form machinery

def _normalize_b(a, b, D, rt):
    """b' = b mod 2|a|, in the window normalization requires."""
    m = 2 * abs(a)
    hi = abs(a) if abs(a) > rt else rt
    return b + ((hi - b) // m) * m


def rho(f, D, rt):
    """One step of the cycle: (a,b,c) -> (c, b', c')."""
    a, b, c = f
    b2 = _normalize_b(c, -b, D, rt)
    return (c, b2, (b2 * b2 - D) // (4 * c))


def is_reduced(f, D, rt):
    """|sqrt(D) - 2|a|| < b < sqrt(D), decided in integers -- rt is a floor,
    so comparing against it directly admits forms that are not reduced."""
    a, b, c = f
    if b <= 0 or b * b >= D:
        return False
    t = 2 * abs(a)
    lo_ok = (t - b < 0) or (D > (t - b) * (t - b))
    return lo_ok and (t + b) * (t + b) > D


def reduce_form(f, D, rt):
    """Reduce an indefinite form by iterating rho."""
    for _ in range(4 * rt + 64):
        if is_reduced(f, D, rt):
            return f
        f = rho(f, D, rt)
    raise RuntimeError("reduction did not terminate")


def cycle_of(f, D, rt):
    """The full rho-cycle through a reduced form, as a list."""
    out, g = [f], rho(f, D, rt)
    while g != f:
        out.append(g)
        g = rho(g, D, rt)
        if len(out) > 200000:
            raise RuntimeError("cycle did not close")
    return out


def principal_cycle(D, rt):
    b0 = D % 2
    f = reduce_form((1, b0, (b0 * b0 - D) // 4), D, rt)
    return cycle_of(f, D, rt)


def all_reduced_forms(D, rt):
    """Every reduced indefinite form of discriminant D."""
    out = []
    for b in range(1, rt + 1):
        if (b - D) % 2:
            continue
        n = (b * b - D) // 4          # = a*c, negative
        for a in divisors_signed(-n):
            if n % a:
                continue
            c = n // a
            if is_reduced((a, b, c), D, rt):
                out.append((a, b, c))
    return out


def divisors_signed(n):
    """All divisors of n > 0, both signs."""
    ds = []
    for d in range(1, isqrt(n) + 1):
        if n % d == 0:
            ds.append(d)
            if d != n // d:
                ds.append(n // d)
    return ds + [-d for d in ds]


def class_data(D, rt):
    """(wide class number h, narrow h+, N(eps) sign) from the cycles.

    N(eps) = -1 exactly when the kernel of Cl+ -> Cl is trivial, i.e. when
    the OPPOSITE of the principal form is narrow-equivalent to it. Cycle
    LENGTH parity does not decide this -- D = 8 (N = -1) and D = 12
    (N = +1) both have principal cycle length 2."""
    forms = set(all_reduced_forms(D, rt))
    hplus, seen = 0, set()
    b0 = D % 2
    c0 = (b0 * b0 - D) // 4
    prin = reduce_form((1, b0, c0), D, rt)
    prin_cycle = None
    for f in forms:
        if f in seen:
            continue
        cyc = cycle_of(f, D, rt)
        seen.update(cyc)
        hplus += 1
        if prin in cyc:
            prin_cycle = set(cyc)
    opp = reduce_form((-1, b0, -c0), D, rt)
    neps = -1 if opp in prin_cycle else +1
    h = hplus if neps == -1 else hplus // 2
    return h, hplus, neps


# ------------------------------------------------------- the principality test

def is_principal_real(D, p, prin_set, rt):
    """Is a degree-1 place above p principal, over D > 0?

    The p = 2 branch is correct and unexercised: L_1 walks odd
    characteristics, so no caller reaches it. Kept because the function is
    a principality test and not an L_1 helper, and struck the moment that
    stops being true."""
    if p == 2:
        b = 1
    else:
        x = sqrt_mod_p(D, p)
        b = x if (x - D) % 2 == 0 else x + p
        # b = x mod p gives b^2 = D mod p; b = D mod 2 gives b^2 = D mod 4;
        # p is odd, so the two compose. Asserted rather than branched on:
        # a fallback here would be a branch no input can reach, which is a
        # place for a bug to sit unread.
        assert (b * b - D) % (4 * p) == 0
    for sgn in (1, -1):
        a = sgn * p
        num = b * b - D
        if num % (4 * a):
            continue
        f = reduce_form((a, b, num // (4 * a)), D, rt)
        if f in prin_set:
            return True
    return False


def is_principal_imag(D, p):
    """Is a degree-1 place above p principal, over D < 0? 4p = u^2+|D|y^2."""
    b0 = D % 2
    absD = -D
    y = 1
    while absD * y * y <= 4 * p:
        rem = 4 * p - absD * y * y
        u = isqrt(rem)
        if u * u == rem and (u - b0 * y) % 2 == 0:
            return True
        y += 1
    return False


def L1(D, plist, rt=None, prin_set=None):
    """Least principal rank-1 characteristic, or None inside the bound."""
    for p in plist:
        if kronecker(D, p) != 1:
            continue
        ok = (is_principal_real(D, p, prin_set, rt) if D > 0
              else is_principal_imag(D, p))
        if ok:
            return p
    return None


# ----------------------------------------------------------------- controls

def fundamental_unit_small(D):
    """Smallest eps > 1 with N(eps) = +-1, by search. Small D only."""
    b0 = D % 2
    for y in range(1, 20000):
        for rhs in (4, -4):
            rem = D * y * y + rhs
            if rem < 0:
                continue
            u = isqrt(rem)
            if u * u == rem and u > 0 and (u - b0 * y) % 2 == 0:
                return (u + y * (D ** 0.5)) / 2.0
    return None


def brute_principal(D, p, eps):
    """Direct search for |N(alpha)| = p, bounded by the unit normalization."""
    b0 = D % 2
    bound = int((p * eps) ** 0.5 + p ** 0.5) // isqrt(D) + 2
    for y in range(0, bound + 1):
        for rhs in (4 * p, -4 * p):
            rem = D * y * y + rhs
            if rem < 0:
                continue
            u = isqrt(rem)
            if u * u == rem and (u - b0 * y) % 2 == 0 and not (u == 0 and y == 0):
                return True
    return False


# --------------------------------------------------------------- the model

def model_mean(h, plist, cap):
    """First-hit mean at density 1/(2h) over the prime sequence, conditioned
    on the hit landing at or below cap -- the same censoring the measurement
    carries."""
    q = 1.0 / (2 * h)
    num, mass, surv = 0.0, 0.0, 1.0
    for p in plist:
        if p > cap:
            break
        pr = surv * q
        num += pr * p
        mass += pr
        surv *= (1 - q)
    return (num / mass if mass > 0 else float("nan")), mass


# ------------------------------------------------------------------- driver

CAP = 1000
BANDS = [1000, 2500, 5000, 10000, 20000]


def main():
    # ODD primes throughout. L_1 is the incumbent statistic's and it walks
    # odd characteristics, the certified ladder being a walk over those;
    # p = 2 is closed separately by the budget inequality. Including it here
    # would measure a different quantity and compare it to this one.
    plist = [q for q in primes_upto(CAP) if q != 2]
    print("ODD PRIMES to %d: %d" % (CAP, len(plist)))

    # ---- C1: the imaginary anchor -------------------------------------
    print("\n=== C1  IMAGINARY ANCHOR (control) ===")
    anchor = L1(-19995, [q for q in primes_upto(6000) if q != 2])
    print("L_1(-19995) = %s   (the published anchor is 4999)" % anchor)
    viol = 0
    imag = fundamental_discriminants(0, 4000, -1)
    for D in imag:
        v = L1(D, plist)
        if v is not None and 4 * v < -D:
            viol += 1
    print("floor L_1 >= |D|/4 violated at %d of %d fields swept" % (viol, len(imag)))

    # ---- C2/C3: the real branch's own controls -------------------------
    print("\n=== C2  TRIVIAL-CLASS IDENTITY (control) ===")
    bad2 = 0
    tested2 = 0
    small = fundamental_discriminants(0, 400, +1)
    cache = {}
    for D in small:
        rt = isqrt(D)
        if rt * rt == D:
            continue
        h, hplus, neps = class_data(D, rt)
        pc = set(principal_cycle(D, rt))
        cache[D] = (rt, pc, h, neps)
        if h != 1:
            continue
        tested2 += 1
        least_split = next(p for p in plist if kronecker(D, p) == 1)
        got = L1(D, plist, rt, pc)
        if got != least_split:
            bad2 += 1
            print("  MISMATCH D=%d: L_1=%s least split=%d" % (D, got, least_split))
    print("h=1 fields tested: %d, mismatches: %d" % (tested2, bad2))

    print("\n=== C3  CYCLE TEST vs BRUTE FORCE (control) ===")
    pairs = agree = 0
    for D in small[:40]:
        rt = isqrt(D)
        if rt * rt == D or D not in cache:
            continue
        _, pc, _, _ = cache[D]
        eps = fundamental_unit_small(D)
        if eps is None or eps > 500:
            continue
        for p in plist[:20]:
            if kronecker(D, p) != 1:
                continue
            pairs += 1
            if is_principal_real(D, p, pc, rt) == brute_principal(D, p, eps):
                agree += 1
    print("pairs compared: %d, agreements: %d" % (pairs, agree))

    if anchor != 4999 or viol or bad2 or pairs != agree:
        print("\nCONTROLS FAILED -- results not read.")
        return 1

    # ---- the sweep -----------------------------------------------------
    print("\n=== THE SWEEP: L_1 over real quadratic fields ===")
    rows = []   # (D, L1 or None, h, neps)
    for D in fundamental_discriminants(0, BANDS[-1], +1):
        rt = isqrt(D)
        if rt * rt == D:
            continue
        pc = set(principal_cycle(D, rt))
        v = L1(D, plist, rt, pc)
        rows.append((D, v, None, None))
    print("fields swept: %d" % len(rows))

    # K1 -- the floor's shape
    hits = [(D, v) for D, v, _, _ in rows if v is not None and v <= 100]
    print("\n[K1] fields with L_1 <= 100: %d" % len(hits))
    if hits:
        Dmax, vmax = max(hits, key=lambda t: t[0])
        print("     max |D| among them: %d (L_1 = %d there; the imaginary "
              "floor would forbid |D| > %d)" % (Dmax, vmax, 4 * vmax))
        worst = max(hits, key=lambda t: t[0] / (4.0 * t[1]))
        print("     deepest violation of a |D|/4 floor: D=%d, L_1=%d, "
              "|D|/(4*L_1) = %.1f" % (worst[0], worst[1], worst[0] / (4.0 * worst[1])))

    # K3 -- coverage by band
    print("\n[K3] coverage by |D| band (fraction with L_1 <= %d):" % CAP)
    lo = 0
    for hi in BANDS:
        band = [r for r in rows if lo < r[0] <= hi]
        cov = sum(1 for r in band if r[1] is not None)
        print("     %6d < D <= %6d : %5d fields, %5.1f%% covered"
              % (lo, hi, len(band), 100.0 * cov / len(band) if band else 0.0))
        lo = hi

    # K2/K4 -- the model, stratified by h and by the sign of N(eps)
    print("\n[K2/K4] measured vs first-hit model at density 1/(2h):")
    strat = {}
    for D, v, _, _ in rows:
        if D > 4000:          # class data is the expensive half; sample it
            continue
        rt = isqrt(D)
        h, hplus, neps = class_data(D, rt)
        strat.setdefault(h, []).append((D, v, neps))
    print("     %-4s %6s %10s %10s %7s   %10s %10s" %
          ("h", "n", "meas mean", "model", "ratio", "mean N=-1", "mean N=+1"))
    shown, dropped, drop_h = 0, 0, []
    for h in sorted(strat):
        grp = [t for t in strat[h] if t[1] is not None and t[1] <= CAP]
        if len(grp) < 5:
            dropped += len(grp)
            if grp:
                drop_h.append(h)
            continue
        shown += len(grp)
        meas = sum(t[1] for t in grp) / len(grp)
        mm, mass = model_mean(h, plist, CAP)
        neg = [t[1] for t in grp if t[2] == -1]
        pos = [t[1] for t in grp if t[2] == +1]
        print("     %-4d %6d %10.1f %10.1f %7.2f   %10s %10s"
              % (h, len(grp), meas, mm, meas / mm,
                 "%.1f(%d)" % (sum(neg) / len(neg), len(neg)) if neg else "-",
                 "%.1f(%d)" % (sum(pos) / len(pos), len(pos)) if pos else "-"))
    print("     table rests on %d fields; %d more dropped as strata under 5 "
          "(h = %s) -- a cap that is printed rather than silent"
          % (shown, dropped, ", ".join(str(x) for x in drop_h) or "none"))

    # K5 -- the density itself, not the first hit. If the undershoot is an
    # equidistribution effect then the principal share of SPLIT primes below
    # the cap sits under 1/h, by a margin that grows with h. This reads the
    # suspicion directly and does not go through L_1 at all.
    print("\n[K5] principal share of split primes p <= %d, against 1/h:" % CAP)
    # The SAME population as the K2/K4 table: a share divided into an
    # undershoot must come from the fields that undershot.
    share = {}
    for D in fundamental_discriminants(0, 4000, +1):
        rt = isqrt(D)
        if rt * rt == D:
            continue
        h, _, _ = class_data(D, rt)
        pc = set(principal_cycle(D, rt))
        sp = [p for p in plist if kronecker(D, p) == 1]
        if len(sp) < 20:
            continue
        pr = sum(1 for p in sp if is_principal_real(D, p, pc, rt))
        share.setdefault(h, []).append(pr / len(sp))
    print("     %-4s %6s %10s %10s %8s" % ("h", "n", "share", "1/h", "ratio"))
    for h in sorted(share):
        v = share[h]
        if len(v) < 4:
            continue
        m = sum(v) / len(v)
        print("     %-4d %6d %10.4f %10.4f %8.2f" % (h, len(v), m, 1.0 / h, m * h))
    return 0


if __name__ == "__main__":
    sys.exit(main())
