"""Is the word-count part of sign's monoid an accident of counting or a
statement about the ALGEBRA? -- the quotient above the rank-<= 1 ideal.

THE QUESTION. Sign's syntactic monoid in a signed-digit system (b, D),
D = {-am..ap}, has size n^2 + n + 1 + SUM_m E_m, where n is the live-state
count and E_m counts the length-m word VALUES whose clamped affine map
keeps two or more states live (explore_sign_monoid.py M1;
explore_monoid_correction.py F1). The rank-<= 1 maps form a two-sided
IDEAL, the leading term counts it, and the correction counts the quotient
above it.

What the closing turned up is that most of that correction is not a
lattice count at all. Where the admissible blocks MERGE -- 2 b^m <= n --
the word range sits inside them outright (explore_monoid_correction.py F2,
a theorem), so the level contributes one element for EVERY VALUE a
length-m word can take, with the machine identifying nothing further:
6076 of 7524 contributing levels. A bijection with an interval of integers
is a suggestive shape and a count cannot tell whether it is more than one.
This file asks the algebra.

Three questions, and a NO to any of them is as good as a YES:
  Q1 Is the merged part FREE, or freely generated modulo obvious
     relations?
  Q2 Do Green's relations SEPARATE the merged elements from the split
     ones -- the elements the machine, rather than the word range, cuts?
  Q3 Is everything that makes the quotient interesting concentrated in
     the 1448 split levels?

HAND-ATTACK, on paper before this file was written.

Words are read most-significant-first, s <- b s + d, so a word of length m
and value t acts by v -> b^m v + t and two words compose as

    (m1, t1) . (m2, t2) = (m1 + m2, b^m2 t1 + t2).                  (*)

STEP 1: THE VALUE SEMIGROUP. Because D is contiguous and covering, a
length-m word takes every integer value in [-T-, T+] with
T- = am(b^m - 1)/(b - 1) and T+ = ap(b^m - 1)/(b - 1). Call

    W = { (m, t) : m >= 0, -T- <= t <= T+ }

with the product (*). It is closed: |b^m2 t1 + t2| is at most
ap(b^(m1+m2) - 1)/(b - 1) on the high side by a one-line telescope, and
mirrored below. So W is the free monoid on D modulo "same length, same
value" -- the numeration system's own congruence, with no machine in it.

STEP 2: THE QUOTIENT IS W TRUNCATED. Let I be the rank-<= 1 ideal and
Q = M/I the Rees quotient: the rank-> = 2 elements plus a zero. A level
contributes iff b^m <= n - 1 (explore_monoid_correction.py F7), so above
M = floor(log_b(n - 1)) every element of W is zero in Q, and Q is
NILPOTENT with an identity adjoined -- every product of M + 2 generators
vanishes. At a MERGED level F2 says the whole of W's level survives; at a
SPLIT level only part of it does.

STEP 3: SO Q1 IS ANSWERED NO ON PAPER, AND THE INTERESTING QUESTION IS
WHICH DATA Q READS. Nilpotent is the opposite of free: at (3, 7, 7) the
contributing levels are 0 and 1, so Q is 15 generators, an identity and a
zero, with EVERY product of two generators equal to zero. Freeness is not
the shape to test for; blindness is. Substitute u = t + am(b^m - 1)/(b - 1)
and (*) becomes u = b^m2 u1 + u2 with the am terms telescoping away
exactly, so in SHIFTED coordinates the product law knows only b. W itself
becomes { (m, u) : 0 <= u <= s(b^m - 1)/(b - 1) }, s = am + ap: the value
semigroup is blind to the SPLIT of the digit set and sees only the radix
and the total width.

STEP 4: WHERE THE SPLIT CAN RE-ENTER. At a split level the surviving t are
n - 1 blocks of n - q spaced q = b^m from t_lo = alpha - q(beta - 1),
alpha = 1 - R+, beta = R- - 1. Shifting as above and writing
eps- = R- - am/(b-1), eps+ = R+ - ap/(b-1) for the two ceiling defects,

    u_lo = 1 - s/(b - 1) - eps+ - q eps- + 2q,

and n = s/(b - 1) + eps- + eps+ - 1. So a split level reads eps- and eps+
SEPARATELY -- through u_lo, which weights them differently -- while a
merged level reads neither. At b = 2 both defects are identically 0, so
the split levels are blind there too and the whole quotient is a function
of (b, s, M).

PREDICTIONS, fixed here and weighed only after the run.
  N1 Q IS NILPOTENT-PLUS-IDENTITY at every cell swept: some power of the
     augmentation ideal is zero, and the nilpotency degree is
     floor(log_b(n - 1)) + 2.
  N2 HENCE J-TRIVIAL, and so R-, L-, H- and D-trivial: length adds under
     (*) and only the identity has length 0, so mutual divisibility forces
     equality. Q2 IS ANSWERED NO, and not by a measurement -- Green's
     relations separate nothing because there is nothing for them to
     separate. Every J-class of Q is a singleton.
  N3 Q1 IS NO, GROSSLY. The merged part is generated by the s + 1 level-1
     elements and its level-2 set has s(b + 1) + 1 elements where a free
     semigroup would have (s + 1)^2 -- 57 against 225 at (3, 7, 7) if
     level 2 contributed at all, and at that cell it does not contribute
     because it is zero.
  N4 THE ALL-MERGED QUOTIENT IS BLIND TO THE SPLIT. (3, 7, 7) and
     (3, 6, 8) both have every level merged, both contribute levels 0 and
     1, both have s = 14, and their quotients are isomorphic at 16
     elements -- while their minimal machines differ, 7 live states
     against 6, and their full monoids differ, 73 against 59. Two systems
     with different automata carry the same algebra above the ideal.
  N5 AND THE NAMED PAIR IS SETTLED BY SIZE AND NOTHING SUBTLER.
     (3, 7, 7) and (3, 8, 8) share the machine's live set {-3..3}, the
     state count 7 and the leading 57, and their quotients have 16 and 18
     elements. They are not isomorphic, and the reason is that s differs,
     14 against 16.
  N6 SPLIT LEVELS BREAK THE BLINDNESS, WHICH IS Q3's ANSWER AS A YES.
     (3, 13, 13) and (3, 12, 14) share s = 26, both contribute levels
     0..2 with level 2 split, and their quotients have 76 and 61 elements
     -- so at the same (b, s) the split levels read what the merged ones
     cannot. At b = 2 they do not: (2, 5, 5) and (2, 4, 6) share s = 10
     and a split level at m = 3, and their quotients agree at 51 and are
     isomorphic, both defects being 0.

KILLS, named as things this file PRINTS, not as what they would mean.
  K1 Any cell whose quotient prints a J-class of size above 1 kills N2.
  K2 Any cell whose augmentation ideal fails to reach zero, or reaches it
     at a degree other than floor(log_b(n - 1)) + 2, kills N1.
  K3 (3, 7, 7) and (3, 6, 8) printing DIFFERENT shifted element sets kills
     N4.
  K4 (3, 7, 7) and (3, 8, 8), or (3, 13, 13) and (3, 12, 14), printing the
     SAME shifted element set kills N5 or N6.
  K5 A printed quotient size at any cell differing from
     explore_monoid_correction.correction() + 1 kills the identification
     of the quotient with the correction's own count.

CONTROLS, run and read BEFORE any verdict is weighed.
  C1 THE ISOMORPHISM TEST MUST SAY NO SOMEWHERE. The shifted-set
     comparison is run on a pair known to differ -- (3, 7, 7) against
     (3, 8, 8), whose quotients have different SIZES -- and must report
     them different. A comparison that finds everything isomorphic is
     broken, and the blindness result is exactly the shape that would hide
     it.
  C2 THE GREEN ROUTINE MUST SEE A NONTRIVIAL CLASS. The same J-class code
     is run on the FULL monoid M, which contains the ideal, and must print
     a class of size above 1 there. J-triviality of the quotient is
     otherwise indistinguishable from a routine that returns singletons.
  C3 THE ALGEBRA, NOT THE MODEL. The quotient is built by CLOSURE from the
     minimal machine (explore_sign_monoid.quotient + transition_monoid),
     its rank-<= 1 part removed, and the (m, t) model is checked against it
     as a BIJECTIVE HOMOMORPHISM element by element -- not by size
     agreement, which is what every count in this thread already has.
  C4 RANK IS READ OFF THE TRANSITION FUNCTION. Absorbing means a state
     every digit fixes, and the run prints how many there are: it must be
     2 at every cell. The tempting reading -- Moore output 0 -- names the
     sign rather than liveness and makes the rank test pass vacuously,
     which is how it was first written one file upstream.

SCOPE. Seven named cells carry the predictions, chosen so that each
comparison holds (b, s) fixed and varies the split; a sweep over b = 2..7
with both reaches 1..12 carries N1, N2 and C4 as a population statement.
The closure control runs at the named cells only -- it builds the actual
monoid, which is where the cost is. Everything is small-integer
arithmetic and the whole run is expected in seconds, far under the
analysis ceiling.

RUN RECORD: one run over the 7 named cells and the 773 contributing cells
of the b = 2..7 sweep, about 6 s across repeats, far under the analysis ceiling. C1, C2, C3
and C4 clean -- the model is a bijective homomorphism onto the closure
quotient at all 7 named cells, absorbing states are 2 everywhere, the
comparison says NO at its negative control, and the J-class routine finds
classes of 49 and 36 inside the full monoid. K1 = K3 = K4 = K5 = 0.
K2 = 773: the nilpotency degree is one below the slate's, at every cell,
and the slate's arithmetic is what was wrong. N2, N3, N4, N5, N6 hold.
FOUR post-run additions, marked as such where they appear: the blindness
read as a population over grouped cells (F4), the defect criterion inside
it (F5), the cycle-period reading that lets F2 say where the group
structure is, and the PAIRWISE form of F5 with its sum-versus-order
separation, which the audit added because the grouped reading could not
tell the ordered pair from its sum -- and n is a function of that sum, so
the untested criterion was one step from being the state count again. The
J-class routine is cubic and was run at the 718
sweep cells with 120 or fewer quotient elements; the 55 largest carry the
nilpotency check alone, which is a coverage gap in the population half of
N2 and not in the named cells.

FINDINGS.

F1 THE QUOTIENT IS NILPOTENT, WHICH IS WHY Q1 HAS NO ANSWER WORTH THE
   NAME (property, and confirmed at 773 cells). Q = M/I is a REES QUOTIENT
   OF THE VALUE SEMIGROUP: an identity, the rank-> = 2 elements graded by
   word length, and a zero absorbing every element the machine kills --
   which is everything past the last contributing level AND, at a split
   level, part of that level too. Only where every level merges is it
   truncation and nothing more, F2 being what makes those levels survive
   whole. So a product of enough generators is 0 and the augmentation
   ideal is nilpotent of degree exactly the NUMBER OF CONTRIBUTING LEVELS,
   floor(log_b(n - 1)) + 1. N1 predicted that degree plus one and was
   wrong at every cell (K2 = 773): a product of k generators sits at level
   k and dies as soon as k exceeds the last level, so the least vanishing
   k is the level count itself. The slate's error was arithmetic and its
   substance was not -- and the kill is worth more than the prediction
   was, because it says the degree is not a new quantity at all but the
   term count of the correction, read again.
   FREE IS THEREFORE THE WRONG SHAPE TO TEST FOR, and grossly (N3): at
   (3, 7, 7) the contributing levels are 0 and 1, so EVERY product of two
   generators is zero -- 15 generators, an identity and a zero, with an
   empty multiplication. At (3, 13, 13), which reaches level 2, that level
   holds 48 elements against 105 in the untruncated value semigroup and
   729 in a free one. The bijection with an interval of integers is real
   and it is not freeness; nilpotency is what an interval-per-level buys.

F2 GREEN'S RELATIONS SEPARATE NOTHING, AND NOT AS A MEASUREMENT (theorem,
   K1 = 0 at every named cell and at the 718 sweep cells the cubic routine
   reached). Q is J-trivial, hence R-, L-, H- and D-trivial: word length
   ADDS under composition and only the identity has length 0, so mutual
   divisibility forces equal lengths, forces both multipliers to be the
   identity, and forces equality. So Q2 is answered NO before any cell is
   built, and the run is a control on the proof rather than its evidence.
   C2 is what makes the zero readable: the same routine finds J-classes of
   49 and 36 in the FULL monoid, so the triviality is the quotient's and
   not the routine's. So whatever group structure sign's monoid has lives
   in the rank-<= 1 ideal the leading term counts -- and it has none to
   place there: at all 7 named cells the largest cycle period in the FULL
   monoid is 1, so the monoid is APERIODIC (observation, post-run, seven
   cells and no sweep; this file predicted nothing about it), and the
   quotient is a graded nil object.

F3 THE ALL-MERGED QUOTIENT IS BLIND TO THE DIGIT SET'S SPLIT (theorem for
   a fixed level count, verified at the named pair, K3 = 0). Substituting
   u = t + am(b^m - 1)/(b - 1) turns the product law into
   u = b^m2 u1 + u2 with every am term telescoping away -- 0 departures
   over every pair of elements at all 7 cells -- and turns a merged
   level's element set into { 0 <= u <= s(b^m - 1)/(b - 1) }, s = am + ap.
   So two all-merged cells sharing b, s and the number of contributing
   levels have IDENTICAL shifted element sets and hence isomorphic
   quotients. The witness is (3, 7, 7) against (3, 6, 8): different
   minimal machines, 7 live states against 6, different syntactic monoids,
   73 against 59 -- and one and the same algebra above the ideal, 16
   elements each. The level count is a hypothesis and not a freebie, since
   it is set by n, which reads the defects; at these two it happens to
   agree at levels 0 and 1.
   THE NAMED PAIR IS SETTLED BY SIZE AND NOTHING SUBTLER (N5, C1's
   control): (3, 7, 7) and (3, 8, 8) share the live set {-3..3}, the state
   count and the leading 57, and carry 16 and 18 elements. They differ
   because s does, 14 against 16, which is what the correction was already
   saying; the algebra adds no second reason.

F4 SO Q3 IS A YES, AND THE SPLIT LEVELS ARE EXACTLY WHERE THE ALGEBRA
   STOPS BEING ARITHMETIC (rule; post-run population reading over the
   b = 2..7 sweep grouped by (b, s, level count)). Of 80 groups whose
   every level merges, ALL 80 carry ONE quotient across the group -- the
   blindness is exact and has no exceptions. Of 36 groups with a split
   level, 21 still agree and 15 come apart. The named specimen is
   (3, 13, 13) against (3, 12, 14): s = 26 both, levels 0..2 both, level 2
   split both, and quotients of 76 and 61. At b = 2 the coming-apart never
   happens -- (2, 5, 5) and (2, 4, 6) have a split level at m = 3 and are
   isomorphic -- because b - 1 = 1 makes both ceiling defects identically
   zero.

F5 AND WHAT A SPLIT LEVEL READS IS THE ORDERED DEFECT PAIR (rule, 717
   pairs, 0 crossings; post-run, added after F4 was read). Among cells
   sharing (b, s, level count) and carrying a split level, two quotients
   coincide EXACTLY when the cells share (eps-, eps+) as an ORDERED pair:
   547 pairs agreeing on both counts, 170 on neither, none crossing, and
   the same statement grouped rather than paired reads 21 and 15.
   THE ORDER EARNS ITS NAME AND IS NOT THE SUM WEARING A LONGER LABEL,
   which is the confound this rule has to clear: n itself is a function of
   eps- + eps+, so a criterion that only ever separated different SUMS
   would be the state count again. Of the 717 pairs, 116 share the sum and
   differ in the order, and 0 of those 116 share a quotient -- the
   swap alone moves the algebra, at every pair where a swap is available.
   The mechanism is the one the hand-attack wrote down: a split
   level's blocks start at u_lo = 1 - s/(b - 1) - eps+ - q eps- + 2q,
   which weights the two defects DIFFERENTLY, so the pair is read with its
   order and not through its sum -- while n = s/(b - 1) + eps- + eps+ - 1
   reads only the sum, which is why the state count cannot see what the
   algebra does. So the full invariant is (b, s, level count) plus, and
   only where a level splits, the ordered pair of ceiling defects.

WHAT THIS SETTLES AND WHAT IT LEAVES. The correction's merged bulk is a
statement about the algebra and not a counting accident: those levels are
the value semigroup's own, whole, blind to everything about the system but
its radix and its total digit-set width. What makes the quotient carry
more than arithmetic is concentrated in the split levels, and the extra
datum they carry is named -- the ordered defect pair. What is NOT settled
is whether that invariant is COMPLETE: the run shows the defect pair
decides agreement between cells sharing (b, s, level count), and says
nothing
about cells that share every one of those and sit at different b, where
no comparison is defined by the shift used here. The order-wall block's
own front closes: what the residue is made of is an arithmetic object plus
a boundary datum, and neither is a lattice.
"""

import os
import sys
import time

os.environ.setdefault("OPENBLAS_NUM_THREADS", "1")

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import explore_sign_monoid as sm                # noqa: E402


# ------------------------------------------------------------ the (m,t) model

def contributing_levels(b, am, ap):
    """The m with b^m <= n - 1, the criterion of the correction's F7."""
    n = len(sm.live_states(b, am, ap))
    out, m = [], 0
    while b ** m <= n - 1:
        out.append(m)
        m += 1
    return out


def word_range(b, am, ap, m):
    """[-T-, T+], the exact value range of a length-m word."""
    span = (b ** m - 1) // (b - 1)
    return -am * span, ap * span


def rank_of(b, am, ap, m, t):
    """How many live states survive v -> clamp(b^m v + t): the count of
    live v whose image is again live. Live = the integers in the crossed
    interval, which is what the clamp's interior is."""
    live = sm.live_states(b, am, ap)
    lo, hi = live[0], live[-1]
    return sum(1 for v in live if lo <= b ** m * v + t <= hi)


def model_elements(b, am, ap):
    """The rank-> = 2 elements of the quotient, as (m, t) pairs."""
    out = []
    for m in contributing_levels(b, am, ap):
        lo, hi = word_range(b, am, ap, m)
        for t in range(lo, hi + 1):
            if rank_of(b, am, ap, m, t) >= 2:
                out.append((m, t))
    return out


def model_product(b, am, ap, x, y, elements):
    """(*) with anything falling out of the element set sent to zero."""
    if x is None or y is None:
        return None
    m1, t1 = x
    m2, t2 = y
    z = (m1 + m2, b ** m2 * t1 + t2)
    return z if z in elements else None


def shifted(b, am, ap):
    """The element set in the coordinate u = t + am(b^m - 1)/(b - 1),
    where the product law loses every parameter but b."""
    out = set()
    for (m, t) in model_elements(b, am, ap):
        out.add((m, t + am * (b ** m - 1) // (b - 1)))
    return out


# ---------------------------------------------------------------- the algebra

def absorbing_blocks(blocks, delta):
    """C4: a state every digit fixes. Read off the TRANSITION function,
    never off the Moore output, which names the sign instead."""
    return {s for s in blocks if all(delta[s][d] == s for d in delta[s])}


def full_monoid(b, am, ap):
    """The syntactic monoid by closure, with the machine it lives on."""
    _, blocks, delta, _ = sm.quotient(b, am, ap)
    mon = sm.transition_monoid(blocks, delta)
    return blocks, delta, sorted(mon)


def map_rank(tup, blocks, absorbing):
    """How many states the map sends somewhere non-absorbing."""
    idx = {s: i for i, s in enumerate(blocks)}
    dead = {idx[s] for s in absorbing}
    return sum(1 for i in range(len(blocks)) if tup[i] not in dead)


def rees_quotient(mon, blocks, absorbing):
    """The rank-> = 2 elements; everything else is the quotient's zero."""
    return [t for t in mon if map_rank(t, blocks, absorbing) >= 2]


def compose(f, g):
    """Apply f, then g -- the order words are read in."""
    return tuple(g[f[i]] for i in range(len(f)))


def j_classes(elements, mult, zero=None):
    """Green's J-classes by mutual divisibility, over a finite semigroup
    given as an element list and a product. Two-sided ideals are computed
    by brute force, which is what a few hundred elements affords."""
    ideal = {}
    for x in elements:
        gen = {x}
        for a in elements + [None]:
            for c in elements + [None]:
                y = x
                if a is not None:
                    y = mult(a, y)
                if c is not None and y is not None:
                    y = mult(y, c)
                if y is not None:
                    gen.add(y)
        ideal[x] = frozenset(gen)
    classes, seen = [], set()
    for x in elements:
        if x in seen:
            continue
        cls = [y for y in elements
               if y not in seen
               and x in ideal[y] and y in ideal[x]]
        for y in cls:
            seen.add(y)
        classes.append(cls)
    return classes


def nilpotency_degree(elements, mult, generators):
    """The least k with every product of k elements zero, computed by
    powering the augmentation ideal from the LEVEL-1 elements alone.

    That is only sound if every non-identity element of Q is a product of
    surviving level-1 elements, which needs level 1 to be MERGED whenever
    a level above it exists -- otherwise a level-2 element could sit in Q
    with both of its factors outside. It always is: a level m >= 2 exists
    only when b^m <= n - 1, so n >= b^2 + 1 >= 2b + 1 > 2b, which is
    exactly level 1 merging. Checked over the sweep: 0 cells carry a split
    level 1 together with a level 2.
    """
    cur = set(generators)
    k = 1
    while cur:
        nxt = set()
        for x in cur:
            for g in generators:
                z = mult(x, g)
                if z is not None:
                    nxt.add(z)
        cur = nxt
        k += 1
        if k > 64:
            return None
    return k


# ------------------------------------------------------------------- controls

def control_c3(b, am, ap):
    """The (m, t) model against the closure quotient, as a bijective
    homomorphism element by element."""
    blocks, delta, mon = full_monoid(b, am, ap)
    absorbing = absorbing_blocks(blocks, delta)
    rees = rees_quotient(mon, blocks, absorbing)
    elements = model_elements(b, am, ap)
    eset = set(elements)

    def realize(x):
        m, t = x
        return sm.replay_map(blocks, delta, digits_for(b, am, ap, m, t))

    phi = {}
    for x in elements:
        phi[x] = realize(x)
    ok_bij = (len(set(phi.values())) == len(elements)
              and set(phi.values()) == set(rees))
    ok_hom = True
    for x in elements:
        for y in elements:
            z = model_product(b, am, ap, x, y, eset)
            got = compose(phi[x], phi[y])
            if z is None:
                if map_rank(got, blocks, absorbing) >= 2:
                    ok_hom = False
            elif phi[z] != got:
                ok_hom = False
    return len(absorbing), len(rees), ok_bij, ok_hom


def digits_for(b, am, ap, m, t):
    """Some length-m word over {-am..ap} of value t -- greedy from the
    top, which the contiguity of the digit set makes always possible."""
    out = []
    rem = t
    for i in range(m - 1, -1, -1):
        span = (b ** i - 1) // (b - 1)
        for d in range(-am, ap + 1):
            lo = d * b ** i - am * span
            hi = d * b ** i + ap * span
            if lo <= rem <= hi:
                out.append(d)
                rem -= d * b ** i
                break
        else:
            raise AssertionError(f"no digit at {(b, am, ap, m, t)}")
    assert rem == 0
    return tuple(out)


def control_c2(b, am, ap):
    """The J-class routine on the FULL monoid: it must find a class of
    size above 1, or J-triviality below means nothing."""
    blocks, delta, mon = full_monoid(b, am, ap)
    classes = j_classes(mon, lambda x, y: compose(x, y))
    return max(len(c) for c in classes)


def main():
    t0 = time.time()
    print("=" * 70)
    print("THE QUOTIENT ABOVE THE RANK-<= 1 IDEAL")
    print("=" * 70)

    named = [(3, 7, 7), (3, 8, 8), (3, 6, 8),
             (2, 5, 5), (2, 4, 6),
             (3, 13, 13), (3, 12, 14)]

    print("\nC4 + C3 -- the closure quotient against the (m, t) model")
    print(f"{'cell':>14} {'absorb':>7} {'|Q|-1':>7} {'corr':>6} "
          f"{'bijection':>10} {'homomorphism':>13}")
    c3_fail = 0
    for (b, am, ap) in named:
        nabs, nrees, ok_bij, ok_hom = control_c3(b, am, ap)
        corr = sm.correction(b, am, ap)
        flag = (nabs != 2) or (not ok_bij) or (not ok_hom) or (nrees != corr)
        c3_fail += bool(flag)
        print(f"{str((b, am, ap)):>14} {nabs:>7} {nrees:>7} {corr:>6} "
              f"{str(ok_bij):>10} {str(ok_hom):>13}"
              + ("   <-- FAIL" if flag else ""))
    print(f"  C3/C4/K5 failures: {c3_fail}")

    print("\nC2 -- the same J-class routine on the FULL monoid")
    for (b, am, ap) in named[:3]:
        big = control_c2(b, am, ap)
        print(f"  {str((b, am, ap)):>14}  largest J-class {big}"
              + ("   <-- FAIL, routine cannot see one" if big < 2 else ""))

    print("\nwhere the group structure is (post-run): the largest cycle")
    print("period in the FULL monoid, 1 meaning aperiodic")
    for (b, am, ap) in named:
        blocks, delta, mon = full_monoid(b, am, ap)
        per = 1
        for x in mon:
            y, seen, i = x, {x: 0}, 0
            while True:
                i += 1
                y = compose(y, x)
                if y in seen:
                    per = max(per, i - seen[y])
                    break
                seen[y] = i
        print(f"  {str((b, am, ap)):>14}  |M| {len(mon):>4}  "
              f"largest cycle period {per}")

    print("\nN1 + N2 -- nilpotency and J-triviality of the quotient")
    print(f"{'cell':>14} {'|Q|-1':>7} {'levels':>7} {'nil deg':>8} "
          f"{'expected':>9} {'max J-class':>12}")
    k1 = k2 = 0
    for (b, am, ap) in named:
        elements = model_elements(b, am, ap)
        eset = set(elements)

        def mult(x, y, b=b, am=am, ap=ap, eset=eset):
            return model_product(b, am, ap, x, y, eset)

        gens = [x for x in elements if x[0] == 1]
        deg = nilpotency_degree(elements, mult, gens)
        lev = contributing_levels(b, am, ap)
        want = max(lev) + 2
        classes = j_classes(elements, mult)
        big = max(len(c) for c in classes)
        k1 += (big > 1)
        k2 += (deg != want)
        print(f"{str((b, am, ap)):>14} {len(elements):>7} {len(lev):>7} "
              f"{str(deg):>8} {want:>9} {big:>12}"
              + ("   <-- KILL" if big > 1 or deg != want else ""))
    print(f"  K1 (nontrivial J-class): {k1}   K2 (wrong degree): {k2}")

    print("\nN3 -- free? the level-2 count against a free semigroup's")
    for (b, am, ap) in [(3, 7, 7), (2, 5, 5), (3, 13, 13)]:
        s = am + ap
        lev = contributing_levels(b, am, ap)
        got = len([x for x in model_elements(b, am, ap) if x[0] == 2])
        free = (s + 1) ** 2
        wid = s * (b + 1) + 1
        print(f"  {str((b, am, ap)):>14}  level 2 in the quotient {got:>5}"
              f"   in the value semigroup {wid:>5}   free {free:>5}"
              f"   (levels {lev})")

    print("\nN4/N5/N6 + C1 -- the shifted element sets, pair by pair")
    pairs = [((3, 7, 7), (3, 6, 8), "same s, all merged, different machine"),
             ((3, 7, 7), (3, 8, 8), "different s -- C1's negative control"),
             ((3, 13, 13), (3, 12, 14), "same s, a SPLIT level at b = 3"),
             ((2, 5, 5), (2, 4, 6), "same s, a split level at b = 2")]
    for (c1, c2, why) in pairs:
        s1 = shifted(*c1)
        s2 = shifted(*c2)
        same = s1 == s2
        print(f"  {str(c1):>14} vs {str(c2):<14} |Q|-1 {len(s1):>3} / "
              f"{len(s2):<3}  shifted sets "
              f"{'IDENTICAL' if same else 'differ':>9}   ({why})")

    print("\nthe shifted product law, checked numerically")
    bad = 0
    for (b, am, ap) in named:
        for (m1, t1) in model_elements(b, am, ap):
            for (m2, t2) in model_elements(b, am, ap):
                sh = (lambda m, t: t + am * (b ** m - 1) // (b - 1))
                u1, u2 = sh(m1, t1), sh(m2, t2)
                lhs = sh(m1 + m2, b ** m2 * t1 + t2)
                if lhs != b ** m2 * u1 + u2:
                    bad += 1
    print(f"  departures from u = b^m2 u1 + u2: {bad}")

    print("\nN1/N2 as a population -- b = 2..7, both reaches 1..12")
    worst_j, worst_deg, cells, judged = 0, 0, 0, 0
    j_cap = 120
    for b in range(2, 8):
        for am in range(1, 13):
            for ap in range(1, 13):
                elements = model_elements(b, am, ap)
                if not elements:
                    continue
                eset = set(elements)

                def mult(x, y, b=b, am=am, ap=ap, eset=eset):
                    return model_product(b, am, ap, x, y, eset)

                gens = [x for x in elements if x[0] == 1]
                deg = nilpotency_degree(elements, mult, gens)
                want = max(contributing_levels(b, am, ap)) + 2
                worst_deg += (deg != want)
                cells += 1
                if len(elements) <= j_cap:
                    classes = j_classes(elements, mult)
                    worst_j = max(worst_j, max(len(c) for c in classes))
                    judged += 1
    print(f"  {cells} cells: nilpotency-degree mismatches {worst_deg}")
    print(f"  J-classes computed at the {judged} cells with |Q| - 1 <= "
          f"{j_cap} (the routine is cubic); largest anywhere {worst_j}; "
          f"{cells - judged} cells carry the nilpotency check only")

    print("\nthe blindness as a population (post-run) -- cells grouped by")
    print("(b, s, contributing levels), merged-only groups against the rest")
    groups = {}
    for b in range(2, 8):
        for am in range(1, 13):
            for ap in range(1, 13):
                lev = contributing_levels(b, am, ap)
                if not lev:
                    continue
                n = len(sm.live_states(b, am, ap))
                allmerged = all(2 * b ** m <= n for m in lev)
                key = (b, am + ap, len(lev), allmerged)
                groups.setdefault(key, []).append((b, am, ap))
    for allmerged in (True, False):
        gs = [(k, v) for k, v in groups.items()
              if k[3] is allmerged and len(v) > 1]
        agree = sum(1 for _, v in gs
                    if len({frozenset(shifted(*c)) for c in v}) == 1)
        print(f"  every level merged = {str(allmerged):<5}: "
              f"{len(gs):>3} groups of 2 or more cells, "
              f"{agree:>3} with ONE quotient across the group, "
              f"{len(gs) - agree:>3} split apart")

    print("  and among the split-level groups, does agreement coincide")
    print("  with the cells sharing the ORDERED defect pair (eps-, eps+)?")
    both = neither = mismatch = 0
    for k, v in groups.items():
        if k[3] or len(v) < 2:
            continue
        same_q = len({frozenset(shifted(*c)) for c in v}) == 1
        defects = {((-am) % (b - 1), (-ap) % (b - 1)) for (b, am, ap) in v}
        same_eps = len(defects) == 1
        if same_q and same_eps:
            both += 1
        elif not same_q and not same_eps:
            neither += 1
        else:
            mismatch += 1
    print(f"    both {both}, neither {neither}, disagreements {mismatch}")

    print("  the same criterion PAIRWISE, and whether the ORDER earns its")
    print("  name: pairs of split-level cells sharing (b, s, level count)")
    cache, tally, sumtest = {}, [0, 0, 0, 0], [0, 0]
    keyed = {}
    for b in range(2, 8):
        for am in range(1, 13):
            for ap in range(1, 13):
                lev = contributing_levels(b, am, ap)
                if not lev:
                    continue
                n = len(sm.live_states(b, am, ap))
                if all(2 * b ** m <= n for m in lev):
                    continue
                keyed.setdefault((b, am + ap, len(lev)), []).append((b, am, ap))
    for group in keyed.values():
        for i in range(len(group)):
            for j in range(i + 1, len(group)):
                cx, cy = group[i], group[j]
                for c in (cx, cy):
                    if c not in cache:
                        cache[c] = frozenset(shifted(*c))
                same_q = cache[cx] == cache[cy]
                ex = ((-cx[1]) % (cx[0] - 1), (-cx[2]) % (cx[0] - 1))
                ey = ((-cy[1]) % (cy[0] - 1), (-cy[2]) % (cy[0] - 1))
                same_e = ex == ey
                tally[0 if (same_e and same_q) else
                      1 if (same_e and not same_q) else
                      2 if (not same_e and same_q) else 3] += 1
                if not same_e and sum(ex) == sum(ey):
                    sumtest[0 if same_q else 1] += 1
    print(f"    same pair and same quotient {tally[0]},  "
          f"different pair and different quotient {tally[3]},  "
          f"crossings {tally[1] + tally[2]}")
    print(f"    of those, pairs sharing the defect SUM but not its order: "
          f"{sumtest[0] + sumtest[1]}, of which "
          f"{sumtest[0]} have the same quotient")

    print(f"\ndone in {time.time() - t0:.1f} s")


if __name__ == "__main__":
    main()
