"""IS THE SURVIVING QUADRATIC COMPONENT THE HALF OF THE DUAL THE LADDER'S
2-TORSION TERM CANNOT REACH? -- the same per-class deficit carried to a
narrow class group that is no longer assumed cyclic, over every field with
h+ >= 2, and split by a criterion the cyclic population could not state.

THE QUESTION, AND WHY IT IS NOT THE ONE THE LAST PROBE HANDED OVER. Probe 4
(explore_class_character.py) transformed the per-class principal deficit
over the fields whose narrow class group is cyclic and found the spectrum
to be the order ladder to first order, with a component surviving on the
QUADRATIC characters at three strata after a per-field amplitude control.
It closed by naming the deciding question as GENUS versus SIZE CLASS: the
genus characters being an identified subgroup of the dual and the quadratic
ones a size class, cyclic groups confounding them because a cyclic group of
even order has exactly one character of order 2. THAT QUESTION DISSOLVES ON
PAPER and derivation (1) below is the whole of it: the genus characters are
by definition the characters trivial on Cl+^2, which is to say the
characters chi with chi^2 = 1, which is to say the characters of order
dividing 2. Genus and quadratic name the same set at EVERY field, cyclic or
not, and no population can separate them because there is nothing to
separate. What was confounded in the cyclic population is not genus with
quadratic but the whole 2-torsion of the dual with a single coordinate.

So this probe asks the question that survives, and derivation (2) is where
it comes from: the ladder's 2-TORSION TERM does not reach every quadratic
character, though the ladder's other terms all do.
An order-graded class function is a combination of torsion-subgroup
indicators, and a subgroup's indicator transforms onto the characters
trivial ON that subgroup, so the ladder's 2-torsion term reaches exactly
the quadratic characters that are trivial on Cl+[2] -- and on a cyclic
group of order h that is the whole story of h mod 4, which is precisely the
congruence probe 4 found its three survivors sitting at without being able
to say why. On a NON-CYCLIC group the two kinds coexist inside one field,
and the question becomes a within-field comparison that needs no strata
matching and no cross-field normalization at all.

WHOSE VOCABULARY THE SUSPICION IS WRITTEN IN. Probe 4 spoke the dual's, but
with one coordinate per size class, because that is all a cyclic group
offers. This probe stays in the dual and changes what a COORDINATE is: the
dual of a product of cyclic factors is the product of their duals, so a
character is a tuple and its relation to the 2-torsion subgroup is a
property of the tuple. THE TRANSPLANT, flagged: the surviving component was
measured on cyclic fields alone, and the prediction that it lands on the
ladder-unreachable characters is an intuition carried from a population
where "unreachable" and "h+ = 2 mod 4" are the same condition to one where
they are not. Probe 4's congruence reading is a WHERE with a
mechanism-shaped fact beside it, and this probe promotes that fact to a
criterion and tests it -- which is a different act from confirming it.

THE HAND-DERIVATION (pre-engine, on paper).

  (1) GENUS = QUADRATIC, EVERYWHERE, AND THE LAST PROBE'S DECIDING
      QUESTION IS EMPTY. A genus character is a character of Cl+ trivial on
      Cl+^2. chi trivial on Cl+^2 <=> chi(C^2) = 1 for every C <=> chi^2 =
      1. So the genus characters are exactly the 2-torsion of the dual and
      the non-trivial ones are exactly the characters of order 2. Classical
      genus theory says |Cl+/Cl+^2| = 2^(t-1) for t the number of prime
      discriminant factors of D, so there are 2^(t-1) of them including the
      trivial one and 2^(t-1) - 1 non-trivial -- and since a finite abelian
      group has |G[2]| = |G/G^2|, that count is also the 2-rank statement
      2^r with r = t - 1. The claim this probe was minted to test, that the
      quadratic characters are strictly more numerous than the genus ones,
      is false as arithmetic and not as a matter of evidence, and this
      derivation and not any run is what corrects it.

  (2) THE LADDER REACHES SOME QUADRATIC CHARACTERS AND NOT OTHERS, AND
      THAT IS THE SPLIT THE CYCLIC POPULATION COULD NOT STATE. For a
      subgroup H <= G the indicator 1_H transforms as sum_{C in H} chi(C) =
      |H| if chi is trivial on H and 0 otherwise -- so 1_H lands on H
      PERPENDICULAR, the characters trivial on H, and nowhere else. A class
      function of ord(C) alone is a combination of the indicators of the
      torsion subgroups G[d], so the ladder's d-torsion term reaches
      exactly the characters trivial on G[d]. Take d = 2. Writing G =
      prod_i Z/d_i with generators g_i, G[2] is generated by the g_i^(d_i/2)
      over the even d_i, and chi_j(g_i^(d_i/2)) = e(pi i j_i) = (-1)^(j_i).
      So chi_j is trivial on G[2] exactly when j_i is EVEN at every i with
      d_i even. A quadratic character has j_i in {0, d_i/2} at each i, so it
      is REACHABLE exactly when every coordinate it is supported on has
      4 | d_i, and UNREACHABLE as soon as it is supported on a coordinate
      with d_i = 2 mod 4. On a cyclic group of even order h there is one
      quadratic character, chi_(h/2), and it is reachable iff 4 | h: probe
      4's congruence pattern is this criterion read at rank 1, and its
      three survivors were all unreachable. Both halves are invariants: an
      automorphism of G permutes the dual preserving order and preserving
      triviality on G[2], so pooling by (order, reachability) is legitimate
      exactly as pooling by order alone was.

  (3) THE COMPARISON IS THEREFORE WITHIN A FIELD, WHICH BUYS OFF THREE OF
      THE LAST PROBE'S UNCONTROLLED THINGS AT ONCE. Where a group carries
      both kinds -- 2-Sylow of the shape Z/2 x Z/2^a with a >= 2, the
      smallest being Z/2 x Z/4 -- the reachable and unreachable quadratic
      characters sit in ONE field, under one class number, one amplitude,
      one noise level and one stratum. So the reading is a PAIRED per
      character energy, its null is 1 by exchangeability rather than by a
      fitted reference, and the trivial class's derived hard zero at D < 0
      cannot fake it: a delta contributes FLAT, equally to both kinds, and
      cancels in the ratio. That is a strictly stronger instrument than
      probe 4's share-against-flat and it exists only off the cyclic
      population.

  (4) THE AMPLITUDE CONTROL IS HELD OUT, WHICH IS THE CONTROL PROBE 4 SAID
      IT OWED AND DID NOT RUN. Probe 4's C8 fitted the per-field ladder
      amplitude alpha = <dev_s, fit>/<fit, fit> on the same field it then
      subtracted from, so alpha absorbed the field's own noise along the
      fit direction -- and the fit direction is quadratic-heavy, which is
      the direction under test. The fix is not a data split: the transform
      is unitary up to scale (Parseval), so an inner product may be taken
      in the DUAL, and alpha can be fitted over the characters OUTSIDE the
      tested set. alpha_held = sum_{j not in T, j != 0} E_fit(j) E_s(j) /
      sum_{j not in T} E_fit(j)^2 with T the order-2 characters. It cannot
      absorb anything at a tested coordinate because it never reads one, so
      unlike C8 it is neither conservative nor anti-conservative there --
      it is simply blind to the direction it is protecting. Both are
      printed side by side.

  (5) A DELTA IS FLAT AND THE NOISE IS FLAT, UNCHANGED FROM PROBE 4 AND
      RE-STATED BECAUSE THE DENOMINATOR CHANGED. Per field the bin-0 counts
      are multinomial over tot0 split primes, so under the nominal 1/h the
      deviations are exchangeable across classes and an exchangeable
      perturbation carries the same expected energy at every j != 0. Noise
      therefore dilutes any concentration toward flat and can never
      manufacture one, and a flat contribution is invisible to the paired
      ratio of derivation (3). What is NOT inherited is the flat allowance
      as a number: a share is now read against |S|/(h+ - 1) for the
      character set S at issue, and the sets differ field to field within a
      stratum only if the group does, which the iso-type strata forbid.

  (6) THE STRATUM IS THE ISOMORPHISM TYPE AND NOT h+, WHICH IS FORCED
      RATHER THAN CHOSEN. The fitted order profile of derivation (2) is a
      vector indexed by class order and its transform depends on how many
      classes carry each order, which is a function of the iso type and not
      of h+ alone: Z/8, Z/2 x Z/4 and (Z/2)^3 have different profiles and
      different duals. Pooling them would subtract one group's ladder from
      another's spectrum. So strata are invariant-factor tuples per sign,
      and a stratum is READABLE for the share readings when its non-trivial
      characters carry more than one distinct order, and MIXED -- readable
      for the paired reading -- when it carries both reachable and
      unreachable quadratic characters.

  (7) THE POPULATION IS PROBE 2'S SWEEP WITH THE CYCLICITY CUT REMOVED.
      Same discriminant bound, same prime cap, same bottom bin, same
      MIN_SPLIT, same composition, so probe 2's composition controls
      re-print unchanged; probe 4 could read only the 166 real and 820
      imaginary cyclic fields with h+ >= 3 because it needed one discrete
      log, and a structure decomposition reads every field with h+ >= 2.
      h+ = 1 has no non-trivial character and never enters; h+ = 2 has
      exactly one and carries no shape, so it enters the population and not
      the share readings. WIDENING TRIGGER, declared before the run: if
      fewer than three NON-CYCLIC iso types across both signs carry
      MINSTRAT fields, or if fewer than MINSTRAT fields in total carry a
      MIXED group, the sweep re-runs at |D| <= 8000 under memwatch and both
      populations are reported.

THE SLATE -- PREDICTIONS, FROZEN BEFORE THE ENGINE, AT BOTH SIGNS.

  P1. THE CONCENTRATION TRANSPORTS OFF THE CYCLIC POPULATION. On the
      symmetrized dev, the energy share at character order 2 exceeds its
      flat allowance |S_2|/(h+ - 1) at every readable NON-CYCLIC stratum of
      either sign. The reason: derivation (2) says the ladder's 2-torsion
      term is there regardless of the group's shape, and probe 4 measured
      the observed share between flat and the ladder's own transform at
      sixteen of sixteen extreme cells on the cyclic side.

  P2. AND WHAT SURVIVES THE HELD-OUT LADDER SITS ON THE UNREACHABLE HALF.
      At the mixed strata, the residual after alpha_held carries MORE
      energy per unreachable quadratic character than per reachable one:
      the within-field mean ratio exceeds 1, and it exceeds the placebo
      band. The reason is probe 4's congruence pattern read through
      derivation (2): its three survivors were exactly the strata where the
      one quadratic character is unreachable, and the fourth such stratum
      missed by 0.002 while all four reachable strata failed outright.

  P3. AND THE HELD-OUT AMPLITUDE LEAVES MORE STANDING THAN THE SAME-DATA
      ONE. Re-read on probe 4's own cyclic strata, the count of strata
      where the residual's quadratic share beats both the flat allowance
      and the placebo band is at least three under alpha_held -- probe 4's
      count under the same-data alpha. The reason: derivation (4) says C8
      absorbed noise along the tested direction and therefore understated,
      so removing that absorption cannot lower the count by construction,
      and may raise it.

THE KILLS, AS OBSERVABLES -- what the rig PRINTS, weighed for meaning only
after the controls are read.

  K1 kills P1: the printed per-stratum energy share at character order 2 of
     the symmetrized dev, against the printed flat allowance. At or below
     it at any readable non-cyclic stratum is the kill.

  K2 kills P2: the printed within-field mean of (energy per unreachable
     quadratic character)/(energy per reachable quadratic character) on the
     residual after alpha_held, per mixed stratum and pooled over every
     mixed field, beside the same statistic on the placebo. At or below 1,
     or inside the placebo band, is the kill -- and a ratio BELOW 1 beyond
     the band is the informative opposite outcome: the surviving component
     would then sit where the ladder DOES reach, which would say it is the
     ladder's own amplitude structure and not a second mechanism.

  K3 kills P3: the printed count of probe 4's cyclic strata whose
     alpha_held residual quadratic share exceeds both the flat allowance
     and the whole placebo band. Below three is the kill.

THE POSITIVE CONTROLS, run and read FIRST.

  C1. INVERSION. The inverse transform must return the measured deviations:
      max over every kept field and class of |dev(a) - (1/h) sum_j
      conj(chi_j)(a) E_j|, printed. Above 1e-9 voids the rig.

  C2. THE TRIVIAL CHARACTER IS EXACTLY ZERO. max |E_0| over every kept
      field, which is the constant sum seen in the dual. Above 1e-9 voids
      every share below, the shares being taken over j != 0.

  C3. PARSEVAL. max relative deviation of sum_j |E_j|^2 from h sum_a
      dev(a)^2, printed. This is what licenses reading a SHARE, and it is
      also what licenses derivation (4)'s inner product being taken in the
      dual.

  C4. THE SYMMETRIZED TRANSFORM IS REAL. max |Im E_j| over every kept field
      and every j on the symmetrized dev. The inverse of a class in
      coordinates is the negated tuple, so evenness must survive the change
      of basis; a non-zero value means the pairing is wrong.

  C5. THE DECOMPOSITION IS A DECOMPOSITION. Per kept field: the factor
      orders multiply to h+; the coordinate map is a bijection from the
      classes onto the product of the factors; the trivial class sits at
      the zero tuple; and every class's ORDER computed from its coordinates
      as lcm_i d_i/gcd(a_i, d_i) equals the order the sweep measured
      independently. Violation counts printed, and must be zero. Fields
      where the greedy peel fails to span are counted separately and never
      silently dropped.

  C6. PROBE 2'S COMPOSITION CONTROLS, RE-PRINTED through the imported sweep
      as violation counts -- discriminant and integrality, key in
      inventory, walk overrun, order divides h+, two-sided identity,
      commutativity, associativity, and the order-at-most-2 count against
      the independent form-symmetry ambiguity test.

  C7. THE EXCHANGEABILITY PLACEBO, in probe 4's form and for its reason.
      The deviations are ROTATED across the non-trivial classes within each
      field over five fixed offsets read off |D|, none the identity, and
      re-symmetrized exactly as the treatment is -- which holds the
      constant sum and the trivial class and moves only WHICH class carries
      which deviation. It runs over CLASSES and never over inverse PAIRS: a
      pair carries two classes and a self-inverse class one, so rotating
      pairs moves a two-class value onto a one-class slot and breaks the
      constant sum, leaving a null differing from the treatment in two
      variables. The count of DISTINCT draws per field is printed beside
      the band, a field of class number h admitting h - 2 non-identity
      rotations.

  C8. THE REACHABILITY CRITERION AGAINST DIRECT EVALUATION. Derivation (2)
      says chi_j is trivial on Cl+[2] iff j_i is even at every even d_i.
      The rig also evaluates chi_j on every class of order dividing 2
      directly in exact integer arithmetic and compares. Disagreements
      printed, and must be zero -- the criterion is the whole reading and a
      derivation is not a check on itself.

  C9. THE HELD-OUT AMPLITUDE READS NOTHING AT A TESTED COORDINATE. Printed
      beside each mixed stratum: the same-data alpha and the held-out
      alpha, and the max over fields of |alpha_held - alpha| -- a control
      on the CONTROL, since the two agreeing everywhere would mean the
      held-out fit changed nothing and K2 is then reading probe 4's
      instrument under a new name.

THE FINDINGS.

  THE CONTROLS. C6 prints zero at all eight composition counts over 1216
  real and 1217 imaginary fields -- the imported sweep is the object probes
  2, 3 and 4 measured. C5 prints zero at all four decomposition identities
  over the 981 real and 1208 imaginary fields with h+ >= 2, and the greedy
  peel failed to span at NO field of either sign: the factor orders
  multiply to h+, the coordinate map is a bijection onto the product, the
  trivial class sits at the zero tuple, and every class's order read off
  its coordinates equals the order the sweep measured independently. The
  transform's identities hold at float noise -- inversion 2.2e-16 real and
  1.3e-15 imaginary, |E_0| 8.9e-16 and 9.3e-15, Parseval 4.6e-16 and
  4.5e-16 relative, largest imaginary part of the symmetrized transform
  4.5e-16 and 3.3e-15 -- so the transform inverts over a PRODUCT of cyclic
  factors as it did over one and the negated tuple is the inverse class.
  C8 prints zero disagreements between derivation (2)'s reachability
  criterion and direct evaluation on Cl+[2], over every kept field and
  every character of order 2. C9 -- the control on the CONTROL, which
  would void every held-out reading if the two amplitudes agreed -- prints
  max |alpha_held - alpha| between 0.4241 and 1.1242 at the seven strata of
  complement dimension 3 or more, so they differ field to field by an
  amount comparable to alpha itself; and it independently finds the void
  cells, printing 2.2575 at the widest dimension-2 stratum and 6.8103 and
  2.7917 at the two of dimension 1, where a one-parameter fit against a
  one-dimensional complement swings freely. And an unplanned control the general rig
  supplies for free: at all EIGHT cyclic strata a probe over one discrete
  log read, two real and six imaginary, OBS, FLAT, FIT, RES and RES-a
  reproduce that probe's printed figures to the last digit of all four
  decimals, and the placebo band's upper edge matches at each of the three
  strata it quoted one for. So the decomposition machinery specializes to
  the single discrete log exactly.

  **GENUS AND QUADRATIC ARE THE SAME SET, SO THE QUESTION THIS PROBE WAS
  MINTED TO DECIDE HAS NO CONTENT** (property, derivation (1), no run).
  The genus characters are those trivial on Cl+^2, which is to say the chi
  with chi^2 = 1, which is to say the characters of order dividing 2. The
  standing statement that the non-cyclic groups separate them -- "the
  genus characters are 2^(t-1) - 1 of the dual's
  2-torsion and the quadratic ones are strictly more" -- is false as
  arithmetic: |Cl+/Cl+^2| = 2^(t-1) by genus theory and |G[2]| = |G/G^2|
  in any finite abelian group, so both counts are 2^(t-1) - 1 at EVERY
  field. Probe 4's closing verdict that the coincidence was an artifact of
  cyclicity was wrong, and it was wrong in the direction that made a
  further probe look decisive.

  **THE QUADRATIC CONCENTRATION TRANSPORTS OFF THE CYCLIC POPULATION**
  (observation; P1 SURVIVES, K1 misses at every readable non-cyclic
  stratum). The symmetrized dev's energy share at character order 2 beats
  its flat allowance at all five: real Z/2 x Z/4 0.6349 against 0.4286;
  imaginary Z/2 x Z/4 0.6727 against 0.4286, Z/2 x Z/6 0.4884 against
  0.2727, Z/2 x Z/8 0.4187 against 0.2000 and Z/2 x Z/10 0.2662 against
  0.1579 -- 1.48 to 2.09 times nominal, inside the 1.48-to-2.58 band probe
  4 read on the cyclic side. (SETTLED LATER by explore_class_null.py: read
  against the SYMMETRIZED allowance 2*n2/(h+-1+n2) rather than flat --
  symmetrizing preserves a real character's energy and halves a complex
  one's, and the order-2 characters are exactly the real ones -- this is
  four of the five at 1.06 to 1.26x, with Z/2 x Z/10 just under at 0.98.
  Every reading here against the ROTATION band is untouched.) And the
  observed share again sits between flat
  and the transform of the stratum's own order profile at four of the five,
  the exception being imaginary Z/2 x Z/4 where OBS 0.6727 exceeds a FIT of
  0.6169. So the deficit's spectrum is quadratic-heavy at 2-rank 2 as it is
  at 2-rank 1, which is signal diluted toward flat by exchangeable counting
  noise exactly as derivation (5) has it.

  **BUT THAT SPLIT DOES NOT CARRY THE SURVIVING COMPONENT, AND IF IT
  LEANS AT ALL IT LEANS THE OTHER WAY** (observation;
  P2 DIES, K2 unreadable as frozen and read on the statistics that
  replaced it). At the three mixed strata the residual after the held-out
  amplitude carries LESS energy per unreachable quadratic character than
  per reachable one relative to the rotation null, not more: ratio of means
  0.349 against a null 1.251 at real Z/2 x Z/4, 0.719 against 0.801 at
  imaginary Z/2 x Z/4, and 0.998 against 0.729 at imaginary Z/2 x Z/8;
  pooled over 129 mixed fields, 0.746 against 0.805, a median ratio of
  0.890 against 1.316, and the unreachable character larger at 0.488 of
  fields against 0.543. The null is the ROTATION and not derivation (3)'s
  exchangeable 1, which is an expectation over draws and not a value any
  finite population takes: the measured nulls sit at 0.805, 1.316 and 0.543
  and every observed figure is read against those. Two of the three strata and all three pooled
  statistics sit below the null, one stratum (imaginary Z/2 x Z/8) sits
  above it on the ratio of means and below on the other two, and every
  margin is small with no error bar under it. So the frozen prediction is
  refuted and its opposite is not established: what the reading supports is
  that reachability does not grade the residual.

  **AND THE FROZEN K2 STATISTIC WAS UNREADABLE, WHICH IS A FINDING ABOUT
  THE SLATE.** The mean of the per-field ratio is dominated by fields whose
  reachable energy is near zero -- it prints 36.2, 17.0 and 86.6 at the
  three strata against nulls of 1e59, 3e30 and 203.8. A ratio of two
  energies was frozen as a kill observable without asking what its
  denominator can do, and a heavy-tailed statistic has no band. The three
  replacements were added at audit and are stated as such: the ratio of
  means, the median ratio, and the paired sign count, all against the same
  rotation.

  **AND THE HELD-OUT AMPLITUDE LEAVES 1.35 TO 3.18 TIMES THE ENERGY AT THE
  TESTED COORDINATE THAT PROBE 4'S SAME-DATA ONE DID, WHERE IT IS STABLE
  ENOUGH TO SAY SO** (observation; P3
  and K3 both unreadable as frozen, and the question they were for is
  answered by a column added at audit). RES-h was frozen as a SHARE, and a
  share divides by the residual's own total -- which the held-out fit
  shrinks by construction, being fitted on exactly the characters in that
  denominator and on no others. So RES-h and RES-a are not on one scale and
  K3's count of strata is arithmetic about denominators; at complement real
  dimension 1 the fit annihilates the complement and RES-h is exactly
  1.0000 at both Z/4 strata. Divided instead by the PRE-residual total, the
  two amplitudes are comparable, and the ratio is read by complement
  dimension because the fit is one parameter against exactly that many.
  At the SEVEN strata of complement dimension 3 or more, all imaginary,
  RES-a* against RES-h* runs 0.0629 to 0.2003 at Z/8, 0.0534 to 0.0999 at
  Z/10, 0.0235 to 0.0555 at Z/12, 0.0481 to 0.0895 at Z/14, 0.1433 to
  0.2670 at Z/2 x Z/6, 0.1704 to 0.2305 at Z/2 x Z/8 and 0.0886 to 0.1278
  at Z/2 x Z/10 -- a factor of 1.353 to 3.184, in the direction derivation
  (4) predicted. So probe 4's C8 was absorbing real energy at the
  coordinate it was protecting, and by a factor and not a rounding. Below
  that dimension the fit is not a control and the cells say so themselves:
  at dimension 2 (real Z/6 and Z/2 x Z/4, imaginary Z/6 and Z/2 x Z/4) the
  factor runs 2.317 to 4.578, larger than anywhere above it, and at
  dimension 1 (both Z/4 strata) RES-h is exactly 1.0000 because the fit
  annihilates the complement while RES-h* prints 4.2835 and 1.7190 --
  ABOVE 1, so more energy stands at order 2 after the subtraction than
  stood in the whole spectrum before it, which is a fit amplifying rather
  than removing. Those two cells are VOID and not large.

  WHAT THIS LEAVES THE FRONT. The genus reading is closed by arithmetic:
  there is no genus-versus-quadratic question at any field, so no
  population can be the deciding one and the standing reading is corrected
  rather than extended. The invariant that does split the quadratic characters --
  which of them the order ladder's 2-torsion term can reach -- has been
  measured where it is not degenerate and does not grade the residual, so
  probe 4's h+ = 2 mod 4 pattern is not this criterion showing through. And
  the surviving quadratic component itself is now known to have been
  measured through a control that understates it by 1.353 to 3.184 where
  the held-out fit is stable enough to say so,
  which is a reason to re-read it rather than to believe it: the reading
  that would settle it is the held-out amplitude on a complement wide
  enough to fit against -- which this population supplies at seven strata,
  every one of them imaginary, so the real side has no readable cell at
  all -- and against a null run through that same pipeline, which is the
  one thing here that has none.

RUN RECORD: wall 5.8 s, peak working set 136.8 MB and peak commit 132.3 MB
under memwatch at a 512 MB ceiling. Probe 2's population unchanged per
derivation (7) -- 1216 real and 1217 imaginary fundamental discriminants to
|D| <= 4000 over the odd split p <= 10^4 -- cut to the 981 real and 1208
imaginary fields with h+ >= 2. Five non-cyclic iso types carry MINSTRAT
fields across both signs and 129 fields over three strata carry a MIXED
group, so the widening trigger of derivation (7) did NOT fire. WHAT THE
TABLE OMITS, printed rather than left to be inferred: on the real side 7
iso types holding 790 fields carry ONE character order and so no shape at
all, and 11 more holding 59 fields are readable but under the 30-field
floor, so the table reads 132 of the 981; on the imaginary side the same
counts are 23 types / 233 fields and 66 types / 499 fields, and the table
reads 476 of the 1208. The real side's 790 is not attrition but the
arithmetic -- a narrow class group of order 2 or of prime order has one
character order by construction, and that is most real quadratic fields. Pure Python;
the cost is probe 2's sweep run once per sign, the class inventory rebuilt
once per field to recover the group law the sweep discards, the greedy
peel, and h^2 arithmetic per transform against a per-field precomputed
character table.

WHAT IS NOT CONTROLLED, declared with the design rather than left for a
reader to find. THE READABLE TABLE IS A MINORITY OF THE POPULATION at both
signs -- 13% of the real fields and 39% of the imaginary -- so every share
reading is about the strata that carry more than one character order and
clear the floor, and never about fields with h+ >= 2 as a class. THE MIXED
POPULATION IS THREE STRATA AND 129 FIELDS, all
of 2-rank exactly 2, so "per reachable character" averages over ONE
character and the paired reading compares two single coordinates rather
than two populations of them; a group of 2-rank 3 would carry three of each
kind and none is readable here. The FIT is fitted on the same fields it is then subtracted
from, unchanged from probe 4 -- the leave-one-out this probe runs is on the
per-field AMPLITUDE and not on the stratum profile, and a profile fitted on
the field's own stratum still sees it. The strata are iso types and nothing
finer, so a stratum mixes fields whose group is the same and whose
arithmetic is not otherwise matched, and the two signs are never pooled.
The placebo is a null for "the spectrum is unstructured" and never for "the
spectrum is the fit", and it thins toward the small strata exactly as it
did for probe 4. No error bar is computed on any cell mean, and two shares
close together are not thereby distinguished. The paired reading of
derivation (3) compares per-character energies, so at 2-rank 2 it compares
two single coordinates rather than two populations of them. And every
reading past OBS is taken on a residual after a fitted profile and a fitted
amplitude, so it is a statement about what those two leave and never about
the raw deficit.
"""

import os
import sys
import time
from cmath import exp as cexp, pi
from collections import defaultdict
from math import gcd

os.environ.setdefault("OPENBLAS_NUM_THREADS", "1")

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import explore_class_order as P2                      # noqa: E402
from explore_principal_share import (                 # noqa: E402
    primes_upto, class_data_real, class_number_imag,
)
from explore_class_share import (                     # noqa: E402
    classes_imag, classes_real, mean,
)

MINSTRAT = 30                 # fields an iso type needs to be read
PLACEBO_SHIFTS = (1, 2, 3, 4, 5)


def lcm(a, b):
    return a * b // gcd(a, b)


def factorize(n):
    f, d = {}, 2
    while d * d <= n:
        while n % d == 0:
            f[d] = f.get(d, 0) + 1
            n //= d
        d += 1
    if n > 1:
        f[n] = f.get(n, 0) + 1
    return f


def invariant_factors(dims):
    """Canonical label: d_1 | d_2 | ... | d_m from any factor list."""
    byp = defaultdict(list)
    for d in dims:
        for p, e in factorize(d).items():
            byp[p].append(e)
    for p in byp:
        byp[p].sort(reverse=True)
    m = max((len(v) for v in byp.values()), default=0)
    out = []
    for i in range(m):
        v = 1
        for p, es in byp.items():
            if i < len(es):
                v *= p ** es[i]
        out.append(v)
    return tuple(sorted(out))


def label(inv):
    return " x ".join("Z/%d" % d for d in inv) if inv else "trivial"


def group_of(D, sign):
    """The class inventory the sweep discards: trivial class and the law."""
    if sign < 0:
        recs, triv = classes_imag(D)
        member = rt = None
    else:
        recs, member, triv, rt = classes_real(D)
    comp = P2.make_composer(D, sign, recs, member, rt, [0, 0, 0, 0])
    return recs, triv, comp


def span_of(gens, dims, triv, comp):
    """Coordinates of every class in the span of the chosen generators."""
    cur = {triv: ()}
    for g, d in zip(gens, dims):
        new = {}
        for k, c in cur.items():
            e = k
            for a in range(d):
                new[e] = c + (a,)
                e = comp(e, g)
        cur = new
    return cur


def decompose(recs, orders, hplus, triv, comp):
    """Peel off factors: the largest-order class whose span meets trivially.

    In a finite abelian group an element of maximal order generates a direct
    summand, so the greedy peel terminates at a basis; derivation (2)'s
    criterion and every reading below are basis-independent, but the peel
    failing to span is a rig failure and is counted rather than dropped.
    """
    gens, dims = [], []
    cur = {triv: ()}
    while len(cur) < hplus:
        best = None
        for k in sorted(recs):
            if orders[k] == 1:
                continue
            e, t = k, 1
            while e not in cur:
                e = comp(e, k)
                t += 1
            if t == orders[k] and (best is None or orders[k] > best[1]):
                best = (k, orders[k])
        if best is None:
            return None
        gens.append(best[0])
        dims.append(best[1])
        cur = span_of(gens, dims, triv, comp)
    return cur, tuple(dims)


def chars_of(dims):
    """Every character as a coordinate tuple, in a fixed order."""
    out = [()]
    for d in dims:
        out = [c + (j,) for c in out for j in range(d)]
    return out


def char_order(j, dims):
    o = 1
    for ji, d in zip(j, dims):
        o = lcm(o, d // gcd(ji, d))
    return o


def reachable(j, dims):
    """Derivation (2): chi_j is trivial on G[2] iff j_i even at even d_i."""
    return all(ji % 2 == 0 for ji, d in zip(j, dims) if d % 2 == 0)


def char_table(coords, chars, dims):
    """M[jx][ax] = chi_j(class a), precomputed once per field."""
    L = 1
    for d in dims:
        L = lcm(L, d)
    w = [cexp(2j * pi * t / L) for t in range(L)]
    return [[w[sum(ji * a[i] * (L // dims[i])
                   for i, ji in enumerate(j)) % L] for a in coords]
            for j in chars]


def transform(M, dev):
    return [sum(m * x for m, x in zip(row, dev)) for row in M]


def invert(M, E):
    h = len(E)
    return [(sum(E[jx] * M[jx][ax].conjugate()
                 for jx in range(h)) / h).real for ax in range(h)]


def energy_split(E, orders, reach):
    """Total energy, energy at order 2, and the two halves of it."""
    tot = q = u = r = 0.0
    nu = nr = 0
    for jx in range(1, len(E)):
        e = abs(E[jx]) ** 2
        tot += e
        if orders[jx] == 2:
            q += e
            if reach[jx]:
                r += e
                nr += 1
            else:
                u += e
                nu += 1
    return tot, q, u, nu, r, nr


def symmetrize(dev, inv_ix):
    return [(dev[a] + dev[inv_ix[a]]) / 2 for a in range(len(dev))]


def median(xs):
    s = sorted(xs)
    n = len(s)
    if n == 0:
        return float("nan")
    return s[n // 2] if n % 2 else (s[n // 2 - 1] + s[n // 2]) / 2


def centred(vec):
    m = sum(vec) / len(vec)
    return [x - m for x in vec]


def placebo(dev, D, shift, inv_ix):
    """C7: rotate values across the non-trivial classes, then re-even."""
    h = len(dev)
    n = h - 1
    start = 1 + (abs(D) + shift) % (n - 1) if n > 1 else 0
    out = [dev[0]] + [dev[1 + (i + start) % n] for i in range(n)]
    return symmetrize(out, inv_ix)


def collect(sign, plist, box):
    """Per field with h+ >= 2: coordinates, dims, deviations, controls."""
    rows, bad, idb, c2b, c4b, lawb = P2.sweep(sign, plist)
    box.append((bad, idb, c2b, c4b, lawb, len(rows)))
    out, viol = [], [0, 0, 0, 0, 0]      # span, bijection, zero, order, C8
    for D, h, recs0, orders, n0, tot0, q, _ in rows:
        if h < 2 or tot0 == 0:
            continue
        recs, triv, comp = group_of(D, sign)
        got = decompose(recs, orders, h, triv, comp)
        if got is None:
            viol[0] += 1
            continue
        coords_by_key, dims = got
        prod = 1
        for d in dims:
            prod *= d
        if prod != h or len(coords_by_key) != h:
            viol[1] += 1
            continue
        if coords_by_key[triv] != tuple(0 for _ in dims):
            viol[2] += 1
            continue
        if any(orders[k] != char_order(c, dims)
               for k, c in coords_by_key.items()):
            viol[3] += 1
            continue
        coords = sorted(coords_by_key.values())
        ix = {c: i for i, c in enumerate(coords)}
        dev = [0.0] * h
        for k, c in coords_by_key.items():
            dev[ix[c]] = P2.ratio(n0.get(k, 0), tot0, h) - 1.0
        inv_ix = [ix[tuple((-a) % d for a, d in zip(c, dims))]
                  for c in coords]
        chars = chars_of(dims)
        M = char_table(coords, chars, dims)
        cords = [char_order(j, dims) for j in chars]
        reach = [reachable(j, dims) for j in chars]
        two = [c for c in coords
               if char_order(c, dims) in (1, 2)]        # the 2-torsion
        L = LCM(dims)
        for jx, j in enumerate(chars):
            if cords[jx] != 2:
                continue
            direct = all(
                sum(ji * a[i] * (L // dims[i])
                    for i, ji in enumerate(j)) % L == 0
                for a in two)
            if direct != reach[jx]:
                viol[4] += 1
        out.append((D, h, dims, dev, inv_ix, M, cords, reach))
    return out, viol


def LCM(dims):
    L = 1
    for d in dims:
        L = lcm(L, d)
    return L


def fit_profile(fields):
    """The stratum's own mean deviation at each class ORDER (derivation 2).

    Kept as a function of the order rather than as a vector: two fields of
    one iso type can be peeled onto different bases, so the same profile
    lands on different coordinate tuples and must be rebuilt per field.
    """
    acc = defaultdict(list)
    for D, h, dims, dev, inv_ix, M, cords, reach in fields:
        for a, c in enumerate(sorted(chars_of(dims))):
            acc[char_order(c, dims)].append(dev[a])
    return {d: mean(v) for d, v in acc.items()}


def fit_vec(prof, dims):
    return centred([prof[char_order(c, dims)] for c in sorted(chars_of(dims))])


def amplitudes(Es, Ef, cords):
    """Same-data alpha, and derivation (4)'s alpha with order 2 held out."""
    num = den = hnum = hden = 0.0
    for jx in range(1, len(Es)):
        a, b = Ef[jx].real, Es[jx].real
        num += a * b
        den += a * a
        if cords[jx] != 2:
            hnum += a * b
            hden += a * a
    return (num / den if den > 0 else 0.0,
            hnum / hden if hden > 0 else 0.0)


def main():
    t0 = time.time()
    plist = primes_upto(P2.PCAP)
    print("population: |D| <= %d both signs, odd split p <= %d, bottom bin"
          " p < %d, min split %d; every field with h+ >= 2, strata are"
          " ISO TYPES needing %d fields"
          % (P2.DBOUND, P2.PCAP, P2.BIN0, P2.MIN_SPLIT, MINSTRAT))
    print("\nDERIVATION (1), which needs no run: the genus characters are"
          "\n  those trivial on Cl+^2, i.e. the chi with chi^2 = 1, i.e."
          "\n  exactly the characters of order dividing 2. Genus and"
          "\n  quadratic are the same set at every field. The split this"
          "\n  rig reads is derivation (2)'s instead: which quadratic"
          "\n  characters the order ladder's 2-torsion term can REACH.")

    pops, viols, boxes = {}, {}, {}
    for sign, name in ((+1, "real"), (-1, "imag")):
        box = []
        fields, viol = collect(sign, plist, box)
        pops[sign], viols[sign], boxes[sign] = fields, viol, box[0]
        bad, idb, c2b, c4b, lawb, nrows = box[0]
        print("\n%s: %d fields kept by the sweep, %d of them decomposed at"
              " h+ >= 2 -- a count of SURVIVORS, so it equals the count"
              " attempted only because the C5 line below reads zero"
              % (name, nrows, len(fields)))
        print("  C6 composition: disc/integrality %d | key not in inventory"
              " %d | walk overran %d | order does not divide h+ %d |"
              " identity %d | non-commuting %d | non-associative %d |"
              " order<=2 vs form-symmetry disagreements %d"
              % (bad[0], bad[1], bad[2], bad[3], idb, lawb[0], lawb[1], c2b))
        print("  C5 decomposition: greedy peel failed to span %d | factor"
              " orders do not multiply to h+ or the map is not a bijection"
              " %d | trivial class off the zero tuple %d | a class's order"
              " disagrees with its coordinates %d" % tuple(viol[:4]))
        print("  C8 reachability criterion vs direct evaluation on Cl+[2]:"
              " %d disagreements" % viol[4])

    print("\n--- C1/C2/C3/C4: THE TRANSFORM'S IDENTITIES over a PRODUCT of"
          "\n    cyclic factors. Inversion returns the measured deviations;"
          "\n    the trivial character is exactly zero by the constant sum;"
          "\n    Parseval fixes the total energy, which licenses both a"
          "\n    SHARE and derivation (4)'s inner product in the dual; and"
          "\n    the symmetrized transform is real, the inverse class being"
          "\n    the negated coordinate tuple.")
    for sign, name in ((+1, "real"), (-1, "imag")):
        w1 = w2 = w3 = w4 = 0.0
        for D, h, dims, dev, inv_ix, M, cords, reach in pops[sign]:
            E = transform(M, dev)
            w1 = max(w1, max(abs(x - y) for x, y in zip(dev, invert(M, E))))
            w2 = max(w2, abs(E[0]))
            par = sum(abs(x) ** 2 for x in E)
            ref = h * sum(x * x for x in dev)
            w3 = max(w3, abs(par - ref) / ref if ref > 0 else 0.0)
            Es = transform(M, symmetrize(dev, inv_ix))
            w4 = max(w4, max(abs(x.imag) for x in Es))
        print("  %-5s inversion %.2e | |E_0| %.2e | Parseval rel %.2e |"
              " max |Im E| symmetrized %.2e" % (name, w1, w2, w3, w4))

    # ---- The per-stratum table, and the paired mixed reading.
    print("\n--- READING A / K1, K3: THE ENERGY SHARE AT CHARACTER ORDER 2,"
          "\n    per ISO TYPE (derivation 6). OBS is the symmetrized dev,"
          "\n    FLAT the allowance |S_2|/(h+-1), FIT the transform of the"
          "\n    stratum's own order profile, RES the residual after that"
          "\n    profile, RES-a after probe 4's same-data amplitude and"
          "\n    RES-h after derivation (4)'s HELD-OUT one, PLA the placebo"
          "\n    band (C7). K3 counts the CYCLIC strata where RES-h beats"
          "\n    both FLAT and the whole band.")
    mixed_all = []
    for sign, name in ((+1, "real"), (-1, "imag")):
        by = defaultdict(list)
        for rec in pops[sign]:
            by[invariant_factors(rec[2])].append(rec)
        print("  %s:" % name)
        k3 = 0
        thin = [0, 0, 0, 0]        # thin strata, their fields; shapeless ditto
        for inv in sorted(by, key=lambda t: (len(t), t)):
            fields = by[inv]
            h = fields[0][1]
            dims0 = fields[0][2]
            chars0 = chars_of(dims0)
            co0 = [char_order(j, dims0) for j in chars0]
            if len(set(co0[1:])) < 2:
                # h+ prime or 2: every non-trivial character has one order
                # and there is no shape to read. Counted, never dropped in
                # silence -- what a table omits is part of what it says.
                thin[2] += 1
                thin[3] += len(fields)
                continue
            if len(fields) < MINSTRAT:
                thin[0] += 1
                thin[1] += len(fields)
                continue
            prof = fit_profile(fields)
            n2 = sum(1 for o in co0 if o == 2)
            obs = res = resa = resh = resas = reshs = 0.0
            amax = 0.0                      # C9
            pla = defaultdict(float)
            draws = set()
            ratios, signs, pratios, psigns = [], [], [], []
            usum = rsum = pusum = prsum = 0.0
            for D, hh, dims, dev, inv_ix, M, cords, reach in fields:
                fit = fit_vec(prof, dims)
                ds = symmetrize(dev, inv_ix)
                Es = transform(M, ds)
                Ef = transform(M, fit)
                tot, q, u, nu, r, nr = energy_split(Es, cords, reach)
                obs += q / tot if tot > 0 else 0.0
                rv = [x - y for x, y in zip(ds, fit)]
                t2, q2, _, _, _, _ = energy_split(
                    transform(M, rv), cords, reach)
                res += q2 / t2 if t2 > 0 else 0.0
                al, alh = amplitudes(Es, Ef, cords)
                amax = max(amax, abs(al - alh))
                for a, store in ((al, "a"), (alh, "h")):
                    v = [x - a * y for x, y in zip(ds, fit)]
                    tt, qq, uu, nnu, rr, nnr = energy_split(
                        transform(M, v), cords, reach)
                    # Shares divide by the RESIDUAL's own total, and the
                    # held-out fit shrinks that total by construction (it
                    # is fitted on exactly the characters in the
                    # denominator and on no others), so RES-a and RES-h are
                    # not on one scale. The starred columns divide by the
                    # PRE-residual total instead, which is the same number
                    # for both and makes the two amplitudes comparable --
                    # added at audit, the frozen columns kept beside them.
                    if store == "a":
                        resa += qq / tt if tt > 0 else 0.0
                        resas += qq / tot if tot > 0 else 0.0
                    else:
                        resh += qq / tt if tt > 0 else 0.0
                        reshs += qq / tot if tot > 0 else 0.0
                        if nu and nr:
                            pu, pr = uu / nnu, rr / nnr
                            ratios.append(pu / pr if pr > 0 else 0.0)
                            signs.append(1.0 if pu > pr else 0.0)
                            usum += pu
                            rsum += pr
                # C7 in probe 4's exact form: the rotation is applied to
                # the symmetrized dev and NOTHING is subtracted from it.
                # Rotating and THEN subtracting alpha*fit would differ from
                # the treatment in two variables, not one -- the rotation
                # destroys the alignment between the data and the fit, so
                # the same subtraction CANCELS the ladder in the treatment
                # and INJECTS it in the null, which drove the null far from
                # the exchangeable 1 the first run printed.
                for sh in PLACEBO_SHIFTS:
                    p = placebo(ds, D, sh, inv_ix)
                    draws.add(tuple(round(x, 12) for x in p))
                    tt, qq, _, _, _, _ = energy_split(
                        transform(M, p), cords, reach)
                    pla[sh] += qq / tt if tt > 0 else 0.0
                # And the paired null rotates the RESIDUAL itself, after
                # the subtraction rather than before it: that holds the
                # residual's own constant sum and destroys only which
                # class carries which value, which is what derivation (3)
                # needs and what the pre-subtraction rotation cannot give.
                if nu and nr:
                    rv2 = [x - alh * y for x, y in zip(ds, fit)]
                    for sh in PLACEBO_SHIFTS:
                        pr2 = placebo(rv2, D, sh, inv_ix)
                        _, _, uu, nnu, rr, nnr = energy_split(
                            transform(M, pr2), cords, reach)
                        if nnr and rr > 0:
                            pratios.append((uu / nnu) / (rr / nnr))
                            psigns.append(1.0 if uu / nnu > rr / nnr
                                          else 0.0)
                            pusum += uu / nnu
                            prsum += rr / nnr
            n = len(fields)
            band = [pla[sh] / n for sh in PLACEBO_SHIFTS]
            flat = n2 / (h - 1)
            Efit = transform(char_table(sorted(chars_of(dims0)),
                                        chars0, dims0),
                             fit_vec(prof, dims0))
            tf, qf, _, _, _, _ = energy_split(Efit, co0,
                                              [reachable(j, dims0)
                                               for j in chars0])
            cyc = len(inv) == 1
            # Added at audit: the held-out fit is ONE parameter against the
            # real dimension of the complement it is fitted on (conjugate
            # character pairs carrying one real dof between them), so where
            # that dimension is 1 the fit annihilates the complement and
            # RES-h is 1 by construction rather than by arithmetic.
            cdim = len({frozenset((jx, chars0.index(
                tuple((-v) % d for v, d in zip(chars0[jx], dims0)))))
                for jx in range(1, h) if co0[jx] != 2})
            print("    %-14s (%4d fields, %.2f distinct placebo draws,"
                  " %d chi of order 2, complement real dim %d, %s):" %
                  (label(inv), n, len(draws) / n, n2, cdim,
                   "cyclic" if cyc else "rank %d" % len(inv)))
            print("      OBS %.4f  FLAT %.4f  FIT %.4f  RES %.4f "
                  " RES-a %.4f  RES-h %.4f  PLA %.4f-%.4f"
                  % (obs / n, flat, qf / tf if tf > 0 else 0.0, res / n,
                     resa / n, resh / n, min(band), max(band)))
            print("      over the PRE-residual total instead, the two"
                  " amplitudes on one scale: RES-a* %.4f  RES-h* %.4f;"
                  " C9 max |alpha_held - alpha| %.4f"
                  % (resas / n, reshs / n, amax))
            if cyc and resh / n > flat and resh / n > max(band):
                k3 += 1
            if ratios:
                mixed_all.append((name, inv, ratios, signs,
                                  pratios, psigns,
                                  usum, rsum, pusum, prsum))
                print("      MIXED, K2 AS FROZEN: mean of the per-field"
                      " ratio unreachable/reachable = %.3f (placebo %.3f)"
                      % (mean(ratios),
                         mean(pratios) if pratios else float("nan")))
                print("      MIXED, ADDED AT AUDIT because that mean is"
                      " dominated by fields whose reachable energy is near"
                      " zero: ratio of MEANS %.3f (placebo %.3f), MEDIAN"
                      " ratio %.3f (placebo %.3f), unreachable larger at"
                      " %.3f of fields (placebo %.3f)"
                      % (usum / rsum if rsum > 0 else float("nan"),
                         pusum / prsum if prsum > 0 else float("nan"),
                         median(ratios), median(pratios),
                         mean(signs),
                         mean(psigns) if psigns else float("nan")))
        print("    K3: %d cyclic strata where RES-h beats FLAT and the"
              " whole band" % k3)
        print("    NOT IN THE TABLE ABOVE: %d iso types (%d fields) readable"
              " but under the %d-field floor, and %d iso types (%d fields)"
              " carrying one character order and so no shape at all"
              % (thin[0], thin[1], MINSTRAT, thin[2], thin[3]))

    print("\n--- READING B / K2: THE PAIRED MIXED READING, pooled. A group"
          "\n    carrying both kinds of quadratic character compares them"
          "\n    inside ONE field, under one class number, one amplitude"
          "\n    and one noise level (derivation 3), so a flat"
          "\n    contribution cancels and the null is 1 in expectation --"
          "\n    the rotation below supplies what it is in fact.")
    if not mixed_all:
        print("  no mixed stratum in the population")
    else:
        rr = [x for m in mixed_all for x in m[2]]
        ss = [x for m in mixed_all for x in m[3]]
        pr = [x for m in mixed_all for x in m[4]]
        ps = [x for m in mixed_all for x in m[5]]
        us = sum(m[6] for m in mixed_all)
        rs = sum(m[7] for m in mixed_all)
        pus = sum(m[8] for m in mixed_all)
        prs = sum(m[9] for m in mixed_all)
        print("  %d mixed fields over %d strata. K2 as frozen, the mean of"
              " the per-field ratio: %.3f against a placebo %.3f."
              % (len(rr), len(mixed_all), mean(rr), mean(pr)))
        print("  Added at audit: ratio of MEANS %.3f (placebo %.3f),"
              " MEDIAN ratio %.3f (placebo %.3f), unreachable larger at"
              " %.3f of fields (placebo %.3f)."
              % (us / rs if rs > 0 else float("nan"),
                 pus / prs if prs > 0 else float("nan"),
                 median(rr), median(pr), mean(ss), mean(ps)))

    print("\nwall %.1f s" % (time.time() - t0))


if __name__ == "__main__":
    main()
