"""explore_flatten_band.py -- IS THE RANK WINDOW A LAW ABOUT RANK?

explore_flatten_select.py closed 695 cells of h(M, J) -- the least
HEIGHT of a nonzero M-atom vector whose first J moments vanish, read as
the sup-norm shortest vector of the rank-(M - J) lattice (x-1)^J Z[x]
cut at degree < M -- over M = 4..40, J = 2..30, and found that h beats
the least PURE-PRODUCT height at 83 of them. Every one of the 83 sits
at lattice rank M - J between 5 and 18. Outside that window 325 cells
fail zero times, 221 of them with h >= 2 and so able to fail at all.
The window did not widen when the chart grew from 550 cells to 695.

That census answered WHICH cells fail and gave no reason for either
wall past its innermost rank, where a rank-1 lattice is generated by
(x-1)^(M-1) and the only pure product that fits is the same
polynomial, so the two bounds coincide by construction.

THE QUESTION. Is the two-sided rank window a law about the RANK -- or
is it the shadow, on a chart cut off at M = 40, of something that is
not about rank at all?

(FLATTENING, HEIGHT, PURE PRODUCT, RANK and RESIDUAL keep their earlier
senses, restated because this rig is read alone: a vector c on M atoms
is the polynomial P(x) = sum_r c_r x^r; its moments m_j = sum_r C(r,j)
c_r are its coefficients in the (x-1) basis, so the flattening -- the
least j with m_j nonzero -- IS the multiplicity of the root 1. HEIGHT
is the sup norm max_r |c_r|. A PURE PRODUCT is prod_i (x^{d_i} - 1)
over a multiset D of positive parts; it has |D| factors, degree sum D,
and flattening |D|. RANK is always r = M - J. A cell FAILS when h is
strictly below the least pure-product height ph at that cell.)

THE HAND ATTACK, worked before any engine code. Its first three steps
are on paper; the fourth was run as a SMOKE PROBE at a few dozen cells,
because the cost estimate for the census below depends on an answer it
could not get on paper, and because the probe is what turned a vague
suspicion into the frozen predictions. Everything it found is named
here as a probe reading and is re-measured by the rig at full scope.

FIRST, THE COFACTOR. Every lattice vector is q(x)(x-1)^J with deg q <
r, so the whole question is a question about q of degree at most r - 1
and h(M, J) = min over nonzero such q of height(q(x-1)^J).

The pure family lands in the same variable. A pure product with c >= J
parts and sum D <= M - 1 factors as (x-1)^c prod_i [d_i]_x, writing
[d]_x = 1 + x + ... + x^(d-1) = (x^d - 1)/(x - 1), and the parts equal
to 1 contribute nothing. So its cofactor is

    q = (x-1)^t * prod_{d in E} [d]_x,   t = c - J,

with E the multiset of parts exceeding 1, and the degree budget deg q =
sum D - J <= r - 1 reads

    t + sum_{d in E} (d - 1) <= r - 1.

THAT IS AN INSTRUMENT AND NOT ONLY A RESTATEMENT. The parent rigs price
the pure bound by enumerating multisets of parts summing to at most M -
1, which is a partition count in M and is what confines every census so
far to M <= 40. In the cofactor variable the enumeration is over
partitions of at most r - 1, which does not grow with the depth at all.
A census at fixed small rank and unbounded depth becomes free, and that
is the census this rig runs.

SECOND, WHAT THE ROOT AT -1 DOES, WHICH IS THE MECHANISM. Write s =
ord_{-1}(q). The coefficients of (x-1)^J are the alternating binomial
row, whose absolute profile is a Gaussian of width about sqrt(J)/2, and
multiplying by q convolves that row with q's coefficients read in
alternating sign. A factor (1 + x) of q is exactly a difference of the
convolved row, which for a smooth row of width sqrt(J) costs a factor
of order 1/sqrt(J) in the height. So s DIFFERENCES buy a factor of
order J^(-s/2), and to leading order in J nothing else about q matters.
The largest s available to a cofactor of degree at most r - 1 is r - 1,
attained by q = c(1 + x)^(r-1) and by nothing else, and the integer c
is best taken as +-1. So the asymptotically forced minimiser at fixed
rank is

    CHAMP(M, J) = (1 + x)^(r-1) (x-1)^J,

WHICH IS A PURE PRODUCT: it is (x^2 - 1)^(r-1) (x-1)^(J-r+1), with
(r - 1) + (J - r + 1) = J factors and degree J + r - 1 = M - 1,
available whenever J >= r - 1.

THIRD, WHAT THAT PREDICTS ABOUT THE WINDOW. The argument is asymptotic
in J at FIXED rank, so it says the pure family wins for J large enough
at every rank -- and says nothing at small J, where the Gaussian is
narrow, r - 1 differences of it are not a smooth object, and a cofactor
of lower s can win on its constant instead. If that is the whole story
then the failing set at fixed rank is bounded ABOVE in J, the bound
J_hi(r) grows with r because more differences need a wider Gaussian to
be smooth, and the chart's HIGH wall is not a wall at all: it is the
line M <= 40 crossing a rising boundary. The LOW wall would be the
mirror -- a lower boundary J_lo(r), below which the cell is clean for
the different reason that the pure family's own argmin is no longer the
champion -- and the rank window is then the set of ranks whose band
[J_lo, J_hi] meets the chart's corner.

FOURTH, THE SMOKE PROBE, and it is why the predictions below are sharp.
Run at ranks 2 to 7 over J = 20..60 and at ranks 10, 14, 19 at coarse
J, on the existing route_h: at ranks 2, 3 and 4 the exhibited minimiser
had ord_{-1} equal to r - 1 at every cell tried and h equalled CHAMP's
height; at rank 5 the ratio h/height(CHAMP) read 0.69, 0.75, 0.86, 0.92
at J = 20, 24, 28, 30 and reached exactly 1 at J = 32; at rank 6 it
reached 1 at J = 34 and at rank 7 at J = 60, with the cell clean again
at those depths and at every depth tried past them. At rank 7 the cells
at J = 20, 22, 24 were clean as well, on the low side. So the band is
real at the ranks a probe can reach, and BOTH its ends move up with the
rank. The probe also timed the corner: rank 25 at J = 70 costs about 3
s for h and half a second for ph, so the census below is minutes.

THE PROBE IS NOT THE MEASUREMENT AND THREE OF ITS READINGS ARE KNOWN
WEAK. It used height(CHAMP) as the pure bound at the ranks where it
scanned by ratio, which is an UPPER bound on ph and not ph, so its
"fails" at ranks 10, 14 and 19 are not failures and are discarded here;
the flag below is h < ph with ph the true pure minimum. It never
scanned J downward to find a low end. And it never collected a
minimiser SET, so its uniqueness readings are readings of one
enumeration's choice.

THE PREDICTIONS, fixed here before the engine ran.

P1. At every rank r in 5..22 the failing set in J is a nonempty
    INTERVAL: scanning J upward there is a first failure J_lo(r) and,
    where the sweep reaches it, a last failure J_hi(r), with every J
    between them failing and every J outside clean.
P2. J_lo(r) is nondecreasing in r over 5..22.
P3. At ranks 1, 2, 3 and 4 the failing set is EMPTY at every J swept,
    which is the low wall.
P4. At every clean cell with J > J_hi(r), h = height(CHAMP(M, J)) and
    the minimiser set at the fixed radius h*sqrt(M) is exactly the two
    vectors +-CHAMP(M, J).
P5. THE RECONCILIATION, and it is the headline the other four serve.
    The chart's rank window is DERIVABLE from the band endpoints and
    the chart's own corner: {r : [J_lo(r), J_hi(r)] meets [2, min(30,
    40 - r)]} equals {5, ..., 18} exactly. Both walls come out of one
    structure and neither is a fact about rank.

THE KILLS, frozen as OBSERVABLES the rig prints, never as inferences.

K-A NON-INTERVAL. At some rank the printed failure flags read failing,
    then clean, then failing again as J rises. P1 dies.
K-B INSTRUMENT. The cofactor pure bound disagrees with the parent's
    multiset pure bound at any of the 695 answer-key cells.
K-C ORDER. h > ph at any cell, ph being the height of an exhibited
    lattice vector and so an upper bound on h by construction.
K-D ANSWER KEY. The failure flag over the parent's rectangle does not
    reproduce its committed 83 failures at the same 83 cells, or its
    committed rank window 5..18.
K-E CHAMPION. A clean cell above its rank's last failure whose
    minimiser set is anything but +-CHAMP. P4 dies.
K-F RECONCILIATION. The window derived in P5 differs from 5..18.
K-G MONOTONE. J_lo falls as the rank rises anywhere in 5..22. P2 dies.
K-H LOW WALL. A failing cell at rank 1, 2, 3 or 4. P3 dies.

THE POSITIVE CONTROLS, run before any survive/kill result is read.
C1 the cofactor pure bound against the parent's multiset bound at every
answer-key cell of rank at most CTRL_RANK. THE RESTRICTION IS THE
INSTRUMENT'S OWN MEMORY AND IS NOT A CHOICE: the cofactor list at rank
38 -- the parent rectangle's widest -- runs to a few hundred thousand
polynomials and a first run of this rig was killed by memwatch at 523
MB building it. The bound is controlled exactly over the ranks the
sweep below USES and nowhere else, and the answer key is read with the
parent's own instrument instead. C2 h against the parent's three
committed values. C3 the champion's identity as a pure product, by the
polynomial identity and by the part accounting, at every rank swept.
C4 the failure flag over the parent's whole rectangle -- with the
MULTISET bound, so that the key is reproduced by the established
instrument and not by the new one -- against its committed 83 failures
and its committed window (K-D). C5 arms A and B measure the same first
failing depth by different scans -- one stopping at it, one running
past it -- and are checked against each other at every rank they share
(K-B).

THE SWEEP, and it is two arms because the two ends cost differently.
ARM A, the low end and the walls: ranks 1..22, scanning J upward from 2
and STOPPING at the first failure, which is all J_lo needs; ranks 1..4
scan the whole range to J = 45 instead, since P3 is a claim of absence
and only a completed scan can carry it. ARM B, the high end: ranks 2..8
scanning J upward past the first failure to the last, declared found
only after CLEAR_RUN consecutive depths at which the CHAMPION ATTAINS h
-- not merely CLEAR_RUN clean depths, which is the weaker rule a first
run of this rig used and which arm C2 caught declaring a crossing at
rank 8 that four cells above it contradicted: a cell can be clean
because some OTHER pure product is the minimiser, and that state is
transient where the champion's is the one the mechanism predicts is
permanent. Two thresholds are therefore reported per rank and they are
different measurements: J_hi, the last failing depth, and J_ch, the
depth from which the champion attains h. It remains a stopping RULE and
not a proof -- the claim it supports holds within the swept range and
no further. ARM C, the minimiser sets at ranks 2..4 at
EVERY depth from r - 1 to 30 and not only above each rank's crossover
-- the whole column is collected because what the crossover does to the
SET is part of the question, and only the KILL is scoped to the cells
where the champion attains h at all, P4 saying nothing where it does
not. ARM D, the reconciliation.

COST. Single process, exact integer and rational arithmetic throughout,
no array library, memory a few megabytes. The probe's timings put the
whole rig in the low minutes, well inside the ordinary analysis
footprint.

THE FINDINGS.

F1. THE RANK WINDOW IS NOT A LAW ABOUT RANK, AND P5 HOLDS EXACTLY. The set of
ranks that can fail, derived from the measured first-failure depths and the
chart's own corner alone as {r : J_lo(r) <= min(30, 40 - r)}, is {5, 6, ...,
18}. The census's own failing ranks are {5, 6, ..., 18}. They agree rank for
rank. AND WHERE THAT AGREEMENT IS EVIDENCE HAS TO BE SAID, BECAUSE INSIDE THE
WINDOW IT IS NOT: for a rank between 5 and 18, "its first failing depth sits on
the chart" and "it fails on the chart" are one sentence, so the comparison
restates a fact there and checks the plumbing. THE CONTENT IS AT THE RANKS THE
WINDOW EXCLUDES -- which is to say it is F2 and F3, the two walls, and they
turn out to be different things. What arm D adds over them is that nothing ELSE
is needed: the corner and each rank's own first failing depth reproduce the
census's rank set with no further input, so the two-sided window is the line M
<= 40 crossing a per-rank depth threshold and neither wall is a fact about the
rank. WHAT CARRIES THE DERIVATION IS 22 OF THE CHART'S 38 RANKS AND NOT ALL OF
THEM: arm A scans ranks 1 to 22: the whole of the low wall, every failing rank,
and the first four ranks of the high wall, 19 to 22 -- not the whole of that
wall, which runs to 38. At ranks 23 to 38
the chart's own depths are J <= 40 - r <= 17, all inside the parent rectangle,
so C4's completed scan decides them -- that is the census itself and not an
independent measurement, and their exclusion from the window is therefore
inherited rather than derived. Scanning their columns past the corner would
need cells at rank 38 and depth beyond 30, which is where this instrument is
dearest.

F2. THE LOW WALL IS A REAL ABSENCE AND IT IS WIDER THAN THE CHART. P3
holds without qualification: at ranks 1, 2, 3 and 4 the failure flag is
clean at EVERY depth from 2 to 45, a completed scan reaching M = 49 and
so past the chart's own M = 40 at all four. K-H never fired. At these
ranks the pure family is extremal outright over the scanned range and
not merely inside the census's corner.

F3. THE HIGH WALL IS A CORNER EFFECT AND IS NOT A WALL AT ALL. Rank 19
fails first at J = 26, rank 20 at J = 23, rank 21 at J = 25 and rank 22
at J = 30 -- cells at M = 45, 43, 46 and 52. Every rank the census
called clean above its window fails, and fails just outside the corner:
a rank-19 cell on that chart has J at most 40 - 19 = 21, five short of
where the failures start. "Rank 19 and above never fails" was a true
statement about a chart and a false one about the lattice.

F4. THE MECHANISM IS THE ROOT AT -1, AND IT NAMES A CLOSED FORM FOR h.
The champion (1+x)^(r-1) (x-1)^J -- the unique cofactor of maximal
vanishing order at -1, and the pure product (x^2-1)^(r-1)
(x-1)^(J-r+1) -- attains h from a per-rank depth up, at every depth
past it the sweep reached, so h has a closed form there with no search
of any kind. THE SWEEP IS WHAT BOUNDS THAT: eight depths past the
threshold at ranks 5 to 8 and every depth to 140 at ranks 2, 3 and 4,
which is a stopping rule and not a proof that it never reverses.
At ranks 5, 6, 7 and 8
that depth is J_ch = 31, 34, 59 and 61, and at ALL FOUR

    J_ch = J_hi + 1,

the depth the champion takes over being exactly the depth after the
last failure. Those are two independently measured thresholds -- one
read off a comparison with the whole pure family, one off a single
closed-form polynomial -- and they coincide at every rank where both
were reached. And the second threshold is confirmed OUT OF SAMPLE: arm
C2 re-reads h at the four depths PAST the run each rank's stopping rule
consumed, and the champion attains it at all 16.

F5. P1 IS REFUTED: THE FAILING SET IS CONTAINED IN A BAND BUT IS NOT
ALL OF IT. K-A fired at three of the four ranks whose high end the
sweep reached. Rank 6 is clean at J = 23 inside [22, 33]; rank 7 at 55
and 57 inside [26, 58]; rank 8 at seven depths -- 20, 25, 27, 28, 29,
30, 31 -- inside [19, 60]. Rank 5 alone is a clean interval, 13 for 13.
The holes cluster at the ENDS rather than the middle, which is what a
threshold phenomenon with a rough boundary looks like and not what an
interval law looks like. What survives is the CONTAINMENT, and the
containment is all F1 uses.

F6. P2 IS REFUTED: THE LOW BOUNDARY IS RAGGED. J_lo falls with rising
rank seven times over 5..22 -- 26 to 19 at rank 8, 19 to 12 at 9, 24 to
14 at 11, 15 to 10 at 13, 19 to 17 at 15, 23 to 19 at 17, 26 to 23 at
20 -- so "the wall rises with the rank" is too smooth a story for what
is there. THE RECONCILIATION NEVER NEEDED MONOTONICITY, only each
rank's own comparison against the corner, which is why F1 survives P2's
death intact. What the raggedness does cost is any hope of reading
J_lo(r) off a formula on this evidence.

F7. P4 HOLDS ABOVE EACH RANK'S THRESHOLD AND FAILS BELOW IT. Of the 86
collected cells at ranks 2, 3 and 4, sixty-nine carry exactly TWO
minimisers at the fixed radius and both are +-CHAMP: every cell from J
= 2 at rank 2, from J = 9 at rank 3 and from J = 13 at rank 4. Below
those depths the set is larger -- eight minimisers at rank 3, J = 3,
carrying three different vanishing orders at -1 -- and K-E fired at the
five cells there where the champion ties h without being the whole set.
So the minimiser is unique up to sign exactly where the mechanism says
it is forced, and the ord_{-1} readings above each threshold are 1, 2
and 3 at ranks 2, 3 and 4: r - 1 at every one, which is the mechanism's
own signature read directly off the answer.

F8. THE COFACTOR BOUND IS THE INSTRUMENT THAT MADE THE CENSUS POSSIBLE.
It agrees with the parent's multiset bound at all 604 answer-key cells
of rank at most 25, and it is priced by partitions of r - 1 rather than
of M - 1, so its cost does not grow with the depth at all. That is what
lets this rig decide cells out to M = 144 -- rank 4 at depth 140, the
widest cell the sweep actually reaches, the deeper ranks stopping at
their own crossings long before the depth ceiling -- when every census
before it stopped at 40. The whole rig closes in 71 s at a 64 MB peak.

THE RUN RECORD. THREE full runs. The FIRST was KILLED by memwatch at
523 MB inside its first control: the cofactor list at rank 38 -- the
parent rectangle's widest, and a rank this rig's own sweep never
reaches -- runs to a few hundred thousand polynomials. The control was
narrowed to the ranks the sweep uses and the answer key moved onto the
parent's own instrument, which is where both belong; no science had
printed. The SECOND ran clean and is superseded on ONE reading: it
declared the last failure at rank 8 to be J = 26 on a stopping rule of
four consecutive CLEAN depths, and its own arm C2 immediately
contradicted that by finding the champion short of h at all four of
them. The rule was wrong rather than the cell: a cell can be clean
because some other pure product wins, which is transient, where the
champion's win is the state the mechanism predicts is permanent. Under
the corrected rule rank 8's last failure is J = 60, thirty-four depths
further out, and its seven interior clean depths are F5's holes. Every
other value in the second run reproduces in the THIRD exactly. A FOURTH
and a FIFTH run followed the audit and reproduce every value of the
third. It
carries two fixes that no result moved on, both found by re-smoking
after the stopping rule changed. Arm C2 had become a TAUTOLOGY: the
rule it exists to check is now "the champion attains h for four
depths", and the arm was re-reading those same four, so it could not
fail; it now starts four depths further out and is out of sample. And
arm B was reading arm A's first failing depth rather than its own,
which made its hole count depend on another arm's ceiling and print
zero holes where the honest answer is that it cannot say -- it measures
its own now, and the two arms checking each other is C5. A SIXTH run
carries two more, again with no value moved. C4 was printing C1's
restricted cell count, 604, as its own denominator: it scans all 695 of
the rectangle and reported "83 failures at 604 cells", a right numerator
over a wrong denominator, and the count it should have been checking --
that it scanned the whole rectangle at all -- was checked by nothing. It
counts its own cells now and K-D reads that too. And arm A was carrying
a per-rank list of clean depths that nothing ever read. A SEVENTH run
carries an OFF-BY-ONE in the cofactor bound itself, found by tracing
the convolution's index range by hand rather than by any output: q has
nq coefficients and (x-1)^J has J + 1, so the product has nq + J, and
the loop ran to nq + J - 1 and dropped the leading one. It changed
nothing and could not have -- every cofactor this family builds is a
product of (x-1) and [d]_x factors, all monic, so the dropped value is
always 1 while the running maximum is at least the constant term, also
+-1. That is a property of the family and not of the routine, and the
enriched multipliers A, B and C are exactly the non-monic cofactors it
would have broken on. The seventh run's output diffs against the sixth
at three lines, two timings and the memory peak; every scientific value
is identical. An EIGHTH run adds arm D's own split -- 14 of the 22
scanned ranks inside the window where the comparison restates a fact,
against the 8 outside it that carry the evidence -- printed because F1
had claimed a rank-for-rank agreement without saying that fourteen of
those ranks agree by construction. Nothing else moved. The fifth run
carries one more, and it moved no value either: arm D was deriving the
window by iterating the ranks this rig SWEEPS, so ranks 23 to 38 were
excluded from the derived set by a loop bound rather than by anything
measured, and the result was reported as a derivation. It now ranges
over every rank the chart has and prints which ranks its own scan
decides and which the census does -- 22 against 16. Before
all three, a SMOKE RUN at ranks 1..6 and J <= 12 exercised every arm
and found two faults no full run would have shown: a control passed a
POLYNOMIAL to a routine that takes a cyclotomic index multiset, which
hung rather than erring, and arm C's kill was scoped to every depth it
scanned while the prediction it tests speaks only where the champion
attains h at all -- so it fired at seven cells that refute nothing. The
first is replaced by the polynomial identity and the part accounting;
the second is scoped to h == height(CHAMP) and the kill list gained the
letter K-H, which P3's death had had no observable of its own. Both
were fixed before any science printed. Single process, exact arithmetic
throughout, peak 64 MB against the 512 MB ceiling, wall 71 s.
"""
import os

os.environ.setdefault("OPENBLAS_NUM_THREADS", "1")

import sys
import time
from fractions import Fraction as F

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from explore_flatten_offchart import NodeCap
from explore_flatten_lattice import basis
from explore_flatten_family import (route_h, lll_incr, enum_ball,
                                    split_witness, family_tables,
                                    family_bound)

# The parent chart, which is this rig's answer key and nothing else.
KEY_M = 40
KEY_J = 30
KEY_CELLS = 695
KEY_FAILURES = 83
KEY_WINDOW = (5, 18)
KEY_VALUES = {(21, 12): (39, (1,) * 9 + (2, 2, 3)),
              (23, 10): (9, (1,) * 6 + (2, 2, 3, 5)),
              (25, 12): (25, (1,) * 8 + (2, 2, 3, 5))}

# The rank ceiling for the cofactor bound. See C1: above this the
# cofactor list stops fitting in the memory ceiling, and the sweep
# below never goes there.
CTRL_RANK = 25
# ARM A: every rank whose wall this rig is asked about, and the depth
# ceiling a scan for the LOW end is allowed before it reports nothing.
LOW_RANKS = range(1, 23)
LOW_JCAP = 45
# ARM B: the ranks whose HIGH end is reachable, and the stopping rule.
HIGH_RANKS = range(2, 9)
HIGH_JCAP = 140
CLEAR_RUN = 4
# ARM C: the ranks the minimiser set is collected at, and its budget.
SET_RANKS = range(2, 5)
SET_JCAP = 30
SET_CAP = 20000000


# ------------------------------------------ the polynomial instruments

def mulp(a, b):
    """Product of integer polynomials, low degree first."""
    r = [0] * (len(a) + len(b) - 1)
    for i, c in enumerate(a):
        if c:
            for j, d in enumerate(b):
                r[i + j] += c * d
    return r


def xm1_pow(J):
    """(x - 1)^J, low degree first."""
    p = [1]
    for _ in range(J):
        p = mulp(p, [-1, 1])
    return p


def champ(r, J):
    """CHAMP = (1 + x)^(r-1) (x-1)^J, the asymptotically forced
    cofactor times the flattening factor. None when J < r - 1, where
    the pure product it stands for has too few factors to exist."""
    if J < r - 1:
        return None
    p = [1]
    for _ in range(r - 1):
        p = mulp(p, [1, 1])
    return mulp(p, xm1_pow(J))


def cofactors(r):
    """Every pure-product cofactor of degree at most r - 1: q =
    (x-1)^t prod_{d in E} [d]_x with t + sum_{d in E} (d - 1) <= r - 1.
    The CHAMPION is placed first so that the early abort in ph_cof
    starts from a good bound rather than from an arbitrary one."""
    out = []

    def rec(start, e, poly):
        t, q = 0, poly
        while t + e <= r - 1:
            out.append(q)
            q = mulp(q, [-1, 1])
            t += 1
        for d in range(start, r + 1):
            if e + d - 1 > r - 1:
                break
            rec(d, e + d - 1, mulp(poly, [1] * d))

    rec(2, 0, [1])
    ch = [1]
    for _ in range(r - 1):
        ch = mulp(ch, [1, 1])
    out.sort(key=lambda q: q != ch)
    return out


COF = {}


def ph_cof(M, J, xm1):
    """The least pure-product height at the cell, computed in the
    cofactor variable. The inner loop builds the convolution one
    coefficient at a time and ABORTS as soon as the running maximum
    reaches the best height so far, which is what makes the sweep
    affordable: nearly every candidate dies within a few
    coefficients. Returns (height, witness cofactor)."""
    r = M - J
    if r not in COF:
        COF[r] = cofactors(r)
    best, wit = None, None
    for q in COF[r]:
        nq = len(q)
        mx = 0
        ok = True
        # q has nq coefficients and (x-1)^J has J + 1, so the product
        # has nq + J of them and the LAST index is nq + J - 1. An
        # earlier draft stopped the range one short and dropped that
        # leading coefficient. It changed no answer here and could not
        # have: every cofactor this family builds is a product of
        # (x-1) and [d]_x factors, all MONIC, so the dropped value is
        # always 1, while mx is at least the constant term, also +-1.
        # That is a property of the family and not of the routine, and
        # a non-monic cofactor -- which is exactly what the enriched
        # multipliers A, B and C are -- would have broken it silently.
        for k in range(nq + J):
            lo = max(0, k - J)
            hi = min(nq - 1, k)
            s = 0
            for i in range(lo, hi + 1):
                c = q[i]
                if c:
                    s += c * xm1[k - i]
            a = -s if s < 0 else s
            if a > mx:
                mx = a
                if best is not None and mx >= best:
                    ok = False
                    break
        if ok and (best is None or mx < best):
            best, wit = mx, q
    return best, wit


def ordm1(p):
    """Multiplicity of -1 as a root of an integer polynomial, after its
    monomial factor is stripped. Synthetic division at -1, exact."""
    p = list(p)
    while len(p) > 1 and p[-1] == 0:
        p.pop()
    while len(p) > 1 and p[0] == 0:
        p.pop(0)
    n = 0
    while len(p) > 1:
        out, acc = [], 0
        for c in reversed(p):
            acc = c + acc * (-1)
            out.append(acc)
        if out[-1] != 0:
            break
        p = list(reversed(out[:-1]))
        n += 1
    return n


def height(p):
    return max(abs(c) for c in p)


def same_up_to_sign(u, v):
    """Two integer vectors equal, or negatives of each other, after
    trailing zeros are dropped."""
    a, b = list(u), list(v)
    while len(a) > 1 and a[-1] == 0:
        a.pop()
    while len(b) > 1 and b[-1] == 0:
        b.pop()
    return a == b or a == [-c for c in b]


def cell(M, J, xm1):
    """One cell: h with its witness, the pure bound, the failure flag.
    ph is the height of an exhibited lattice vector, so h <= ph holds
    by construction and a violation is K-C."""
    h, v, nodes, _ = route_h(M, J)
    ph, pw = ph_cof(M, J, xm1)
    return h, v, nodes, ph, pw


def main():
    t_all = time.time()
    fired = dict(("K-" + c, 0) for c in "ABCDEFGH")

    print("=" * 70)
    print("explore_flatten_band.py -- is the rank window a law about rank?")
    print("=" * 70)

    # ------------------------------------------- C1, C2: the instruments
    print("\n[C1] the cofactor pure bound against the parent's multiset "
          "bound, over the parent's %d answer-key cells" % KEY_CELLS)
    t = time.time()
    ptab, _ = family_tables(KEY_M - 1, [1])
    mism = ncells = nkey = 0
    KEYPH = {}
    for M in range(4, KEY_M + 1):
        for J in range(2, min(KEY_J, M - 1) + 1):
            a = family_bound(ptab, J, M - 1)[0]
            KEYPH[(M, J)] = a
            nkey += 1
            if M - J > CTRL_RANK:
                continue
            b, _ = ph_cof(M, J, xm1_pow(J))
            ncells += 1
            if a != b:
                mism += 1
                fired["K-B"] += 1
                if mism <= 6:
                    print("   K-B M=%d J=%d r=%d multiset %s cofactor %s"
                          % (M, J, M - J, a, b))
    print("   %d of the %d answer-key cells are at rank <= %d; %d "
          "compared, %d mismatches (%.1f s)"
          % (ncells, nkey, CTRL_RANK, ncells, mism, time.time() - t))

    print("\n[C2] h at the parent's three committed cells")
    bad2 = 0
    for (M, J), (wh, wD) in sorted(KEY_VALUES.items()):
        h, v, _, _ = route_h(M, J)
        _, _, res = split_witness(v)
        if h != wh:
            bad2 += 1
            fired["K-D"] += 1
            print("   K-D M=%d J=%d: h=%d want %d" % (M, J, h, wh))
    print("   %d cells, %d wrong; the committed multisets are %s"
          % (len(KEY_VALUES), bad2,
             [list(d) for (_, d) in sorted(KEY_VALUES.values())]))

    print("\n[C3] the champion is a pure product, by exact division")
    bad3 = ntried = 0
    for r in list(LOW_RANKS) + list(HIGH_RANKS):
        for J in (max(2, r - 1), max(2, r - 1) + 7):
            c = champ(r, J)
            if c is None:
                continue
            ntried += 1
            # (x^2-1)^(r-1) (x-1)^(J-r+1) is the claimed factorisation
            want = [1]
            for _ in range(r - 1):
                want = mulp(want, [-1, 0, 1])
            want = mulp(want, xm1_pow(J - r + 1))
            if want != c:
                bad3 += 1
                fired["K-E"] += 1
                print("   K-E champion factorisation wrong at r=%d J=%d"
                      % (r, J))
            # and the part multiset that identity names, checked as a
            # pure product's accounting rather than as a factorisation
            # search: J parts and degree M - 1, which is what makes it
            # an admissible member of the family at this cell.
            D = [2] * (r - 1) + [1] * (J - r + 1)
            if len(D) != J or sum(D) != J + r - 1:
                bad3 += 1
                fired["K-E"] += 1
                print("   K-E champion's parts do not fit at r=%d J=%d: "
                      "%d parts of degree sum %d" % (r, J, len(D), sum(D)))
    print("   %d champions checked, %d wrong" % (ntried, bad3))

    print("\n[C4] the failure flag over the parent's rectangle against "
          "its committed record")
    t = time.time()
    fails = []
    scanned = 0
    for M in range(4, KEY_M + 1):
        for J in range(2, min(KEY_J, M - 1) + 1):
            scanned += 1
            h, _, _, _ = route_h(M, J)
            if h > KEYPH[(M, J)]:
                fired["K-C"] += 1
                print("   K-C h above the pure bound at M=%d J=%d" % (M, J))
            if h < KEYPH[(M, J)]:
                fails.append((M, J))
    ranks = sorted(set(M - J for (M, J) in fails))
    win = (min(ranks), max(ranks)) if ranks else None
    print("   %d failures over %d cells scanned (want %d over %d); "
          "rank window %s (want %s) in %.1f s"
          % (len(fails), scanned, KEY_FAILURES, KEY_CELLS, win,
             KEY_WINDOW, time.time() - t))
    if (len(fails) != KEY_FAILURES or win != KEY_WINDOW
            or scanned != KEY_CELLS):
        fired["K-D"] += 1
        print("   K-D the answer key is not reproduced")
    print("   KILLS after the controls: %s" % fired)

    # ------------------------------------ arm A: the low end, every rank
    print("\n[arm A] the LOW end -- scan J upward to the first failure, "
          "ranks %d..%d" % (LOW_RANKS[0], LOW_RANKS[-1]))
    t = time.time()
    JLO = {}
    for r in LOW_RANKS:
        full = r <= 4
        first = None
        for J in range(2, LOW_JCAP + 1):
            M = J + r
            xm1 = xm1_pow(J)
            h, v, nodes, ph, pw = cell(M, J, xm1)
            if h > ph:
                fired["K-C"] += 1
                print("   K-C h above ph at M=%d J=%d" % (M, J))
            if h < ph:
                if first is None:
                    first = J
                if full:
                    fired["K-H"] += 1
                    print("   K-H FAILURE at rank %d, J=%d (P3 says none)"
                          % (r, J))
                    first = J
                    break
            if first is not None and not full:
                break
        JLO[r] = first
        print("   rank %2d: first failure at J = %s%s"
              % (r, first if first is not None
                 else "none up to %d" % LOW_JCAP,
                 "   (scanned J = 2..%d whole)" % LOW_JCAP if full else ""))
    print("   arm A in %.1f s" % (time.time() - t))

    prev = None
    for r in LOW_RANKS:
        if JLO[r] is None:
            continue
        if prev is not None and JLO[r] < prev:
            fired["K-G"] += 1
            print("   K-G J_lo falls at rank %d: %d after %d"
                  % (r, JLO[r], prev))
        prev = JLO[r]

    # --------------------------------- arm B: the high end where it fits
    print("\n[arm B] the HIGH end -- scan past the first failure to the "
          "last, ranks %d..%d, declared after %d clean depths"
          % (HIGH_RANKS[0], HIGH_RANKS[-1], CLEAR_RUN))
    t = time.time()
    JHI, JCH, FLAGS = {}, {}, {}
    for r in HIGH_RANKS:
        flags = {}
        run = 0
        last = None
        first_ch = None
        seen = False
        for J in range(2, HIGH_JCAP + 1):
            M = J + r
            xm1 = xm1_pow(J)
            h, v, nodes, ph, pw = cell(M, J, xm1)
            bad = h < ph
            flags[J] = bad
            if bad:
                seen, last = True, J
            c = champ(r, J)
            if c is not None and h == height(c):
                if run == 0:
                    first_ch = J
                run += 1
            else:
                run, first_ch = 0, None
            if seen and run >= CLEAR_RUN:
                break
        done = seen and run >= CLEAR_RUN
        JHI[r] = last if done else None
        JCH[r] = first_ch if done else None
        FLAGS[r] = flags
        # K-A: the flags must read clean*, failing*, clean* and no more
        Js = sorted(flags)
        runs = []
        for J in Js:
            if not runs or runs[-1][0] != flags[J]:
                runs.append([flags[J], 1])
            else:
                runs[-1][1] += 1
        blocks = [b for (b, _) in runs]
        if blocks.count(True) > 1:
            fired["K-A"] += 1
            print("   K-A rank %d: failure flag is not an interval, "
                  "blocks %s" % (r, runs))
        # THIS ARM MEASURES ITS OWN LOW END rather than borrowing arm
        # A's. Borrowing made the hole count depend on a cap belonging
        # to a different arm: where arm A stops before the first
        # failure its J_lo is None and the hole count silently prints
        # 0 instead of refusing to answer. Measured here the two arms
        # become an independent CHECK on each other at every rank they
        # share, which is what K-B now reads.
        failing = [J for J in Js if flags[J]]
        lo_b = min(failing) if failing else None
        if (JLO.get(r) is not None and lo_b is not None
                and JLO[r] != lo_b):
            fired["K-B"] += 1
            print("   K-B rank %d: arm A's first failure is J=%d, arm "
                  "B's is J=%d" % (r, JLO[r], lo_b))
        print("   rank %2d: failing J = %s..%s, champion from J = %s, "
              "scanned to J = %d, %d failing of %d"
              % (r, lo_b, JHI[r], JCH[r], max(Js), len(failing), len(Js)))
        if lo_b is None or JHI[r] is None:
            print("      clean depths strictly inside the band: not "
                  "answerable, the band has no two ends here")
        else:
            holes = [J for J in Js
                     if lo_b < J < JHI[r] and not flags[J]]
            print("      clean depths strictly inside the band: %d %s"
                  % (len(holes), holes))
    print("   arm B in %.1f s" % (time.time() - t))

    print("\n   the band, rank by rank")
    print("      rank |  J_lo  |  J_hi  |  J_ch  |  span")
    for r in sorted(set(list(LOW_RANKS) + list(HIGH_RANKS))):
        lo = JLO.get(r)
        hi = JHI.get(r)
        w = (hi - lo + 1) if (lo is not None and hi is not None) else None
        print("      %4d | %6s | %6s | %6s | %5s"
              % (r, lo, hi, JCH.get(r), w))

    # ------------------------- arm C: the minimiser set above the band
    print("\n[arm C] the minimiser SET at the fixed radius h*sqrt(M), "
          "ranks %d..%d" % (SET_RANKS[0], SET_RANKS[-1]))
    t = time.time()
    setrows = []
    for r in SET_RANKS:
        for J in range(max(2, r - 1), SET_JCAP + 1):
            M = J + r
            B, T, mu, A = lll_incr(basis(M, J))
            h, v, _, _ = route_h(M, J)
            got = []
            try:
                enum_ball(B, mu, A, M, F(h * h * M), SET_CAP, collect=got)
            except NodeCap:
                setrows.append((r, J, h, None, None, None))
                continue
            mins = [w for w in got if height(w) == h]
            c = champ(r, J)
            allc = all(same_up_to_sign(w, c) for w in mins)
            setrows.append((r, J, h, len(mins),
                            sorted(set(ordm1(w) for w in mins)), allc))
            # P4 SPEAKS ONLY WHERE THE CHAMPION IS A MINIMISER AT ALL.
            # The scan starts at J = r - 1 and so walks depths where h
            # is strictly below the champion's height; there the
            # champion is not in the set and its absence is the band,
            # not a refutation. The kill is scoped to h == that height,
            # which is exactly the clean-above-the-band regime P4 names.
            if h == height(c) and (not allc or len(mins) != 2):
                fired["K-E"] += 1
                print("   K-E rank %d J=%d: %d minimisers, all champion "
                      "%s" % (r, J, len(mins), allc))
    ok = [row for row in setrows if row[3] == 2 and row[5]]
    print("   %d cells collected, %d with exactly two minimisers both "
          "+-CHAMP" % (len(setrows), len(ok)))
    for row in setrows:
        print("      rank %d J=%2d h=%-10s |min|=%-3s ord_{-1}=%-10s "
              "all champion %s"
              % (row[0], row[1], row[2], row[3], row[4], row[5]))
    orders = sorted(set((row[0], tuple(row[4])) for row in setrows
                        if row[4] is not None))
    print("   ord_{-1} of the minimisers by rank: %s" % orders)
    print("   arm C in %.1f s" % (time.time() - t))

    # ------------------------ arm C2: the closed form above the crossing
    print("\n[arm C2] h against the champion's height at the %d depths "
          "PAST the run each rank's stopping rule consumed" % CLEAR_RUN)
    n2 = bad = 0
    for r in HIGH_RANKS:
        hi = JCH.get(r)
        if hi is None:
            continue
        # OUT OF SAMPLE, AND THAT IS THE POINT. Arm B's stopping rule
        # is itself "the champion attains h for CLEAR_RUN depths", so
        # re-testing those same depths is a tautology that cannot
        # fail -- which is what this arm silently became when that
        # rule was tightened. It starts CLEAR_RUN depths PAST the run
        # the rule consumed, and is the only thing here that could
        # catch a crossing declared too early.
        for J in range(hi + CLEAR_RUN, hi + 2 * CLEAR_RUN):
            M = J + r
            h, _, _, _ = route_h(M, J)
            c = height(champ(r, J))
            n2 += 1
            if h != c:
                bad += 1
                fired["K-E"] += 1
                print("   K-E rank %d J=%d: h=%d champion height=%d"
                      % (r, J, h, c))
    print("   %d cells out of sample, %d where h is not the champion's "
          "height" % (n2, bad))

    # ------------------------------------- arm D: the reconciliation
    print("\n[arm D] the reconciliation -- the chart's rank window "
          "derived from the band and the chart's own corner M <= %d, "
          "J <= %d" % (KEY_M, KEY_J))
    # THE DERIVATION MUST RANGE OVER EVERY RANK THE CHART HAS, NOT OVER
    # THE ONES THIS RIG SWEEPS. The chart reaches rank 38 and arm A
    # scans to 22. Iterating the swept ranks alone EXCLUDES 23..38 by
    # the loop bound and then reports the result as a derived set,
    # which is an artefact dressed as a finding. They are carried here
    # explicitly, and what carries them is named: for a rank above the
    # sweep the chart's own depths are J <= 40 - r <= 17, all inside
    # the parent rectangle, so C4's completed scan of that rectangle
    # decides them -- which is the CENSUS, not an independent
    # measurement, and the print says exactly that.
    chart_ranks = [r for r in range(1, KEY_M - 1)
                   if min(KEY_J, KEY_M - r) >= 2]
    derived, by_census = [], []
    for r in chart_ranks:
        top = min(KEY_J, KEY_M - r)
        if r in LOW_RANKS:
            lo = JLO.get(r)
            if lo is not None and lo <= top:
                derived.append(r)
        else:
            by_census.append(r)
            if any(M - J == r for (M, J) in fails):
                derived.append(r)
    print("   ranks whose band reaches the chart: %s" % derived)
    print("   of the %d chart ranks, %d are decided by this rig's own "
          "scan of their columns and %d only by the census C4 re-ran "
          "-- ranks %d..%d, whose chart depths all sit inside that "
          "rectangle, so the window's exclusion of them is the census "
          "and not an independent measurement"
          % (len(chart_ranks), len(chart_ranks) - len(by_census),
             len(by_census), min(by_census), max(by_census)))
    got = (min(derived), max(derived)) if derived else None
    print("   derived window %s against the census's %s"
          % (got, KEY_WINDOW))
    # AND WHERE THE AGREEMENT IS EVIDENCE AND WHERE IT IS A TAUTOLOGY.
    # For a rank INSIDE the window, "J_lo(r) <= min(30, 40 - r)" says
    # the rank's first failure sits on the chart, which is the same
    # sentence as "this rank fails on the chart". The two sides of the
    # comparison are one fact there and the agreement is bookkeeping.
    # The CONTENT is at the ranks the window excludes: those that fail
    # only past the corner, and those that fail at no depth scanned.
    lo_side = [r for r in LOW_RANKS
               if JLO.get(r) is None and r not in derived]
    hi_side = [r for r in LOW_RANKS
               if JLO.get(r) is not None and r not in derived]
    print("   of the %d ranks this rig scans, %d are inside the window, "
          "where the comparison restates one fact and is a check on the "
          "plumbing rather than evidence"
          % (len([r for r in LOW_RANKS]), len(derived)))
    print("   the evidence is the %d excluded ranks it scanned: %s fail "
          "at NO depth to %d, and %s fail first at %s -- past the "
          "corner, which is why the census never saw it"
          % (len(lo_side) + len(hi_side), lo_side, LOW_JCAP, hi_side,
             [JLO[r] for r in hi_side]))
    if got != KEY_WINDOW:
        fired["K-F"] += 1
        print("   K-F the derived window is not the census's")
    inchart = sorted(set(M - J for (M, J) in fails))
    print("   and the census's own failing ranks are %s" % inchart)
    if derived != inchart:
        fired["K-F"] += 1
        print("   K-F the derived rank SET is not the census's rank set")

    print("\nKILLS: %s" % fired)
    print("wall %.1f s" % (time.time() - t_all))


if __name__ == "__main__":
    main()
