"""
THE RANK FACE -- is Dirichlet's S-unit rank the deleted budget read in
ranks?

The deleted-budget law (explore_deleted_budget.py) prices what deleting
a place buys at a global constraint as the deleted term's own local
group -- three points measured, all torsion-or-value-group shaped: one
parity bit (reciprocity), one 2-torsion bit (the Brauer sum),
everything (the product formula). Dirichlet's S-unit theorem gives the
S-unit group rank |S| - 1: adding a place buys exactly one rank, and
Z's unit group is finite BECAUSE the tower's one archimedean place is
the whole of S. This probe asks whether that rank is the same budget --
a fourth constraint shape (a rank, not a torsion budget) -- or whether
it refuses (the regulator or the unit lattice pricing differently).

TRANSPLANT FLAG: the budget reading is imported from torsion-valued
constraint sums (the reciprocity sign, the Brauer invariant sum) to a
rank-valued setting. The local group at a finite place decomposes as
O_v^* x pi^Z; the three measured points all read the compact/torsion
part, and the rank face would read the value-group part. The import is
flagged: nothing yet says both parts price alike.

THE HAND-ATTACK (before any engine code).
  (i) The constraint IS the product formula. An S-unit is x with
  v(x) = 0 at every finite place outside S; the log map
  x -> (log|x|_v)_{v in S} lands in the hyperplane sum = 0 because the
  terms outside S vanish. So the rank arithmetic is: |S| coordinates,
  each a rank-1 log-value group, minus ONE global relation -- the
  product formula's -- leaving |S| - 1. The counting alone gives only
  an upper bound; that the lattice FILLS the hyperplane is Dirichlet's
  theorem, and the engine measures the attained ranks. Each deleted
  term buys exactly the rank of its own value group, which is 1 for
  every place: the budget law's own prediction, term by term.
  (ii) Over Q with S = {oo} u {first s primes}: x = +-prod p^(a_p)
  realizes every vector in Z^s (the archimedean term absorbs the
  product formula), rank s = |S| - 1. Class number 1: the image is
  ALL of Z^s.
  (iii) Over K = Q(sqrt(-5)) (discriminant -20, Cl(K) = Z/2, unit
  group {+-1}, one complex place): rank of the S-unit group =
  (number of finite places in S), since the one archimedean place
  contributes 1 - 1 = 0. Places over p: 2 ramifies ((2) = P2^2),
  3 splits (-5 = 1^2 mod 3), 11 is inert (-5 = 6 mod 11, a
  non-residue), 29 splits (13^2 = 169 = -5 mod 29). So deleting "the
  places over p" buys rank 1, 2, 1, 2 for p = 2, 3, 11, 29 -- the
  budget counts deleted TERMS, and the term count consults the
  splitting of p in K.
  (iv) THE INDEX FACE. The valuation map O_{K,S}^* -> Z^{S_f} has
  image of full rank but finite index: the exact sequence
  1 -> O_K^* -> O_{K,S}^* -> Z^{S_f} -> Cl(K) -> Cl_S(K) -> 1
  makes the index the order of the subgroup of Cl(K) generated by the
  classes of the S-primes. [P2] is non-principal (a^2 + 5b^2 = 2 has
  no solution) with P2^2 = (2) principal, so support-{P2} elements
  are +-2^k: image 2Z, index 2. [P3] likewise (a^2 + 5b^2 = 3
  impossible); (2 + sqrt(-5)) has norm 9 and lands in the r = 1
  place doubly (Hensel: R = 7 mod 9, 2 + 7 = 9), so a single split
  place over 3 also prices index 2. The places over 29 are principal
  (3 + 2 sqrt(-5) has norm 29): index 1. P11 = (11): index 1.
  (v) THE WHICH-PLACE WITNESS: p = 2 and p = 11 have the same place
  count (1) and the same rank (1) but different index (2 vs 1) -- the
  rank face is uniform BECAUSE every value group has rank 1 (the
  law's own statement), and the which-place data is the index, a
  torsion budget again: the class of the deleted ideal.
  (vi) Valuation machinery, index convention re-derived: for split p
  with root r (r^2 = -5 mod p), the place P_r reads sqrt(-5) |-> R,
  the Hensel lift of r, and v_{P_r}(a + b sqrt(-5)) = v_p(a + bR);
  residue degree f = 1. Inert p: one place, f = 2,
  v = v_p(N(x)) / 2. Ramified p (2 and 5): one place, e = 2, f = 1,
  v_P(x) = v_p(N(x)) -- so v_P2(2) = v_2(4) = 2, the uniformizer
  valuation 1 is NOT attained by any element of Z[sqrt(-5)] with
  support {P2} (that would make P2 principal).

THE PREDICTIONS (frozen before the engine; kills are what the rig
PRINTS, weighed after).
  F0 POSITIVE CONTROLS, run first: (a) splitting verdicts for
  2, 3, 11, 29 in K print ram/split/inert/split, computed from
  x^2 + 5 mod p; (b) the valuation machinery reprints the
  hand-derived values v_P2(2) = 2, v_{P3,r=1}(3) = 1,
  v_{P3,r=1}(2 + sqrt(-5)) = 2, v_{P3,r=2}(2 + sqrt(-5)) = 0,
  v_P11(11) = 1, v_{P29,r=13}(3 + 2 sqrt(-5)) = 1; (c) the norm
  identity |N(x)| = prod p^(f * v) over the support, checked for
  every enumerated element; (d) non-principality: a^2 + 5b^2 = 2 and
  = 3 have no solutions (exhaustive, |a|,|b| <= 2).
  F1 (Q): for s = 0..6, the S-unit lattice at S = {oo} u {first s
  primes} is ALL of Z^s (each basis vector realized by the prime
  itself), rank s = |S| - 1, index 1; and the product formula
  |x|_oo * prod p^(-v_p(x)) prints exactly 1 as a Fraction for a
  deterministic grid of 100 constructed S-units.
  F2 (K ranks): the measured lattice rank at S_f = {places over p}
  is 1, 2, 1, 2 for p = 2, 3, 11, 29 -- equal to the place count,
  each deleted term buying exactly 1.
  F3 (K indexes): the measured index of the valuation lattice in
  Z^{S_f}, per S_f: {P2}: 2; {both P3}: 2; {P3, r=1 alone}: 2;
  {P11}: 1; {P29, r=13 alone}: 1; {both P29}: 1; {P2 + both P3}: 2;
  {all six places over 2, 3, 11, 29}: 2. The law: index = order of
  the subgroup of Cl(K) = Z/2 generated by the S-classes.
  F4 (the Z reading): S_f empty prints rank 0 in both fields -- the
  unit groups are torsion; Z's unit group is finite because {oo} is
  the whole of S.
  F5 (the which-place witness): the pair p = 2 vs p = 11 prints
  equal rank (1, 1) and unequal index (2, 1).
KILL OBSERVABLES (frozen at parking and here):
  K1 (vacuity, the parked kill-shape): every rank prints the place
  count AND every index prints 1 -- then no printed observable
  consults WHICH place was deleted, the rank face is vacuous
  bookkeeping, and the shelf's promotion event dies with it. The
  F5 pair is the designated observable.
  K2 (law refusal): some S prints rank != |S_f| -- the budget law's
  term-by-term pricing mispredicts the rank face; the refusal is
  the finding.
  K3 (index anarchy): some index prints a value other than the
  order of the subgroup of Cl(K) generated by the S-classes -- the
  which-place correction is not the class group.

ENGINE. Exact integer arithmetic throughout (Fraction for the
product formula; Hensel lifts mod p^40 for split valuations; an
integer echelon form for lattice rank and index). S-units of K are
enumerated as a + b sqrt(-5), |a|, |b| <= 60, norm support inside
the rational primes under S, and every place over a support prime
outside S must read valuation 0. Runtime well under the 5-minute
line; memory trivial (no numpy).

FINDINGS (post-run edit; printed output copied from the run).
  RUN RECORD: python prime/code/explore_rank_face.py -- 0.23 s,
  ALL GREEN. F0 controls all reprinting the hand values (splitting
  ram/split/inert/split at 2/3/11/29; the six valuation controls
  exact; no elements of norm 2 or 3); the norm identity
  |N(x)| = prod p^(f v) checked 784 times over (element, S-set)
  pairs. No kill fired.
  F1 (rule, s = 0..6): rank = s = |S| - 1 and index 1 at every s,
  basis vectors realized by the primes themselves; the product
  formula |x|_oo * prod p^-v printed exactly 1 as a Fraction on all
  100 grid S-units. Over class number 1 the budget is paid in full
  with no correction.
  F2 (rule, the rank face LANDS): measured ranks 1, 2, 1, 2 at
  p = 2, 3, 11, 29 -- exactly the place count, exactly the budget
  law's term-by-term price: each deleted term buys the rank of its
  own value group, which is 1, always. The rank consults WHICH
  rational prime only through how many terms it contributes (the
  splitting).
  F3 (rule, the index face is the CLASS GROUP): measured indexes
  2, 2, 2, 1, 1, 1, 2, 2 across the eight frozen S-sets -- each the
  order of the subgroup of Cl(K) = Z/2 generated by the classes of
  the S-primes (K3 dead). {P2} prices image 2Z (no odd valuation
  attained at the enumeration bound, consistent with principality
  of P2^2 = (2) only); a single split place over 3 prices index 2
  through (2 + sqrt(-5)) landing doubly; the principal places over
  29 price index 1.
  F4 (property, restated by the rig): empty S_f prints rank 0 in
  both fields -- the unit groups are torsion; Z's unit group is
  finite because {oo} is the whole of S and |S| - 1 = 0.
  F5 (the witness pair, K1 dead): p = 2 vs p = 11 print equal rank
  (1, 1) and unequal index (2, 1) -- the printed table consults
  which place was deleted. The rank face's uniformity is the law's
  own content (every finite place's value group has rank exactly
  1), not a failure to consult.
  SYNTHESIS: the budget law covers a fourth constraint shape. The
  local group at a finite place decomposes as O_v^* x pi^Z; the
  three earlier points read the compact/torsion factor (a sign, a
  Brauer class, a value group made void), and the rank face reads
  the pi^Z factor: rank 1 per deleted term, summed over exactly
  the terms deleted -- so the transplant flag resolves, both
  factors pricing the same way, the deleted term's own group
  exactly. What the rank cannot see -- which place -- returns one
  floor down as the index of the valuation lattice in Z^{S_f}, and
  that correction is the CLASS of the deleted ideal: a torsion
  budget again, at the lattice the rank forgot. The refusal
  candidate named at parking (the regulator pricing differently)
  found no purchase at this scope: over an imaginary quadratic
  field the archimedean contribution is 0 = 1 - 1 and the
  regulator never enters; a real-quadratic sweep would meet it,
  and is a different probe.
"""

from fractions import Fraction

# ---------------------------------------------------------------- basics

PRIMES = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47]


def vp(n, p):
    """p-adic valuation of a nonzero integer."""
    assert n != 0
    v = 0
    while n % p == 0:
        n //= p
        v += 1
    return v


def factor(n):
    """Trial-division factorization of |n| >= 1 into {p: e}."""
    n = abs(n)
    assert n >= 1
    out = {}
    d = 2
    while d * d <= n:
        while n % d == 0:
            out[d] = out.get(d, 0) + 1
            n //= d
        d += 1
    if n > 1:
        out[n] = out.get(n, 0) + 1
    return out


# ------------------------------------------- K = Q(sqrt(-5)) place layer

D = -5          # the field is Q(sqrt(D)): disc -20, ramified 2 and 5
HENSEL_K = 40   # lift precision p^HENSEL_K


def norm(a, b):
    """N(a + b sqrt(-5)) = a^2 + 5 b^2."""
    return a * a + 5 * b * b


def splitting(p):
    """('ram'|'split'|'inert', roots) for p in K, from x^2 + 5 mod p."""
    if p in (2, 5):
        return "ram", []
    roots = [r for r in range(p) if (r * r - D) % p == 0]
    return ("split", roots) if roots else ("inert", [])


def hensel_lift(p, r):
    """Lift r with r^2 = D mod p to R with R^2 = D mod p^HENSEL_K."""
    mod = p
    R = r
    for _ in range(HENSEL_K - 1):
        newmod = mod * p
        t = (((D - R * R) // mod) * pow(2 * R, -1, p)) % p
        R = (R + t * mod) % newmod
        mod = newmod
    assert (R * R - D) % mod == 0
    return R, mod


class Place:
    """A finite place of K over p: kind in ram/split/inert; split
    places carry the root r and its Hensel lift."""

    def __init__(self, p, kind, r=None):
        self.p, self.kind, self.r = p, kind, r
        self.f = 2 if kind == "inert" else 1
        if kind == "split":
            self.R, self.Rmod = hensel_lift(p, r)

    def name(self):
        tag = {"ram": "ram", "inert": "inert", "split": "r=%d" % self.r
               if self.r is not None else ""}[self.kind]
        return "P(%d,%s)" % (self.p, tag)

    def val(self, a, b):
        """v_P(a + b sqrt(-5)) for a nonzero element."""
        n = norm(a, b)
        if self.kind == "ram":
            return vp(n, self.p)                 # e = 2, f = 1
        if self.kind == "inert":
            v = vp(n, self.p) if n % self.p == 0 else 0
            assert v % 2 == 0, "inert valuation of a norm must be even"
            return v // 2
        x = (a + b * self.R) % self.Rmod
        if x == 0:
            raise AssertionError("Hensel precision exceeded")
        v = vp(x, self.p)
        assert v < HENSEL_K - 5, "valuation too close to lift precision"
        return v


def places_over(p):
    kind, roots = splitting(p)
    if kind == "split":
        return [Place(p, "split", r) for r in sorted(roots)]
    return [Place(p, kind)]


# ------------------------------------------------- integer lattice layer

def echelon(vectors, k):
    """Integer echelon basis of the lattice spanned by vectors in Z^k
    (row ops: add integer multiples, negate, drop zeros -- lattice
    preserved). Returns the basis; rank = len; if rank == k the index
    in Z^k is the product of the pivots."""
    rows = [list(v) for v in vectors if any(v)]
    basis = []
    for col in range(k):
        while True:
            nz = [r for r in rows if r[col] != 0]
            if len(nz) <= 1:
                break
            nz.sort(key=lambda r: abs(r[col]))
            small = nz[0]
            for r in nz[1:]:
                q = r[col] // small[col]
                for i in range(k):
                    r[i] -= q * small[i]
            rows = [r for r in rows if any(r)]
        nz = [r for r in rows if r[col] != 0]
        if nz:
            piv = nz[0]
            if piv[col] < 0:
                piv[:] = [-x for x in piv]
            basis.append(piv)
            rows.remove(piv)
    return basis


def rank_index(vectors, k):
    b = echelon(vectors, k)
    rank = len(b)
    idx = 1
    if rank == k:
        for i, row in enumerate(b):
            # pivot of row i is its first nonzero entry
            piv = next(x for x in row if x != 0)
            idx *= abs(piv)
    else:
        idx = None
    return rank, idx


# ---------------------------------------------------- K-side enumeration

BOUND = 60


def sunit_vectors(S_places):
    """Valuation vectors (over S_places, in order) of every
    a + b sqrt(-5), |a|,|b| <= BOUND, that is an S-unit: norm support
    inside the rational primes under S, and valuation 0 at every place
    over those primes NOT in S. Checks the norm identity
    |N(x)| = prod p^(f v) over ALL places over the support, for every
    candidate whose support primes are S-primes."""
    S_ps = sorted({pl.p for pl in S_places})
    all_places = {p: places_over(p) for p in S_ps}
    in_S = {(pl.p, pl.r, pl.kind) for pl in S_places}
    vecs = []
    checked = 0
    for a in range(-BOUND, BOUND + 1):
        for b in range(-BOUND, BOUND + 1):
            if (a, b) == (0, 0):
                continue
            n = norm(a, b)
            if n == 1:
                vecs.append([0] * len(S_places))
                continue
            supp = factor(n)
            if not all(p in S_ps for p in supp):
                continue
            # norm identity over the full fiber, then S-membership
            prod = 1
            ok = True
            vals = {}
            for p in supp:
                for pl in all_places[p]:
                    v = pl.val(a, b)
                    vals[(pl.p, pl.r, pl.kind)] = v
                    prod *= pl.p ** (pl.f * v)
                    if v > 0 and (pl.p, pl.r, pl.kind) not in in_S:
                        ok = False
            assert prod == n, "norm identity failed at %d+%d sqrt(-5)" \
                % (a, b)
            checked += 1
            if ok:
                vecs.append([vals.get((pl.p, pl.r, pl.kind), 0)
                             for pl in S_places])
    return vecs, checked


# ----------------------------------------------------------------- runs

def main():
    import time
    t0 = time.time()

    # F0 (a): splitting verdicts
    verdicts = {p: splitting(p)[0] for p in (2, 3, 11, 29)}
    print("F0a splitting:", verdicts)
    assert verdicts == {2: "ram", 3: "split", 11: "inert", 29: "split"}

    # F0 (b): hand-derived valuations reprint
    P2 = places_over(2)[0]
    P3a, P3b = places_over(3)          # r = 1, r = 2
    P11 = places_over(11)[0]
    P29a = [pl for pl in places_over(29) if pl.r == 13][0]
    ctrl = [
        ("v_P2(2)", P2.val(2, 0), 2),
        ("v_{P3,r=1}(3)", P3a.val(3, 0), 1),
        ("v_{P3,r=1}(2+s)", P3a.val(2, 1), 2),
        ("v_{P3,r=2}(2+s)", P3b.val(2, 1), 0),
        ("v_P11(11)", P11.val(11, 0), 1),
        ("v_{P29,r=13}(3+2s)", P29a.val(3, 2), 1),
    ]
    for label, got, want in ctrl:
        print("F0b %-22s = %d (hand: %d)" % (label, got, want))
        assert got == want
    # F0 (d): non-principality of P2, P3
    for target in (2, 3):
        sols = [(a, b) for a in range(-2, 3) for b in range(-2, 3)
                if norm(a, b) == target]
        assert sols == [], "norm %d element exists" % target
    print("F0d no elements of norm 2 or 3 -- P2, P3 non-principal")

    # F1: Q side, constructive
    print("\nF1 Q-side sweep, S = {oo} u {first s primes}:")
    for s in range(7):
        ps = PRIMES[:s]
        vecs = []
        for i, p in enumerate(ps):
            v = [0] * s
            v[i] = 1                     # realized by the prime itself
            vecs.append(v)
        rank, idx = rank_index(vecs, s) if s else (0, 1)
        print("  s=%d rank=%d (=|S|-1=%d) index=%s" % (s, rank, s, idx))
        assert rank == s and idx == 1
    # product formula on a deterministic grid of constructed S-units
    ps6 = PRIMES[:6]
    count = 0
    for j in range(100):
        x = Fraction(1)
        exps = [((3 * i + 7 * j) % 11) - 5 for i in range(6)]
        for p, e in zip(ps6, exps):
            x *= Fraction(p) ** e
        prod = abs(x)                    # |x|_oo
        for p in ps6:
            v = (vp(x.numerator, p) if x.numerator % p == 0 else 0) \
                - (vp(x.denominator, p) if x.denominator % p == 0 else 0)
            prod *= Fraction(p) ** (-v)
        assert prod == 1
        count += 1
    print("  product formula |x|_oo * prod p^-v = 1 exactly on %d"
          " grid S-units" % count)

    # F2 + F3: K side, the eight frozen S-sets
    S_sets = [
        ("{P2}", [P2], 1, 2),
        ("{P3 both}", [P3a, P3b], 2, 2),
        ("{P3 r=1}", [P3a], 1, 2),
        ("{P11}", [P11], 1, 1),
        ("{P29 r=13}", [P29a], 1, 1),
        ("{P29 both}", places_over(29), 2, 1),
        ("{P2,P3 both}", [P2, P3a, P3b], 3, 2),
        ("{2,3,11,29 all}", [P2, P3a, P3b, P11] + places_over(29), 6, 2),
    ]
    print("\nF2+F3 K = Q(sqrt(-5)) sweep, bound |a|,|b| <= %d:" % BOUND)
    print("  %-18s %5s %5s %6s %6s %9s" %
          ("S_f", "|S_f|", "rank", "pred", "index", "pred-idx"))
    total_checked = 0
    for label, pls, pred_rank, pred_idx in S_sets:
        vecs, checked = sunit_vectors(pls)
        total_checked += checked
        rank, idx = rank_index(vecs, len(pls))
        print("  %-18s %5d %5d %6d %6s %9d" %
              (label, len(pls), rank, pred_rank, idx, pred_idx))
        assert rank == pred_rank, "K2 fires: rank != place count"
        assert idx == pred_idx, "K3 fires: index != class subgroup order"
    print("  norm identity checked %d times, over (element, S-set)"
          " pairs" % total_checked)

    # F4: empty S_f
    vecs, _ = sunit_vectors([])
    rank, _ = rank_index(vecs, 0) if vecs else (0, 1)
    print("\nF4 empty S_f: K rank = %d; Q rank = 0 -- unit groups are"
          " torsion, |S| - 1 = 0" % rank)
    assert rank == 0

    # F5: the which-place witness pair
    r2, i2 = rank_index(sunit_vectors([P2])[0], 1)
    r11, i11 = rank_index(sunit_vectors([P11])[0], 1)
    print("\nF5 witness pair: p=2 (rank %d, index %d) vs p=11 (rank %d,"
          " index %d)" % (r2, i2, r11, i11))
    assert (r2, r11) == (1, 1) and (i2, i11) == (2, 1), \
        "K1 fires: table constant in which-place"
    print("  K1 dead: equal rank, unequal index -- the table consults"
          " which place")

    print("\nALL GREEN (%.2f s)" % (time.time() - t0))


if __name__ == "__main__":
    main()
