"""
explore_masking_layer.py — where the residue-masking dispute actually
lives, measured against the exact hiding laws.

THE QUESTION. Two literatures make opposite noises about the same
object. A countermeasure family says that carrying a secret as residues
hides it from a physical observer; an attack literature says the
protected implementations still fall. The exact hiding laws proved on
the residue decomposition itself (explore_size_crystallization.py,
explore_size_transform.py) are algebra, not physics — so the question
is not who wins, it is WHICH LAYER the dispute is fought on, and
whether any claim on either side is one the algebra grades.

Two full texts are the specimens, both read whole rather than
summarized (a search summary invented a claim the last such specimen
never made, so full-text-or-nothing):

  LRA — Bajard, Imbert, Liardet, Teglia, "Leak Resistant Arithmetic",
  CHES 2004, LNCS 3156, 62-75. The founding countermeasure. A set B of
  2k pairwise-coprime moduli; a random permutation splits it into two
  bases of k, and the Montgomery constant M_1,gamma = product of the
  first k acts as a multiplicative mask on the message. Its two claims:
  DATA randomization ("the output X*M_1,gamma mod N has a uniform
  distribution (if k is large enough)"), with its own strength stated
  in Table 1 as the bit-size of C(2k, k); and SPATIAL randomization
  (a given cell computes modulo a randomly drawn modulus).

  THE ATTACK — Papachristodoulou, Fournaris, Papagiannopoulos, Batina,
  "Practical Evaluation of Protected Residue Number System Scalar
  Multiplication", TCHES 2019(1), 259-282. LRA-protected Montgomery
  ladder scalar multiplication on a Cortex A8, n = 4 moduli of ~50
  bits over p = 2^192 - 2^64 - 1, evaluated by TVLA and template
  attacks.

THREE LEGS, each an exact measurement on an object one of the two
papers defines, none of them a physical claim.

  L1 THE MASK IS NOT A FREE MASK. LRA's Table 1 equates its mask to a
     random factor r_i of log2 C(2k, k) BITS. Bits are an entropy
     count; a mask also has a distribution. Every LRA mask is a product
     of k of the 2k fixed moduli, so the mask family satisfies exact
     multiplicative relations that an equally-sized family of free
     masks does not. Measured: the complement identity, and the
     SWAP-SQUARE relation — swapping modulus i out for j, and
     independently k out for l, commutes. L1b then REFUTES the
     smallness gloss those relations invite, by measuring what the
     moduli generate in (Z/p)*.

  L2 WHERE THE ENTROPY ACTUALLY SITS. Reproduce LRA's Table 1 column
     from C(2k, k) alone (a check that the paper is being read at its
     own parameters, not paraphrased), then read the same figure at the
     parameters the attack paper actually deployed.

  L3 WHY THE EXACT ZERO IS UNAVAILABLE. The sharpest hiding law the
     corpus holds is a bias of EXACTLY zero: fibers over a known proper
     channel subset are arithmetic progressions, so the sign bit's bias
     is at most half an element, and exactly zero whenever channel 2 is
     among the unknowns. Every deployed cryptographic residue base is
     built from large odd moduli. Measured: the bias at every fiber of
     an all-odd base against the bias at every fiber of a base carrying
     channel 2.

THE SLATE, frozen before any engine code. Predictions hand-derived;
kills named as things the rig PRINTS, never as what they would mean.

  P1 (L1, hand-derived). Writing S for a k-subset and M_S for the
     product of its moduli mod p: M_S * M_(complement of S) = M mod p
     at every one of the C(2k, k) subsets, since the two halves
     partition B. And for i, k in S distinct and j, l outside S
     distinct, M_(S-i+j) * M_(S-k+l) = M_S * M_(S-i+j-k+l) mod p at
     every such quadruple, since both sides are the same product of
     moduli times i^-1 j k^-1 l. PREDICTION: both hold at 100% of the
     quadruples enumerated, and the count of quadruples is printed
     rather than assumed.

  P2 (L1 control, hand-derived). A family of C(2k, k) values drawn
     uniformly from [1, p) satisfies a fixed nontrivial multiplicative
     relation with probability ~1/p. PREDICTION: 0 of the same
     quadruples hold, at both the complement identity and the swap
     square. This is the POSITIVE CONTROL and it runs FIRST: a test
     that fires on random data is measuring nothing.

  P2b (L1b, added at the audit that refuted it). The subgroup of
     (Z/p)* generated by the 2k moduli is measured, not assumed: p - 1
     is factored by a table the rig multiplies back and asserts, each
     modulus's multiplicative order is found by descent through those
     factors, and the generated subgroup's order is their lcm since
     (Z/p)* is cyclic. PREDICTION, and it is a REFUTATION of the gloss
     this rig first carried: the order equals p - 1 exactly — the
     moduli generate everything, and no smallness claim survives.

  P3 (L2, hand-derived by arithmetic on the paper's own table).
     floor(log2 C(2k, k)) reproduces LRA's printed "equiv. size of r_i"
     column at every row: |B| = 36, 44, 52, 60, 68, 80 giving 33, 40,
     48, 56, 64, 76. PREDICTION: exact agreement at all six rows.

  P4 (L2, at the attack paper's parameters). Its n = 4 gives C(8, 4) =
     70 base permutations over a 192-bit field. PREDICTION: the mask
     carries log2 70 = 6.13 bits. Stated by that paper itself as a
     memory/resistance trade-off, so this is a reproduction, not a
     catch.

  P5 (L3, hand-derived). Let the adversary know the residues on a
     NONEMPTY proper subset with product M_S, leaving L = M / M_S
     unknown. The qualifier is load-bearing on the converse below: at
     an empty known subset M_S = 1 and L = M, the two branches collapse
     to {0, 1/M} and the bias IS zero on an all-odd base — trivially,
     the adversary having learned nothing. The
     fiber is an arithmetic progression of length L and common
     difference M_S. If L is EVEN (equivalently, an even modulus is
     among the unknowns), exactly L/2 of its elements lie in the top
     half, and the top half of Z/M is exactly half of it, so the bias
     against the prior is EXACTLY 0 at every fiber. If every modulus is
     odd, M and L are odd, the top half {x > M/2} holds (M-1)/2
     elements, and the fiber's count is (L-1)/2 when its residue r
     satisfies r <= (M_S - 1)/2 and (L+1)/2 otherwise — so the bias
     against the prior is |1/(2M) -+ 1/(2L)|, NEVER zero.
     PREDICTION: max bias exactly 0 over all fibers of the base
     carrying channel 2; and over the all-odd base, every fiber's bias
     equal to one of those two hand-derived values, with the maximum
     strictly positive.

  THE KILLS, as observables.
  K1 Any swap-square or complement quadruple failing at either paper's
     parameters — the mask family is not the subset-product family
     derived above, and L1 is measuring the wrong object.
  K2 Any quadruple holding on the uniform control — the relation test
     fires on random data and L1 is vacuous.
  K3 Any row where floor(log2 C(2k, k)) differs from LRA's printed
     column — the paper is not being read at its own parameters and L2
     grades nothing.
  K4 A nonzero bias at any fiber of the channel-2 base, or a zero bias
     at any fiber of the all-odd base — the exact-zero law's stated
     hypothesis is not what makes it exact, and L3's reading of why the
     law is unavailable on cryptographic bases is wrong.

  WHAT THE RIG DOES NOT MEASURE, stated so no reading drifts into it.
  Nothing here touches power, electromagnetic emanation, timing, cache
  or memory-address behaviour, and no relation measured in L1 is
  claimed to be exploitable by any adversary. L1 grades a stated
  EQUIVALENCE (mask ~ random factor of that many bits), not the
  countermeasure's security.

FINDINGS (naming tiers named; run record follows; all sections assert).

1. THE MASK IS NOT A FREE MASK (property, from construction; measured
   at both parameter sets). Every LRA mask is a product of k of the 2k
   fixed moduli, so the family satisfies exact multiplicative relations
   that a free family of the same size does not: the complement
   identity M_S * M_comp = M held 70/70 at the attack paper's
   parameters and 924/924 at a 12-modulus set, and the swap-square
   relation held 2520/2520 and 207900/207900 — against 0/70 and 0/2520
   on the uniform control of the same size. THE RELATIONS ARE THE
   WHOLE CONTENT, and the tempting stronger gloss is FALSE — measured,
   not argued (L1b). "The masks lie in the small subgroup the 2k
   moduli generate" imports free-abelian intuition into a group that
   has none: (Z/p)* is CYCLIC of order p - 1, so any number of
   generators buys no smallness whatever. Measured at these very
   moduli: one of the eight is a PRIMITIVE ROOT outright (index 1, the
   other seven index 2), so the moduli generate the whole group and
   the containment is vacuous exactly where it was going to be used.
   What is exactly true is DEPENDENCE:
   C(2k, k) masks are determined by 2k values, and the relations above
   are what that dependence looks like from outside. So LRA's Table 1
   equivalence — mask ~ a random factor of log2 C(2k, k) BITS — is an
   ENTROPY count and not a distributional one. NOT CLAIMED
   EXPLOITABLE: this grades a stated equivalence, not the
   countermeasure's security, and nothing here is a break.

2. THE ENTROPY IS THE SUBSET COUNT (reproduction, exact at every row).
   floor(log2 C(2k, k)) reproduces LRA's printed column at all six of
   its rows: |B| = 36, 44, 52, 60, 68, 80 giving 33, 40, 48, 56, 64,
   76. At the parameters the attack paper actually deployed the same
   figure reads log2 C(8, 4) = log2 70 = 6.13 bits of data mask
   against a 192-bit field — ratio 0.032. That paper states the
   trade-off itself ("the security level provided by 70 different
   bases might not seem enough"), so this is a reproduction and not a
   catch; what it fixes is the SIZE of the thing under dispute.

3. THE EXACT-ZERO HALF IS UNAVAILABLE ON CRYPTOGRAPHIC BASES (rule,
   proved + measured exactly). The sign-hiding law's exact half needs
   an EVEN modulus among the UNKNOWN channels. The law does not become
   vacuous, it loses its sharp half: the bound of at most half an
   element survives untouched. Measured in exact rational arithmetic,
   at every NONEMPTY known subset (the qualifier P5 derives, and
   without it the converse has a trivial counterexample): a base
   carrying channel 2 gives bias EXACTLY 0 at every fiber with prior
   exactly 1/2; the all-odd bases give exactly the hand-derived pair
   |1/(2M) -+ 1/(2L)| and never zero — {1/165, 8/1155} at
   {3, 5, 7, 11} and {4/1155, 53/15015} at {3, 5, 7, 11, 13}.
   AND THE HYPOTHESIS IS AN IMPLEMENTATION CHOICE, NOT A FACT ABOUT
   CRYPTOGRAPHIC BASES — the correction that survived this rig's own
   audit. The attack paper's list of recommended moduli forms includes
   the POWER-OF-TWO channel 2^k beside the odd 2^k - c_i and Mersenne
   forms, so an even channel is entirely ordinary; measured on
   {8, 3, 5, 7}, the bias is exactly 0 when that channel is unknown
   and strictly positive when it is known. So the exact zero is a
   property of which SIDE the even channel falls on, and NEITHER paper
   states the moduli it used — the sharpest law the corpus holds
   cannot be pointed at this dispute even in principle, because the
   primary texts do not report the datum that decides whether it
   applies.

4. THE DISPUTE IS FOUGHT BELOW THE ALGEBRA, and both full texts say so
   in their own words (observation, from the two texts). LRA never
   claims the DECOMPOSITION hides anything: its hiding is
   RANDOMIZATION — a multiplicative mask whose strength it states
   itself (finding 2), plus spatial randomization of which cell holds
   which modulus. Its one decomposition-intrinsic claim is about
   FAULTS, not hiding ("since RNS is not such a positional number
   system, this assumption is not valid anymore"). On the attack side
   what broke is located by its own authors in the platform rather
   than the arithmetic: location-dependent templates classify the key
   bit at 87-99% because the two ladder registers sit at fixed
   addresses — "the implementation has no memory address
   randomization" — and the authors attribute the success to "the
   leakage of the platform and the fact that those chunks of values
   are probably stored in capacitors next to each other". Data-
   dependent leakage falls when the data is randomized; what survives
   is location. So no claim on either side is one the exact hiding
   laws settle or sharpen.

5. THE ORDER HOMONYM — a false stitch, killed before it was made
   (guard). The countermeasure that moved the attack paper's numbers
   furthest toward chance randomizes the SEQUENCE in which the
   per-channel operations run — and the scope matters: it took
   DATA-dependent classification to 55-58%, near chance, while
   LOCATION-dependent templates still ran 70-83% against that same
   combination, so it hardened one attack and did not close the
   other. The corpus
   holds exact laws about residue "order". They are different words.
   The laws bound the ORDER RELATION on VALUES — which of two is
   larger, cyclic orientation — and say nothing about the order in
   which a machine visits channels, which is invisible to them.
   Welding the two would be the paraphrase trap with the paraphrase
   supplied by our own vocabulary rather than someone else's summary.

RUN RECORD. 0.5 s, peak working set 13.1 MB (memwatch, 512 MB limit),
all asserts green, no kill fired. Exact
integer and rational arithmetic throughout; no floating point decides
any verdict (the log2 prints are display only, and finding 2's
comparison is against integer floors).

THREE CATCHES, all by a guard doing its job, all recorded because the
prints alone would not show them.
  (c) THE AUDIT REFUTED THIS RIG'S OWN FIRST GLOSS, which is why L1b
      exists. Finding 1 was first written explaining the relations by
      a subgroup containment — vacuous in a cyclic group, and measured
      false at the deployed moduli. The relations were always the
      measured content; only the explanation was wrong, so no number
      here moved.
  (a) THE CONTROL FIRED FIRST TIME, correctly. The complement
      identity's target M was first derived from one of the splits it
      then tested, so that split passed by construction and the
      uniform control scored 2/70 instead of 0/70. The target is now
      computed from the moduli and passed in; control 0/70.
  (b) K4 FIRED AND CAUGHT THE INSTRUMENT, not the law. The sign
      predicate was first coded as a strict [x > M/2]. At an even M
      the value M/2 is an integer sitting inside exactly one fiber, so
      dropping it manufactured a bias of 17/385 where the law says
      exactly zero. Re-coded as the residue literature's own [x >=
      M/2], which coincides with the strict form at every odd M and so
      changes no all-odd number.
"""

import os
os.environ.setdefault("OPENBLAS_NUM_THREADS", "1")

from itertools import combinations
from math import comb, gcd, log2
from fractions import Fraction
import random


def line(s=""):
    print(s)


def head(s):
    line()
    line("=" * 68)
    line(s)
    line("=" * 68)


# ---------------------------------------------------------------- bases

def build_moduli(nbits, count, p):
    """count pairwise-coprime moduli just under 2^nbits, each coprime to p.

    The forms cited by both papers are 2^k - c; taking the c in
    increasing order reproduces that shape without importing a table.
    """
    out = []
    c = 1
    while len(out) < count:
        m = (1 << nbits) - c
        c += 2 if (1 << nbits) % 2 == 0 else 1
        if all(gcd(m, o) == 1 for o in out) and gcd(m, p) == 1:
            out.append(m)
    return out


# ------------------------------------------------- L1: the mask family

def subset_masks(moduli, k, p):
    """Every k-subset's product mod p, keyed by the subset (as a tuple)."""
    idx = range(len(moduli))
    masks = {}
    for S in combinations(idx, k):
        prod = 1
        for i in S:
            prod = prod * moduli[i] % p
        masks[S] = prod
    return masks


def swap_quadruples(n, k):
    """(S, S-i+j, S-k+l, S-i+j-k+l) for i,k in S distinct, j,l out distinct.

    Enumerated once per unordered pair of swaps, so each square is
    counted a single time.
    """
    idx = list(range(n))
    for S in combinations(idx, k):
        inside, outside = list(S), [x for x in idx if x not in S]
        for (i, kk) in combinations(inside, 2):
            for (j, ll) in combinations(outside, 2):
                # the two swaps, then both applied
                a = tuple(sorted(set(S) - {i} | {j}))
                b = tuple(sorted(set(S) - {kk} | {ll}))
                d = tuple(sorted(set(S) - {i, kk} | {j, ll}))
                yield (S, a, b, d)


def check_relations(masks, n, k, p, full, label):
    """Complement identity + swap squares. Returns (held, total) for each.

    `full` is the product of all 2k moduli mod p, computed from the
    moduli themselves and passed in. Deriving it from one of the splits
    being tested would make that split pass by construction — which is
    what the control caught on its first run.
    """
    comp_hold = comp_tot = 0
    for S in masks:
        C = tuple(x for x in range(n) if x not in S)
        if C not in masks:
            continue
        comp_tot += 1
        if masks[S] * masks[C] % p == full:
            comp_hold += 1

    sq_hold = sq_tot = 0
    for (S, a, b, d) in swap_quadruples(n, k):
        sq_tot += 1
        if masks[a] * masks[b] % p == masks[S] * masks[d] % p:
            sq_hold += 1

    line(f"  {label}")
    line(f"    complement identity  M_S * M_comp = M : "
         f"{comp_hold}/{comp_tot}")
    line(f"    swap-square relation             : {sq_hold}/{sq_tot}")
    return (comp_hold, comp_tot, sq_hold, sq_tot)


# ------------------------------------- L1b: what the moduli generate

# p - 1 for p = 2^192 - 2^64 - 1. Carried as data and multiplied back
# below, so nothing here has to be trusted — a wrong table fails the
# assert rather than quietly producing a wrong order.
P192_MINUS_1_FACTORS = [2, 59, 149309, 11393611,
                        108341181769254293,
                        288626509448065367648032903]


def element_order(g, p, factors):
    """Multiplicative order of g mod p, by descent through the factors."""
    o = p - 1
    for q in factors:
        while o % q == 0 and pow(g, o // q, p) == 1:
            o //= q
    return o


def generated_order(moduli, p, factors):
    """Order of the subgroup <moduli> in the CYCLIC group (Z/p)*: the lcm."""
    from math import lcm
    out = 1
    for m in moduli:
        out = lcm(out, element_order(m, p, factors))
    return out


# --------------------------------------------------- L3: the sign bias

def sign_bias(moduli, known):
    """Max |P(sign | fiber) - P(sign | Z/M)| over every fiber.

    known = indices the adversary reads. The fiber over a residue
    assignment is {x : x = r mod M_S}; sign is the top-half indicator
    [x >= M/2] — the residue literature's own predicate, and the one
    the sibling hiding rigs use. The convention is load-bearing at an
    EVEN M, where M/2 is an integer sitting in a fiber: reading it as
    a strict [x > M/2] drops that boundary point from exactly one
    fiber and manufactures a bias of 17/385 where the law says zero.
    Exact rational arithmetic throughout — no float decides a verdict.
    """
    M = 1
    for m in moduli:
        M *= m
    M_S = 1
    for i in known:
        M_S *= moduli[i]
    L = M // M_S

    half = Fraction(M, 2)
    prior = Fraction(sum(1 for x in range(M) if Fraction(x) >= half), M)

    biases = set()
    for r in range(M_S):
        cnt = sum(1 for j in range(L) if Fraction(r + j * M_S) >= half)
        biases.add(abs(Fraction(cnt, L) - prior))
    return M, M_S, L, prior, biases


def report_bias(moduli, known, label):
    M, M_S, L, prior, biases = sign_bias(moduli, known)
    mx = max(biases)
    line(f"  {label}")
    line(f"    base {moduli}, known {[moduli[i] for i in known]}")
    line(f"    M = {M}, M_S = {M_S}, L = {L}, prior = {prior}")
    line(f"    distinct fiber biases: "
         f"{sorted(str(b) for b in biases)}")
    line(f"    max bias = {mx}  (zero at every fiber: {mx == 0})")
    return M, M_S, L, prior, biases, mx


# ============================================================== the run

def main():
    rng = random.Random(20260731)

    # ---- the attack paper's own parameters
    p = (1 << 192) - (1 << 64) - 1
    n, k = 8, 4
    moduli = build_moduli(50, n, p)
    M_all = 1
    for m in moduli:
        M_all *= m

    head("PARAMETERS — the attack paper's deployed instance")
    line(f"  field p = 2^192 - 2^64 - 1, {p.bit_length()} bits")
    line(f"  {n} moduli of {moduli[0].bit_length()} bits: {moduli}")
    line(f"  dynamic range M = {M_all.bit_length()} bits, 4p < M: "
         f"{4 * p < M_all}")
    line(f"  base permutations C({n}, {k}) = {comb(n, k)}")
    assert 4 * p < M_all, "the papers' own condition 4p < M must hold"
    # odd BY THIS RIG'S CONSTRUCTION (the 2^k - c form), not by any law
    # about cryptographic bases — see L3, where a power-of-two channel
    # is the case that matters.
    assert all(m % 2 == 1 for m in moduli), "the 2^k - c form is odd"

    # ---- POSITIVE CONTROL FIRST (K2): the relation test on free masks
    head("L1 CONTROL (runs first) — a free-mask family of the same size")
    idx = range(n)
    free = {S: rng.randrange(1, p) for S in combinations(idx, k)}
    c_ch, c_ct, c_sh, c_st = check_relations(free, n, k, p, M_all % p,
                                             "uniform masks in [1, p)")
    assert c_ch == 0, "K2 FIRED: complement identity holds on free masks"
    assert c_sh == 0, "K2 FIRED: swap square holds on free masks"
    line("  control passes: neither relation fires on free masks.")

    # ---- L1 proper
    head("L1 — the LRA mask family at the attack paper's parameters")
    masks = subset_masks(moduli, k, p)
    line(f"  distinct mask values: {len(set(masks.values()))}"
         f" of {len(masks)} subsets")
    ch, ct, sh, st = check_relations(masks, n, k, p, M_all % p,
                                     "LRA subset products")
    assert (ch, sh) == (ct, st), "K1 FIRED: a derived relation failed"

    # the same at a second, larger parameter set (NOT an LRA table row —
    # its table starts at |B| = 36; this is a second set, nothing more)
    head("L1 — the same relations at a second parameter set (|B| = 12)")
    n2, k2 = 12, 6
    mod2 = build_moduli(32, n2, p)
    M_all2 = 1
    for m in mod2:
        M_all2 *= m
    masks2 = subset_masks(mod2, k2, p)
    line(f"  {n2} moduli of {mod2[0].bit_length()} bits, "
         f"C({n2}, {k2}) = {comb(n2, k2)} subsets")
    line(f"  distinct mask values: {len(set(masks2.values()))}"
         f" of {len(masks2)} subsets")
    ch2, ct2, sh2, st2 = check_relations(masks2, n2, k2, p, M_all2 % p,
                                         "LRA subset products")
    assert (ch2, sh2) == (ct2, st2), "K1 FIRED at the second parameter set"

    # ---- L1b: refute the smallness gloss this rig first carried
    head("L1b — what the moduli actually generate in (Z/p)*")
    prod = 1
    for q in P192_MINUS_1_FACTORS:
        prod *= q
    line(f"  factor table multiplies back to p - 1: {prod == p - 1}")
    assert prod == p - 1, "the carried factorization of p - 1 is wrong"
    orders = [element_order(m, p, P192_MINUS_1_FACTORS) for m in moduli]
    for m, o in zip(moduli, orders):
        line(f"    modulus {m}: index [G : <m>] = {(p - 1) // o}")
    gen = generated_order(moduli, p, P192_MINUS_1_FACTORS)
    line(f"  |<all {n} moduli>| = p - 1: {gen == p - 1}")
    line("  so the moduli generate the WHOLE group: no subgroup")
    line("  containment can carry any smallness claim about the masks.")
    assert gen == p - 1, "P2b FIRED: the moduli do NOT generate everything"

    # ---- L2: the entropy, read off the papers' own parameters
    head("L2 — where the entropy sits")
    printed = {36: 33, 44: 40, 52: 48, 60: 56, 68: 64, 80: 76}
    line("  LRA Table 1, reproduced from C(2k, k) alone:")
    line("    |B|            C(2k,k)   floor(log2)  paper   match")
    for B in sorted(printed):
        c = comb(B, B // 2)
        f = int(log2(c))
        ok = (f == printed[B])
        line(f"    {B:3d} {c:24d} {f:9d} {printed[B]:8d}   {ok}")
        assert ok, f"K3 FIRED: row |B| = {B} disagrees with the paper"
    line()
    c70 = comb(n, k)
    line(f"  the attack paper's deployed instance: C({n}, {k}) = {c70}")
    line(f"    mask entropy = log2 {c70} = {log2(c70):.2f} bits")
    line(f"    field width  = {p.bit_length()} bits")
    line(f"    ratio        = {log2(c70) / p.bit_length():.4f}")

    # ---- L3: the exact-zero law's hypothesis
    head("L3 — the exact-zero hiding law against cryptographic bases")
    odd_base = [3, 5, 7, 11]
    even_base = [2, 5, 7, 11]
    line("  the law: fibers over a known proper channel subset are")
    line("  arithmetic progressions; bias is exactly 0 when channel 2")
    line("  is among the UNKNOWN channels.")
    line()
    _, _, Lo, _, bo, mxo = report_bias(odd_base, [0, 1], "all-odd base")
    line()
    _, Me, Le, _, be, mxe = report_bias(even_base, [1, 2],
                                        "base carrying channel 2, 2 unknown")
    assert mxe == 0, "K4 FIRED: nonzero bias with channel 2 unknown"
    assert mxo > 0, "K4 FIRED: zero bias on an all-odd base"

    # the hand-derived values from P5
    Mo = 3 * 5 * 7 * 11
    pred = {abs(Fraction(1, 2 * Mo) - Fraction(1, 2 * Lo)),
            abs(Fraction(1, 2 * Mo) + Fraction(1, 2 * Lo))}
    line()
    line(f"  P5's hand-derived odd-base biases: "
         f"{sorted(str(b) for b in pred)}")
    line(f"  measured set equals hand-derived set: {bo == pred}")
    assert bo == pred, "K4 FIRED: odd-base biases are not the derived pair"

    # and a second all-odd base, at the shape a cryptographic base has
    line()
    _, _, _, _, _, mx2 = report_bias([3, 5, 7, 11, 13], [0, 1, 2],
                                     "all-odd base, wider known subset")
    assert mx2 > 0, "K4 FIRED: zero bias on the second all-odd base"

    # The realistic even case: a POWER-OF-TWO CHANNEL, which the attack
    # paper's own list of recommended moduli forms includes (2^k, beside
    # the odd 2^k - c_i and Mersenne forms). Whether the exact zero is
    # available is decided by which SIDE that channel falls on.
    line()
    pow2 = [8, 3, 5, 7]
    _, _, _, _, _, mx_hid = report_bias(pow2, [1, 2],
                                        "power-of-two channel UNKNOWN")
    _, _, _, _, _, mx_seen = report_bias(pow2, [0, 1],
                                         "power-of-two channel KNOWN")
    assert mx_hid == 0, "K4 FIRED: 2-channel unknown but bias nonzero"
    assert mx_seen > 0, "K4 FIRED: 2-channel known yet bias vanished"
    line("  so the exact zero is not a property of the BASE but of")
    line("  which side the even channel falls on — and neither paper")
    line("  states the moduli it used.")

    head("ALL LEGS GREEN — no kill fired")


if __name__ == "__main__":
    main()
