"""
THE REGULATOR FACE -- does the S-unit COVOLUME price per deleted term?

The deleted-budget law (explore_deleted_budget.py,
explore_rank_face.py) prices what deleting a place buys at a global
constraint as the deleted term's own local group -- torsion budgets at
the compact factor (a sign, a Brauer class), rank 1 per term at the
value-group factor, with the class of the deleted ideal as the one
global correction. Neither the rank nor the index sees the COVOLUME:
over a real quadratic field the S-unit lattice has a regulator, and
this probe asks whether volumes are the same budget -- the covolume
factoring into per-deleted-term factors (each the covolume of the
deleted term's own local log-value group, log NP) times the field's
own unit regulator, with the class group returning as the correction
-- or whether a cross-term residual no single deleted place owns
refuses the fifth point.

TRANSPLANT FLAG: the per-term reading is imported from group-valued
budgets (torsion bits, ranks) to a VOLUME, which is a real number a
lattice basis computes jointly -- nothing yet says the joint quantity
respects the term decomposition. The kill was frozen when the probe
was banked, before this rig existed: a cross-term residual is the
refusal.

THE HAND-ATTACK (before any engine code).
  (i) The log map x -> (log|x|_v)_{v in S} sends the S-unit group
  (mod torsion, {+-1} in both fields here) to a full lattice in the
  sum-zero hyperplane of R^|S| -- the sum is zero by the product
  formula, and fullness is Dirichlet's S-unit theorem. R_S is the
  absolute determinant of a fundamental system's log vectors with
  one coordinate dropped; independent of the system and of the
  dropped coordinate (row/column operations of determinant 1).
  (ii) THE BLOCK TRIANGLE. Choose the fundamental system as: the
  fundamental unit e (finite coordinates ALL ZERO), plus one element
  g_j per basis vector of the valuation lattice L <= Z^{S_f}. Drop
  the second archimedean coordinate. The matrix is block triangular:
  det = log|e|_1 * det(-v_{P_i}(g_j) log NP_i)
      = R_K * (prod_i log NP_i) * |det v_{P_i}(g_j)|
      = R_K * (prod_i log NP_i) * [Z^{S_f} : L].
  The index [Z^{S_f} : L] is the order of the subgroup of Cl(K)
  generated by the S-classes (the rank-face rig's measured law). So
  the PREDICTED fifth point: R_S = R_K * i_S * prod log NP -- exact
  per-term factorization, each factor the covolume of the deleted
  term's own local log-value group log|K_P^*| = (log NP) Z, the
  correction the class group again. Changing g_j by unit multiples
  adds multiples of the e row: det unchanged, so any lifts serve.
  Classical contact: this is the S-regulator formula underlying the
  S-class-number formula (h_S R_S vs h R_K); the rig MEASURES it
  from enumerated elements rather than assuming it.
  (iii) THE FIELDS. K1 = Q(sqrt(2)): disc 8, Cl trivial, fundamental
  unit 1 + sqrt(2) (norm -1), R_K = log(1 + sqrt(2)) ~ 0.881374.
  Odd p splits iff 2 is a QR mod p iff p = +-1 mod 8: 7 splits
  (roots 3, 4; 3 + sqrt(2) has norm 7), 17 splits (roots 6, 11;
  5 + 2 sqrt(2) has norm 17), 3 inert (NP = 9), 2 ramified
  (sqrt(2), NP = 2). Every index 1.
  K2 = Q(sqrt(10)): disc 40, Cl = Z/2, fundamental unit
  3 + sqrt(10) (norm -1), R_K = log(3 + sqrt(10)) ~ 1.818446.
  P2 (ramified) is non-principal: x^2 - 10 y^2 = +-2 needs
  +-2 to be a square mod 5, and the squares mod 5 are {0, 1, 4} --
  the same obstruction kills +-3, so the places over 3 (split,
  roots 1, 2) are non-principal too, while [P3][P3'] = [(3)] is
  trivial, so both P3-classes ARE the nontrivial class. 41 splits
  (16^2 = 256 = 10 mod 41; roots 16, 25) with 9 + 2 sqrt(10) of
  norm 41: principal, index 1.
  (iv) Valuation hand-values for the controls. Ramified: e = 2,
  f = 1, v_P(x) = v_p(N(x)): v_P2(sqrt(2)) = v_2(-2) = 1 in K1;
  v_P2(2) = v_2(4) = 2 in K2 (odd v_P2 would need norm +-2^odd,
  killed mod 5 -- the lattice at {P2} is 2Z, index 2). Split p with
  root r: the place P_r reads sqrt(D) -> R (Hensel lift of r),
  v(a + b sqrt(D)) = v_p(a + bR). In K1: 3 + sqrt(2) lands at
  r = 4 (3 + 4 = 7), so v_{P7,r=4} = 1, v_{P7,r=3} = 0. In K2:
  1 + sqrt(10) has norm -9 and lands DOUBLY at r = 2 (R = 8 mod 9,
  1 + 8 = 9), so v_{P3,r=2} = 2, v_{P3,r=1} = 0 -- a single split
  place over 3 prices index 2. Inert: f = 2, v = v_p(N)/2:
  v_P3(3) = 1 in K1.
  (v) THE FACTOR-IDENTITY DISCRIMINATOR. For inert P3 in K1 the
  per-term factor is log NP = log 9 = 2 log 3, NOT log p = log 3.
  The designated print: R_S / (R_K * log 3) at S_f = {P3} -- the
  per-term law says 2.0 exactly, the rational-prime reading says
  1.0. One number separates "each deleted TERM contributes its own
  group's covolume" from "each deleted rational prime contributes
  log p".
  (vi) ENUMERATION HONESTY. Enumerated elements up to a coefficient
  bound could generate a proper finite-index sublattice, which
  would inflate both the measured index and the measured covolume
  by the same factor -- so the ratio test alone cannot see it. The
  guard is the hand-derived index table in (iii): the measured
  index must EQUAL the class-group order, which the mod-5
  obstruction proves at every size. All needed generators sit well
  inside |a|, |b| <= 60: 1 + sqrt(2), sqrt(2), 3, 3 + sqrt(2),
  5 + 2 sqrt(2); 3 + sqrt(10), 2, 1 + sqrt(10), 9 + 2 sqrt(10).

THE PREDICTIONS (frozen before the engine; kills are what the rig
PRINTS, weighed after).
  F0 POSITIVE CONTROLS, run first: (a) splitting verdicts -- K1:
  2 ram, 3 inert, 7 split (3, 4), 17 split (6, 11); K2: 2 ram,
  3 split (1, 2), 41 split (16, 25). (b) the valuation machinery
  reprints the hand values in (iv), all six. (c) the minimal
  enumerated unit is exactly (1, 1) in K1 and (3, 1) in K2, with
  R_K printing 0.8814 and 1.8184 to 4 dp. (d) the norm identity
  |N(x)| = prod NP^v over the support, exact, for every enumerated
  S-unit -- which IS the product formula, the archimedean product
  |x sigma(x)| being |N(x)|; and the float log-vector sum prints
  < 1e-9 for every fundamental-system element. (e) the mod-5
  obstruction: {+-2, +-3} mod 5 misses the squares {0, 1, 4} --
  the non-principality proof at every size.
  F1 (K1, class number 1): at every frozen S-set the measured
  ratio R_S / (R_K * prod log NP) prints 1 (relative tol 1e-6) and
  the measured lattice index prints 1 -- the covolume factors
  per-term with no correction.
  F2 (K2, the class correction in volumes): measured (index,
  ratio) per frozen S-set: {} (1, 1); {P2} (2, 2); {both P3}
  (2, 2); {P3 r=2 alone} (2, 2); {both P41} (1, 1); {P41 r=16
  alone} (1, 1); {P2, both P3} (2, 2); {P2, both P41} (2, 2). The
  ratio equals the index everywhere -- the volume correction IS
  the class of the deleted ideal.
  F3 (the factor identity): the K1 S_f = {P3} discriminator
  prints 2.0 -- the per-term factor is the deleted term's own
  log NP, residue degree included, not the rational prime's log p.
  F4 (degenerate): S_f empty prints rank 1 and R_S = R_K in both
  fields -- no terms deleted, the budget is the unit regulator
  alone.
  F5 (the witness pair): P2 vs {P41 r=16} in K2 -- one deleted
  term each, equal rank 2, covolume ratios 2 against 1: the volume
  face consults WHICH place through the class group and nothing
  else.
KILL OBSERVABLES (frozen at banking and here):
  K1 (cross-term residual, THE kill): some S-set prints a ratio
  R_S / (R_K * prod log NP) differing from that same set's
  measured integer index by more than 1e-6 relative -- a residual
  no per-term factor and no class correction owns; the fifth point
  refuses.
  K2 (vacuity): every ratio prints 1 in both fields -- the
  covolume face never consults which place and the correction
  claim is empty. The F5 pair is the designated observable.
  K3 (factor-identity refusal): the F3 discriminator prints 1.0 --
  the per-term factor is the rational prime's, not the term's own
  group's, and the "own local group" reading fails at volumes.

ENGINE. Exact integer arithmetic for norms, valuations, echelon and
index (Hensel lifts mod p^40 for split places); floats only for logs
and the covolume determinant (Gaussian elimination; |S| <= 7).
S-units of K = Q(sqrt(D)) enumerated as a + b sqrt(D), |a|, |b| <=
60, norm support inside the S rational primes, every place over a
support prime outside S reading valuation 0. The fundamental system
is assembled, not assumed: echelon rows carry their integer
combination of enumerated elements, so each basis vector's log
vector is the exact integer combination of measured element logs.
Runtime seconds; memory trivial (no numpy).

FINDINGS (post-run edit; printed output copied from the run).
  RUN RECORD: python prime/code/explore_regulator_face.py -- 0.39 s,
  ALL GREEN. F0 controls all reprinting the hand values (splitting
  ram/inert/split-split at 2/3/7/17 in K1 and ram/split/split at
  2/3/41 in K2; the seven valuation controls exact; the minimal
  enumerated units (1,1) and (3,1) after sign-fixing torsion, with
  R_K printing 0.881374 = log(1+sqrt2) and 1.818446 = log(3+sqrt10);
  the norm identity exact on every enumerated S-unit; every
  fundamental-system log-vector sum < 1.1e-12; the mod-5 obstruction
  disjointness printed). The one edit between the two runs fixed the
  fundamental-unit CONTROL, not a measurement: enumeration returned
  (-1,-1) = -(1+sqrt2), the same unit up to torsion with the same
  log, and the comparison now fixes the sign first.
  F1 (rule, K1 = Q(sqrt2), Cl trivial): at all eight frozen S-sets
  the ratio R_S / (R_K * prod log NP) prints 1.000000 and the index
  prints 1 -- the covolume factors per-term exactly, no correction.
  R_S at the 7-place set: 40.800366, ratio still 1.
  F2 (rule, K2 = Q(sqrt10), Cl = Z/2 -- the class correction in
  volumes): measured (index, ratio) = ({} 1,1; {P2} 2,2; {both P3}
  2,2; {P3 r=2} 2,2; {both P41} 1,1; {P41 r=16} 1,1; {P2,both P3}
  2,2; {P2,both P41} 2,2) -- ratio = index at every set, each the
  order of the subgroup of Cl(K) the S-classes generate. The volume
  correction IS the class of the deleted ideal.
  F3 (rule, the factor identity): the K1 {P3 inert} discriminator
  R_S / (R_K * log 3) prints 2.000000 -- the per-term factor is the
  deleted term's own log NP = log 9 (residue degree included), not
  the rational prime's log p (K3 dead).
  F4 (property, restated by the rig): empty S_f prints rank 1 and
  R_S = R_K in both fields -- no terms deleted, the budget is the
  unit regulator alone.
  F5 (the witness pair, K2 dead): {P2} vs {P41 r=16} in K2 -- one
  deleted term each, equal rank 2, ratios 2.000000 against
  1.000000: the volume face consults WHICH place through the class
  group and nothing else.
  THE KILL DOES NOT FIRE (K1 dead): no S-set in either field prints
  a ratio differing from its own measured integer index -- largest
  deviation at the 1e-6 tolerance is 0 to six printed decimals
  across all 17 measurements (16 distinct S-sets, the discriminator
  re-measuring one). No cross-term residual exists at this scope.
  SYNTHESIS: the fifth point lands -- volumes price per-term like
  everything else. The covolume of the S-unit lattice is
  R_K * i_S * prod log NP exactly: the field's own unit regulator
  (the no-deletion budget), one factor log NP per deleted term --
  the covolume of that term's own local log-value group
  log|K_P^*| = (log NP) Z, so "the deleted term's own local group"
  survives the passage from group invariants to volumes with the
  residue degree riding along -- and the class group as the one
  global correction, arriving in volumes at the same place it
  arrived in ranks (the valuation lattice's index). The transplant
  flag resolves: the joint quantity a lattice basis computes
  respects the term decomposition because the fundamental system
  can be chosen block-triangular, unit against valuations -- which
  is also why the correction is the index and nothing new. The
  classical contact is the S-regulator formula under the
  S-class-number formula; what the rig adds is the budget READING
  measured from enumerated elements: deletion buys volume
  multiplicatively, term by term, in both fields, with the
  which-place data once again the deleted ideal's class.
"""

import math

# ---------------------------------------------------------------- basics


def vp(n, p):
    """p-adic valuation of a nonzero integer."""
    assert n != 0
    v = 0
    while n % p == 0:
        n //= p
        v += 1
    return v


def factor(n):
    """Trial-division factorization of |n| >= 1 into {p: e}."""
    n = abs(n)
    assert n >= 1
    out = {}
    d = 2
    while d * d <= n:
        while n % d == 0:
            out[d] = out.get(d, 0) + 1
            n //= d
        d += 1
    if n > 1:
        out[n] = out.get(n, 0) + 1
    return out


# ----------------------------------------------- real quadratic K layer

HENSEL_K = 40   # lift precision p^HENSEL_K
BOUND = 60      # coefficient bound for enumeration


class Field:
    """K = Q(sqrt(D)), D squarefree positive (real quadratic)."""

    def __init__(self, D, ram, pool):
        self.D = D
        self.ram = ram            # the ramified primes we may use
        self.pool = pool          # rational primes places are built over
        self.places = []
        for p in pool:
            self.places.extend(self.places_over(p))
        self.sqrtD = math.sqrt(D)

    def norm(self, a, b):
        """N(a + b sqrt(D)) = a^2 - D b^2 (can be negative)."""
        return a * a - self.D * b * b

    def splitting(self, p):
        if p in self.ram:
            return "ram", []
        roots = [r for r in range(p) if (r * r - self.D) % p == 0]
        return ("split", roots) if roots else ("inert", [])

    def places_over(self, p):
        kind, roots = self.splitting(p)
        if kind == "split":
            return [Place(self, p, "split", r) for r in sorted(roots)]
        return [Place(self, p, kind)]

    def logs_arch(self, a, b):
        """(log|sigma1(x)|, log|sigma2(x)|), sigma1: sqrt(D) -> +."""
        s = b * self.sqrtD
        return math.log(abs(a + s)), math.log(abs(a - s))


class Place:
    """A finite place over p: kind in ram/split/inert; split places
    carry the root r and its Hensel lift. NP = p^f."""

    def __init__(self, K, p, kind, r=None):
        self.K, self.p, self.kind, self.r = K, p, kind, r
        self.f = 2 if kind == "inert" else 1
        self.NP = p ** self.f
        if kind == "split":
            self.R, self.Rmod = self.hensel(p, r)

    def hensel(self, p, r):
        D = self.K.D
        mod, R = p, r
        for _ in range(HENSEL_K - 1):
            newmod = mod * p
            t = (((D - R * R) // mod) * pow(2 * R, -1, p)) % p
            R = (R + t * mod) % newmod
            mod = newmod
        assert (R * R - D) % mod == 0
        return R, mod

    def name(self):
        tag = {"ram": "ram", "inert": "inert",
               "split": "r=%d" % self.r if self.r is not None else ""}[
                   self.kind]
        return "P(%d,%s)" % (self.p, tag)

    def val(self, a, b):
        """v_P(a + b sqrt(D)) for a nonzero element."""
        n = self.K.norm(a, b)
        if self.kind == "ram":
            return vp(n, self.p)                 # e = 2, f = 1
        if self.kind == "inert":
            v = vp(n, self.p) if n % self.p == 0 else 0
            assert v % 2 == 0, "inert valuation of a norm must be even"
            return v // 2
        x = (a + b * self.R) % self.Rmod
        if x == 0:
            raise AssertionError("Hensel precision exceeded")
        v = vp(x, self.p)
        assert v < HENSEL_K - 5, "valuation too close to lift precision"
        return v


# ------------------------------------------------- integer lattice layer

def echelon_tracked(vectors, k):
    """Integer echelon basis of the lattice spanned by vectors in Z^k,
    each row carrying its combination {source_index: exponent} so the
    basis rows remain exact integer combinations of the sources. Row
    ops: subtract integer multiples, negate, drop zeros -- lattice
    preserved. Returns (basis_rows, combos)."""
    rows = []
    for i, v in enumerate(vectors):
        if any(v):
            rows.append((list(v), {i: 1}))

    def sub(row, q, small):
        rv, rc = row
        sv, sc = small
        for j in range(k):
            rv[j] -= q * sv[j]
        for key, e in sc.items():
            rc[key] = rc.get(key, 0) - q * e
            if rc[key] == 0:
                del rc[key]

    basis = []
    for col in range(k):
        while True:
            nz = [r for r in rows if r[0][col] != 0]
            if len(nz) <= 1:
                break
            nz.sort(key=lambda r: abs(r[0][col]))
            small = nz[0]
            for r in nz[1:]:
                q = r[0][col] // small[0][col]
                sub(r, q, small)
            rows = [r for r in rows if any(r[0])]
        nz = [r for r in rows if r[0][col] != 0]
        if nz:
            piv = nz[0]
            if piv[0][col] < 0:
                piv = ([-x for x in piv[0]],
                       {key: -e for key, e in piv[1].items()})
            basis.append(piv)
            rows = [r for r in rows if r is not nz[0]]
    return [b[0] for b in basis], [b[1] for b in basis]


def lattice_index(basis, k):
    """Index of the lattice in Z^k from an echelon basis (product of
    pivots), or None if the rank is short."""
    if len(basis) != k:
        return None
    idx = 1
    for row in basis:
        piv = next(x for x in row if x != 0)
        idx *= abs(piv)
    return idx


def det_abs(M):
    """|det| of a square float matrix by Gaussian elimination."""
    n = len(M)
    A = [row[:] for row in M]
    d = 1.0
    for i in range(n):
        piv = max(range(i, n), key=lambda r: abs(A[r][i]))
        if abs(A[piv][i]) < 1e-12:
            return 0.0
        if piv != i:
            A[i], A[piv] = A[piv], A[i]
        d *= A[i][i]
        for r in range(i + 1, n):
            f = A[r][i] / A[i][i]
            for c in range(i, n):
                A[r][c] -= f * A[i][c]
    return abs(d)


# ------------------------------------------------------- S-unit engine

def enumerate_s_units(K, s_places):
    """All a + b sqrt(D), |a|,|b| <= BOUND, that are S-units for
    S = {both archimedean} u s_places: norm support inside the S
    rational primes, valuation 0 at every pool place over a support
    prime that is not in S. Returns list of (a, b, valvec) with
    valvec over s_places. Excludes 0; keeps torsion (norm +-1)."""
    s_primes = {P.p for P in s_places}
    out = []
    for a in range(-BOUND, BOUND + 1):
        for b in range(-BOUND, BOUND + 1):
            if a == 0 and b == 0:
                continue
            n = K.norm(a, b)
            supp = factor(n) if abs(n) != 1 else {}
            if any(p not in s_primes for p in supp):
                continue
            ok = True
            for P in K.places:
                if P.p in supp and P not in s_places:
                    if P.val(a, b) != 0:
                        ok = False
                        break
            if not ok:
                continue
            out.append((a, b, tuple(P.val(a, b) for P in s_places)))
    return out


def fundamental_unit(K, units):
    """Minimal positive log among enumerated units; (a, b, log)."""
    best = None
    for (a, b, _) in units:
        if a < 0 or (a == 0 and b < 0):
            a, b = -a, -b            # torsion is {+-1}: fix the sign
        l1, _l2 = K.logs_arch(a, b)
        if l1 > 1e-9 and (best is None or l1 < best[2]):
            best = (a, b, l1)
    assert best is not None, "no nontrivial unit enumerated"
    return best


def measure(K, s_places, label):
    """Measure (rank, index, R_S, ratio) at S = arch u s_places."""
    k = len(s_places)
    elems = enumerate_s_units(K, s_places)
    units = [(a, b, v) for (a, b, v) in elems if not any(v)]
    eps = fundamental_unit(K, units)

    # norm identity control (exact): |N| = prod NP^v over s_places
    for (a, b, v) in elems:
        n = abs(K.norm(a, b))
        pr = 1
        for P, e in zip(s_places, v):
            pr *= P.NP ** e
        assert n == pr, "norm identity fails at %s" % ((a, b),)

    basis, combos = echelon_tracked([v for (_, _, v) in elems], k)
    rank = len(basis)
    idx = lattice_index(basis, k)

    # fundamental system log vectors (drop sigma2): eps + basis rows
    def logvec(a, b):
        l1, _ = K.logs_arch(a, b)
        return [l1] + [-P.val(a, b) * math.log(P.NP) for P in s_places]

    rows = [[eps[2]] + [0.0] * k]
    maxsum = 0.0
    for comb in combos:
        vec = [0.0] * (k + 1)
        full = [0.0] * (k + 2)
        for i, e in comb.items():
            a, b, _ = elems[i]
            lv = logvec(a, b)
            l1, l2 = K.logs_arch(a, b)
            for j in range(k + 1):
                vec[j] += e * lv[j]
            full[0] += e * l1
            full[1] += e * l2
            for j in range(k):
                full[2 + j] += e * lv[1 + j]
        maxsum = max(maxsum, abs(sum(full)))
        rows.append(vec)
    R_S = det_abs(rows) if rank == k else None
    ratio = None
    if R_S is not None:
        prod = 1.0
        for P in s_places:
            prod *= math.log(P.NP)
        ratio = R_S / (eps[2] * prod)
    print("  %-22s rank %d  index %s  R_S %s  ratio %s  logsum %.1e"
          % (label, rank + 1 if rank == k else rank,
             idx, "%.6f" % R_S if R_S is not None else "short",
             "%.6f" % ratio if ratio is not None else "-", maxsum))
    return rank, idx, R_S, ratio, eps


# --------------------------------------------------------------- run

def main():
    print("== F0 controls ==")
    K1 = Field(2, ram=[2], pool=[2, 3, 7, 17])
    K2 = Field(10, ram=[2, 5], pool=[2, 3, 41])
    for K, name in ((K1, "Q(sqrt2)"), (K2, "Q(sqrt10)")):
        verdicts = []
        for p in K.pool:
            kind, roots = K.splitting(p)
            verdicts.append("%d %s%s" % (p, kind,
                            " %s" % roots if roots else ""))
        print("  %-10s %s" % (name, "; ".join(verdicts)))

    def pl(K, p, kind, r=None):
        for P in K.places:
            if P.p == p and P.kind == kind and P.r == r:
                return P
        raise KeyError

    ctrl = [
        ("v_P2(sqrt2) K1", pl(K1, 2, "ram").val(0, 1), 1),
        ("v_P7r4(3+sqrt2)", pl(K1, 7, "split", 4).val(3, 1), 1),
        ("v_P7r3(3+sqrt2)", pl(K1, 7, "split", 3).val(3, 1), 0),
        ("v_P3(3) K1 inert", pl(K1, 3, "inert").val(3, 0), 1),
        ("v_P3r2(1+sqrt10)", pl(K2, 3, "split", 2).val(1, 1), 2),
        ("v_P3r1(1+sqrt10)", pl(K2, 3, "split", 1).val(1, 1), 0),
        ("v_P2(2) K2", pl(K2, 2, "ram").val(2, 0), 2),
    ]
    for name, got, want in ctrl:
        assert got == want, (name, got, want)
        print("  %-22s %d  (hand: %d)" % (name, got, want))

    sq5 = {(x * x) % 5 for x in range(5)}
    bad = [c % 5 for c in (2, -2, 3, -3)]
    assert all(c not in sq5 for c in bad)
    print("  mod-5 obstruction: {+-2,+-3} mod 5 =", sorted(set(bad)),
          "squares mod 5 =", sorted(sq5), "-- disjoint")

    print("== K1 = Q(sqrt2), Cl trivial ==")
    P2, P3 = pl(K1, 2, "ram"), pl(K1, 3, "inert")
    P7a, P7b = pl(K1, 7, "split", 3), pl(K1, 7, "split", 4)
    P17a, P17b = pl(K1, 17, "split", 6), pl(K1, 17, "split", 11)
    k1_sets = [
        ("{}", []),
        ("{P2}", [P2]),
        ("{P3 inert}", [P3]),
        ("{both P7}", [P7a, P7b]),
        ("{P7 r=3}", [P7a]),
        ("{P2,P3}", [P2, P3]),
        ("{P2,both P7}", [P2, P7a, P7b]),
        ("{P2,P3,P7x2,P17x2}", [P2, P3, P7a, P7b, P17a, P17b]),
    ]
    eps1 = None
    for label, s in k1_sets:
        _, _, _, _, eps1 = measure(K1, s, label)
    print("  fundamental unit K1: (%d,%d)  R_K = %.6f  (hand: (1,1),"
          " log(1+sqrt2) = %.6f)"
          % (eps1[0], eps1[1], eps1[2], math.log(1 + math.sqrt(2))))

    print("== F3 factor-identity discriminator ==")
    _, _, R_S, _, eps = measure(K1, [P3], "{P3 inert} again")
    disc = R_S / (eps[2] * math.log(3))
    print("  R_S / (R_K * log 3) = %.6f  (per-term law: 2.0;"
          " rational-prime reading: 1.0)" % disc)

    print("== K2 = Q(sqrt10), Cl = Z/2 ==")
    Q2 = pl(K2, 2, "ram")
    Q3a, Q3b = pl(K2, 3, "split", 1), pl(K2, 3, "split", 2)
    Q41a, Q41b = pl(K2, 41, "split", 16), pl(K2, 41, "split", 25)
    k2_sets = [
        ("{}", []),
        ("{P2}", [Q2]),
        ("{both P3}", [Q3a, Q3b]),
        ("{P3 r=2}", [Q3b]),
        ("{both P41}", [Q41a, Q41b]),
        ("{P41 r=16}", [Q41a]),
        ("{P2,both P3}", [Q2, Q3a, Q3b]),
        ("{P2,both P41}", [Q2, Q41a, Q41b]),
    ]
    eps2 = None
    for label, s in k2_sets:
        _, _, _, _, eps2 = measure(K2, s, label)
    print("  fundamental unit K2: (%d,%d)  R_K = %.6f  (hand: (3,1),"
          " log(3+sqrt10) = %.6f)"
          % (eps2[0], eps2[1], eps2[2], math.log(3 + math.sqrt(10))))

    assert (eps1[0], eps1[1]) == (1, 1)
    assert (eps2[0], eps2[1]) == (3, 1)
    print("ALL GREEN")


if __name__ == "__main__":
    main()
