"""
The Galois-stable skeleton of curves (MOONSHOT probe, P82).

The joint-measurement entry's named reopen (LOGIC.md SI), taken with
its bar: beyond the additive lines a + b = c, which algebraic shadows
[f(a, b) = 0] have word-visible points -- is the stable locus of a
general algebraic condition again rational-trace torsion, or does a
new species appear past degree 1? Bar: a LAW naming the stable loci
(the lines precedent: all-u stability forces phi(ord) <= 2, the
crystallographic skeleton 1, 2, 3, 4, 6), verified by exhaustive
census over small p.

Setting (P77 inherited): per channel F_p a shadow is word-decidable
iff constant on conjugacy orbits (a, b) -> (a^u, b^u), u a unit; the
STABLE LOCUS of [f = 0] is the union of orbits lying wholly inside
the shadow. For a unit pair (a, b) put d = lcm(ord a, ord b). Every
monomial of f takes the value w_m = a^{i_m} b^{j_m} on the pair, an
element of mu_d, so the orbit trace is the character sum
F(t) = f(a^t, b^t) = sum_m c_m w_m^t on Z/d (coefficients COLLECTED
over equal w's), and stability says F vanishes on the units of Z/d.

PREDICTIONS (stated before the run):
 P1 (criterion, proved): THE FIBER CRITERION. (a, b) is stable for
    [f = 0] iff its collected fiber is (i) identically zero -- f
    vanishes on the whole cyclic group <(a, b)>: the GROUP SPECIES,
    the finite shadow of Lang's torsion-coset theorem -- or (ii) a
    nonzero multiple of the cyclotomic polynomial Phi_d in
    F_p[T]/(T^d - 1): the CODEWORD SPECIES, a codeword of the cyclic
    code generated by Phi_d. Proof: t -> theta^t identifies units of
    Z/d with primitive d-th roots; vanishing there = divisibility.
 P2 (rule, proved, field-free): THE RUN BOUND. The longest run of
    consecutive units mod d is exactly q_min(d) - 1 (q_min = least
    prime factor; any q_min consecutive integers contain a multiple
    of q_min, and CRT builds a run of length q_min - 1 avoiding
    every prime of d). A nonzero collected M-term character sum
    cannot vanish at M consecutive points (scaled-Vandermonde,
    distinct nodes w_m), so a codeword-species point of torsion d
    needs at least q_min(d) collected monomials.
 P3 (rule, proved, field-free): THE TORSION-MENU LAW. The q-gon
    (T^d - 1)/(T^{d/q} - 1), q = q_min(d), is a weight-q multiple of
    Phi_d, so the minimum weight tau(d) of the cyclotomic code
    (Phi_d) equals q_min(d) exactly -- every d > 1, every field
    containing mu_d; weight 1 is empty (Phi_d(0) != 0), and weight 2
    exists iff d is even (theta^e constant on primitive roots forces
    e = 0 mod d; the even-d words are the ANTIPODAL SPECIES
    c T^e (T^{d/2} + 1): w, -w with equal coefficients -- unbounded
    even torsion, the lines' c = 0 generalized). Hence an M-monomial
    shadow admits codeword-species torsion of order d only if
    q_min(d) <= M, realized with free exponents: the lines'
    crystallographic skeleton is the M = 3 row (their unit
    coefficients + constant term cut {q_min <= 3} down to
    phi(d) <= 2), and a NEW SPECIES arrives at every prime q at
    M = q monomials. Census side: exhaustive min-weight search
    (all supports, kernel rank) confirms no weight < q_min for odd
    d <= 35; the run bound makes char-p sporadic minima impossible
    (Mann's vanishing-sums theorem, the char-0 shadow of this, is
    not needed: the run argument is field-free).
 P4 (rule): THE PENTAGON WITNESS -- the first new species past
    degree 1. The conic y^2 + xy + x + y + 1 = 0 carries the fiber
    1 + T + T^2 + T^3 + T^4 = (T^5 - 1)/(T - 1) at (theta, theta^2),
    theta of order 5: a stable order-5 orbit at EVERY p = 1 mod 5 --
    torsion outside the lines' skeleton {1, 2, 3, 4, 6}, at degree
    2. By P2/P3 five monomials are MINIMAL for 5-torsion, so conics
    (budget 6) are the first degree that fits it. The order-5 stable
    locus of this conic is exactly ONE orbit {(theta^u, theta^{2u})}
    (exponent bookkeeping mod 5: {0, A, B, A+B, 2B} = Z/5 forces
    (A, B) = u(1, 2)); no order-5 point at p != 1 mod 5.
 P5 (rule): SPECIES EXERCISERS. [x^2 y = 1] is group-species at
    every point (the coset IS a subgroup graph); [xy = -1] is
    antipodal at every point (F = (-1)^t + 1, d forced even);
    x^8 + x^4 + 1 = the order-{3, 6, 12} gate in curve clothing
    (codeword Phi_12 Phi_6 Phi_3 -- one-variable shadows reduce to
    the ladder's order conditions, P75).
 P6 (rule): LINE CONTINUITY. The criterion reproduces the P77
    crystallographic law verbatim on a + b = c: c != 0 stable points
    = {(a, a^{-1}): a + a^{-1} = c, ord(a) in {1, 2, 3, 6}}, c = 0
    = all (a, -a).
 P7 (observation): DEGREE CAPS STARVE REALIZABILITY. The torsion
    menu counts monomials, not degree, and bounded degree can fail
    to reach a codeword's exponents: at p = 101 no conic stabilizes
    any pair of torsion d = 25 THROUGH THE CODEWORD SPECIES (every
    Phi_25-codeword is a scalar shifted 5-gon -- the code is
    Phi_5(T^5) times degree-<5 multipliers, weights all multiples
    of 5 -- and the 5-gon's exponent set is unreachable from
    {0, A, B, 2A, 2B, A+B} with lcm-order 25), though
    tau(25) = 5 <= 6. The GROUP species is degree-blind and stays
    available: pairs whose six conic exponents collide mod 25
    admit a nonzero conic vanishing on their whole cyclic group
    (e.g. (1, h) lies on x = 1 with its full orbit) -- the
    codeword scope is load-bearing, not pedantry. (The general law
    this observation seeded: explore_realizability.py, P86.)

RESULTS (the run below prints the record; all confirmed):
  P1 brute orbit check == criterion over EVERY unit pair x battery
     (lines all c, pentagon conic, gate curves, coset curves, 25
     seeded random curves): p in {7, 11, 13, 31}, 67,704 curve-point
     stability tests, zero disagreements.
  P2 run law exhaustive d = 2..5000; Vandermonde implicit in P3.
  P3 min-weight search exhaustive (all supports up to shift, kernel
     rank over the field): no codeword of weight < q_min(d) for
     d in {3, 5, 7, 9, 11, 13, 15, 21, 25, 27, 33, 35} at the least
     p = 1 mod d (primes 17..31 unswept -- combinatorially large
     and exactly the proved DS-extremal case); q-gon divisibility
     verified at every swept d (odd and even), so tau(d) = q_min(d)
     on the sweep -- census agreeing with the field-free proof.
  P4 pentagon: order-5 stable points exist at p in {11, 31, 41, 61}
     and equal the single predicted orbit; absent at p = 7; species
     = codeword, collected weight 5.
  P5 species labels confirmed at every battery point (group /
     antipodal / codeword as predicted).
  P6 line stable sets == P77 law at all c, p in {7, 11, 13, 31}.
  P7 conic-25 obstruction: all 600 pairs of torsion 25 at p = 101,
     no conic coefficient vector (kernel search over the distinct
     monomial values) stabilizes any through the codeword species;
     120 of the 600 admit a group-species conic (exponent
     collision), so the scope is doing real work.

Tier: P1 criterion (proved; verified exhaustively as stated).
P2, P3 rule (proved field-free by the run/Vandermonde/q-gon
arguments; min-weight census exhaustive for the swept d). P4, P5,
P6 rule (proved per channel + exhaustive censuses as stated).
P7 observation (exhaustive at p = 101; expected all p).

Classical contacts: Lang's theorem on torsion points of subvarieties
of tori (the group species is its finite shadow); Mann / Conway-Jones
vanishing sums of roots of unity (in char 0 the menu law's minimum
follows from Mann's theorem; the run bound proves that consequence
directly, in any characteristic); coding theory --
the stable loci are graded by the minimum distance of cyclotomic
cyclic codes on the exponent ring: the index-ring contact (LOGIC.md
SI) now carrying ECC vocabulary one level down.

Runs in ~3 s, tiny memory. ALL CHECKS PASSED (51).
"""

import sys, os, random
from math import gcd

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

random.seed(82)

CHECKS = 0
def check(cond, msg):
    global CHECKS
    CHECKS += 1
    print(f"  [{'ok' if cond else 'FAIL'}] {msg}")
    assert cond, msg

def section(t):
    print(); print("=" * 72); print(t); print("=" * 72)

# ---------------------------------------------------------------- helpers

def factorize(n):
    fs, q = {}, 2
    while q * q <= n:
        while n % q == 0:
            fs[q] = fs.get(q, 0) + 1
            n //= q
        q += 1
    if n > 1:
        fs[n] = fs.get(n, 0) + 1
    return fs

def spf(n):
    q = 2
    while q * q <= n:
        if n % q == 0:
            return q
        q += 1
    return n

def mult_order(x, p):
    n, o = p - 1, 1
    t = x % p
    assert t != 0
    while t != 1:
        t = t * x % p
        o += 1
    return o

def primitive_root(p):
    n = p - 1
    qs = list(factorize(n))
    for g in range(2, p):
        if all(pow(g, n // q, p) != 1 for q in qs):
            return g

def units_mod(n):
    return [u for u in range(n) if gcd(u, n) == 1]

_CYC = {}
def cyclotomic(d):
    """Integer coefficient list of Phi_d, low degree first."""
    if d in _CYC:
        return _CYC[d]
    # (T^d - 1) / prod_{e | d, e < d} Phi_e, exact integer division
    num = [-1] + [0] * (d - 1) + [1]
    for e in range(1, d):
        if d % e == 0:
            den = cyclotomic(e)
            num = poly_div_exact(num, den)
    _CYC[d] = num
    return num

def poly_div_exact(A, B):
    A = A[:]
    out = [0] * (len(A) - len(B) + 1)
    for i in range(len(A) - len(B), -1, -1):
        c = A[i + len(B) - 1] // B[-1]
        out[i] = c
        for j, bj in enumerate(B):
            A[i + j] -= c * bj
    assert all(x == 0 for x in A[:len(B) - 1])
    return out

def poly_rem_modp(A, B, p):
    """Remainder of A mod B over F_p (lists, low degree first)."""
    A = [a % p for a in A]
    B = [b % p for b in B]
    while len(B) > 1 and B[-1] == 0:
        B.pop()
    inv = pow(B[-1], p - 2, p)
    for i in range(len(A) - len(B), -1, -1):
        c = A[i + len(B) - 1] * inv % p
        if c:
            for j, bj in enumerate(B):
                A[i + j] = (A[i + j] - c * bj) % p
    while len(A) > 1 and A[-1] == 0:
        A.pop()
    return A

# A curve is a list of (coeff, i, j): f(x, y) = sum c x^i y^j.

def eval_curve(f, x, y, p):
    return sum(c * pow(x, i, p) * pow(y, j, p) for c, i, j in f) % p

def brute_stable(f, a, b, p):
    """Definition: the whole orbit (a^u, b^u), u unit mod p-1, in the shadow."""
    return all(eval_curve(f, pow(a, u, p), pow(b, u, p), p) == 0
               for u in units_mod(p - 1))

def fiber(f, a, b, p):
    """d, collected fiber as exponent list F (F[E] = coeff of T^E)."""
    d = (lambda oa, ob: oa * ob // gcd(oa, ob))(mult_order(a, p),
                                                mult_order(b, p))
    g = primitive_root(p)
    h = pow(g, (p - 1) // d, p)          # generator of mu_d
    dlog = {}
    t = 1
    for e in range(d):
        dlog.setdefault(t, e)
        t = t * h % p
    F = [0] * d
    for c, i, j in f:
        w = pow(a, i, p) * pow(b, j, p) % p
        F[dlog[w]] = (F[dlog[w]] + c) % p
    return d, F

def criterion(f, a, b, p):
    """Returns (stable?, species): species in {'group','antipodal','codeword'}."""
    d, F = fiber(f, a, b, p)
    if all(c == 0 for c in F):
        return True, 'group'
    rem = poly_rem_modp(F, [c % p for c in cyclotomic(d)], p)
    if rem != [0]:
        return False, None
    wt = sum(1 for c in F if c)
    if wt == 2 and d % 2 == 0:
        es = [e for e, c in enumerate(F) if c]
        if (es[1] - es[0]) % d == d // 2 and F[es[0]] == F[es[1]]:
            return True, 'antipodal'
    return True, 'codeword'

# ----------------------------------------------------------------------
section("I. THE RUN BOUND (longest unit run mod d = q_min(d) - 1)")
# ----------------------------------------------------------------------

ok = True
for d in range(2, 5001):
    run = best = 0
    for r in range(1, d):
        run = run + 1 if gcd(r, d) == 1 else 0
        best = max(best, run)
    if best != spf(d) - 1:
        ok = False
        break
check(ok, "longest run of consecutive units mod d == q_min(d)-1, d=2..5000")

# ----------------------------------------------------------------------
section("II. THE TORSION-MENU LAW (tau(d) = q_min(d), exhaustive sweep)")
# ----------------------------------------------------------------------

def least_prime_1mod(d):
    p = d + 1
    while True:
        if all(p % q for q in range(2, int(p ** 0.5) + 1)):
            if (p - 1) % d == 0:
                return p
        p += d

def rank_modp(rows, p):
    M = [r[:] for r in rows]
    rank, col = 0, 0
    ncols = len(M[0]) if M else 0
    for col in range(ncols):
        piv = next((r for r in range(rank, len(M)) if M[r][col]), None)
        if piv is None:
            continue
        M[rank], M[piv] = M[piv], M[rank]
        inv = pow(M[rank][col], p - 2, p)
        M[rank] = [x * inv % p for x in M[rank]]
        for r in range(len(M)):
            if r != rank and M[r][col]:
                c = M[r][col]
                M[r] = [(x - c * y) % p for x, y in zip(M[r], M[rank])]
        rank += 1
    return rank

from itertools import combinations

for d in [3, 5, 7, 9, 11, 13, 15, 21, 25, 27, 33, 35]:
    q = spf(d)
    p = least_prime_1mod(d)
    g = primitive_root(p)
    h = pow(g, (p - 1) // d, p)
    prim = [pow(h, u, p) for u in units_mod(d)]
    found = False
    for w in range(2, q):
        for rest in combinations(range(1, d), w - 1):
            support = (0,) + rest
            rows = [[pow(th, e, p) for e in support] for th in prim]
            if rank_modp(rows, p) < w:
                found = True
                break
        if found:
            break
    # q-gon: weight-q multiple of Phi_d
    qgon = [0] * d
    for s in range(q):
        qgon[s * (d // q)] = 1
    rem = poly_rem_modp(qgon, cyclotomic(d), p)
    check(not found and rem == [0],
          f"d={d} (p={p}): no codeword below weight {q}, q-gon hits it "
          f"-- tau({d}) = {q}")

for d in [4, 6, 8, 10, 12]:
    p = least_prime_1mod(d)
    half = [0] * d
    half[0] = half[d // 2] = 1
    rem = poly_rem_modp(half, cyclotomic(d), p)
    check(rem == [0], f"d={d}: antipodal word T^{d//2}+1 is a codeword "
                      f"-- tau({d}) = 2")

# ----------------------------------------------------------------------
section("III. THE FIBER CRITERION vs BRUTE ORBITS (exhaustive battery)")
# ----------------------------------------------------------------------

PENTAGON = [(1, 0, 0), (1, 1, 0), (1, 0, 1), (1, 1, 1), (1, 0, 2)]

def battery(p):
    fs = []
    for c in range(p):
        fs.append([(1, 1, 0), (1, 0, 1), (-c % p, 0, 0)])      # lines
    fs.append(PENTAGON)
    fs.append([(1, 8, 0), (1, 4, 0), (1, 0, 0)])               # gate curve
    fs.append([(1, 6, 0), (1, 0, 0)])                          # x^6 = -1
    fs.append([(1, 1, 1), (1, 0, 0)])                          # xy = -1
    fs.append([(1, 2, 1), (-1, 0, 0)])                         # x^2 y = 1
    g = primitive_root(p)
    fs.append([(1, 1, 1), (-g % p, 0, 0)])                     # xy = g
    for _ in range(25):
        terms = random.randint(3, 6)
        fs.append([(random.randint(1, p - 1), random.randint(0, 4),
                    random.randint(0, 4)) for _ in range(terms)])
    return fs

total = 0
for p in [7, 11, 13, 31]:
    fs = battery(p)
    bad = 0
    for f in fs:
        for a in range(1, p):
            for b in range(1, p):
                total += 1
                if brute_stable(f, a, b, p) != criterion(f, a, b, p)[0]:
                    bad += 1
    check(bad == 0, f"p={p}: criterion == brute orbit check over "
                    f"{len(fs)} curves x {(p-1)**2} unit pairs")
print(f"  ({total} stability tests total)")

# ----------------------------------------------------------------------
section("IV. LINE CONTINUITY (the P77 crystallographic law reproduced)")
# ----------------------------------------------------------------------

for p in [7, 11, 13, 31]:
    ok = True
    for c in range(p):
        f = [(1, 1, 0), (1, 0, 1), (-c % p, 0, 0)]
        got = {(a, b) for a in range(1, p) for b in range(1, p)
               if brute_stable(f, a, b, p)}
        if c == 0:
            want = {(a, -a % p) for a in range(1, p)}
        else:
            want = {(a, pow(a, p - 2, p)) for a in range(1, p)
                    if (a + pow(a, p - 2, p)) % p == c
                    and mult_order(a, p) in (1, 2, 3, 6)}
        if got != want:
            ok = False
    check(ok, f"p={p}: line stable sets == P77 law at every c")

# ----------------------------------------------------------------------
section("V. THE PENTAGON WITNESS (the first new species past lines)")
# ----------------------------------------------------------------------

for p in [7, 11, 31, 41, 61]:
    stable5 = set()
    for a in range(1, p):
        for b in range(1, p):
            st, sp = criterion(PENTAGON, a, b, p)
            if st:
                d, F = fiber(PENTAGON, a, b, p)
                if d == 5:
                    stable5.add((a, b))
                    check(sp == 'codeword' and sum(1 for c in F if c) == 5,
                          f"p={p}: ({a},{b}) is codeword species, weight 5")
    if (p - 1) % 5 == 0:
        g = primitive_root(p)
        th = pow(g, (p - 1) // 5, p)
        orbit = {(pow(th, u, p), pow(th, 2 * u, p)) for u in [1, 2, 3, 4]}
        check(stable5 == orbit,
              f"p={p}: order-5 stable locus == the one orbit of "
              f"(theta, theta^2), size 4")
    else:
        check(stable5 == set(), f"p={p}: no order-5 stable point "
                                f"(5 does not divide p-1)")

# species exercisers
p = 31
ok_g = all(criterion([(1, 2, 1), (-1, 0, 0)], a, b, p) == (True, 'group')
           for a in range(1, p) for b in range(1, p)
           if a * a * b % p == 1)
ok_a = all(criterion([(1, 1, 1), (1, 0, 0)], a, b, p) == (True, 'antipodal')
           for a in range(1, p) for b in range(1, p)
           if a * b % p == p - 1)
check(ok_g, f"p={p}: every point of [x^2 y = 1] is group species")
check(ok_a, f"p={p}: every point of [xy = -1] is antipodal species")

# ----------------------------------------------------------------------
section("VI. DEGREE CAPS: 25-TORSION IS CODEWORD-INVISIBLE TO CONICS (p=101)")
# ----------------------------------------------------------------------

p = 101
g = primitive_root(p)
h = pow(g, (p - 1) // 25, p)            # order 25
mu25 = [pow(h, e, p) for e in range(25)]
CONIC_EXP = [(0, 0), (1, 0), (0, 1), (2, 0), (0, 2), (1, 1)]
pairs = 0
codeword_stab = 0
group_stab = 0
for ea in range(25):
    for eb in range(25):
        a, b = mu25[ea], mu25[eb]
        oa, ob = 25 // gcd(ea, 25), 25 // gcd(eb, 25)
        if oa * ob // gcd(oa, ob) != 25:
            continue
        pairs += 1
        exps = [(i * ea + j * eb) % 25 for i, j in CONIC_EXP]
        ws = sorted(set(exps))
        if len(ws) < len(exps):
            # two conic monomials share a value: a nonzero conic
            # collects to the zero fiber = a GROUP-species stabilizer
            group_stab += 1
        rows = [[pow(h, u * e, p) for e in ws] for u in units_mod(25)]
        if rank_modp(rows, p) < len(ws):
            codeword_stab += 1
check(pairs == 600 and codeword_stab == 0,
      f"p=101: all {pairs} torsion-25 pairs, NO conic stabilizes any "
      f"through the CODEWORD species (tau(25)=5 <= 6, but no shifted "
      f"5-gon fits degree 2)")
check(group_stab > 0,
      f"p=101: {group_stab}/{pairs} pairs DO admit a group-species "
      f"conic (exponent collision) -- the codeword scope is load-bearing")

print()
print("=" * 72)
print(f"ALL CHECKS PASSED ({CHECKS})")
print("=" * 72)
